### ISSUE TITLE
Connection to Hyper-V VM on Windows Server 2016 fails

### ISSUE THREAD

**Issue by mkisielewski** [FreeRDP/FreeRDP#3700] opened 2017-01-12 10:31 UTC
Connection to Hyper-V VM on Windows Server 2016 using /vmconnect ends with error described below. On the other hand it works correctly on Windows Server 2012 R2. Also RDP connection to the same Windows Server 2016 on port 3389 works well.

FreeRDP version: freerdp-nightly-2.0-0+0~20161229033923.270~1.git90877f5, freerdp-nightly-2.0-0+0~20170112033917.272~1.git9e636f2
Client OS: Fedora 25 (also tested on Windows using wfreerdp)

```
/opt/freerdp-nightly/bin/xfreerdp /u:Administrator /vmconnect:3b32e28e-2117-4d7c-866e-021fb94316d9 /v:os-hyperv01 /log-level:trace
...
[12:08:38:425] [23596:23597] [INFO][com.freerdp.core] - ERRINFO_RPC_INITIATED_DISCONNECT (0x00000001):The disconnection was initiated by an administrative tool on the server in another session.
[12:08:38:425] [23596:23597] [DEBUG][com.freerdp.core.rdp] - DisconnectProviderUltimatum: reason: 1
```

Event log on Windows shows successfull logon session creation, but it's destroyed immediately (logoff without any errors).

**Comment by akallabeth** [comment] 2017-01-12 11:02
Duplicate of #2421. Please search existing issues before creating new ones.

**Closed by akallabeth** 2017-01-12 11:02 UTC

**Comment by akallabeth** [comment] 2017-01-13 10:37
@mkisielewski Could you verify that it is not some policy on server side disconnecting the session (as the error suggests) and add the results to issue #2421?

**Comment by mkisielewski** [comment] 2017-01-23 10:35
@akallabeth Verified & solved. Results added to https://github.com/FreeRDP/FreeRDP/issues/2421#issuecomment-274452213
