### ISSUE TITLE
Constantly getting disconnected from remote sessions

### ISSUE THREAD

**Issue by PadreAdamo** [FreeRDP/FreeRDP#4695] opened 2018-06-04 13:02 UTC
This previous bug report was posted on Remmina issue tracker: https://github.com/FreeRDP/Remmina/issues/1494

I have used two different distros and both have the same issue with constantly getting disconnected from the remote session. Remmina just closes out my session. Windows RDP stays connected all day until I close it; Remmina just closes my session. This has been occurring for about two months now and I just finally decided to report it because I used another distro to rule that out.

I have tried various versions in the Solus repositories using eopkg to install. I'm still getting consistent disconnects. The following output is happening when running Remmina from konsole:

> 
>     ** (remmina:15648): CRITICAL **: 08:30:37.992: secret_service_load_collections_sync: assertion 'paths != NULL' failed
>     [glibsecret] unable to get secret service: Unknown error.
>     Plugin entry returned false: /usr/lib64/remmina/plugins/remmina-plugin-secret.so.
>     StatusNotifier/Appindicator support: your desktop does support it, but you did not compile remmina with cmake's -DWITH_APPINDICATOR=on
>     WARNING: Remmina is running with a secret plugin, but it cannot connect to a secret service.
> 
>     (remmina:15648): Gtk-WARNING **: 08:30:38.162: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
>     Gtk-Message: 08:31:51.686: GtkDialog mapped without a transient parent. This is discouraged.
>     [08:31:51:681] [15648:15681] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
>     [08:31:51:681] [15648:15681] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
>     [08:31:51:681] [15648:15681] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
>     [08:31:51:737] [15648:15681] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
>     [08:31:51:793] [15648:15681] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
>     [08:31:52:783] [15648:15681] [INFO][com.freerdp.gdi] - Local framebuffer format PIXEL_FORMAT_BGRA32
>     [08:31:52:783] [15648:15681] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
>     [08:31:52:786] [15648:15681] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp
>     [08:31:52:786] [15648:15686] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [Shared] (static)
>     [08:31:52:787] [15648:15686] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer (static)
>     [08:31:56:612] [15648:15686] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: Shared (type=8 id=1)
>     [08:31:56:612] [15648:15686] [INFO][com.freerdp.channels.rdpdr.client] - registered device #2: PRN1 (type=4 id=2)
>     [08:31:56:612] [15648:15686] [INFO][com.freerdp.channels.rdpdr.client] - registered device #3: PRN2 (type=4 id=3)
>     [08:32:29:479] [15648:15686] [ERROR][com.freerdp.channels.rdpdr.client] - Ignoring unhandled message PAKID_PRN_CACHE_DATA (EventID: 0x00000002)
>     [08:32:29:536] [15648:15686] [ERROR][com.freerdp.channels.rdpdr.client] - Ignoring unhandled message PAKID_PRN_CACHE_DATA (EventID: 0x00000002)
>     [08:35:07:256] [15648:15681] [INFO][com.freerdp.core] - ERRINFO_DECRYPT_FAILED (0x00001192):(a) Decryption using Standard RDP Security mechanisms (section 5.3.6) failed.
>     (b) Session key creation using Standard RDP Security mechanisms (section 5.3.5) failed.
>     [08:35:07:256] [15648:15681] [ERROR][com.freerdp.core.transport] - BIO_read returned an error: error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library
>     [08:35:07:256] [15648:15681] [ERROR][com.freerdp.core.transport] - BIO_read returned an error: error:25070067:DSO support routines:DSO_load:could not load the shared library
>     Failed to check FreeRDP event handles

** Application details:
* Version of FreeRDP: 2.0.0_rc2
* OS version connecting to: Windows Server 2008 R2
**Desktop (please complete the following information):**
Solus PLASMA

**Comment by akallabeth** [comment] 2018-06-04 13:15
Duplicate of #2190, server side bug, sorry. You need to change your connection options.

**Closed by akallabeth** 2018-06-04 13:15 UTC

**Comment by apath001** [comment] 2018-07-11 10:23
hi akallabeth, you said " Duplicate of #2190(#4695), server side bug, sorry. You need to change your connection options."  -- could you tell me how to change my connection options to aviod this issue? thanks a lot.

**Comment by akallabeth** [comment] 2018-07-11 10:38
@apath001 if you tell me what you're using yes ;)
