### ISSUE TITLE
Distorted text when connecting to Windows Server2008r2 with FreeRDP 2.0.0 f9a47a3

### ISSUE THREAD

**Issue by Nalyden** [FreeRDP/FreeRDP#4126] opened 2017-09-11 06:27 UTC
We're experiencing intermittent text corruption issues when connecting to Windows Server 2008r2 Standard with FreeRDP 2.0.0 (git f9a47a3), it looks like rows of pixels get offset slightly.

Minimizing and maximizing the window with the distorted text or scrolling the document so the text disappears then reappears will change the distortion and can sometimes fix it.

The command line options are as follows and we have tried using /gdi:sw

-sec-nla /cert-ignore /multimon /sound:sys:pulse /drive:USB,/mnt/usbdevice

Any assistance is greatly appreciated.

![freerdp issues](https://user-images.githubusercontent.com/19770101/30260767-a665a01c-970c-11e7-982b-eae2eee125b5.jpg)
![freerdp issues 2](https://user-images.githubusercontent.com/19770101/30260791-c9832588-970c-11e7-98b3-d829c9a5f4dc.jpg)

**Comment by akallabeth** [comment] 2017-09-11 11:06
@Nalyden Ok, that is indeed an issue. Using ```/rfx``` or any of the ```/gfx``` options should work as work around for your issue (using the newer RDP graphics stack instead of old GDI).
Do you know by chance if there are older versions working?

**Comment by akallabeth** [comment] 2017-09-11 11:08
@Nalyden And it could help if you name one or two applications along with win28k RDP server settings to reproduce the issue.

**Comment by Nalyden** [comment] 2017-09-11 12:32
@akallabeth Thanks Akallabeth, the FreeRDP version we were using previously was 1.2, this is the first time I've tried 2.0.0. I'll give the /rfx option a shot, is there any documentation on the /gfx option? I couldn't seem to find it in command line page on the wiki.

Applications that it occurs in are varied, the common ones are Word, Excel and Acrobat but it occurs in others as well.

The Server 2008r2 box is configured as a Remote Desktop Services host, are there any particular settings you'd like to know about?

**Comment by akallabeth** [comment] 2017-09-12 10:07
@Nalyden Sorry for the late reply, thought I already sent it  :/ 
No, GFX is not yet documented, the wiki is not up to date in that regard.
What it is is the 'new' graphics channel used by windows 8 and up.

As for settings, best all options in ```Administrative Templates/Windows Components/Remote Desktop Services/Remote Desktop Session Host/Remote Session Environment``` and subkeys.

**Comment by Nalyden** [comment] 2017-09-12 14:48
@akallabeth No worries. In that section we only have "Set compression algorithm for RDP data" configured and it is set to "Optimized to use less network bandwidth".

**Comment by akallabeth** [comment] 2017-09-29 11:19
With #4154 there were a few fixes regarding drawing issues. Does this solve this issue?

**Comment by akallabeth** [comment] 2017-11-06 10:54
@Nalyden Does this error still affect the current master/nigthtlies?

**Comment by Nalyden** [comment] 2017-11-07 05:15
Hi Akallabeth, I apologize for not checking in since my last post. I switched everyone over to use /rfx and everything has been working well. Then things got busy and I completely forgot about it.

I'll fire up a test machine and give it a test. Just keep in mind that the issue is intermittent so I'll need to run it for a bit before I can be reasonably confident that I haven't just had a lucky run.

**Comment by akallabeth** [comment] 2017-11-07 09:19
@Nalyden No problem, just trying to eliminate dead issues to get 2.0 out at some point...

**Comment by akallabeth** [comment] 2017-11-20 16:29
Ok, closing this as resolved (could not reproduce locally).
Reopen if you experience differing results.

**Closed by akallabeth** 2017-11-20 16:29 UTC
Labels: blocker, waiting-feedback
