### ISSUE TITLE
Fatal frequent crashes

### ISSUE THREAD

**Issue by nanxiongchao** [FreeRDP/FreeRDP#4120] opened 2017-09-06 08:48 UTC
This problem is very serious in use, it exits frequently in use, it appears once in a few minutes.
test method:
After the remote desktop connected just now shakes the mouse without any other operation
Note that only the cursor movement, less than a minute will quit.
this is the test result:
<pre>
xfreerdp /u:user /p: passwd /w:1366 /h:768 /v:IP
[16:08:33:175] [3071:3072] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
[16:08:33:248] [3071:3072] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
[16:08:33:695] [3071:3072] [INFO][com.freerdp.gdi] - Local framebuffer format PIXEL_FORMAT_BGRX32
[16:08:33:696] [3071:3072] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[16:08:34:820] [3071:3072] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[16:09:42:413] [3071:3072] [INFO][com.freerdp.core] - ERRINFO_DECRYPT_FAILED (0x00001192):(a) Decryption using Standard RDP Security mechanisms (section 5.3.6) failed.
(b) Session key creation using Standard RDP Security mechanisms (section 5.3.5) failed.
[16:09:42:413] [3071:3072] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 131: Connection reset by peer
[16:09:42:413] [3071:3072] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[16:09:42:413] [3071:3072] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
</pre>
Refer to the description of the connection：
https://github.com/FreeRDP/Remmina/issues/1270
https://github.com/FreeRDP/FreeRDP/issues/433

**Comment by akallabeth** [comment] 2017-09-06 11:12
@nanxiongchao So, do I understand correctly that this happens:
* Disconnect due to some decryption related error
* With old (w2k3 servers)

**Comment by akallabeth** [comment] 2017-09-06 11:33
Ok, after reading the whole issue (Remmina and #433) it looks like this is a duplicate of #433

**Closed by akallabeth** 2017-09-06 11:33 UTC
