### ISSUE TITLE
avc444_decompress() function never gets CHROMA only LUMA part, but why?

### ISSUE THREAD

**Issue by marsohod4you** [FreeRDP/FreeRDP#6602] opened 2020-11-24 10:52 UTC
This is probably not a bug of xfreerdp, but who knows..
I am digging into xfreerdp internals and especially AVC444 mode.
I start xfreerdp with additional option /gfx:avc444 and my Windows Server 2019 has option 
1) Prioritize H.264/AVC 444 Graphics mode for Remote Desktop connections - Enabled
2) Configure H.264/AVC hardware encoding for Remote Desktop connections - Not Configured because server is in VMWARE virtual machine.

I see AVC444 commands arrive but they cover only first part, LUMA.
I never see second part which is CHROMA.
Function
`INT32 avc444_decompress(H264_CONTEXT* h264, BYTE op,
                        RECTANGLE_16* regionRects, UINT32 numRegionRects,
                        const BYTE* pSrcData, UINT32 SrcSize,
                        RECTANGLE_16* auxRegionRects, UINT32 numAuxRegionRect,
                        const BYTE* pAuxSrcData, UINT32 AuxSrcSize,
                        BYTE* pDstData, DWORD DstFormat,
                        UINT32 nDstStep, UINT32 nDstWidth, UINT32 nDstHeight,
                        UINT32 codecId)
{
	INT32 status = -1;
	avc444_frame_type chroma = (codecId == RDPGFX_CODECID_AVC444) ? AVC444_CHROMAv1 : AVC444_CHROMAv2;

	if (!h264 || !regionRects ||
	    !pSrcData || !pDstData)
		return -1001;

	switch (op)
	{
		case 0: /* YUV420 in stream 1
		 * Chroma420 in stream 2 */
			if (!avc444_process_rects(h264, pSrcData, SrcSize, pDstData, DstFormat, nDstStep, nDstWidth,
			                          nDstHeight,
			                          regionRects, numRegionRects, AVC444_LUMA))
				status = -1;
			else if (!avc444_process_rects(h264, pAuxSrcData, AuxSrcSize, pDstData, DstFormat, nDstStep,
			                               nDstWidth, nDstHeight,
			                               auxRegionRects, numAuxRegionRect, chroma))
				status = -1;
			else
				status = 0;

			break;

		case 2: /* Chroma420 in stream 1 */
			if (!avc444_process_rects(h264, pSrcData, SrcSize, pDstData, DstFormat, nDstStep, nDstWidth,
			                          nDstHeight,
			                          regionRects, numRegionRects, chroma))
				status = -1;
			else
				status = 0;

			break;

		case 1: /* YUV420 in stream 1 */
			if (!avc444_process_rects(h264, pSrcData, SrcSize, pDstData, DstFormat, nDstStep, nDstWidth,
			                          nDstHeight,
			                          regionRects, numRegionRects, AVC444_LUMA))
				status = -1;
			else
				status = 0;

			break;

		default: /* WTF? */
			break;
	}`
Only gets parameter "op==1" and never 0 or 2.
What can it be?
Without op==0 or op==2 xfreerdp shows image as YUV420 only.
It is never extended to real YUV444.

Is it issue of xfreerdp? Or is it issue with Server configuration?
How to enable real full YUV444?

**Comment by akallabeth** [comment] 2020-11-24 11:08
because the server never sends `chroma`.
Not a bug, closing.

**Closed by akallabeth** 2020-11-24 11:08 UTC

**Comment by jgrzelak** [comment] 2020-11-24 11:29
You mean the 2016/2019 servers in general never send the chroma frames, even though the 'Prioritize H.264/AVC 444 Graphics mode for Remote Desktop connections' GP setting is enabled?

**Comment by akallabeth** [comment] 2020-11-24 11:33
@jgrzelak no, just that your test setup does not.
this is no freerdp related issue. check your test setup, the chroma frames are not always sent, only if the image can be improved by this (`cmd` with blinking cursor is  a prime example for that)

**Comment by marsohod4you** [comment] 2020-11-24 12:12
I understand that chroma should be sent when picture can be improved.
I guess it should work that way: when image is constantly changing like browser page scroll, or animations than no need to enhance picture, at that time only luma->yuv420. When user stops scrolling or no animations then picture should become clearer so server should send chroma for enhancements. 

My issue is that I never see chroma part. Even my desktop has only text and nothing changes on screen, even in that case no chroma. I tried when text cursor is blinking or not blinking - no change. Always only luma.

I am wondering that maybe client reports something wrong during negotiation and so server avoids sending chroma?

In server Terminal Server event logs I see Event ID 162 "client mode 2, AVC Available: 1 Initial Profile: 2048". In page https://techcommunity.microsoft.com/t5/microsoft-security-and/remote-desktop-protocol-rdp-10-avc-h-264-improvements-in-windows/ba-p/249588 they write that "AVC Available: 1 Initial Profile: 2048" mean server is using AVC444, that is correct. But what is "client mode 2"? When MSTSC connects then I see "client mode 0". Maybe this mode defines behave of chroma part arrival?
