### ISSUE TITLE
Remoteapp recursive lock

### ISSUE THREAD

**Issue by f-fanni** [FreeRDP/FreeRDP#6591] opened 2020-11-19 22:30 UTC
**Describe the bug**
On Ubuntu 18.04, when using the remoteapp connection, the gnome interface becomes extremely buggy. If there is any window under the dock, the mouse clicks (left and right) go through the dock and reach the app, whilst if there is nothing under the dock, the left click is registered as right click. The topbar appears to break too, but I cannot reproduce it as consistently as the dock.
Hovering the mouse for a couple of seconds over an icon in the dock before clicking cause it to be correctly registered. In the activity overview the issue is not present.
These problems are not present when connecting without remoteapp.

The terminal repeatedly logs of a recursive lock: `[23:03:39:655] [26935:26936] [WARN][com.freerdp.client.x11] - xf_lock_x11_:	[1] recursive lock from xf_UpdateWindowArea`. Additionally, after closing the app window xfreerdp does not return, and I have to kill it via Ctrl-C in terminal.

Both the stable and the nightly builds present this bug.

**To Reproduce**
Simply run a remote app connection, put any window under the gnome dock, and click on an icon of the dock.
A simple command like `xfreerdp /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} /app:"explorer.exe" ` is enough to show the bug.
On the other hand `xfreerdp /u:"${RDP_USER}" /p:"${RDP_PASS}" /v:${RDP_IP} ` behaves correctly.

**Expected behavior**
The remoteapp should not break the gnome interface.

**Application details**
* FreeRDP version (`xfreerdp /version`): `This is FreeRDP version 2.2.0 (n/a)`. I also tested on the nightly builds: `This is FreeRDP version 3.0.0-dev (077358224)`
* Command line used: See "How to reproduce"
* Output of `xfreerdp /buildconfig`: [Stable version](https://pastebin.com/raw/7MuU7BAg), [Nightly version](https://pastebin.com/raw/Ti5yDHPi)
* OS version connecting to (server side): Windows 10 Pro Education
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` : [Here](https://pastebin.com/raw/N1HknWSF)

**Environment:**
 - OS: Linux
 - Version/Distribution: Ubuntu 18.04, GNOME Shell 3.28.4
 - Architecture: amd64

**Additional context**
The same problem appears to be present in PopOS 20.10, which surely has a more updated Gnome version than mine, as reported here Fmstrat/winapps#81

**Comment by f-fanni** [comment] 2020-11-19 22:59
I tried to make a [video](https://imgur.com/a/PIhFF5X) to showcase the bug. It's not very clear, but at least you can see how I can highlight the text in the terminal clicking through the dock, without the dock reacting in any way.

**Comment by akallabeth** [comment] 2020-11-20 07:27
@f-fanni Remote app is highly dependent on desktop environment.
1. If you close the local windows the server will keep the connection open for around a minute, so that is normal behaviour.
1. The log message is kind of a TODO item on the list, you can ignore it for your use cases
1. As for dock and clicking through, that is most likely an issue because the remote app window is over the dock (there are some invisible areas around each remote app window).

**Comment by f-fanni** [comment] 2020-11-20 08:02
1. I just tested it, the process hangs for more than 10 minutes (i killed it after, it did not return), so it looks like it's not due to the connection staying open for one minute. Furthermore, this happens only when using remoteapp.
2. Well, ok
3. Yeah, I thought that too, but it happens even when the remoteapp is on the opposite side of the desktop, when it's minimized, when I change workspace, and also persist until I kill the process after closing the remoteapp window.

**Comment by akallabeth** [comment] 2020-11-20 08:39
that the 'hang' only happens with remote app is expected (protocol design). the amount of time sadly varies (some apps keep hidden windows (tray icons?) open)
as for the dock issue, I´ve tried it with gnome3 on debian bullseye, can´t reproduce it here (there are some other issues as I´ve got a multimon setup and that has known issues)

**Comment by mp1994** [comment] 2021-03-05 16:12
I'm also having a similar issue using FreeRDP with WinApps. It's kinda worse though. If I have a remoteapp, I am not able to interact with the dock at all! And the process hangs indefinitely also in my case (I have to `killall xfreerdp` to go back to normal operation). This is quite annoying. Any updates on this?

**Comment by awnz** [comment] 2021-07-03 11:38
Also affected as per OP, although "Hovering the mouse for a couple of seconds over an icon in the dock before clicking cause it to be correctly registered" does not apply to me, the right-click issue continues even after waiting. Otherwise the same.

xfreerdp 2.3.2, GNOME 3.28.2, Ubuntu 18.04.5.

**Comment by awnz** [comment] 2021-07-04 21:46
No longer affected after upgrading Ubuntu to 20.04 LTS (with GNOME 3.36.8)

**Comment by dreamcat4** [comment] 2021-12-08 16:13
same issue here, with latest version of xfreerdp built into flatpak. ubuntu 21.04 with budgie desktop

**Comment by krovostok-1c** [comment] 2022-02-18 08:25
Guys! This is very annoying problem on Linux Mint 20.3 Cinnamon + xfreerdp 2.2.0  used as RemoteApp launcher fom WS 2016
After RemoteApp closing, xfreerdp not exits and every action on RemoteApp get that messages in console.

**Comment by peng-1998** [comment] 2022-09-23 10:34
I would like to know if this problem has been solved, because I still encounter this problem now. I am using manjaro, both gnome and freerdp are up to date.

**Comment by akallabeth** [comment] 2022-09-23 13:05
2.8.0 fixed the annoying log message.
The `disconnection` issue is by remote app design, the server keeps the connection open for a configured time.

**Closed by akallabeth** 2022-09-23 13:05 UTC
Labels: channel:rail
