### ISSUE TITLE
Strange graphics issues when connecting to older Windows versions

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#3833] opened 2017-03-02 11:49 UTC
Just tried master from March 2 2017 and am seeing several strange graphical artifacts when connection to a Windows Server 2003 R2 machine.

Any ideas what might cause this?

![freerdp_artifacts_01](https://cloud.githubusercontent.com/assets/186198/23506031/67c91bb2-ff46-11e6-9b23-862538134974.png)
![freerdp_artifacts_02](https://cloud.githubusercontent.com/assets/186198/23506036/6ba83218-ff46-11e6-8e5e-ed1f667350c2.png)
![freerdp_artifacts_03](https://cloud.githubusercontent.com/assets/186198/23506066/9e459b98-ff46-11e6-8f6a-b94662665dfb.png)

**Comment by akallabeth** [comment] 2017-03-02 12:14
@lemonmojo Without a command line these can be anything, but I suspect you played with ```glyph-cache```?

**Comment by akallabeth** [comment] 2017-03-02 12:29
@lemonmojo Oh, and does it happen when using ```/gdi:sw``` too?

**Comment by lemonmojo** [comment] 2017-03-02 12:44
@akallabeth I'm indeed using both, software GDI and glyph caching. When turning off glyph caching the issues seem to disappear. Unfortunately glyph caching has always been turned on by default in my FreeRDP based RDP client and I can't simply change the default value for thousands of customers. ;)
Unfortunately I can't really tell when this stopped working correctly since I didn't update FreeRDP in a long time. I think the last version I used was from around September or October of last year.

**Comment by akallabeth** [comment] 2017-03-02 14:07
@lemonmojo Ok, that is good (for me) to hear, unfortunately bad for you. We've disabled glyph cache because It is working well with some, bad with others and does not give noticeable performance improvements.
Closing as duplicate of #3539

**Closed by akallabeth** 2017-03-02 14:07 UTC

**Comment by lemonmojo** [comment] 2017-03-02 15:07
@akallabeth So does that basically mean glyph cache in FreeRDP is not to be used anymore?

**Comment by akallabeth** [comment] 2017-03-02 15:21
@lemonmojo Makes life easier, yes.

**Comment by lemonmojo** [comment] 2017-03-02 17:23
@akallabeth thx for letting me know!
