### ISSUE TITLE
win11 can't connect to freerdp proxy

### ISSUE THREAD

**Issue by RyanCode** [FreeRDP/FreeRDP#8437] opened 2022-11-22 08:12 UTC
### what i did?
i used mstsc on windows 11 to connect freerdp-proxy,but an exception like "**This computer may be low on virtual memory**" was throw out.i tried another win 11 computer's mstsc,but as the same as the first time. and i checked the virtual memory of my computer and found that there were still 8192mb
### freerdp version
```version
[16:04:58:805] [13108:04b7c580] [INFO][proxy.server] - freerdp-proxy version info:
[16:04:58:805] [13108:04b7c580] [INFO][proxy.server] -  FreeRDP version: 3.0.0-dev
[16:04:58:805] [13108:04b7c580] [INFO][proxy.server] -  Git commit: eb77fd7b0
```
### logs
```log
[16:09:39:275] [13108:6b7a7000] [INFO][com.freerdp.core.connection] - Client Security: NLA:1 TLS:1 RDP:0
[16:09:39:275] [13108:6b7a7000] [INFO][com.freerdp.core.connection] - Server Security: NLA:0 TLS:1 RDP:0
[16:09:39:275] [13108:6b7a7000] [INFO][com.freerdp.core.connection] - Negotiated Security: NLA:0 TLS:1 RDP:0
[16:09:39:359] [13108:6b7a7000] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 54: Connection reset by peer
[16:09:39:359] [13108:6b7a7000] [ERROR][com.freerdp.core] - transport_read_layer:freerdp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[16:09:39:359] [13108:6b7a7000] [INFO][proxy.server] - [SessionID=7549CBA777E83E7B53A50D6E602A13B8][pf_server_handle_peer]: starting shutdown of connection
[16:09:39:359] [13108:6b7a7000] [INFO][proxy.server] - [SessionID=7549CBA777E83E7B53A50D6E602A13B8][pf_server_handle_peer]: stopping proxy's client
[16:09:39:359] [13108:6b7a7000] [INFO][proxy.server] - [SessionID=7549CBA777E83E7B53A50D6E602A13B8][pf_server_handle_peer]: freeing server's channels
[16:09:39:360] [13108:6b7a7000] [ERROR][com.freerdp.core.transport] - BIO_should_retry returned a system error 32: Broken pipe
[16:09:39:360] [13108:6b7a7000] [INFO][proxy.server] - [SessionID=7549CBA777E83E7B53A50D6E602A13B8][pf_server_handle_peer]: freeing proxy data
[16:09:40:686] [13108:6b7a7000] [INFO][proxy.server] - [SessionID=8B815D540A7D3CC6D16E31C5984C29D7][pf_server_handle_peer]: new connection: proxy address: 0.0.0.0, client address: 192.168.1.164
[16:09:40:686] [13108:6b7a7000] [INFO][com.freerdp.core.connection] - Client Security: NLA:1 TLS:1 RDP:0
[16:09:40:686] [13108:6b7a7000] [INFO][com.freerdp.core.connection] - Server Security: NLA:0 TLS:1 RDP:0
[16:09:40:686] [13108:6b7a7000] [INFO][com.freerdp.core.connection] - Negotiated Security: NLA:0 TLS:1 RDP:0
[16:09:40:713] [13108:6b7a7000] [INFO][com.freerdp.core.connection] - Accepted client: IDEAL
[16:09:40:713] [13108:6b7a7000] [INFO][com.freerdp.core.connection] - Accepted channels:
[16:09:40:713] [13108:6b7a7000] [INFO][com.freerdp.core.connection] -  rdpdr
[16:09:40:713] [13108:6b7a7000] [INFO][com.freerdp.core.connection] -  rdpsnd
[16:09:40:713] [13108:6b7a7000] [INFO][com.freerdp.core.connection] -  cliprdr
[16:09:40:713] [13108:6b7a7000] [INFO][com.freerdp.core.connection] -  drdynvc
[16:09:40:713] [13108:6b7a7000] [INFO][com.freerdp.core.gcc] - Active rdp encryption level: NONE
[16:09:40:713] [13108:6b7a7000] [INFO][com.freerdp.core.gcc] - Selected rdp encryption method: NONE
[16:09:40:736] [13108:6b7a7000] [ERROR][com.freerdp.core] - Expected MCS DomainMCSPDU_ChannelJoinRequest, got DomainMCSPDU_SendDataRequest
[16:09:40:736] [13108:6b7a7000] [ERROR][com.freerdp.core.peer] - peer_recv_callback_internal: CONNECTION_STATE_MCS_ATTACH_USER - rdp_server_accept_mcs_channel_join_request() fail
[16:09:40:736] [13108:6b7a7000] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[16:09:40:736] [13108:6b7a7000] [INFO][proxy.server] - [SessionID=8B815D540A7D3CC6D16E31C5984C29D7][pf_server_handle_peer]: starting shutdown of connection
[16:09:40:736] [13108:6b7a7000] [INFO][proxy.server] - [SessionID=8B815D540A7D3CC6D16E31C5984C29D7][pf_server_handle_peer]: stopping proxy's client
[16:09:40:736] [13108:6b7a7000] [INFO][proxy.server] - [SessionID=8B815D540A7D3CC6D16E31C5984C29D7][pf_server_handle_peer]: freeing server's channels
[16:09:40:736] [13108:6b7a7000] [INFO][proxy.server] - [SessionID=8B815D540A7D3CC6D16E31C5984C29D7][pf_server_handle_peer]: freeing proxy data
```

**Comment by akallabeth** [comment] 2022-11-22 08:18
closing as duplicate of #8436

**Closed by akallabeth** 2022-11-22 08:18 UTC
