### ISSUE TITLE
serial redirect not work

### ISSUE THREAD

**Issue by fedsed** [FreeRDP/FreeRDP#2333] opened 2015-01-26 08:11 UTC
Version freerdp of 26.01.2015.
Run xfreerdp +clipboard /seria:COM2,/dev/ttyUSB0 /v:server
Through the command 'change port' serial port redirect.
Run a program which does the following actions:
<20150126105130.649 SYS>
COM port is opened
<20150126105130.649 SYS>
Set timeouts: ReadInterval=-1, ReadTotalTimeoutMultiplier=0, ReadTotalTimeoutConstant=0, WriteTotalTimeoutMultiplier=5, WriteTotalTimeoutConstant=50
<20150126105130.649 SYS>
Baud rate 38400
<20150126105130.665 SYS>
RTS on
<20150126105130.665 SYS>
DTR on
<20150126105130.665 SYS>
Data bits=8, Stop bits=1, Parity=None
<20150126105130.665 SYS>
Set chars: Eof=0x00, Error=0x00, Break=0x00, Event=0x00, Xon=0x00, Xoff=0x00
<20150126105130.665 SYS>
Handflow: ControlHandShake=(DTR_CONTROL), FlowReplace=(TRANSMIT_TOGGLE, RTS_CONTROL), XonLimit=0, XoffLimit=0
<20150126105130.665 SYS>
Baud rate 9600
<20150126105130.665 SYS>
RTS off
<20150126105130.665 SYS>
DTR on
<20150126105130.680 SYS>
Data bits=8, Stop bits=1, Parity=None
<20150126105130.680 SYS>
Set chars: Eof=0x00, Error=0x00, Break=0x00, Event=0x00, Xon=0x00, Xoff=0x00
<20150126105130.680 SYS>
Handflow: ControlHandShake=(DTR_CONTROL), FlowReplace=(), XonLimit=0, XoffLimit=0
<20150126105130.883 SYS>
Purge the serial port: TXCLEAR
<20150126105130.883 TX>
<SI>
<20150126105131.087 SYS>
Baud rate 115200
<20150126105131.087 SYS>
RTS off
<20150126105131.087 SYS>
DTR on
<20150126105131.087 SYS>
Data bits=8, Stop bits=1, Parity=None
<20150126105131.087 SYS>
Set chars: Eof=0x00, Error=0x00, Break=0x00, Event=0x00, Xon=0x00, Xoff=0x00
<20150126105131.087 SYS>
Handflow: ControlHandShake=(DTR_CONTROL), FlowReplace=(), XonLimit=0, XoffLimit=0
<20150126105131.196 SYS>
Purge the serial port: TXCLEAR
<20150126105131.196 TX>
<SI>
<20150126105131.305 RX>
<SI>
<20150126105131.305 SYS>
Baud rate 115200
<20150126105131.305 SYS>
RTS on
<20150126105131.305 SYS>
DTR on
<20150126105131.305 SYS>
Data bits=8, Stop bits=1, Parity=None
<20150126105131.305 SYS>
Set chars: Eof=0x00, Error=0x00, Break=0x00, Event=0x00, Xon=0x00, Xoff=0x00
<20150126105131.305 SYS>
Handflow: ControlHandShake=(DTR_CONTROL), FlowReplace=(TRANSMIT_TOGGLE, RTS_CONTROL), XonLimit=0, XoffLimit=0
<20150126105131.415 SYS>
Baud rate 115200
<20150126105131.415 SYS>
RTS off
<20150126105131.415 SYS>
DTR on
<20150126105131.415 SYS>
Data bits=8, Stop bits=1, Parity=None
<20150126105131.415 SYS>
Set chars: Eof=0x00, Error=0x00, Break=0x00, Event=0x00, Xon=0x00, Xoff=0x00
<20150126105131.415 SYS>
Handflow: ControlHandShake=(DTR_CONTROL), FlowReplace=(), XonLimit=0, XoffLimit=0
<20150126105131.415 SYS>
Purge the serial port: TXCLEAR
<20150126105131.415 TX>
<BEL>
<20150126105131.524 SYS>
Purge the serial port: TXCLEAR
<20150126105131.524 TX>
6
<20150126105131.633 SYS>
Purge the serial port: TXCLEAR
<20150126105131.633 TX>
Q
<20150126105131.743 SYS>
Baud rate 115200
<20150126105131.743 SYS>
RTS on
<20150126105131.743 SYS>
DTR on
<20150126105131.743 SYS>
Data bits=8, Stop bits=1, Parity=None
<20150126105131.743 SYS>
Set chars: Eof=0x00, Error=0x00, Break=0x00, Event=0x00, Xon=0x00, Xoff=0x00
<20150126105131.743 SYS>
Handflow: ControlHandShake=(DTR_CONTROL), FlowReplace=(TRANSMIT_TOGGLE, RTS_CONTROL), XonLimit=0, XoffLimit=0
<20150126105131.743 SYS>
In/out queue size 6144/6144
<20150126105131.743 SYS>
Purge the serial port: RXCLEAR
<20150126105132.071 SYS>
Purge the serial port: TXCLEAR
<20150126105132.071 TX>
READ [len=4]
<20150126105132.087 RX>
ACK [len=3]
<20150126105132.087 RX>
<NUL>10000000170034000100|1.00<FF><ENQ> [len=28]
<20150126105132.102 SYS>
Purge the serial port: TXCLEAR
<20150126105132.102 TX>
ACK [len=3]
<20150126105132.149 RX>
<SOH>4606446718149|1.00è<ETX> [len=21]
<20150126105132.149 SYS>
Purge the serial port: TXCLEAR
<20150126105132.149 TX>
ACK [len=3]
<20150126105132.196 RX>
OVER [len=4]
<20150126105132.196 RX>
OVER [len=4]
<20150126105132.196 SYS>
COM port is closed

freerdp when it writes: 
xfreerdp +clipboard /v:server /serial:COM2,/dev/ttyUSB0 /w:800 /h:600 
[10:13:13:257] [4307:-1225610432] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[10:13:13:257] [4307:-1225610432] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[10:13:13:257] [4307:-1225610432] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[10:13:14:430] [4307:-1225610432] [ERROR][com.freerdp.locale] - Unable to get current timezone rule
[10:13:14:911] [4307:-1235440832] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service serial (static)
[10:13:18:832] [4307:-1235440832] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: COM2 (type=1 id=1)
[10:13:38:532] [4307:-1270879424] [WARN][com.winpr.comm] - TIOCGICOUNT ioctl failed, errno=[22] Invalid argument.
[10:13:38:533] [4307:-1270879424] [WARN][com.winpr.comm] - could not read counters.
[10:13:50:237] [4307:-1270879424] [WARN][com.winpr.comm] - TIOCGICOUNT ioctl failed, errno=[22] Invalid argument.
[10:13:50:237] [4307:-1270879424] [WARN][com.winpr.comm] - could not read counters.
[10:13:51:317] [4307:-1270879424] [WARN][com.winpr.comm] - SERIAL_DTR_CONTROL:ON and SERIAL_RTS_CONTROL:OFF cannot be different, HUPCL will be set since it is claimed for one of the both lines.
[10:13:51:514] [4307:-1270879424] [WARN][com.winpr.comm] - Expecting SERIAL_PURGE_TXABORT since SERIAL_PURGE_TXCLEAR is set

and running my program hangs, not complying with their actions.

**Comment by eledoux** [comment] 2015-01-26 10:44
I'll do a few more tests. The first one would be to make sure your program works as expected with a Windows client (mstsc.exe). 

Based on the latest warning message I'd try the following CLI argument: /serial:COM2,/dev/ttyUSB0,Serial 

If you want to support a particular device (I tested a very limited number of them), you could also try: /serial:COM2,/dev/ttyUSB0,Serial,permissive

The permissive mode will ignore most of the ioctl errors. For instance it won't be possible to set the queue size to 6144, Linux will continue to use its 4096 internal buffer but the device might still be functional. 

Most often the warning messages about counters is due to the USB to Serial adapter, the adapter's driver usually don't support them. It could be worth to check if your program works plugged on a regular serial port.

(Such issues could be resolved by adding another buffer on the top of N_TTY, or with an implementation which would not rely at all on the too specific Linux' N_TTY line discipline. If someone volunteers...)

**Comment by fedsed** [comment] 2015-01-26 11:59
In standart Windows client (mstsc.exe), my program works.
Argument: "/serial:COM2,/dev/ttyUSB0,Serial" and "/serial:COM2,/dev/ttyUSB0,Serial,permissive", result is not given.
If necessary I can provide a hex sequence of commands.

**Comment by fedsed** [comment] 2015-01-26 12:54
https://gist.github.com/fedsed/341c4162ac824e2d43bd  - Windows client (mstsc.exe) good job log files

**Comment by eledoux** [comment] 2015-01-26 14:26
@fedsed with "/serial:COM2,/dev/ttyUSB0,Serial", I'd expect you don't see the warning message about SERIAL_PURGE_TXABORT anymore?

Is it an actual device or just a test program you're trying to make working? If it is a test program there is a good chance you'll be able to identify the function call that makes your program to hang and if it is an issue purely due to the current implementation, it is most likely due to one of the limitations of the current implementation, to get an idea of those you can look at the TODO and FIXME tags from this file: https://github.com/FreeRDP/FreeRDP/blob/master/winpr/libwinpr/comm/comm_sercx_sys.c

Even if a function call is not supported, xfreerdp should not hang and an error should be reported. 

By the way, you're well using xfreerdp which is the FreeRDP's Linux client?

**Comment by fedsed** [comment] 2015-01-26 14:47
This device and program of work with this device, this barcode scanner.
In the old version 0.8.2 freerdp everything worked.

/usr/freerdp1/bin/xfreerdp /v:server /serial:COM2,/dev/ttyUSB0,Serial /w:800 /h:600
[17:39:15:826] [2910:-1225548992] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[17:39:15:827] [2910:-1225548992] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[17:39:15:830] [2910:-1225548992] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: 
[17:39:15:933] [2910:-1225548992] [ERROR][com.freerdp.locale] - Unable to get current timezone rule
[17:39:15:483] [2910:-1235440832] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service serial (static)
[17:39:27:225] [2910:-1235440832] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: COM2 (type=1 id=1)
[17:39:57:512] [2910:-1264583872] [WARN][com.winpr.comm] - TIOCGICOUNT ioctl failed, errno=[22] Invalid Argument.
[17:39:57:512] [2910:-1264583872] [WARN][com.winpr.comm] - could not read counters.
[17:39:57:632] [2910:-1264583872] [WARN][com.winpr.comm] - SERIAL_DTR_CONTROL:ON and SERIAL_RTS_CONTROL:OFF cannot be different, HUPCL will be set since it is claimed for one of the both lines.

If the full functionality of serial port is not implemented in the current version, the will look for an alternative client.

**Comment by eledoux** [comment] 2015-01-26 15:22
It is good news your device and program works with an old version because all functionalities were not supported either at this time. So a fix should be possible for you.

Today I cannot do some tests to see whether the current master branch still pass my own tests. But I'm curious, what is the barcode scanner model?

If this is easy for you could also try to build the following branch which is bit older than the current master: https://github.com/eledoux/FreeRDP/tree/ports.

**Comment by fedsed** [comment] 2015-01-26 18:03
Model Barcode scanner CipherLab 8300 USB.
Tomorrow I will try to collect your branch and write on the results.

**Comment by fedsed** [comment] 2015-01-27 07:16
Your assembly is compiled, but does not connect. 
/usr/local/freerdp1/bin/xfreerdp /v:server
[10:12:57:737] [18988:-1225536704] [ERROR][com.freerdp.locale] - Unable to get current timezone rule
[10:12:57:740] [18988:-1225536704] [ERROR][com.freerdp.core.connection] - license connection sequence aborted.
[10:12:57:740] [18988:-1225536704] [ERROR][com.freerdp.core] - freerdp_set_last_error 0x2000D

**Comment by eledoux** [comment] 2015-01-27 13:47
@fedsed a build of xfreerdp from my branch 'ports' should connect. Maybe just make sure you didn't mixed FreeRDP's libraries with those from a build of the current master branch. By the way, what's your server?

On my side the only issue I have is that xfreerdp hangs while signing out of the RDP session after to have used the COM port. But your issue is different, this is well your program which hangs and not xfreerdp?

**Comment by fedsed** [comment] 2015-01-27 14:32
From your branch is not connected to Windows 2003 R2. Connected to Windows 2008 R2. 
Behavior such as you have described, hangs at logoff. Programm still does not work.

[17:16:50:899] [2957:-1225548992] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[17:16:50:900] [2957:-1225548992] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[17:16:50:141] [2957:-1225548992] [ERROR][com.freerdp.locale] - Unable to get current timezone rule
[17:16:51:650] [2957:-1235223744] [INFO][com.freerdp.channels.rdprd.client] - Loading device service serial (static)
[17:16:53:595] [2957:-1235223744] [INFO][com.freerdp.channels.rdprd.client] - registered device #1: COM2 (type=1 id=1)

[17:17:02:001] [2957:-1264583872] [WARN][com.winpr.comm] - TIOCGICOUNT ioctl failed, errno=[22] Invalid argument.
[17:17:02:001] [2957:-1264583872] [WARN][com.winpr.comm] - could not read counters.
[17:17:33:059] [2957:-1264583872] [WARN][com.winpr.comm] - TIOCGICOUNT ioctl failed, errno=[22] Invalid argument.
[17:17:33:059] [2957:-1264583872] [WARN][com.winpr.comm] - could not read counters.
[17:17:34:553] [2957:-1264583872] [WARN][com.winpr.comm] - SERIAL_DTR_CONTROL:ON and SERIAL_RTS_CONTROL:OFF cannot be different, HUPCL will be set since it is claimed for one of the both lines.
[17:17:34:765] [2957:-1264583872] [WARN][com.winpr.comm] - Expecting SERIAL_PURGE_TXABORT since SERIAL_PURGE_TXCLEAR is set
[17:17:59:470] [2957:-1225548992] [ERROR][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off his or her session on the server.
[17:17:59:470] [2957:-1225548992] [ERROR][com.freerdp.core.rdp] - DisconnectProviderUltimatum: reason: 3

I think that does not work due to the fact that the program works c RTS DTR signals that are not currently implemented in xfreerdp. It can be seen from protocol:

Baud rate 38400
RTS on
DTR on
Data bits=8, Stop bits=1, Parity=None
Set chars: Eof=0x00, Error=0x00, Break=0x00, Event=0x00, Xon=0x00, Xoff=0x00
Handflow: ControlHandShake=(DTR_CONTROL), FlowReplace=(TRANSMIT_TOGGLE, RTS_CONTROL), XonLimit=0, XoffLimit=0
Baud rate 9600
RTS off
DTR on

**Comment by eledoux** [comment] 2015-01-27 20:53
@fedsed I confirm I could not connect on a 2003 server with my branch. The issue wasn't on the master branch so I don't investigate more. I have anyway now merged the master on my branch.

The pull request #2339 might fix the hanging while signing out of the session but I'm afraid this won't be enough for your issue. I thought there could have a chance your issue happens on a close operation, you can make a try but I'm not confident for a final fix yet.

I didn't investigate much on your hypothesis yet, but is it possible to specify another flow control among your device settings?

Also thinking that a minimalistic program could help to reproduce your issue...

**Comment by fedsed** [comment] 2015-01-28 06:27
Unfortunately the device and the program can only change the port number and speed.
I have a subroutine call (windows only), the device C from the developers, it can somehow help?
https://gist.github.com/fedsed/03264d234eb30cd0c797

**Comment by eledoux** [comment] 2015-02-02 21:08
@fedsed a part of the problem seems to be due to the fact that ReadFile() should immediately return with the timeouts you set but hangs. Timeouts are implemented differently in comparison to former versions of xfreerdp so that could explain the regression.

**Comment by eledoux** [comment] 2015-02-03 20:39
@fedsed the recent fix of the timeouts on my branch may also have fixed your issue: https://github.com/eledoux/FreeRDP/tree/ports

Can you please confirm?

I'm otherwise hesitating to force the initial state of the DTR and RTS lines when SERIAL_DTR_CONTROL or SERIAL_RTS_CONTROL are ON because I'm not quite sure on how to do it without side effects.

**Comment by fedsed** [comment] 2015-02-04 06:56
Your assembly is compiled. The programm works!

**Comment by fedsed** [comment] 2015-02-04 07:24
Not running another program that loads the firmware into the scanner.

Log:
[10:20:36:349] [3074:-1225352384] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[10:20:36:349] [3074:-1225352384] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[10:20:36:474] [3074:-1225352384] [ERROR][com.freerdp.locale] - Unable to get current timezone rule
[10:20:37:093] [3074:-1235223744] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service serial (static)
[10:20:37:336] [3074:-1235223744] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: COM2 (type=1 id=1)
[10:21:24:833] [3074:-1266681024] [WARN][com.winpr.comm] - TIOCGICOUNT ioctl failed, errno=[22] Invalid argument.
[10:21:24:833] [3074:-1266681024] [WARN][com.winpr.comm] - could not read counters.
[10:21:24:882] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:24:882] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:24:152] [3074:-1266681024] [WARN][com.winpr.comm] - SERIAL_DTR_CONTROL:ON and SERIAL_RTS_CONTROL:OFF cannot be different, HUPCL will be set since it is claimed for one of the both lines.
[10:21:24:152] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:24:152] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:25:632] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:25:632] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:25:896] [3074:-1266681024] [WARN][com.winpr.comm] - SERIAL_DTR_CONTROL:ON and SERIAL_RTS_CONTROL:OFF cannot be different, HUPCL will be set since it is claimed for one of the both lines.
[10:21:25:896] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:25:896] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:25:182] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:25:182] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:25:347] [3074:-1266681024] [WARN][com.winpr.comm] - SERIAL_DTR_CONTROL:ON and SERIAL_RTS_CONTROL:OFF cannot be different, HUPCL will be set since it is claimed for one of the both lines.
[10:21:25:348] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:25:348] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:26:631] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:26:631] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:26:818] [3074:-1266681024] [WARN][com.winpr.comm] - SERIAL_DTR_CONTROL:ON and SERIAL_RTS_CONTROL:OFF cannot be different, HUPCL will be set since it is claimed for one of the both lines.
[10:21:26:818] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:26:818] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:26:101] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:26:101] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:26:270] [3074:-1266681024] [WARN][com.winpr.comm] - SERIAL_DTR_CONTROL:ON and SERIAL_RTS_CONTROL:OFF cannot be different, HUPCL will be set since it is claimed for one of the both lines.
[10:21:26:270] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:26:270] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:27:555] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:27:555] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:27:720] [3074:-1266681024] [WARN][com.winpr.comm] - TIOCGICOUNT ioctl failed, errno=[22] Недопустимый аргумент.
[10:21:27:720] [3074:-1266681024] [WARN][com.winpr.comm] - could not read counters.
[10:21:27:772] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:27:772] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:27:026] [3074:-1266681024] [WARN][com.winpr.comm] - SERIAL_DTR_CONTROL:ON and SERIAL_RTS_CONTROL:OFF cannot be different, HUPCL will be set since it is claimed for one of the both lines.
[10:21:27:027] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:27:027] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:27:499] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:27:499] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:28:810] [3074:-1266681024] [WARN][com.winpr.comm] - SERIAL_DTR_CONTROL:ON and SERIAL_RTS_CONTROL:OFF cannot be different, HUPCL will be set since it is claimed for one of the both lines.
[10:21:28:810] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:28:811] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:28:103] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:28:103] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:28:268] [3074:-1266681024] [WARN][com.winpr.comm] - SERIAL_DTR_CONTROL:ON and SERIAL_RTS_CONTROL:OFF cannot be different, HUPCL will be set since it is claimed for one of the both lines.
[10:21:28:268] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:28:268] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:29:537] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:29:537] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:29:693] [3074:-1266681024] [WARN][com.winpr.comm] - SERIAL_DTR_CONTROL:ON and SERIAL_RTS_CONTROL:OFF cannot be different, HUPCL will be set since it is claimed for one of the both lines.
[10:21:29:693] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:29:693] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:29:976] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:29:976] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:29:145] [3074:-1266681024] [WARN][com.winpr.comm] - SERIAL_DTR_CONTROL:ON and SERIAL_RTS_CONTROL:OFF cannot be different, HUPCL will be set since it is claimed for one of the both lines.
[10:21:29:145] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:29:145] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0
[10:21:29:415] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XonLimit with an unsupported value: 0
[10:21:29:415] [3074:-1266681024] [WARN][com.winpr.comm] - Attempt to set XoffLimit with an unsupported value: 0

**Comment by eledoux** [comment] 2015-02-04 12:01
@fedsed thanks for feedback. As you may have understood I cannot work more than an hour or two in a day on the issue and likely so do you. So a good and a bad news for today ! :)

Is the second issue also a regression in comparison to the old version of xfreerdp?

The capture of the actions like you did here: https://gist.github.com/fedsed/341c4162ac824e2d43bd was very useful with the first issue. Is it possible to get something similar for the second issue?

**Comment by fedsed** [comment] 2015-02-04 13:31
In old version freerdp second program is also working, ie this regression. I will try in the near future to provide the capture of the program.

**Comment by fedsed** [comment] 2015-02-04 13:56
Since the capture file is very large cite only a small part.

https://gist.github.com/fedsed/748be3fd056e19743ee3

**Comment by eledoux** [comment] 2015-02-04 19:11
@fedsed did you also tried with: "/serial:COM2,/dev/ttyUSB0,Serial,permissive" ?

The 'permissive' mode doesn't report some errors on some unsupported features like the old version of xfreerdp does.

I'm otherwise thinking to make 'Serial' the default instead of 'SerCx2' and even to remove this flag. I introduced this flag because I thought some different behaviors would be expected according it. It appears 'SerCx2' and 'SerCx' just adds some restrictions which doesn't make sense to be checked from a RDP client standpoint, the RDP client just have to rely on the server.

A "not so bad" news from your capture is that the transfer of the file is well initiated. Is the transfer fails on a error or it just hangs at some point? It'd be interesting so to get the end of your capture. A luxurious thing would be also to get the end of a capture done with Windows RDP client for a comparison purpose.

**Comment by fedsed** [comment] 2015-02-04 20:17
No it capture with standart Windows client (mstsc.exe). Tomorrow I will do with capture your ports and placed here.

**Comment by fedsed** [comment] 2015-02-05 06:59
Yes, with these settings "/serial:COM2,/dev/ttyUSB0,Serial,permissive" it worked!
Thank you very much for job!

**Comment by eledoux** [comment] 2015-02-06 19:34
@fedsed I submitted to the project's owners the pull request #2367. I made of Serial the default but didn't make the permissive mode the default. So you'll still have to use "/serial:COM2,/dev/ttyUSB0,Serial,permissive" on the command line. Is it okay for you?

**Comment by fedsed** [comment] 2015-02-07 06:34
Yes, it is normal. The main thing that worked.

**Closed** 2015-02-12 06:11 UTC
