### ISSUE TITLE
Freerdp v2.0.0.rc3 session reconnect not working with /gfx or +gfx-progressive

### ISSUE THREAD

**Issue by gnshkl1** [FreeRDP/FreeRDP#4861] opened 2018-09-18 09:19 UTC
Client OS :- xubuntu 16.04_x86
Server OS :- windows 10_x64

Scenario:-
1:-connect to remote session over wifi 
2:- created script to up and down wifi 
#!/bin/bash
iface="wlp3s0"
while true;
do
ifconfig $iface up
sleep  60
ifconfig $iface  down
sleep  35
done

3:-run up_down.sh in terminal
4:-launch session from another terminal

Result:-
1:-auto reconnect should work smoothly

Note:-
1:-auto reconnect working smoothly with /gfx-h264 only

This is FreeRDP version 2.0.0-rc3 (2.0.0-rc3)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=ON WITH_LIBAVCODEC=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=OFF WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -march=i686 -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls
Compiler:            GNU, 5.4.0
Target architecture: x86

"""
xfreerdp /u:xx  /p:xx  /v:x.x.x.x  /f  /gdi:hw  -themes +auto-reconnect +fonts /gfx

[09:07:10:898] [25746:25747] [INFO][com.freerdp.client.common.cmdline] - loading channelEx resrdr
[09:07:10:898] [25746:25747] [INFO][com.freerdp.client.common.cmdline] - loading channelEx hyprint
[09:07:10:898] [25746:25747] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[09:07:10:898] [25746:25747] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[09:07:10:090] [25746:25747] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[09:07:10:090] [25746:25747] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
[09:07:10:115] [25746:25747] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[09:07:10:129] [25746:25747] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel gpio
[09:07:10:130] [25746:25747] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
[09:08:05:088] [25746:25747] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 101: Network is unreachable
[09:08:05:088] [25746:25747] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[09:08:05:088] [25746:25747] [INFO][com.freerdp.client.x11] - Network disconnect!
[09:08:05:088] [25746:25747] [INFO][com.freerdp.client.x11] - Attempting reconnect (1 of 20)
[09:08:05:092] [25746:25747] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_FAILED [0x00020006]
[09:08:05:092] [25746:25747] [ERROR][com.freerdp.core] - failed to connect to 172.17.5.157
[09:08:10:092] [25746:25747] [INFO][com.freerdp.client.x11] - Attempting reconnect (2 of 20)
[09:08:10:093] [25746:25747] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_FAILED [0x00020006]
[09:08:10:094] [25746:25747] [ERROR][com.freerdp.core] - failed to connect to 172.17.5.157
[09:08:15:094] [25746:25747] [INFO][com.freerdp.client.x11] - Attempting reconnect (3 of 20)
[09:08:15:095] [25746:25747] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_FAILED [0x00020006]
[09:08:15:095] [25746:25747] [ERROR][com.freerdp.core] - failed to connect to 172.17.5.157
[09:08:20:095] [25746:25747] [INFO][com.freerdp.client.x11] - Attempting reconnect (4 of 20)
[09:08:20:096] [25746:25747] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_FAILED [0x00020006]
[09:08:20:096] [25746:25747] [ERROR][com.freerdp.core] - failed to connect to 172.17.5.157
[09:08:25:096] [25746:25747] [INFO][com.freerdp.client.x11] - Attempting reconnect (5 of 20)
[09:08:27:361] [25746:25747] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel gpio
[09:08:27:361] [25746:25747] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
[09:08:27:018] [25746:26094] [ERROR][com.freerdp.codec.clear] - vBarEntry->count 12 != vBarHeight 10
[09:08:27:018] [25746:26094] [ERROR][com.freerdp.codec.clear] - clear_decompress_bands_data failed!
[09:08:27:018] [25746:26094] [ERROR][com.freerdp.gdi] - clear_decompress failure: -1
[09:08:27:018] [25746:26094] [ERROR][com.freerdp.channels.rdpgfx.client] - context->SurfaceCommand failed with error 1359
[09:08:27:018] [25746:26094] [ERROR][com.freerdp.channels.rdpgfx.client] - rdpgfx_decode failed with error 1359!
[09:08:27:019] [25746:26094] [ERROR][com.freerdp.channels.rdpgfx.client] - rdpgfx_recv_wire_to_surface_1_pdu failed with error 1359!
[09:08:27:019] [25746:26094] [ERROR][com.freerdp.channels.rdpgfx.client] - Error while parsing GFX cmdId: RDPGFX_CMDID_WIRETOSURFACE_1 (0x0001)
[09:08:27:019] [25746:26094] [ERROR][com.freerdp.channels.rdpgfx.client] - rdpgfx_recv_pdu failed with error 1359!
[09:08:27:019] [25746:26094] [ERROR][com.freerdp.channels.drdynvc.client] - drdynvc_order_recv failed with error 1359!
[09:08:27:019] [25746:25747] [ERROR][com.freerdp.core] - drdynvc_virtual_channel_client_thread reported an error. Error was 1359
[09:08:27:019] [25746:25747] [ERROR][com.freerdp.core] - checkChannelErrorEvent() failed - 0
[09:08:27:020] [25746:25747] [INFO][com.freerdp.client.x11] - Network disconnect!
[09:08:27:020] [25746:25747] [INFO][com.freerdp.client.x11] - Attempting reconnect (1 of 20)
[09:08:27:091] [25746:25747] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
[09:08:27:091] [25746:25747] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[09:08:27:091] [25746:25747] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[09:08:27:091] [25746:25747] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[09:08:32:091] [25746:25747] [INFO][com.freerdp.client.x11] - Attempting reconnect (2 of 20)
[09:08:32:115] [25746:25747] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
[09:08:32:115] [25746:25747] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[09:08:32:115] [25746:25747] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[09:08:32:115] [25746:25747] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[09:08:37:115] [25746:25747] [INFO][com.freerdp.client.x11] - Attempting reconnect (3 of 20)
[09:08:37:126] [25746:25747] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
[09:08:37:126] [25746:25747] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[09:08:37:126] [25746:25747] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[09:08:37:126] [25746:25747] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[09:08:42:127] [25746:25747] [INFO][com.freerdp.client.x11] - Attempting reconnect (4 of 20)
[09:08:42:146] [25746:25747] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
[09:08:42:146] [25746:25747] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[09:08:42:146] [25746:25747] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[09:08:42:146] [25746:25747] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
"""

**Comment by akallabeth** [comment] 2018-09-18 09:30
Duplicate of #4857

**Closed by akallabeth** 2018-09-18 09:30 UTC
