### ISSUE TITLE
Muli-monitor support appears to be busted with the latest build

### ISSUE THREAD

**Issue by meanbunny** [FreeRDP/FreeRDP#2748] opened 2015-06-30 13:32 UTC
Hey All,

The multimon feature used to work flawlessly. However, with the latest build from source when I use the command, it goes full screen on my left monitor but doesn't even show up on the right monitor. Any suggestions? I am running Ubuntu GNOME 15.04 and have pulled the latest build from source. Connecting up to a Windows 8.1 Pro virtual machine. 

Below is my command

```
xfreerdp /title:mm-local-desk2 +wallpaper +clipboard /multimon /sound:sys:pulse /microphone:sys:pulse /usb:id,dev:18d1:4ee2 /v:192.168.56.110
```

Thanks!

**Comment by bmiklautz** [comment] 2015-06-30 13:52
@meanbunny what version are you referring to with "now"? - What Windows version you are connecting to?

**Comment by meanbunny** [comment] 2015-06-30 14:05
Connecting up to the same Windows 8.1 Pro virtual that I always have been. I am aware multimon support isn't on all Windows versions. Now refers to the latest code build.

**Comment by bmiklautz** [comment] 2015-06-30 14:13
@meanbunny latest code as in master? - If did you observe what the last working version was?

**Comment by meanbunny** [comment] 2015-06-30 20:47
Looks like I have this for the version number. I unfortunately didn't check what I had before, wish I had now. 

    This is FreeRDP version 1.2.4-dev (git cc4b5f9)

**Comment by bmiklautz** [comment] 2015-06-30 21:42
@meanbunny thanks for the update. I quickly tried today and saw the exact same behavior you've reported.

**Comment by meanbunny** [comment] 2015-06-30 22:37
@bmiklautz Ah ok cool, glad it wasn't just my local setup lol

**Comment by nfedera** [comment] 2015-06-30 22:47
... and a reminder to fill in the blanks here: https://github.com/FreeRDP/FreeRDP/wiki/Quality-Assurance-(QA)#fullscreen

**Comment by giovannitarter** [comment] 2015-07-03 07:50
I think the issue is related to #2707

**Comment by LGLumi** [comment] 2015-07-03 10:21
Have you tried /multimon:force ?

**Comment by giovannitarter** [comment] 2015-07-03 16:12
I tried with /multimon:force but it did not solve the issue. The fullscreen window was on the primary monitor only.

**Comment by LGLumi** [comment] 2015-07-06 11:47
Shame... I have no problem with that in Windows 2012... So, I guess it's related to Windows 8.1 only then - line in issue you linked.

**Comment by bmiklautz** [comment] 2015-07-06 12:16
@LGLumi I could reproduce the problem with window7 so it's there as well.

**Comment by giovannitarter** [comment] 2015-07-06 12:27
I experience the problem also connecting to Windows 2012

**Comment by LGLumi** [comment] 2015-07-08 06:16
@bmiklautz Well, there are few difference between what is described here and how am I using it. First of all, I don't use /title and I use FreeRDP on Debian Wheezy. (I use many things in addition such as gdi:hw /rfx -decorations ... rest are not graphicaly related at all.. so not mentioning ... but it works, now depends if it's compatibility issue or matter of additional stuff..)

**Comment by bmiklautz** [comment] 2015-07-08 15:33
@LGLumi I'v tested/reproduced this with a very simple command line almost without extra options. Maybe you can also add your command line for comparison?

**Comment by LGLumi** [comment] 2015-07-08 15:45
@bmiklautz I will try. Need to some things and will do, hopefully today.

**Comment by LGLumi** [comment] 2015-07-08 16:11
@bmiklautz @meanbunny  I just tried it and nothing. Had to add just -sec-nla due to Windows Server 2012, but I have left rest as meanbunny. Both monitors worked fine. But I am using really excesive build options, so that might make difference while I work... You might want to try that build but seriously you will get more than you need I guess, but worth a try I...

cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/freerdp-git -DWITH_PCSC=ON
-DWITH_CUPS=ON -DCHANNEL_CLIPRDR_SERVER=ON -DCHANNEL_DRDYNVC_SERVER=ON
-DCHANNEL_DRIVE_SERVER=ON -DCHANNEL_ECHO_SERVER=ON
-DCHANNEL_PARALLEL_SERVER=ON -DCHANNEL_PRINTER=ON
-DCHANNEL_RAIL_SERVER=ON -DCHANNEL_RDPDR_SERVER=ON
-DCHANNEL_RDPEI_SERVER=ON -DCHANNEL_SAMPLE=ON -DCHANNEL_SERIAL_SERVER=ON
 -DCHANNEL_SMARTCARD=ON -DCHANNEL_TSMF_SERVER=ON -DCHANNEL_URBDRC=ON
-DWITH_MANPAGES=OFF -DCHANNEL_DISP_SERVER=ON -DCHANNEL_PRINTER_CLIENT=ON
 -DCHANNEL_PRINTER_SERVER=ON -DCHANNEL_RDPGFX_SERVER=ON
-DCHANNEL_SMARTCARD_CLIENT=ON -DCHANNEL_SMARTCARD_SERVER=ON
-DCHANNEL_URBDRC_CLIENT=ON -DCHANNEL_URBDRC_SERVER=ON -DWITH_GSM=OFF
-DWITH_PULSE=ON -DWITH_SERVER=ON -DWITH_THIRD_PARTY=ON
-DWITH_PROFILER=ON -DWITH_FFMPEG=ON -DWITH_JPEG=ON -DWITH_DIRECTFB=OFF
-DWITH_GPROF=ON -DWITH_IPP=OFF -DWITH_DEBUG_ALL=ON

Ehm, I think this "-DCHANNEL_SAMPLE=ON" will get excluded, or at least I remember it did it for me while this option probably does not exist anymore.

**Comment by cmsmith1977** [comment] 2015-11-03 02:34
I posted this on the other thread (https://github.com/FreeRDP/FreeRDP/issues/2707#issuecomment-152856281) - thought you guys may find it useful also:  I was able to rollback client/X11/xf_window.c to eb14ab15f5bca5751d8a71965f31509d4c3b176b and recompile to make FreeRDP start in fullscreen mode across all monitors again. Not sure what all ramifications that might have - perhaps @nfedera could weigh in on this?

**Comment by nfedera** [comment] 2015-11-04 13:42
@cmsmith1977 see my answer in https://github.com/FreeRDP/FreeRDP/issues/2707#issuecomment-153721965

**Comment by caramorsimon** [comment] 2016-10-07 09:13
I have multimonitor support working well with gnome 3.20 under xenial & 6th Oct build of master (uncomplicated build flags). Seems to work fine assigning 2 of 3 real monitors to the rdp session, 
Using:
/multimon /monitors:1,2  +aero +fonts  +window-drag +menu-anims +decorations +smart-sizing 

Windows 7 sees both monitors correctly & uses them fullscreen @ client's native resolution. No problem that monitors are oriented differently (horizontal & vertical). Scales intelligently enough when not running fullscreen, although with the H&V orientation that's hard to use.

**Comment by akallabeth** [comment] 2017-11-17 13:11
Close as duplicate of #2707

**Closed by akallabeth** 2017-11-17 13:11 UTC
