### ISSUE TITLE
ERRCONNECT_PASSWORD_CERTAINLY_EXPIRED using Hostname rather than IP Address

### ISSUE THREAD

**Issue by rossbrower** [FreeRDP/FreeRDP#4351] opened 2018-01-10 22:21 UTC
We are receiving the following error after moving from RC0 to RC1 when an FQDN instead of an IP address is set in context->settings->ServerHostname

freerdp_set_last_error ERRCONNECT_PASSWORD_CERTAINLY_EXPIRED [0x0002000F]
BIO_read returned an error: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error

The host and target machines are both Windows Server 2012 R2. Default settings are used for NLA etc. The FreeRDP code is compiled via vcpkg.

**Comment by akallabeth** [comment] 2018-01-11 07:52
@rossbrower What do the server logs tell? Looks like it does not like the dns name (which is transmitted as part of the ServicePrincipalName)

**Comment by rossbrower** [comment] 2018-01-11 22:23
Seeing these messages on the host:
A logon was attempted using explicit credentials.

Subject:
	Security ID:		SYSTEM
	Account Name:		ALF-T-AMP-4$
	Account Domain:		UAT
	Logon ID:		0x3E7
	Logon GUID:		{00000000-0000-0000-0000-000000000000}

Account Whose Credentials Were Used:
	Account Name:		administrator
	Account Domain:		UAT.AMPLAB.ORG
	Logon GUID:		{a0070b64-14f4-dfcc-ee81-54123f1927b3}

Target Server:
	Target Server Name:	alf-t-amp-5.uat.amplab.org
	Additional Information:	TERMSRV/alf-t-amp-5.uat.amplab.org

Process Information:
	Process ID:		0xe80
	Process Name:		C:\Avanade\AmpRdpService\AmpRdpService.exe

Network Information:
	Network Address:	-
	Port:			-

This event is generated when a process attempts to log on an account by explicitly specifying that account’s credentials.  This most commonly occurs in batch-type configurations such as scheduled tasks, or when using the RUNAS command.

**Comment by rossbrower** [comment] 2018-01-11 22:26
On the target I see:
An account was successfully logged on.

Subject:
	Security ID:		NULL SID
	Account Name:		-
	Account Domain:		-
	Logon ID:		0x0

Logon Type:			3

Impersonation Level:		Impersonation

New Logon:
	Security ID:		UAT\Administrator
	Account Name:		Administrator
	Account Domain:		UAT
	Logon ID:		0x148533D
	Logon GUID:		{7facdc61-815f-2727-48f7-dea16ae27829}

Process Information:
	Process ID:		0x0
	Process Name:		-

Network Information:
	Workstation Name:	-
	Source Network Address:	-
	Source Port:		-

Detailed Authentication Information:
	Logon Process:		Kerberos
	Authentication Package:	Kerberos
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0

This event is generated when a logon session is created. It is generated on the computer that was accessed.

The subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.

The logon type field indicates the kind of logon that occurred. The most common types are 2 (interactive) and 3 (network).

The New Logon fields indicate the account for whom the new logon was created, i.e. the account that was logged on.

The network fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.

The impersonation level field indicates the extent to which a process in the logon session can impersonate.

The authentication information fields provide detailed information about this specific logon request.
	- Logon GUID is a unique identifier that can be used to correlate this event with a KDC event.
	- Transited services indicate which intermediate services have participated in this logon request.
	- Package name indicates which sub-protocol was used among the NTLM protocols.
	- Key length indicates the length of the generated session key. This will be 0 if no session key was requested.



This event is preceded by:

Special privileges assigned to new logon.

Subject:
	Security ID:		UAT\Administrator
	Account Name:		Administrator
	Account Domain:		UAT
	Logon ID:		0x148533D

Privileges:		SeSecurityPrivilege
			SeBackupPrivilege
			SeRestorePrivilege
			SeTakeOwnershipPrivilege
			SeDebugPrivilege
			SeSystemEnvironmentPrivilege
			SeLoadDriverPrivilege
			SeImpersonatePrivilege

**Comment by rossbrower** [comment] 2018-01-11 22:29
Just for clarity if I put back the RC0 bits the FQDN works fine.

**Comment by rossbrower** [comment] 2018-01-11 23:00
@akallabeth let me know if you need more information.

**Comment by akallabeth** [comment] 2018-01-12 07:49
@rossbrower Ok, one last question, is your package compiled with ```-DWITH_GSSAPI=ON```? There was the addition of basic kerberos support by @dodo040 
There have been some reports that this is not working for all use cases.

**Comment by cedrozor** [comment] 2018-02-08 13:48
I have the same exact issue since RC0 when using an FQDN, either with a direct connection or through a connection broker redirection. I ensured the password is not expired, of course,

It may be an openssl issue (using the 1.0.2n), I tried with 1.1.x but wasn't able to build (will recheck later).

Anyway, what I did as a workaround was to resolve the target FQDN and connect with the IP (https://github.com/cedrozor/FreeRDP/blob/master/libfreerdp/core/connection.c#L263). It's clearly not ideal, so it's just that, a workaround, waiting for better (given the issue is not due to an openssl misconfiguration).

While testing that, I also found an issue with the client IP resolution, when using an ipv6 address. the method *freerdp_tcp_get_ip_address* returns null in such case. I adapted the method to use a **sockaddr_in** struct for ipv4 addresses and a **sockaddr_in6** for ipv6 (https://github.com/cedrozor/FreeRDP/blob/master/libfreerdp/core/tcp.c#L678).

Please correct me if I missed something; otherwise I can do a PR.

**Comment by akallabeth** [comment] 2018-02-08 15:33
@cedrozor Already created pull #4411 to resolve that issue.

**Comment by akallabeth** [comment] 2018-02-13 11:11
Closing as resolved, reopen if still an issue.

**Closed by akallabeth** 2018-02-13 11:11 UTC
Labels: client, fixed-waiting-test
