### ISSUE TITLE
FreeRDP issues with OpenSSL 3.0 and gateway

### ISSUE THREAD

**Issue by koe0005** [FreeRDP/FreeRDP#7797] opened 2022-04-14 14:56 UTC
Hello,

We use xfreerdp 2.3.0 on Ubuntu 21.10 to connect to a Windows Terminal Server 2019 via RDP Gateway.
Now we made an update to Ubuntu 22.04 with xfreerdp 2.6.1  using the same parameters.
It seems that authentication works but application then stalls.
Parameters used are:

xfreerdp /v:ts.remote.net /g:gw.remote.net gt:/rpc /u:user /p:pass /cert:ignore /auth.only /log-level:Debug

Playing around with different values on /gt or /sec didn't help.

See attached Logfiles form 22.10 an 22.04

Regards Helmut

[2110_xfreerdp.log](https://github.com/FreeRDP/FreeRDP/files/8490170/2110_xfreerdp.log)
[2204_xfreerdp.log](https://github.com/FreeRDP/FreeRDP/files/8490172/2204_xfreerdp.log)

**Comment by akallabeth** [comment] 2022-04-15 07:33
@koe0005 sure you are using `/auth-only`? that will disconnect right after authentication succeeds.
As for error analysis, sorry, not enough information to tell what is going on there, I can only tell that I have access to a gateway/broker setup (server 2019) and can connect with `2.6.1` and `master` just fine (include redirection to final target host)

**Comment by koe0005** [comment] 2022-04-15 10:04
@akallabeth i used /auth-only for test, because program doesn't come back and i have to interrupt it with ctrl-c.
See attached the logfile with loglevel TRACE and without /auth-only.
[2204_xfreerdp.2.log](https://github.com/FreeRDP/FreeRDP/files/8495344/2204_xfreerdp.2.log)

**Comment by akallabeth** [comment] 2022-04-15 15:36
that is indeed strange.
do you happen to know how your server is configured?

have a few test setups I can test with and can´t reproduce such an issue here, so any hint appreciated.

(also, does `/gt:http` work for you or is your gateway specifically configured for only `/gt:rpc`?)

**Comment by koe0005** [comment] 2022-04-19 08:19
@akallabeth i will try to get some information from hosting company.

**Comment by koe0005** [comment] 2022-04-19 09:10
@akallabeth another strange behavour: if i use xfreerdp 2.3.0 on Ubuntu 21.04 connection works with all /gt:auto|rpc|http options.
Using xfreerdp 2.3.0 on Ubuntu 21.10, only option /gt:rpc works.

**Comment by akallabeth** [comment] 2022-04-19 09:17
this sounds like your server is using outdated encryption settings (we use `OpenSSL` for that, which might have hardened settings for newer distros)
Can you do a local build with current versions to eliminate possible packaging issues?

(e.g. do a `apt build-dep freerdp2-x11` to install required dependencies and then run `cmake -GNinja -DCMAKE_INSTALL_PREFIX=/tmp/freerdp -DBUILD_TYPE=Debug -Hsource_dir -Bsome_build_dir && cmake --build some_build_dir --target install` should do the trick, might complain about some still missing `-dev` package though) or test with our nightly packages?

**Comment by koe0005** [comment] 2022-04-19 11:34
@akallabeth built a new version on 22.04 using the following parameters:
xfreerdp /v:ts.remote.net /g:gw.remote.net gt:/rpc /u:user /p:pass /cert:ignore /log-level:TRACE
See attached the log file. Should i try it with special environment variables?

[2204_xfreerdp.3.log](https://github.com/FreeRDP/FreeRDP/files/8512586/2204_xfreerdp.3.log)

**Comment by akallabeth** [comment] 2022-04-19 12:33
@koe0005 could you try with `/gt:http,no-websockets`? it might be your server just does not support websockets and always tries to use these (it looks like `/gt:rpc` does not disable it)

**Comment by akallabeth** [comment] 2022-04-19 12:52
@koe0005 We´ve fixed that on master now with #7808 , so if you rebuild from current master it should give you some different log

**Comment by koe0005** [comment] 2022-04-19 13:06
@akallabeth ok, made a new build and tried /gt:http,no-websockets
Here is the log but had to interrupt again with ctrl-c.
[2204_xfreerdp.4.log](https://github.com/FreeRDP/FreeRDP/files/8513196/2204_xfreerdp.4.log)

**Comment by koe0005** [comment] 2022-04-19 13:12
@akallabeth Just another hint: Remote site has a self-signed certificate with the following parameters:
Protocol version: TLSv1.2
Ciphersuite: ECDHE-RSA-AES256-GCM-SHA384
Hash used: SHA512
Signature type: RSA
Supported Elliptic Curve Point Formats: uncompressed:ansiX962_compressed_prime:ansiX962_compressed_char2
Server Temp Key: ECDH, prime256v1, 256 bits

**Comment by akallabeth** [comment] 2022-04-19 13:14
@koe0005 certificate with a cipher suite and a TLS version? doubt that ;)
but that stage has long passed with what you see in the log

**Comment by akallabeth** [comment] 2022-04-19 13:14
@koe0005 with the (updated) master you might also try `/gt:rpc` again, as now websocket is disabled for that branch by default.

**Comment by akallabeth** [comment] 2022-04-19 13:17
@koe0005 I don´t know how well you are with compiling and git, but you might try a `git bisect` between the tags `2.3.0` and `2.6.1` to find the commit that breaks it for you (as you told the 2.3.0 version still works)

**Comment by akallabeth** [comment] 2022-04-19 13:20
but from the diff it most likely is the `websocket` support which seems to be not working with your server.

**Comment by koe0005** [comment] 2022-04-19 13:21
@akallabeth I tried it already with /gt:rpc but didn't work.
Above was the output of the gateway against the command:

> echo | openssl s_client -connect gw.remote.net:443 -brief

and cut off private informations

**Comment by koe0005** [comment] 2022-04-19 13:21
Will try some builds.

**Comment by koe0005** [comment] 2022-04-19 14:19
@akallabeth So i did a build party  on Ubuntu 21.10 and Ubuntu 22.04:
On 21.10 all builds work with /gt:rpc - linked against libssl.so.1.1
On 22.04 no build works with any /gt:xxx - linked against libssl.so.3, libssl.so.1.1 isn't available anymore
So it must be an issue with libssl3 versus libssl1.1

**Comment by akallabeth** [comment] 2022-04-19 14:28
@koe0005 ok, thank you for the debugging.
So we need to investigate if there is still something to fix for full openssl 3.0 support

**Comment by ondrejholy** [comment] 2022-04-20 13:28
Just a note that this looks like a duplicate of https://github.com/FreeRDP/FreeRDP/issues/7449.

**Comment by akallabeth** [comment] 2022-04-20 14:06
@ondrejholy thank you, true.

**Closed by akallabeth** 2022-04-20 14:06 UTC
Labels: blocker, help-wanted
