### ISSUE TITLE
in xfreerdp-2.0.0 rdweb two application launch with only one process, it should be different process

### ISSUE THREAD

**Issue by jignesh-kumar** [FreeRDP/FreeRDP#4536] opened 2018-04-04 10:49 UTC
first application(calculator) launch having pid 5123, if i lunch another application(notepad pid 5125) from same sever on same system than first process(pid 5123) goes exist and that application (calculator) still running. in "ps -ax" only 5125 is only running but both application  calculator and notepad are running.

**Comment by akallabeth** [comment] 2018-04-04 12:15
Please be a bit more verbose and answer the basic questions from the template or this link https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by ppokhriyal** [comment] 2018-04-07 11:26
@jignesh-kumar 

While Launching Second  application from "rdweb server" after the launch of First application. First application process id is not visible in "ps -aux" command.

**Comment by akallabeth** [comment] 2018-04-07 12:35
Could you give some details of your setup as requested in the issue template?
There are a million ways to configure such setups so those details are essential to analyze/recreate your issues

**Comment by gnshkl1** [comment] 2018-06-04 10:17
@akallabeth , i think @jignesh-kumar is pointing the issue with rail remote appliations lauched from same server with single PID instead of muliple PID for multiple remote applications.
 i have also seen same issue before .
May be Freerdp is designed to work like this .

**Comment by akallabeth** [comment] 2018-11-22 10:03
Closing as duplicate of #3032

**Closed by akallabeth** 2018-11-22 10:03 UTC
Labels: waiting-feedback
