### ISSUE TITLE
libfreerdp2.so.2.0.0) Makes vinagre segfault failure

### ISSUE THREAD

**Issue by mg169706** [FreeRDP/FreeRDP#6571] opened 2020-11-12 10:36 UTC
**Found a bug? - We would like to help you and smash the bug away.**
1. __Please don't "report" questions as bugs. For these (questions/build instructions/...) please use one of the following means of contact:__
   * We are reachable via IRC _#freerdp on freenode_
   * We are reachable via mailing list <freerdp-devel@lists.sourceforge.net>
   * Try our mailing list for discussions/questions
1. Before reporting a bug have a look into our issue tracker to see if the bug was already reported and you can add some additional information.
1. If it's a __new__ bug - create a new issue.
1. For more details see https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Describe the bug**
Running VirtualBox 6.0.24 on Debian 10.6.0 (Kernel verion 4.19.152-1), I was trying to connect to a virtual machine via RDP. Host port was configured to 33890 and the guest port as 3389. I tried connecting with Remote Desktop Viewer, but it just exited when trying to connect. the syslog reported the following:

Nov 12 10:03:08 A402000895 kernel: [57986.823833] vinagre[3150]: segfault at 9 ip 00007f5b6e2f47c8 sp 00007ffd747b92d0 error 4 in libfreerdp2.so.2.0.0[7f5b6e231000+da000]
Nov 12 10:03:08 A402000895 kernel: [57986.823840] Code: 00 00 00 c3 66 0f 1f 44 00 00 31 c0 c3 0f 1f 44 00 00 48 85 ff 0f 84 94 00 00 00 41 54 49 89 fc 55 49 8d ac 24 38 fa 00 00 53 <48> 8b 7f 08 49 8d 5c 24 38 e8 aa ee f3 ff 49 8b 7c 24 18 e8 c0 e3

**To Reproduce**
Assuming the crash is to do with the libfreerdp2.so.2.0.0, just try connecting to any virtual machine using Remote Desktop Viewer on Debian 10.6.0 with the same kernel version.

**Expected behavior**
I expected to be able to connect to the virtual machine running within VirtualBox

**Screenshots**
N/A

**Application details**
* FreeRDP version (`xfreerdp /version`)
This is FreeRDP version 2.0.0-dev5 (2693389a+debian)

* Command line used:
N/A. Using Remote Desktop Viewer GUI

* Output of `xfreerdp /buildconfig`:
This is FreeRDP version 2.0.0-dev5 (2693389a+debian)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1
                     HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1
                     HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1
                     WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON
                     WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF
                     WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF
                     WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF
                     WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF
                     WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1
                     WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON
                     WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0
                     WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF
                     WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1
                     WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF
                     WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON
                     WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RELWITHDEBINFO
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp2-SZLsIr/freerdp2-2.0.0~git20190204.1.2693389a+dfsg1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
                     -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden
                     -Wimplicit-function-declaration -Wredundant-decls -g -DWINPR_DLL
Compiler:            GNU, 8.3.0
Target architecture: x64

* OS version connecting to (server side)
Ubuntu 20.04 (kernel version 5.4.0-42-generic)
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Debian 10.6.0
 - Architecture: amd64

**Additional context**
None

**Comment by akallabeth** [comment] 2020-11-13 11:34
@mg169706 can you reproduce this with `xfreerdp` bundled with debian? If not I´d ask vinagre if they know something.

**Comment by pnowack** [comment] 2020-12-28 10:04
Vinagre is since 2016 unmaintained (last release 3.22). It also doesn't use FreeRDP 2.x, but FreeRDP 1.x upstream. It only uses FreeRDP 2.x in some cases, because several distributions (Arch, etc.) patch Vinagre downstream with a patch to work with FreeRDP 2.x.  

So, Vinagre may work for you or not, there is however no guarantee. In any case, you should avoid Vinagre though as it does not support codecs to reduce bandwidth usage and has other issues that won't be fixed any more (such as no clipboard support or showing wrong cursor, etc.).  
Even if there is a patch upstream in a merge request, it won't be reviewed any more, as Vinagre is unmaintained.

**Comment by akallabeth** [comment] 2021-01-02 10:20
ok, so closing this as `not a bug on our side`

**Closed by akallabeth** 2021-01-02 10:20 UTC
Labels: waiting-feedback
