### ISSUE TITLE
screen artefacts with Remote app

### ISSUE THREAD

**Issue by boospy** [FreeRDP/FreeRDP#3997] opened 2017-06-10 01:24 UTC
Nice Evening, 

i use here actual nightly build since some month. The problem es that i have, when i use RDP with Remoteapps, i have some Artefacts on rightclick. Sometimes they gone away, but sometimes the stay. 

My System is an KDE-Neon 5.10. But it is not really depending on that, or on the Compositing. It is the same with an Fluxbox. I call the application like this:

`xfreerdp /d:tux.local /u:$USER /p:secret +fonts  +clipboard  /cert-ignore   /v:server.tux.local /app:"||StepsExplorer" /jpeg /jpeg-quality:100 /gdi:hw +window-drag  /disp /drive:HOME,/home/$USER/Downloads`

Screeshot also attached. 
![screenshot_20170606_204828](https://user-images.githubusercontent.com/7432752/26998903-4a766c2e-4d8c-11e7-9b9d-009c379255fe.png)

**Comment by boospy** [comment] 2017-06-12 22:13
No, sorry, same problem also without this options...

**Comment by thanasis1885** [comment] 2017-08-14 09:24
I also have the exact same problem, I'm using
 `xfreerdp /gdi:sw /v:server /u:user /p:password /disp +fonts +clipboard /cert-ignore /app:"||Appname" ` 
with /gdi:sw or /gdi:hw, also same thing happens without the /disp +fonts +clipboard options
CDM output on Linux 

> [12:21:01:847] [28582:28583] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[12:21:01:847] [28582:28583] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rail
[12:21:01:847] [28582:28583] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[12:21:01:001] [28582:28583] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[12:21:01:001] [28582:28583] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[12:21:01:005] [28582:28583] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[12:21:01:005] [28582:28583] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp

Ubuntu Linux 16.04.3 LTS   4.10.0-32-generic

**Comment by thanasis1885** [comment] 2017-08-14 20:00
This is a duplicate of https://github.com/FreeRDP/FreeRDP/issues/3480 
also the same problem appear on https://github.com/FreeRDP/FreeRDP/issues/3444

**Comment by akallabeth** [comment] 2017-12-20 15:29
duplicate

**Closed by akallabeth** 2017-12-20 15:29 UTC
Labels: channel:rail, waiting-feedback
