### ISSUE TITLE
Shadow server segfaults when Win10 client connects

### ISSUE THREAD

**Issue by SriRamanujam** [FreeRDP/FreeRDP#3978] opened 2017-05-26 00:04 UTC
Hi,

On both MacOS and Linux, the shadow server code segfaults when a Win10 client connects. 

MacOS:

```
(lldb) bt
* thread #8, stop reason = EXC_BAD_ACCESS (code=2, address=0x70000717d000)
  * frame #0: 0x00007fff939caec9 libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 41
    frame #1: 0x00007fff9387342e libsystem_c.dylib`__memcpy_chk + 22
    frame #2: 0x000000010040eec0 libfreerdp-server2.2.dylib`Stream_Write(_s=0x0000000102114d10, _b=0x000070000717aaf0, _n=118991416) at stream.h:219
    frame #3: 0x000000010040efc5 libfreerdp-server2.2.dylib`rdpgfx_write_h264_avc420(s=0x0000000102114d10, havc420=0x000070000717a9b8) at rdpgfx_main.c:555
    frame #4: 0x000000010040e79d libfreerdp-server2.2.dylib`rdpgfx_write_surface_command(s=0x0000000102114d10, cmd=0x000070000717aa00) at rdpgfx_main.c:618
    frame #5: 0x000000010040b897 libfreerdp-server2.2.dylib`rdpgfx_send_surface_frame_command(context=0x00000001020214f0, cmd=0x000070000717aa00, startFrame=0x000070000717a9f8, endFrame=0x000070000717a9f0) at rdpgfx_main.c:771
    frame #6: 0x00000001000a02ce libfreerdp-shadow2.2.dylib`shadow_client_send_surface_gfx(client=0x0000000103830400, pSrcData="", nSrcStep=7680, nXSrc=0, nYSrc=0, nWidth=1920, nHeight=1200) at shadow_client.c:775
    frame #7: 0x000000010009ecf1 libfreerdp-shadow2.2.dylib`shadow_client_send_surface_update(client=0x0000000103830400, pStatus=0x000070000717ac40) at shadow_client.c:1272
    frame #8: 0x000000010009cd04 libfreerdp-shadow2.2.dylib`shadow_client_thread(client=0x0000000103830400) at shadow_client.c:1579
    frame #9: 0x000000010011a0a1 libwinpr2.2.dylib`thread_launcher(arg=0x0000000102204050) at thread.c:320
    frame #10: 0x00007fff939d193b libsystem_pthread.dylib`_pthread_body + 180
    frame #11: 0x00007fff939d1887 libsystem_pthread.dylib`_pthread_start + 286
    frame #12: 0x00007fff939d108d libsystem_pthread.dylib`thread_start + 13
```

Linux:

```
(gdb) bt
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:244
#1  0x00007ffff1d07fcb in memcpy (__len=4154151141, __src=<optimized out>, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string3.h:53
#2  Stream_Write (_n=4154151141, _b=<optimized out>, _s=0x7fffd466bf90) at /home/abuild/debbuild/BUILD/FreeRDP-2.0.0+20170522.1495444325~1.git.48163a27d/winpr/include/winpr/stream.h:219
#3  rdpgfx_write_h264_avc420 (havc420=0x7fffe9b54b00, s=0x7fffd466bf90)
    at /home/abuild/debbuild/BUILD/FreeRDP-2.0.0+20170522.1495444325~1.git.48163a27d/channels/rdpgfx/server/rdpgfx_main.c:555
#4  rdpgfx_write_surface_command (s=s@entry=0x7fffd466bf90, cmd=cmd@entry=0x7fffe9b54bf0)
    at /home/abuild/debbuild/BUILD/FreeRDP-2.0.0+20170522.1495444325~1.git.48163a27d/channels/rdpgfx/server/rdpgfx_main.c:618
#5  0x00007ffff1d085b3 in rdpgfx_send_surface_frame_command (context=0x7fffd4019f40, cmd=0x7fffe9b54bf0, startFrame=<optimized out>, endFrame=0x7fffe9b54a90)
    at /home/abuild/debbuild/BUILD/FreeRDP-2.0.0+20170522.1495444325~1.git.48163a27d/channels/rdpgfx/server/rdpgfx_main.c:771
#6  0x00007ffff63d6a01 in shadow_client_send_surface_gfx (nXSrc=0, nYSrc=0, nHeight=768, nWidth=1024, nSrcStep=4096, 
    pSrcData=0x7fffd1fff010 "~iK\377~iK\377~jL\377~iK\377}hJ\377}hJ\377}hJ\377~iK\377~iK\377~iK\377~iK\377~iK\377~iK\377~iK\377~iK\377~iK\377~iK\377~iK\377~iK\377~iK\377~iK\377~iK\377~iK\377~iK\377~iK\377~jL\377~jL\377~jL\377~jL\377~jL\377\177jM\377\177jM\377~iK\377~jL\377\177jM\377\177jM\377\200kN\377\200kN\377\177jM\377\177jM\377\177jM\377\177jM\377\177jM\377\177jM\377\177jM\377\177jM\377\177jM\377\177jM\377\201lN\377\201lN\377"..., client=0x7fffc000e3e0)
    at /home/abuild/debbuild/BUILD/FreeRDP-2.0.0+20170522.1495444325~1.git.48163a27d/server/shadow/shadow_client.c:771
#7  shadow_client_send_surface_update (pStatus=<synthetic pointer>, client=0x7fffc000e3e0)
    at /home/abuild/debbuild/BUILD/FreeRDP-2.0.0+20170522.1495444325~1.git.48163a27d/server/shadow/shadow_client.c:1268
#8  shadow_client_thread (client=<optimized out>) at /home/abuild/debbuild/BUILD/FreeRDP-2.0.0+20170522.1495444325~1.git.48163a27d/server/shadow/shadow_client.c:1575
#9  0x00007ffff66511f2 in thread_launcher (arg=0x7fffc00464f0) at /home/abuild/debbuild/BUILD/FreeRDP-2.0.0+20170522.1495444325~1.git.48163a27d/winpr/libwinpr/thread/thread.c:320
#10 0x00007ffff79b96fa in start_thread (arg=0x7fffe9b55700) at pthread_create.c:333
#11 0x00007ffff56f1b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by akallabeth** [comment] 2017-06-12 07:47
@SriRamanujam Could you attach your build configuration? I'm failing to reproduce, maybe you have a different H264 encoder backend compiled in?

**Comment by SriRamanujam** [comment] 2017-06-12 17:43
```
cmake   -DCMAKE_SKIP_RPATH=FALSE \
        -DCMAKE_SKIP_INSTALL_RPATH=FALSE \
        -DWITH_PULSE=ON \
        -DWITH_CHANNELS=ON \
        -DBUILTIN_CHANNELS=ON \
        -DWITH_CUPS=ON \
        -DWITH_PCSC=ON \
        -DWITH_JPEG=ON \
        -DWITH_GSTREAMER_0_10=OFF \
        -DWITH_GSTREAMER_1_0=ON \
        -DWITH_GSM=ON \
        -DCHANNEL_URBDRC=ON \
        -DCHANNEL_URBDRC_CLIENT=ON \
        -DWITH_SERVER=ON \
        -DWITH_X264=ON \
        -DBUILD_TESTING=OFF \
        -DCMAKE_BUILD_TYPE=RELWITHDEBINFO
```

That's the cmake conf I passed for the Linux build, the MacOS build was a bit more minimal but more-or-less the same thing.

**Comment by akallabeth** [comment] 2017-06-13 10:57
@SriRamanujam Well, looks like we found the culprit. You do not have H264 support compiled in (OpenH264 is currently the only server side supported option), so ensure ```-DWITH_FFMPEG=OFF``` and ```-DWITH_OPENH264=ON```. Have to look if the GFX caps incorrectly announce AVC modes if no H264 encoder/decoder is enabled.

**Comment by SriRamanujam** [comment] 2017-06-19 20:32
Any updates on this? I'd be happy to help out any way I can, pcap dumps from the Windows side, etc.

**Comment by timofonic** [comment] 2017-07-18 01:01
But what about if someone doesn't want to use that CISCO blob? Why not provide optional support for H264 with FFMPEG/X264?

**Comment by akallabeth** [comment] 2017-07-18 05:31
@timofonic Contributions are welcome ;) we're currently busy with other issues in this project.

**Comment by akallabeth** [comment] 2017-07-18 05:32
As update, #4044 should fix some H264 related issues, including compiler error/warnings for partially/not supported backends.

**Comment by akallabeth** [comment] 2017-07-24 08:20
So, I've added basic FFMPEG support for encoder in #4053 but it will require some testing and adjusting the H264 parameter setup to get it working properly. Anyone time to test?

**Comment by akallabeth** [comment] 2017-11-13 14:28
FFMPEG encoder support has been merged, reopen if still an issue.

**Closed by akallabeth** 2017-11-13 14:28 UTC
Labels: fixed-waiting-test
