### ISSUE TITLE
connection failes with ERRINFO_INVALID_INPUT_PDU_MOUSE

### ISSUE THREAD

**Issue by RoadRunnr** [FreeRDP/FreeRDP#1366] opened 2013-07-23 11:32 UTC
connection to Windows Server 2k8 R2 failes with:

ERRINFO_INVALID_INPUT_PDU_MOUSE (0x000010D0):
(a) A Slow-Path Mouse Event (section 2.2.8.1.1.3.1.1.3) or Extended Mouse Event (section 2.2.8.1.1.3.1.1.4) has been received with an invalid pointerFlags field.
(b) A Fast-Path Mouse Event (section 2.2.8.1.2.2.3) or Fast-Path Extended Mouse Event (section 2.2.8.1.2.2.4) has been received with an invalid pointerFlags field.
Failed to check FreeRDP file descriptor

**Comment by akallabeth** [comment] 2017-11-16 12:12
Mouse wheel is now only sent when supported.

**Comment by akallabeth** [comment] 2017-11-20 16:31
Could not reproduce locally, closing.
Reopen if you experience different results.

**Closed** 2017-11-22 10:13 UTC
Labels: fixed-waiting-test
