### ISSUE TITLE
Unable to exit fullscreen via CTRL+ALT+RETURN combination when running with -floatbar and using one monitor

### ISSUE THREAD

**Issue by stilyan** [FreeRDP/FreeRDP#5047] opened 2018-11-21 16:00 UTC
Running custom build of freerdp (master as of 18 Nov) with `-floatbar`, `/f` and `/multimon`
On dual monitor setups exiting from fullscreen via ctrl+alt+return works fine, no output in syslog
On single monitor setups exiting from fullscreen via ctrl+alt+return is not possible. The window tries resizing and then returns to fullscreen.

The following output is recorded in syslog:
`org.gnome.Shell.desktop[1581]: Window manager warning: Treating resize request of legacy application 0x2000001 (FreeRDP: 1) as a fullscreen request`

freerdp is on Ubuntu 18.04.1 LTS with default desktop env - gnome , version .. idk which package to look for, but versions 3.28.1 and 3.28.3 are dominating in output from dpkg --list |grep gnome
remote VM is Windows Server 2016

**Comment by akallabeth** [comment] 2018-11-22 08:36
@stilyan does it work with the nightly packages? Just tried this with gnome on xorg and gnome on wayland and it works here...

**Comment by stilyan** [comment] 2018-11-22 16:20
Same with nightly as of 22 Nov.
Launching like with this script
`#!/bin/sh
/opt/freerdp-nightly/bin/xfreerdp \
-window-drag \
-menu-anims \
-themes \
+fonts \
/bpp:32 \
/f \
-decorations \
-compression \
/audio-mode:0 \
/mic:format:1 \
/sound:latency:50 \
/multimon \
-floatbar \
/v:$1 \
/u:$2 \
/p:$3
`

Will try smart-sizing later and let you know.

**Comment by stilyan** [comment] 2018-11-23 06:55
Works with /smart-sizing on single monitor setups
Using smart-sizing with dual monitor setups however minimizes the RDP screen to fit a single display instead of both displays when smart-sizing is not used.

**Comment by akallabeth** [comment] 2018-11-23 10:01
@stilyan Ok, the multimonitor smart sizing issue is another bug. Should restore to multiple screens if that was initially the case.
As for the single monitor case, looks like another interesting variation of the how to get a fullscreen window accross a variety of window managers opera :/
From what I can telly you is that in your case the WM thinks the application wants to be fullscreen (as the window size matches the monitor resolution) and ignores our request to set the windowed mode.

**Comment by stilyan** [comment] 2018-11-23 10:19
> From what I can telly you is that in your case the WM thinks the application wants to be fullscreen (as the window size matches the monitor resolution) and ignores our request to set the windowed mode.

Thanks @akallabeth , I presumed the same thing is happening.

> Ok, the multimonitor smart sizing issue is another bug. Should restore to multiple screens if that was initially the case.

Should I report or there's an existing issue ?

**Comment by akallabeth** [comment] 2018-11-23 10:33
@stilyan Best open a new issue for that.
Tried it here locally and it restores to multimonitor fullscreen again when pressing `ctrl+alt+enter` even after resizing and moving the window around.
Might have something to do with your environment, so best add all these details there.

**Comment by akallabeth** [comment] 2018-12-18 08:16
Ok, tried also with my ubuntu `18.04` and `18.10` installs @home and could not reproduce.
Therefore closing.
Most likely some extension / setting in your user account. Try to create a test user, log in with defaults and try the same there.

**Closed by akallabeth** 2018-12-18 08:16 UTC
Labels: client, waiting-feedback, x11
