### ISSUE TITLE
Connection to Windows 10 fails after March 13th windows update

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#4483] opened 2018-03-13 21:53 UTC
A couples of Remmina users reported failure to connect to updated windows 10 1709 and 1803. See remmina issues [1512](https://github.com/FreeRDP/Remmina/issues/1512) and [1513](https://github.com/FreeRDP/Remmina/issues/1513).

A quick test of connecting with xfreerdp to a couple of updated Windows 10 gives the following results:
```
giovanni@uno:~$ xfreerdp /v:192.168.56.2 /u:giovanni
[22:36:43:882] [11345:11346] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
Password: 
[22:36:43:166] [11345:11346] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_PASSWORD_CERTAINLY_EXPIRED [0x0002000F]
[22:36:43:166] [11345:11346] [ERROR][com.freerdp.core.transport] - BIO_read returned an error: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
```
As you can see, the error I get is ERRCONNECT_PASSWORD_CERTAINLY_EXPIRED, but the password is not expired. I tried to reset the password, with no success. Also connecting from an older Windows 10 (1703) MS rdp client to the updated Windows 10 works with no problems.

**Comment by kovrom** [comment] 2018-03-13 22:57
As I mentioned in #4449, for a temp workaround put KB4088776 to the Absent state (by uninstalling the update) to make the system reachable again.

**Comment by couilllard45682** [comment] 2018-03-14 02:27
I confirm this issue as well on Windows 2k8r2 with Remmina (Ubuntu) and KDRC (Fedora). Uninstalling KB4088875 work around the issue, but it's not a acceptable long term fix. 
Using directly xfreer on impacted server does work.

**Comment by akallabeth** [comment] 2018-03-14 08:17
Closing as duplicate of #4449

**Closed by akallabeth** 2018-03-14 08:17 UTC
