### ISSUE TITLE
Invalid Atom parameter when upgrading from Fedora 39 to 40 FreeRDP version 3.5.1 (n/a)

### ISSUE THREAD

**Issue by michaelschefczyk** [FreeRDP/FreeRDP#10310] opened 2024-06-26 16:34 UTC
**Describe the bug**
I have been using freerdp on Fedora under QubesOS for a long time to connect to windows servers in the LAN. The last version used was Fedora 39, with this command line string: 

/usr/bin/xfreerdp /multimon /u:user /d:domain /v:[IP or internally resolvable name] /kbd:[Language]/sound:sys:alsa,format:1,quality:high +fonts

Upgrading to Fedora 40, it sees that /kbd and /sound no longer work. To cure a Kerberos bug, one needs to add (including the quotes):  '/auth-pkg-list:!kerberos' resulting in the following string:

/usr/bin/xfreerdp /multimon /u:user /d:domain /v:[IP or internally resolvable name]  '/auth-pkg-list:!kerberos'

That leads to the following error: 

[ERROR][com.freerdp.client.x11] - [xf_error_handler]: BadAtom (invalid Atom parameter)

Such error is not very telling and it seems that BadAtom was not discussed for a long time.

**To Reproduce**
1. Use FreeRDP version 3.5.1 (n/a) under Fedora 40
2. Run /usr/bin/xfreerdp /multimon /u:user /d:domain /v:[IP or internally resolvable name]  '/auth-pkg-list:!kerberos'

**Expected behavior**
RDP connection working.

**Application details**
* FreeRDP version 3.5.1 (n/a)
* Fedora 40

**Comment by akallabeth** [comment] 2024-06-26 19:07
* well, `X11` is not very accommodating with regard to error handling. but since the `Atom` stuff is (mostly) in use for clipboard, can you check if this still occurs with `-clipboard`?
* as for `/sound` that works well here, any details?
* same for `/kbd` what is your issue there?

**Comment by esnovo** [comment] 2024-06-27 20:44
Same problem here, after upgrading to fedora 40 I can no longer use freerdp(v.3.5.1).
Passing -clipboard makes no difference. 
Below is the stack trace of the error:

```
~$ xfreerdp /u:vagrant /p:XXXXXXX /v:192.168.10.50  -clipboard
[22:40:33:580] [3557:00000de6] [INFO][com.freerdp.client.x11] - [xf_setup_x11]: Enabling X11 debug mode.
[22:40:35:01] [3557:00000de6] [WARN][com.freerdp.crypto] - [verify_cb]: Certificate verification failure 'self-signed certificate (18)' at stack position 0
[22:40:35:03] [3557:00000de6] [WARN][com.freerdp.crypto] - [verify_cb]: CN = castelblack.north.sevenkingdoms.local
[22:40:35:09] [3557:00000de6] [ERROR][com.winpr.sspi.Kerberos] - [kerberos_AcquireCredentialsHandleA]: krb5_parse_name (Configuration file does not specify default realm [-1765328160])
[22:40:35:10] [3557:00000de6] [ERROR][com.winpr.sspi.Kerberos] - [kerberos_AcquireCredentialsHandleA]: krb5_parse_name (Configuration file does not specify default realm [-1765328160])
[22:40:37:502] [3557:00000de6] [INFO][com.winpr.timezone] - [winpr_detect_windows_time_zone]: tzid: Europe/Berlin
[22:40:38:754] [3557:00000de6] [WARN][com.freerdp.core.license] - [license_read_binary_blob_data]: license binary blob::type BB_ERROR_BLOB, length=0, skipping.
[22:40:38:827] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [xf_error_handler]: BadAtom (invalid Atom parameter)
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 0: dli_fname=/lib64/libwinpr3.so.3 [0x7d1e888fc000], dli_sname=winpr_backtrace [0x7d1e88944d90]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 1: dli_fname=/lib64/libwinpr3.so.3 [0x7d1e888fc000], dli_sname=winpr_log_backtrace_ex [0x7d1e889466c0]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 2: dli_fname=xfreerdp [0x5e08bc220000], dli_sname=(null) [(nil)]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 3: dli_fname=/lib64/libX11.so.6 [0x7d1e884bd000], dli_sname=_XError [0x7d1e88504440]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 4: dli_fname=/lib64/libX11.so.6 [0x7d1e884bd000], dli_sname=(null) [(nil)]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 5: dli_fname=/lib64/libX11.so.6 [0x7d1e884bd000], dli_sname=_XReply [0x7d1e885062c0]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 6: dli_fname=/lib64/libX11.so.6 [0x7d1e884bd000], dli_sname=XGetAtomName [0x7d1e884e3b40]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 7: dli_fname=xfreerdp [0x5e08bc220000], dli_sname=(null) [(nil)]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 8: dli_fname=xfreerdp [0x5e08bc220000], dli_sname=(null) [(nil)]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 9: dli_fname=xfreerdp [0x5e08bc220000], dli_sname=(null) [(nil)]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 10: dli_fname=/lib64/libfreerdp3.so.3 [0x7d1e88600000], dli_sname=freerdp_connect [0x7d1e886c4d40]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 11: dli_fname=xfreerdp [0x5e08bc220000], dli_sname=(null) [(nil)]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 12: dli_fname=/lib64/libwinpr3.so.3 [0x7d1e888fc000], dli_sname=(null) [(nil)]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 13: dli_fname=/lib64/libc.so.6 [0x7d1e881ed000], dli_sname=(null) [(nil)]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 14: dli_fname=/lib64/libc.so.6 [0x7d1e881ed000], dli_sname=(null) [(nil)]
[22:40:38:828] [3557:00000de6] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 15: unresolvable, address=(nil)
X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  17 (X_GetAtomName)
  Atom id in failed request:  0xcacccf1f
  Serial number of failed request:  128
  Current serial number in output stream:  132
```

**Comment by michaelschefczyk** [comment] 2024-06-27 21:22
Thank you very much to both participants in this conversation.

I am running OubesOS (https://www.qubes-os.org/). The good part is that I can easily run Fedora 39 and 40 side by side. The bad part is that I am unable to exclude an influence of the OS.

If I run:

... kbd:German /sound:sys:alsa,format:1,quality:high +fonts '/auth-pkg-list:!kerberos'

I get:

[23:11:37:536] [1109:00000456] [ERROR][com.freerdp.client.x11] - [xf_error_handler]: BadAtom (invalid Atom parameter)
[23:11:37:538] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 0: dli_fname=/lib64/libwinpr3.so.3 [0x7b39ca0e4000], dli_sname=winpr_backtrace [0x7b39ca12cd90]
[23:11:37:541] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 1: dli_fname=/lib64/libwinpr3.so.3 [0x7b39ca0e4000], dli_sname=winpr_log_backtrace_ex [0x7b39ca12e6c0]
[23:11:37:541] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 2: dli_fname=/usr/bin/xfreerdp [0x5b3ca3f81000], dli_sname=(null) [(nil)]
[23:11:37:541] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 3: dli_fname=/lib64/libX11.so.6 [0x7b39c9fa1000], dli_sname=_XError [0x7b39c9fe8440]
[23:11:37:542] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 4: dli_fname=/lib64/libX11.so.6 [0x7b39c9fa1000], dli_sname=(null) [(nil)]
[23:11:37:542] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 5: dli_fname=/lib64/libX11.so.6 [0x7b39c9fa1000], dli_sname=_XReply [0x7b39c9fea2c0]
[23:11:37:542] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 6: dli_fname=/lib64/libX11.so.6 [0x7b39c9fa1000], dli_sname=XGetAtomName [0x7b39c9fc7b40]
[23:11:37:543] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 7: dli_fname=/usr/bin/xfreerdp [0x5b3ca3f81000], dli_sname=(null) [(nil)]
[23:11:37:543] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 8: dli_fname=/usr/bin/xfreerdp [0x5b3ca3f81000], dli_sname=(null) [(nil)]
[23:11:37:543] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 9: dli_fname=/usr/bin/xfreerdp [0x5b3ca3f81000], dli_sname=(null) [(nil)]
[23:11:37:543] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 10: dli_fname=/lib64/libfreerdp3.so.3 [0x7b39ca200000], dli_sname=freerdp_connect [0x7b39ca2c4d40]
[23:11:37:543] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 11: dli_fname=/usr/bin/xfreerdp [0x5b3ca3f81000], dli_sname=(null) [(nil)]
[23:11:37:544] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 12: dli_fname=/lib64/libwinpr3.so.3 [0x7b39ca0e4000], dli_sname=(null) [(nil)]
[23:11:37:544] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 13: dli_fname=/lib64/libc.so.6 [0x7b39c9c7c000], dli_sname=(null) [(nil)]
[23:11:37:544] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 14: dli_fname=/lib64/libc.so.6 [0x7b39c9c7c000], dli_sname=(null) [(nil)]
[23:11:37:544] [1109:00000456] [ERROR][com.freerdp.client.x11] - [winpr_log_backtrace_ex]: 15: unresolvable, address=(nil)
X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  17 (X_GetAtomName)
  Atom id in failed request:  0x9d6433bb
  Serial number of failed request:  128
  Current serial number in output stream:  132 

Omitting /kbd and /sound does not seem to make a difference. I am not aware how to add -clipboard to such string – at least without causing additional errors.

**Comment by esnovo** [comment] 2024-06-27 21:33
Just FYI. I also use Qubes, so the problem will be similar, which is why I decided to post a comment in this thread :)

**Comment by michaelschefczyk** [comment] 2024-06-28 04:58
Within Qubes, I did an in place upgrade of the Fedora template for the first time (in the past, I did always download fresh). I find it unlikely that downloading a fresh template would make a difference. @esnovo What is your view?

Should we post an issue at Qubes? So far, there is nothing at https://github.com/QubesOS/qubes-issues
Freerdp never seems to be a big topic at Qubes (for the good because it just works or because of low usage base).

**Comment by akallabeth** [comment] 2024-06-28 06:28
@esnovo @michaelschefczyk would be interesting to add a debug log line in `Safe_XGetAtomName` to check which `Atom` is failing.

**Comment by michaelschefczyk** [comment] 2024-06-28 06:34
I would be willing to do this. However, as I am not a developer, I would need further instructions, please. I am also practically restricted to using the package from the Fedora repo without building it myself. If a configuration setting is required somewhere, I will try it as soon as I understand what to do.

**Comment by akallabeth** [comment] 2024-06-28 07:15
@michaelschefczyk sorry then, you need to build yourself to do this.

**Comment by esnovo** [comment] 2024-06-28 16:38
> Within Qubes, I did an in place upgrade of the Fedora template for the first time (in the past, I did always download fresh). I find it unlikely that downloading a fresh template would make a difference. @esnovo What is your view?
> 
> Should we post an issue at Qubes? So far, there is nothing at https://github.com/QubesOS/qubes-issues Freerdp never seems to be a big topic at Qubes (for the good because it just works or because of low usage base).

I usually do an in-place upgrade as well, I don't think it's related as the upgrade should somehow mimic the fresh install of the distribution, but in any case, and to be safe, [better do a fresh install of the fedora vanilla template as suggested](https://www.qubes-os.org/doc/templates/fedora/#installing). You can install it, spin up an AppVm with the fresh template, see if it works, and remove the template/package. Unfortunately I don't have much space to do this myself.
Posting this in the Qubes issues might also be a good idea. 



> @michaelschefczyk sorry then, you need to build yourself to do this.

Can you provide instructions on how to do this?
I'm somewhat perplexed by the fact that the binary was built in such a way as to not allow this level of debug trace/details natively and one instead has to resort to modifying code and recompiling it to validate what it is doing.

**Comment by esnovo** [comment] 2024-06-28 16:55
I just saw that you've already merged this into the master, but I don't see a release reflecting this yet.
Can you please point me to one?

**Comment by michaelschefczyk** [comment] 2024-06-28 22:06
I did delete my Fedora 40 template upgraded in place, installed fresh and applied the same modifications as before (install few packages, mostly smartcard tools, freerdp, chromium & select language). The same situation occurs as with the in place upgrade. Hence, this is unlikely to be the issue. It might be related to the environment provided by QubesOS.

**Comment by d3adc0w** [comment] 2024-06-28 22:13
That's what I suspected. 
It might be something specific to how the template was backed up, but it would be nice to know what, as it worked fine with Fedora 23.

**Comment by akallabeth** [comment] 2024-07-01 08:05
> I just saw that you've already merged this into the master, but I don't see a release reflecting this yet. Can you please point me to one if there is one available?

there is none?
we only provide source and nightly packages, the rest is up to you

**Comment by akallabeth** [comment] 2024-07-01 08:08
> 
> > @michaelschefczyk sorry then, you need to build yourself to do this.
> 
> Can you provide instructions on how to do this? I assume it wouldn't be possible to perform this level of debug trace/details natively via a parameter on the binary instead of resorting to modifying code and recompiling it to validate what it does?

https://github.com/FreeRDP/FreeRDP/wiki/Compilation

your issue is not something that was expected (your `X11` lacks something) and not every function call is logged (that is a lot of work to do for no gain and a lot of performance loss)

**Comment by d3adc0w** [comment] 2024-07-01 13:51
I'm referring specifically to this [commit](https://github.com/FreeRDP/FreeRDP/pull/10319/commits/357a92ce5530b216e92892ff7d0c02f494adc163).

The instructions I'm looking for is not the compilation, although I appreciate that, but rather how to enable that debug log line you mentioned above?

**Comment by akallabeth** [comment] 2024-07-01 15:06
@d3adc0w ah, sorry, just add `/log-level:trace` to your command line.

**Comment by akallabeth** [comment] 2024-07-05 08:00
@d3adc0w @michaelschefczyk which environment do you use? stock fedora workstation/gnome or something different?

**Comment by michaelschefczyk** [comment] 2024-07-05 08:22
It is a Fedora 40 template within QubesOS: https://www.qubes-os.org/doc/templates/

I did also file at QubesOS: https://github.com/QubesOS/qubes-issues/issues/9327

**Comment by akallabeth** [comment] 2024-07-05 08:32
@michaelschefczyk ok, that is fine, but which window-manager/compositor/... is that template using?

**Comment by michaelschefczyk** [comment] 2024-07-05 10:22
Sorry, I this is the only case where I use Fedora and I am also unable to disentangle window-manager vs. compostior vs. display manager ... Could you please be so kind to state a command I can run in a terminal to provide the answer?

**Comment by akallabeth** [comment] 2024-07-05 11:53
@michaelschefczyk best post a screenshot, if you do not use something exotic then they are recognizable from the default themes

**Comment by michaelschefczyk** [comment] 2024-07-05 12:00
Sorry, this is a virtual machine within QubesOS (https://www.qubes-os.org/intro/). If FreeRDP works (as it does in Fedora 39), a window pops up (https://www.qubes-os.org/attachment/doc/r4.0-snapshot12.png). Given the concept of QubesOS, a screenshot would not be meaningful, I think. So far, I could at best take a screenshot of a KDE desktop showing a window looking upon a Windows Server OS via FreeRDP using Fedora 39.

**Comment by akallabeth** [comment] 2024-07-05 12:40
@michaelschefczyk ok. so it just shows the one application started? that smells like some custom window-manager/compositor. No time to check that now, already leaving.

would be great if someone could run an updated version (3.6.2 contains the extended logging) and check the resulting log for which `Atom` now actually fails.

**Comment by akallabeth** [comment] 2024-07-25 05:45
when #10426 is merged you should have the following entries in a log:
1. On creating the `Atom`: `"XInternAtom(<display id number>, <Atom name>, <Create true|false>) -> <Atom value>"` (remember the `Atom value` to `Atom name` mapping for later)
2. On use `XGetAtomName(<Atom value>)`
3. On error `X Error of failed request:  BadAtom (invalid Atom parameter)` -> that might be delayed

also, did check out qubes (just don´t have hardware to install it on, does not properly work in my `kvm`):
you should be able to execute some terminal (`XTerm`, ....) on the VM you use for running `xfreerdp`, then just do that, run `xfreerdp /v:host ... /log-level:trace 2>&1 |tee /tmp/log.txt` to run and log your connection.

when the error happens just check which `Atom name` there should be...

**Comment by rwiesbach** [comment] 2024-07-26 07:25
hey there. I have the same issue on Qubes with the fedora-40-xfce template.
I installed the pre-build nightly https://pub.freerdp.com/repositories/rpm/fedora/fedora-40/freerdp-nightly/

` 
freerdp-nightly        x86_64   3.0-0+0~20240726033813.1648~1.git11aeda6a9
Installing dependencies:
 SDL2_image             x86_64   2.8.2-4.fc40 
 javascriptcoregtk4.0   x86_64   2.44.1-2.fc40
 webkit2gtk4.0          x86_64   2.44.1-2.fc40 
`
it is names 3.0-0, but --version gives 3.6.2 (n/a)

log
[freerdp_trace_log_with_stderr.txt](https://github.com/user-attachments/files/16387747/freerdp_trace_log_with_stderr.txt)

**Comment by rwiesbach** [comment] 2024-07-26 07:36
noteworthy:  fedora 40 removed the "legacy" X11 session from KDE. I do not know weather xfce is a official fedora flavour, or weather the Qubes people may have used the kde version without X11 as a foundation of their template.
In theory there should be x-wayland, but maybe xfce does require legacy x11.

So hypothesis would be: kde version was used, xfce was added (likely kde removed) and that xfce does not mark parts of x11 as a dependency that freerdp requires but does not define as a dependency as before fedora 40 kde it has always been part of the base image.

That would mean it is not about the xfreerdp version but about X11 components in the template.
I'd try the current nightly rpm on fedora-38(-xfce), but right now I do not have time for this.

**Comment by rwiesbach** [comment] 2024-07-26 08:23
oh. installing the nightly on fedora-38 the filename is 3.0-0 as on fedora 40:
freerdp-nightly-3.0-0+0~20240505033816.1596~1.git61d3f1f20.x86_64

but xfreerdp --version still gives 2.11.7

so the logfiles maybe from the default fedora-40-version, not from the nightly.
autocompletion of free, xfree or night however does not recommend any other binary that might be the nightly, what is the nightly named, how do i execute it?

**Comment by rwiesbach** [comment] 2024-07-26 10:18
I did a diff `(diff 38.txt 40.txt)` on the (sorted) list of installed RPMs (without version numbers) between fedora38xfce (xfreerdp ok) and fedora40xfce (xfreerdp broken). I do not see anything related to x11 or rdp by the name, but its not like I have deep knowledge of all dependencies of x11 ... 

[rpm_diff.txt](https://github.com/user-attachments/files/16390213/rpm_diff.txt)

**Comment by rwiesbach** [comment] 2024-07-26 12:31
I tested a fedora 40 xfce live ISO and it works, so it is something about the qubes template.

I noticed that `freerdp2-libs and libwinpr2` are installed in the fedora 40 live ISO (at least after installing xfreerdp) but do not get installed by `sudo dnf install xfreerdp` on fedora-40-xfce on qubes (my forked fedora 40 xfce on qubes where I installed additional software does contain it however, likely they are a dependency of some other tool I installed).

using fedora-40-xfce on qubes with only xfreerdp installed (no other tool added compared to the template) has the same issue, so there is no conflict with any non-template rpm.

**Comment by rwiesbach** [comment] 2024-07-26 13:32
It seems that freerdp2-libs are the freerdp 2.x libs and freerdp-libs are the 3.x libs (why not freerdp3-libs? would that be to easy to understand?!). As a workaround, you can install the old version from rpm, fedora 39 or earlier, without dependencies:

```
sudo dnf remove freerdp
sudo rpm -i --nodeps OLD_FREERDP.rpm 
sudo dnf install freerdp2-libs
```
found it on rpmfind:
https://rpmfind.net/linux/fedora/linux/updates/39/Everything/x86_64/Packages/f/freerdp-2.11.7-1.fc39.x86_64.rpm

**Comment by michaelschefczyk** [comment] 2024-07-26 16:08
Thank you very much! I can confirm that this workaround does work was a workaround.

@rwiesbach did already post under qubes-issues - thanks for that as well.

Is there anything I can contribute to move from a workaround to a lasting soution?

**Comment by rwiesbach** [comment] 2024-07-26 16:29
@michaelschefczyk I dont think we can do anything more.
We will see what @akallabeth says after reading the logfile I provided.

My understanding is now that freerdp-nightly does only change the libs, as installing it after removing freerdp results in bash not knowing about a xfreerdp binary. Based on this I hope that the logs contain the "Atom parameter" details that akallbeth added to the code in order to debug this issue.

**Comment by akallabeth** [comment] 2024-07-26 19:12
On vacation for a week, will take time.

Nightly installs to /opt/freerdp-nightly so you need to call with full path.

The last posted logs suggest some invalid value during multitouch device enumeration (might be a red herring though)

Am 26. Juli 2024 16:29:34 UTC schrieb rwiesbach ***@***.***>:

**Comment by rwiesbach** [comment] 2024-07-29 19:40
when I use log-level trace on the nightly July 26th, I get a reproducable segfault.
So here is loglevel debug.

[debug_nightly.txt](https://github.com/user-attachments/files/16418322/debug_nightly.txt)


have a nice vacation.

**Comment by akallabeth** [comment] 2024-08-02 12:57
@rwiesbach ok, still not enough data to trace.
created https://github.com/FreeRDP/FreeRDP/pull/10441 to also log the variable name we´re trying to get the atom name for.

**Comment by rwiesbach** [comment] 2024-08-05 06:56
There is no new nightly available on https://pub.freerdp.com/repositories/rpm/fedora/fedora-40/freerdp-nightly/x86_64/

**Comment by akallabeth** [comment] 2024-08-07 07:20
should be fixed now @rwiesbach

**Comment by akallabeth** [comment] 2024-08-16 09:27
@rwiesbach any update on this?

**Comment by rwiesbach** [comment] 2024-08-16 11:10
[trace_nightly.txt](https://github.com/user-attachments/files/16636407/trace_nightly.txt)

Thanks for the reminder

**Comment by akallabeth** [comment] 2024-08-16 11:52
@rwiesbach ok, confirmed now.
the issue is a bug with `qubesdev button device (id: 6, mode: 7)` pointer device.
it has an invalid `Atom label` with value `0xbfe776b4`

nothing we can fix, the value is set but to an invalid value.

**Comment by akallabeth** [comment] 2024-08-16 12:01
@rwiesbach opened upstream bug report here: https://github.com/QubesOS/qubes-issues/issues/9412
maybe you can add the missing pieces there.

**Closed by akallabeth** 2024-08-16 12:01 UTC
Labels: waiting-feedback

**Comment by rwiesbach** [comment] 2024-08-16 18:13
Thanks a lot for your help tracking this non-freerdp-bug.
