### ISSUE TITLE
Random disconnections from RDP with TS Gateway

### ISSUE THREAD

**Issue by fjyihan** [FreeRDP/FreeRDP#2615] opened 2015-05-13 08:44 UTC
my tested with recent master。
 I use the following to establish a connection to my computer( win server 2008 r2 )
xfreerdp /g:rdgserver.company.com /gd:companydomain /gu:myusername /gp:mypassword /d:companydomain /u:myusername /p:mypassword /v:internal.computername.
I suspect the issue is not related to Server Side, I think it’s when the xfreerdp is receiving a lot of data like screen updates, it will fail and disconnect.

**Comment by hardening** [comment] 2015-05-13 08:51
Your bug looks verry much like a duplicate of https://github.com/FreeRDP/FreeRDP/issues/2431.

**Comment by fjyihan** [comment] 2015-05-13 09:04
@hardening yeah, I think so.

**Closed** 2015-05-20 15:24 UTC
Labels: duplicate
