### ISSUE TITLE
Out of sync audio

### ISSUE THREAD

**Issue by bowman762** [FreeRDP/FreeRDP#3731] opened 2017-01-30 15:19 UTC
Hello,

I'm trying to use freerdp (latest clone from git master) and I am having issues with out of sync audio when connecting to Windows Server 2016 RDS (note, I've not tested any other server OS) everything else works perfectly. The audio is in sync when I first connect, but during the course of watching a video, the audio gets more and more out of sync.

I've tried running on three different OS':
Ubuntu Server 14.04 (running OpenBox) 
Ubuntu Desktop 16.04
OpenSUSE Leap 42.2

The Ubuntus were compiled with the following cmake:
-DWITH_SSE2=ON -DWITH_PULSE=ON -DWITH_JPEG=ON -DWITH_X264=ON

The OpenSUSE used the latest stable nightly build.

I launch using the following commandline:

xfreerdp /multimedia:sys:pulse /multimon /sound:sys:pulse,format:1,quality:high -bitmap-cache -menu-anims -window-drag /microphone:sys:pulse /rfx /gfx:rfx +gfx-thin-client /gdi:hw /bpp:32 /audio-mode:0 /network:lan /f /u:<username> /p:<password> /cert-ignore /v:<server>

I have a feeling I've either compiled it missing something or I'm just using the wrong commandline to launch it.
Any help would be appreciated.

Thanks!

**Comment by akallabeth** [comment] 2017-02-06 09:21
Duplicate of #3398

**Closed by akallabeth** 2017-02-06 09:21 UTC
