### ISSUE TITLE
Cant connect to TerminalServer over Load Balancer / Broker

### ISSUE THREAD

**Issue by 1nd1r4** [FreeRDP/FreeRDP#10709] opened 2024-10-04 13:33 UTC
Dear freerdp team and contributors, 
I'm sorry in advance if this isn't a well done bug report, I am not a developer in the slightest and I'm kinda new to bug reporting. I'm happy to provide information if something is missing.

**Describe the bug**
I can't connect to a Windows Server 2019 Terminalserver over a Load Balancer (Connection Broker) over Remmina+FreeRDP when downloading it from the arch repositories. The connection fails after entering the credentials.

**To Reproduce**
0. Have Remmina and freerdp downloaded over the arch repo
1. Set up RDP connection with a Load balancer set in "Load balance info"
2. Click on Save
3. Connect to the server
4. Put in credentials
5. Error: Cant connect to the "" RDP server.

**Expected behavior**
A working connection. 

**Application details**
* FreeRDP version: 2:3.8.0-1
* Remmina version: 1.4.35
* Output of `xfreerdp /buildconfig`
* OS version connecting to (server side): Windows Server 2019

**Environment (please complete the following information):**
 - OS: GNU/Linux 
 - Version/Distribution: Arch
 - Architecture: amd64
 - Kernel: 6.11.1-arch1-1

**Additional info**
When using the Flatpak version I get two warnings, that the server certificate fingerprint has changed. The first warning is before entering the credentials. The fingerprint matches the broker server. In the second warning after putting in credentials the fingerprint matches the actual Terminalserver. But it actually works when accepting those warnings. Maybe this is related?

Thank you in advance for your hard work!

**Log**

[13:34:58:383] [51651:0000c9d4] [ERROR][com.winpr.sspi.Kerberos] - [kerberos_InitializeSecurityContextA]: krb5_get_credentials (Server not found in Kerberos database [-1765328377])
[13:34:58:383] [51651:0000c9d4] [WARN][com.winpr.sspi] - [winpr_InitializeSecurityContextA]: InitializeSecurityContextA status SEC_E_INTERNAL_ERROR [0x80090304]
[13:34:58:383] [51651:0000c9d4] [ERROR][com.freerdp.core.auth] - [credssp_auth_authenticate]: InitializeSecurityContext failed with SEC_E_INTERNAL_ERROR [0x80090304]
[13:34:58:383] [51651:0000c9d4] [ERROR][com.freerdp.core.rdp] - [rdp_recv_callback_int][0x55ae1c82bf10]: CONNECTION_STATE_NLA - nla_recv_pdu() fail
[13:34:58:383] [51651:0000c9d4] [ERROR][com.freerdp.core.rdp] - [rdp_recv_callback_int][0x55ae1c82bf10]: CONNECTION_STATE_NLA status STATE_RUN_FAILED [-1]
[13:34:58:383] [51651:0000c9d4] [ERROR][com.freerdp.core.transport] - [transport_check_fds]: transport_check_fds: transport->ReceiveCallback() - STATE_RUN_FAILED [-1]
[13:34:58:383] [51651:0000c9d4] [ERROR][com.freerdp.core] - [rdp_client_wait_for_activation]: ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]

**Comment by akallabeth** [comment] 2024-10-04 14:00
@1nd1r4 looks like a duplicate of https://github.com/FreeRDP/FreeRDP/issues/6508 but with a few nice findings (that the flatpak is working)
closing this, discussion can continue in referenced issue.

**Closed by akallabeth** 2024-10-04 14:00 UTC
