### ISSUE TITLE
DNS gateway issue.

### ISSUE THREAD

**Issue by sebastianuw** [FreeRDP/FreeRDP#4875] opened 2018-09-21 23:53 UTC
I found the following name resolution related bug with FreeRDP.

Our FreeRDP clients are on different networks than our RDS servers. Each network has a different DNS configuration. A firewall allows our FreeRDP clients to connect to our RDS gateways via RDP-HTTP. The session hosts behind the firewall do not have DNS entries on the FreeRDP clients' network.

With Microsoft's client and older FreeRDP clients (from April '18), this works with no problem.

With the current version of FreeRDP pulled from the master branch however, this fails. I receive these logs on our RDS gateways:
' The user "AWESOMEDOMAIN\FANTASTICUSER", on client computer "192.168.0.44", did not meet the resource authorization policy requirements and was therefore not authorized to resource "10.0.0.66". The following error occurred: "23002". '

However, if I add the session hosts' names to the FreeRDP clients' DNS server, the connection succeeds with this log on the RDS gateways:
' The user "AWESOMEDOMAIN\FANTASTICUSER", on client computer "192.168.0.44", connected to resource "sessionserver.awesomedomain.com". Connection protocol used: "HTTP".

It looks like if FreeRDP can't resolve the session host's name, it for some reason instructs the gateway to connect to an IP, which causes the security policy to fail (as the gateway policy wants a DNS name).

Command:

/usr/local/freerdp/bin/xfreerdp /usr/local/kiosk/rdp/gateway.rdp /cert-ignore /f /u:fantasticuser /gu:fantasticuser  /p:PASSWORD /gp:PASSWORD  /drive:hotplug,*  /sound:sys:pulse,format:1,quality:high  /microphone:sys:pulse,format:1,quality:high  /gt:http  +auto-reconnect  /network:lan

Build info:
$ /usr/local/freerdp/bin/xfreerdp /buildconfig
This is FreeRDP version 2.0.0-dev4 (0b7b9c0)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EVENTFD_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_VALGRIND_MEMCHECK_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=ON WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_KRB5=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=TRUE WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=0 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=ON WITH_URBDRC_CLIENT=on WITH_VALGRIND_MEMCHECK=ON WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls
Compiler:            GNU, 4.8.5
Target architecture: x64

OS:
FreeRDP client: Centos 7.5.1804
RDS Server: Windows Server 2016

**Comment by akallabeth** [comment] 2018-09-22 14:36
There should be a new commandline switch to set preference of connection type.
This was necessary as different setups have incompatible requirements.

**Comment by akallabeth** [comment] 2018-09-24 08:09
@sebastianuw Just checked, the new command line is for redirection only.
Gateway should work as it did previously, so if you know how, could you do a `git bisect` to find the commit that caused this (or can you provide a test login)?
Don't have such a setup to test, so it is hard to figure out what exactly is going on.

**Comment by akallabeth** [comment] 2018-10-03 08:15
@sebastianuw Any updates?

**Comment by sebastianuw** [comment] 2018-10-08 17:18
I ran git bisect, but it wasn't helpful. 

The last version I have that works is 103686e .

**Comment by akallabeth** [comment] 2018-10-09 07:13
@sebastianuw so e1c00b878dfd7f4e1c0ff42a60012991269bebf3 was still working? Which commit fixes the issue you had?
Sorry, have to guess here as I can not reproduce this with our rds setup so that information might help enormously.

**Comment by sebastianuw** [comment] 2018-10-12 21:56
103686e is actually the last that I know was working. The problem is there was a show stopping gateway bug that wasn't fixed until recently, so bisect will miss the problem.

Do you have an e-mail I can send more detailed logs to?

**Comment by akallabeth** [comment] 2018-10-13 13:53
Try the one used by my commits

**Comment by akallabeth** [comment] 2018-10-18 13:21
@sebastianuw I've found a hint, could you check if it works if you set `settings->ClientAddress` in `freerdp_tcp_connect` to your desired client url/name?

**Comment by sebastianuw** [comment] 2018-10-19 22:07
If I run:
$ xfreerdp ./rds.rdp /v:session-host-name 

It can connect even if it can't resolve the name.

**Comment by akallabeth** [comment] 2018-10-23 09:07
@sebastianuw two questions here:
1. Does the `rdp` file contain a IP or hostname as destination address?
1. Is session redirection activated on the RDS systems? (then you might want to try  `/redirect-prefer` to avoid resolution checks)

**Comment by akallabeth** [comment] 2018-11-13 14:23
@sebastianuw Any update on this?

**Comment by sebastianuw** [comment] 2018-11-16 00:01
I'm using the rdp files generated by the RD Web Access server. These do not include a destination address.Here is an example:

` cpub-Gateway-CmsRdsb,rdp

redirectclipboard:i:1
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:0
devicestoredirect:s:*
drivestoredirect:s:*
redirectdrives:i:1
session bpp:i:32
prompt for credentials on client:i:1
server port:i:3389
allow font smoothing:i:1
promptcredentialonce:i:1
videoplaybackmode:i:1
audiocapturemode:i:1
gatewayusagemethod:i:1
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
full address:s:GATEWAY.MYCOOLNETWORK.COM
gatewayhostname:s:gateway.mycoolnetwor.com
workspace id:s:gateway.mycoolnetwor.com
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.Gateway
use multimon:i:1
alternate full address:s:GATEWAY.MYCOOLNETWORK.COM
signscope:s:Full Address,Alternate Full Address,Use Redirection Server Name,Server Port,GatewayHostname,GatewayUsageMethod,GatewayProfileUsageMethod,GatewayCredentialsSource,PromptCredentialOnce,RedirectDrives,RedirectPrinters,RedirectCOMPorts,RedirectSmartCards,RedirectClipboard,DevicesToRedirect,DrivesToRedirect,LoadBalanceInfo
signature:s:`

**Comment by akallabeth** [comment] 2018-11-16 06:43
Does it work using /redirect-prefer and no hostname?
Looks like you use redirection over a gateway.
With yesterdays merges gateway related issues are (mostly) resolved but there might be some left in redirection.
Need to add the signscope element to the rdp parser to do this preference automatically.

**Comment by Olen** [comment] 2018-11-16 13:55
Testing out the /redirect-prefer options:
* ip - Same error as before
* fqdn: - Connection hangs for about 30 seconds (dns timeout?)
* netbios: Same as fqdn

**Comment by sebastianuw** [comment] 2018-11-16 16:50
None of the redirect-prefer options help me either. The only way to connect is to manually specify the session server with /v:session-server 

This is with fe1a797

**Comment by sebastianuw** [comment] 2018-11-16 17:12
On a minor semi-related note, right now the command line help for xfreerdp gives this description for /redirect-prefer

" /redirect-prefer:... Override the preferred redirection order". 

Could this be changed to:

 "/redirect-prefer:fqdn|ip|netbios Override the preferred redirection order"?

Not deal breaking, but I had to search the issue tracker for the flag's options.

**Comment by akallabeth** [comment] 2018-11-17 09:01
@sebastianuw the referenced pull with the not resolve fqdn fix is not on master yet.
As for the description, looks like the code to print help is truncating this, will have a look

**Comment by akallabeth** [comment] 2018-11-26 10:30
@sebastianuw All changes have been merged to master, is this still an issue for you?

**Comment by sebastianuw** [comment] 2018-11-26 17:02
I just tested it, it works! No redirect-prefer flag needed. Thanks!

**Comment by akallabeth** [comment] 2018-11-26 22:01
Good to hear, lets move on to fix the nexo one :)

**Closed by akallabeth** 2018-11-26 22:01 UTC
Labels: gateway, waiting-feedback
