### ISSUE TITLE
Feature regression on mac - Multiple monitors.

### ISSUE THREAD

**Issue by adilias3** [FreeRDP/FreeRDP#4565] opened 2018-04-12 01:25 UTC
Previously freerdp was able to correctly identify multiple monitors on mac.
```
$ xfreerdp --version
This is FreeRDP version 2.0.0-dev2 (bcf3babca)

$ xfreerdp /monitor-list
      * [0] 1680x1028	+876+1200
        [1] 1600x1178	+0+0
        [2] 1600x1178	+1600+0
```

This is no longer the case, it now detects it as one big work area..

```
$ xfreerdp --version
This is FreeRDP version 2.0.0-dev2 (04b29575f)

$ xfreerdp /monitor-list
        [0] 3200x2228	+0+0
```

This appears to have occurred after the commit https://github.com/FreeRDP/FreeRDP/commit/4077d55a6c4e921b466897d55f147ccdefe1076f, which merged https://github.com/FreeRDP/FreeRDP/pull/4332

The commit mentions using more xrandr attributes, so not sure if this is helpful, but on my mac xrandr returns one big work area too.

```
$ xrandr -q
Screen 0: minimum 640 x 480, current 3200 x 2228, maximum 3200 x 2250
default connected 3200x2228+0+0 0mm x 0mm
```

My system details are :
MacOS High Sierra 10.13.4
XQuartz 2.7.11

```
$ cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" . -DWITH_X11=ON -DWITH_ALSA=OFF -DWITH_FFMPEG=ON && make install

$ xfreerdp --buildconfig
This is FreeRDP version 2.0.0-dev2 (04b29575f)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_FLAG_SEARCH_PATHS_FIRST=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB= HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H= HAVE_SYS_FILIO_H=1 HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H=1 HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H= HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS= WITH_ALSA=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_FFMPEG=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_JPEG=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=ON WITH_MACAUDIO_AVAILABLE=1 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=OFF WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations
Compiler:            Clang, 9.1.0.9020039
Target architecture: x64
```

**Comment by adilias3** [comment] 2018-04-12 05:45
I've found another regression on mac to do with multiple monitors. Please let me know if this should be in a separate issue.

When assigning freerdp to a monitor in fullscreen using the /monitors parameter, freerdp does not appear to get the correct height for the window. 

```
xfreerdp /monitors:1 /f /v:server
```
Instead of being a fullscreen window, there is around 200 pixels of my desktop showing at the bottom. I'm also losing the same space of the client desktop. So I am unable to see start button or taskbar on the client.

It is working correctly on 2.0.0-rc1, I will do some more digging to work out when it broke..

**Comment by akallabeth** [comment] 2018-04-12 06:11
Could you confirm these issues are not related to os x updates? (Just run the old version on your current setup if you did not already)

**Comment by hardening** [comment] 2018-04-12 07:00
If confirmed that could mean that we should not use xrandr on mac...

**Comment by adilias3** [comment] 2018-04-12 22:36
I can switch between the mentioned versions of freerdp and see the first issues above, without any changes to osx.

The 2nd issue mentioned is happening prior to the xrandr patch, I'll do some more testing to narrow down when it's happened..

**Comment by adilias3** [comment] 2018-04-13 01:41
For the 2nd issue, it looks like it's using the height of the primary monitor, instead of the specified monitor.
```
$ xfreerdp /monitor-list
      * [0] 1680x1028	+876+1200
        [1] 1600x1178	+0+0
        [2] 1600x1178	+1600+0

$ xfreerdp /monitors:1 /f /sec:rdp /v:server
```
I end up with a freerdp window on monitor 1 with approximate dimensions of 1600x1028, when I should have a window 1600x1178 instead.

It also appears to be sending the correct size to the server, so I am missing the bottom part of the server workspace - I can't see taskbar, etc..

**Comment by adilias3** [comment] 2018-04-13 02:49
After some more playing, it looks like it creates the window with the primary monitors resolution, but rdp session workarea with the specified monitor resolution.

If I change my primary monitor resolution to 1280x778..

```
$ xfreerdp /monitor-list
      * [0] 1280x778	+1062+1200
        [1] 1600x1178	+0+0
        [2] 1600x1178	+1600+0

$ xfreerdp /monitors:2 /f /v:server
```
I should get a window on monitor 2 with resolution 1600x1178, but I end up with a window 1280x778.

See screenshot, the actual workarea in the rdp session looks to be correct.
![screen shot 2018-04-13 at 12 37 27](https://user-images.githubusercontent.com/38277187/38714167-46fb17d8-3f18-11e8-89d0-7809ad3328cf.jpg)

If I change the resolution of my external monitor to be smaller than the resolution of the primary monitor, then it works correctly.

```
$ xfreerdp /monitor-list
      * [0] 1680x1028	+1062+1200
        [1] 1600x1178	+0+0
        [2] 1280x938	+1600+240

$ xfreerdp /monitors:2 /f /v:server
```
I get a full screen window on monitor 2 with matching rdp session workarea, and all is good.

**Comment by adilias3** [comment] 2018-04-14 05:28
Looks like this was introduced in commit https://github.com/FreeRDP/FreeRDP/commit/1628045f6702bb922b73e53b8de72dde4c5cbedc

**Comment by adilias3** [comment] 2018-04-16 00:58
Looking through the changes made in commit https://github.com/FreeRDP/FreeRDP/commit/1628045f6702bb922b73e53b8de72dde4c5cbedc

```
XInternAtom(xfc->display, "_NET_WM_FULLSCREEN_MONITORS", False);
```
Does return a value, but the value does not exist in ```xfc->supportedAtoms```

Which means the function ```get_supported_atom(xfc, _NET_WM_FULLSCREEN_MONITORS");``` always returns None - Which appears to be what is causing the issue.

If I replace the current call
```
xfc->_NET_WM_FULLSCREEN_MONITORS = get_supported_atom(xfc, "_NET_WM_FULLSCREEN_MONITORS");
```
With the previous...
```
xfc->_NET_WM_FULLSCREEN_MONITORS = XInternAtom(xfc->display,
		                                   "_NET_WM_FULLSCREEN_MONITORS", False);
```

Then fullscreen on external monitors works correctly...

**Comment by akallabeth** [comment] 2018-04-16 06:55
@adilias3 That sounds like a bug in the mac `X11` implementation. Looks like they're missing `_NET_SUPPORTED` property

**Comment by adilias3** [comment] 2018-04-17 00:29
```xfc->supportedAtoms``` does get populated, it's appears to have values for at least the following..

```
_NET_WM_STATE
_NET_WM_STATE_FULLSCREEN
_NET_WM_STATE_MAXIMIZED_HORZ
_NET_WM_STATE_MAXIMIZED_VERT
_NET_WM_NAME
_NET_WM_WINDOW_TYPE
_NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_WINDOW_TYPE_UTILITY
_NET_WM_WINDOW_TYPE_DROPDOWN_MENU
_NET_WM_STATE_SKIP_TASKBAR
_NET_WM_STATE_SKIP_PAGER
```

But not for ```_NET_WM_FULLSCREEN_MONITORS```

**Comment by akallabeth** [comment] 2018-04-17 09:46
That might explain the issue, looks like the property is not supported, so we should use a different approach.

**Comment by samuelengelking** [comment] 2021-04-22 06:10
Is there any progress on this?
I would like to use my 2 HiDPI monitors in a remote desktop setup for Windows. Unfortunately I haven't been able to find a program where that works. Either it doesn't do HiDPI scaling or it only works in one window.
By FreeRDP I had the problem that it would span instead of multiple monitors

**Comment by akallabeth** [comment] 2021-04-22 08:34
@samuelengelking no, mac client is looking for a maintainer and `xfreerdp` is limited by the (lacking) `X11` available on mac

**Comment by akallabeth** [comment] 2023-07-25 07:10
https://github.com/FreeRDP/FreeRDP/pull/9188 might be of interest for people subscribed here.
the `SDL-client` will replace the platform specific ones, but currently still WIP (the pr adds support for multimonitor in the near future)
https://github.com/FreeRDP/FreeRDP/issues/9074 is tracking progress

**Comment by akallabeth** [comment] 2023-07-26 19:33
#9188 will fix this using the `sdl-freerdp` client. this issue is not freerdp, but lacking `X11` support on mac os.
closing.

**Closed by akallabeth** 2023-07-26 19:33 UTC
Labels: x11, client, mac
