### ISSUE TITLE
connection dns

### ISSUE THREAD

**Issue by oliverav2cloud** [FreeRDP/FreeRDP#4739] opened 2018-07-10 18:49 UTC
root@torvic-Inspiron-7737:/home/torvic/Project2/FreeRDP# xfreerdp /u:183PSMXJ\olivera /p:Olivera123$ /v:149.202.121.64:50959
[14:46:34:045] [29126:29127] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[14:46:34:048] [29126:29127] [INFO][com.freerdp.core.proxy] - Parsed proxy configuration: http://proxy.contoso.com:3128
[14:46:34:104] [29126:29127] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_DNS_NAME_NOT_FOUND [0x00020005]
[14:46:34:104] [29126:29127] [ERROR][com.freerdp.core] - getaddrinfo: Name or service not known

I am getting this error.

**Comment by akallabeth** [comment] 2018-07-11 09:10
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
Please fill in the requested information, otherwise this is useless.

**Comment by oliverav2cloud** [comment] 2018-07-11 12:31
I am tryign to connect to remote compiuter with the ip above. Is there a way to disable the proxy?

**Comment by abma** [comment] 2018-07-11 13:30
duplicate of https://github.com/FreeRDP/FreeRDP/issues/4697 ?

unset http_proxy / https_proxy should make it work.

also: is the provided username + password + server valid? if so you should change it ASAP! :-)

**Comment by oliverav2cloud** [comment] 2018-07-11 14:06
I disabled the proxy, now I just get this error:

[10:03:42:533] [1679:1679] [DEBUG][com.freerdp.utils] - Registering signal hook...
[10:03:42:535] [1679:1679] [DEBUG][com.freerdp.client.common.cmdline] - windows: 0/1 posix: -1000/0 compat: -1000/0
[10:03:42:536] [1679:1680] [DEBUG][com.freerdp.channels.cliprdr.client] - VirtualChannelEntryEx
[10:03:42:536] [1679:1680] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[10:03:42:537] [1679:1680] [DEBUG][com.freerdp.client.x11] - Searching for XInput pointer device
[10:03:42:537] [1679:1680] [DEBUG][com.freerdp.client.x11] - Pointer device: 16
[10:03:42:539] [1679:1680] [DEBUG][com.freerdp.core.nego] - Enabling security layer negotiation: TRUE
[10:03:42:539] [1679:1680] [DEBUG][com.freerdp.core.nego] - Enabling restricted admin mode: FALSE
[10:03:42:539] [1679:1680] [DEBUG][com.freerdp.core.nego] - Enabling RDP security: TRUE
[10:03:42:539] [1679:1680] [DEBUG][com.freerdp.core.nego] - Enabling TLS security: TRUE
[10:03:42:539] [1679:1680] [DEBUG][com.freerdp.core.nego] - Enabling NLA security: TRUE
[10:03:42:539] [1679:1680] [DEBUG][com.freerdp.core.nego] - Enabling NLA extended security: FALSE
[10:03:42:539] [1679:1680] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_NLA
[10:03:42:539] [1679:1680] [DEBUG][com.freerdp.core.nego] - Attempting NLA security
[10:03:42:541] [1679:1680] [DEBUG][com.freerdp.core] - connecting to peer 167.114.33.28
[10:03:57:556] [1679:1680] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_FAILED [0x00020006]
[10:03:57:556] [1679:1680] [ERROR][com.freerdp.core] - failed to connect to vm6804.cloud.v2cloud.com

**Comment by akallabeth** [comment] 2018-07-11 14:16
@oliverav2cloud Would be easier to guess if you could finally provide some information about your setup.

**Comment by oliverav2cloud** [comment] 2018-07-11 15:12
What do you mean by setup?

**Comment by oliverav2cloud** [comment] 2018-07-11 15:31
OS: Ubuntu 18.04
Rdp version: version 2.0.0  
I triy to establish connection with: xfreerdp /u:183PSMXJ\Administrator /p:pass /v:vm6804.cloud.v2cloud.com:3389

I disabled proxy settings.

I get the folllowing error: 

10:03:57:556] [1679:1680] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_FAILED [0x00020006]

**Comment by akallabeth** [comment] 2018-07-11 15:50
There is no version 2.0.0, post the output of /buildconfig (as requested by the issue template and the bug report link)
Adfitionally the server os and configuration or all we can do is guessing...

**Comment by akallabeth** [comment] 2018-07-12 06:47
ok, so your client is current, what about the rest?

**Comment by akallabeth** [comment] 2018-07-30 11:32
Closing due to lack of feedback.

**Closed by akallabeth** 2018-07-30 11:32 UTC
Labels: waiting-feedback
