### ISSUE TITLE
Repeated connection reset after opening an application window (Windows)

### ISSUE THREAD

**Issue by jonny08152** [FreeRDP/FreeRDP#6368] opened 2020-07-10 06:52 UTC
When I connect to a Windows Server 2008 machine from my Linux machine using **remmina 1.4.7 and freerdp 2.1.2** I get continuous connection resets + retries after I open certain application windows on the remote machine. **Downgrading to freerdp 2.1.1 fixes the issue.** I get the following logs:

[08:34:15:225] [2289072:2289272] [WARN][com.freerdp.core.orders] - Invalid bmf 129
[08:34:15:225] [2289072:2289272] [ERROR][com.freerdp.core.update] - [0x01] PatBlt - update_read_dstblt_order() failed
[08:34:15:225] [2289072:2289272] [ERROR][com.freerdp.core.update] - order flags 0d failed
[08:34:15:225] [2289072:2289272] [ERROR][com.freerdp.core.fastpath] - Fastpath update Orders [0] failed, status 0
[08:34:15:225] [2289072:2289272] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update() - -1
[08:34:15:225] [2289072:2289272] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[08:34:15:225] [2289072:2289272] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -3
[08:34:15:225] [2289072:2289272] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[08:34:15:763] [2289072:2289272] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[08:34:15:792] [2289072:2289272] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[08:34:17:317] [2289072:2289272] [INFO][com.freerdp.channels.rdpsnd.client] - [static] Loaded fake backend for rdpsnd
[08:34:17:318] [2289072:2289272] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel audin
[08:34:17:321] [2289072:2289272] [INFO][com.freerdp.channels.audin.client] - Loaded pulse backend for audin
[08:34:17:321] [2289072:2289272] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp

**Steps to reproduce:**
1. Open remmina
2. Connect to the remote Windows Server 2008 machine
3. See the desktop and some application windows (Chrome/Firefox/Notepad++/VLC) and everything is fine
4. Open some other application window (CMD/PowerShell/IBM Notes) and the connection immediately breaks down to a continuous reset + retry (the retry might actually be remmina behavior) with the aforementioned error messages
5. Minimize the application window on the remote machine (via some other way)
6. Reconnect to the remote machine using remmina + freerdp and everything is fine again, until the application window is opened again

**Expected behavior**
No connection reset no matter what is displayed on the remote machine's screen.

**Application details**
* FreeRDP version 2.1.2
* Remmina version 1.4.7
* Local OS: Arch Linux, amd64, Kernel 5.7.7
* Remote OS: Windows Server 2008

**Comment by akallabeth** [comment] 2020-07-10 08:05
Duplicate of #6309 
Please do a basic search of the issue tracker before opening a new one.

**Closed by akallabeth** 2020-07-10 08:05 UTC

**Comment by jonny08152** [comment] 2020-07-10 08:24
Oh, thanks, did the search but didn't find this one.
