### ISSUE TITLE
freerdp disconnected with Fastpath update Surface Commands [4] failed when playing 1080p full screen video

### ISSUE THREAD

**Issue by amazingfate** [FreeRDP/FreeRDP#6597] opened 2020-11-23 10:41 UTC
buildconfig:
```
This is FreeRDP version 2.2.0 (d60824d80)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=ON WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=ON WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_ICU=OFF WITH_JPEG=ON WITH_LAME=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NEON=ON WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=ON WITH_SSE2=OFF WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 6.3.0
Target architecture: ARM
```
commandline: `./xfreerdp /multimon /sound:format:17 /microphone:format:1 /cert:ignore /rfx /floatbar /gdi:hw /v:${SERVER_IP} /audio-mode:0 /u:${USER} /p:${PASSWD}`

how to reproduce: connect to a windows 10 server on a 1920x1080 monitor, play a 1080p video full screen and wait, freerdp would crash in dozens of minutes or several hours.

log: https://paste.ubuntu.com/p/WjTCtPQJ3C/

I found this crash only happen with option `/gdi:hw`, but this option can improve the video performance significantly.
With addition option `/log-filters:com.freerdp.core.rdp:DEBUG` I found that when the crash happens, the length printed [here](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/core/fastpath.c#L381) is always 131068, which will cause function [update_recv_surfcmd_frame_marker](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/core/surface.c#L119) return False because Stream_GetRemainingLength(s) is 2.
Here is log with the debug option: https://paste.ubuntu.com/p/pb4r7M5Hdg/

**Comment by akallabeth** [comment] 2020-11-23 11:02
* Please run with current nightly to check if already fixed

**Comment by akallabeth** [comment] 2020-11-23 11:03
also, if you require performance, try the `/gfx` options, you´re forcing old windows 7 style RDP pipeline.

**Comment by akallabeth** [comment] 2020-11-23 11:22
Please also post a full log with `/log-level:debug`, the interesting parts are missing from the ones you posted.

**Comment by amazingfate** [comment] 2020-11-23 11:38
> also, if you require performance, try the `/gfx` options, you´re forcing old windows 7 style RDP pipeline.

I've tried `/rfx`, `/gfx`, `gfx:AVC444`, `gfx:AVC420`, but finally `/rfx` with `gdi:hw` have the best performance, it does't have teared frame when playing full screen video.
I've built the mater branch and I will see if the server would disconnect.

**Comment by amazingfate** [comment] 2020-11-23 12:54
@akallabeth The latest build also disconnected to the server, the full log is uploaded to [google drive](https://drive.google.com/file/d/1QpuI882rp4mgcaB8p7dgu3y1NabD0A8A/view?usp=sharing).
The log of the last two seconds when disconnection happended is pasted here: https://paste.ubuntu.com/p/b4qn7xh37p/

**Comment by akallabeth** [comment] 2020-11-23 13:56
@amazingfate ok, strange. can not reproduce with the same flags to a windows 10 server playing a fullscreen video for ~1h now...
anything else you can add?
From the log nothing suspicious, it just seems to be a broken frame from the server :/

**Comment by akallabeth** [comment] 2020-11-23 13:58
@amazingfate oh, and you forgot to redirect `stderr` in your log, there are only debug and info messages.

**Comment by amazingfate** [comment] 2020-11-23 14:16
@akallabeth I've come back home with the console left in my company. But the stderr should be the same as the log I pasted before. Since I've reproduced this issue for several times with the same ERROR log and all the logs have the same line `recv Fast-Path Surface Commands Update (0x04), length:131068`.
The stderr should be like this:
```
[11:13:04:088] [18602:18603] [ERROR][com.freerdp.core.fastpath] - Fastpath update Surface Commands [4] failed, status -1
[11:13:04:088] [18602:18603] [ERROR][com.freerdp.core.fastpath] - FASTPATH_FRAGMENT_LAST fastpath_recv_update_data: fastpath_recv_update() - -1
[11:13:04:088] [18602:18603] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[11:13:04:088] [18602:18603] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -3
[11:13:04:088] [18602:18603] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[11:13:04:089] [18602:18603] [INFO][com.freerdp.client.common] - Network disconnect
[11:13:04:089] [18602:18603] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
```

**Comment by akallabeth** [comment] 2020-11-23 14:34
@amazingfate since I can not reproduce, could you dump the data (e.g. the stream) that is causing the error? I might be able to deduce the issue from the data, but without a proper way to reproduce that is hard.
Checked the parsing loop and it looks like everything according to spec so no easy to spot issue there :/

**Comment by amazingfate** [comment] 2020-11-23 14:34
@akallabeth oh, I forgot my windows 10 server have this [program](https://drive.google.com/file/d/1u_ffsLOmwfBK4gfVimkCMMQJ-BVfFjs9/view?usp=sharing) installed, which modified its group policy for RDP.

**Comment by amazingfate** [comment] 2020-11-23 14:39
@akallabeth could you tell me how to dump the stream, I can reproduce the issue by connecting to the windows 10 server from a ogon session now.

**Comment by akallabeth** [comment] 2020-11-23 15:10
there is `winpr_hexdump` and similar, that can dump to wlog, or better just write the stream to a temporary file (è.g. 
```
fp = fopen("/tmp/somename.txt", "ẅ+");
 fwrite(stream_buffer(), stream_lenght(), fp);
fclose(fp);
```

**Comment by amazingfate** [comment] 2020-11-24 02:12
@akallabeth I added these line below in function [fastpath_recv_update](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/core/fastpath.c#L362), and reproduced successfully:
```
        if (Stream_GetRemainingLength(s) == 131068)
        {
                WLog_INFO(TAG, "fastpath_recv_update stream length is 131068");
                FILE * fp;
                fp = fopen("stream_dump.txt", "w+");
                fwrite(s, Stream_GetRemainingLength(s), 1, fp);
                fclose(fp);
        }
```
Here is log: https://paste.ubuntu.com/p/PsvzQQ7H2T/
Here is the data I dumped: 
[stream_dump.txt](https://github.com/FreeRDP/FreeRDP/files/5586950/stream_dump.txt)

**Comment by akallabeth** [comment] 2020-11-24 07:48
@amazingfate ok, that will not work ;)
1. `wStream*` is a struct, get the buffer with `Stream_Buffer(s)`
1. `fwrite` should be called with `fwrite(buffer, 1, size, fp)` (stream of bytes, not stream of somesize elements)

**Comment by amazingfate** [comment] 2020-11-24 08:17
@akallabeth Here is the diff I made to code:
```
diff --git a/libfreerdp/core/fastpath.c b/libfreerdp/core/fastpath.c
index 6e815c2be..84d81827b 100644
--- a/libfreerdp/core/fastpath.c
+++ b/libfreerdp/core/fastpath.c
@@ -382,6 +382,14 @@ static int fastpath_recv_update(rdpFastPath* fastpath, BYTE updateCode, wStream*
                  fastpath_update_to_string(updateCode), updateCode, Stream_GetRemainingLength(s));
 #endif

+       if (Stream_GetRemainingLength(s) == 131068)
+       {
+               WLog_INFO(TAG, "fastpath_recv_update stream length is 131068");
+               FILE * fp;
+               fp = fopen("stream_dump.txt", "w+");
+               fwrite(Stream_Buffer(s), 1, Stream_GetRemainingLength(s), fp);
+               fclose(fp);
+       }
        switch (updateCode)
        {
                case FASTPATH_UPDATETYPE_ORDERS:
diff --git a/libfreerdp/core/surface.c b/libfreerdp/core/surface.c
index d5c709885..d9064e507 100644
--- a/libfreerdp/core/surface.c
+++ b/libfreerdp/core/surface.c
@@ -116,14 +116,14 @@ static BOOL update_recv_surfcmd_frame_marker(rdpUpdate* update, wStream* s)
 {
        SURFACE_FRAME_MARKER marker;

-       if (Stream_GetRemainingLength(s) < 6)
+       if (Stream_GetRemainingLength(s) < 2)
                return FALSE;

        Stream_Read_UINT16(s, marker.frameAction);
        Stream_Read_UINT32(s, marker.frameId);
        WLog_Print(update->log, WLOG_DEBUG,
-                  "SurfaceFrameMarker: action: %s (%" PRIu32 ") id: %" PRIu32 "",
-                  (!marker.frameAction) ? "Begin" : "End", marker.frameAction, marker.frameId);
+                  "SurfaceFrameMarker: action: %s (%" PRIu32 ") id: %" PRIu32 ", stream length is %d",
+                  (!marker.frameAction) ? "Begin" : "End", marker.frameAction, marker.frameId, Stream_GetRemainingLength(s));

        if (!update->SurfaceFrameMarker)
        {
@@ -155,6 +155,15 @@ int update_recv_surfcmds(rdpUpdate* update, wStream* s)
                                break;

                        case CMDTYPE_FRAME_MARKER:
+                               if (Stream_GetRemainingLength(s) == 2)
+                               {
+                                       WLog_INFO(TAG, "fastpath_recv_surfmd_frame_marker gonna start, stream length is 2");
+                                       FILE * fp;
+                                       fp = fopen("stream_frame_marker.txt", "w+");
+                                       fwrite(Stream_Buffer(s), 1, Stream_GetRemainingLength(s), fp);
+                                       fclose(fp);
+                                       winpr_HexDump(TAG, 2, s, Stream_GetRemainingLength(s));
+                               }
                                if (!update_recv_surfcmd_frame_marker(update, s))
                                        return -1;
```
Here is the log: https://drive.google.com/file/d/1-Bk01W4KfiqSWvz1NQCJr5A2N8aYm6Fs/view?usp=sharing
Here is the size 131068 dump file in fastpath_recv_update:
[stream_dump.txt](https://github.com/FreeRDP/FreeRDP/files/5588326/stream_dump.txt)
Here is the size 2 dump file in update_recv_surfcmds:
[stream_frame_marker.txt](https://github.com/FreeRDP/FreeRDP/files/5588330/stream_frame_marker.txt)

**Comment by akallabeth** [comment] 2020-11-24 08:32
@amazingfate ok, this is better, but I´m lacking one more ingredient:
`updateCode` parameter for `fastpath_recv_update` that the stream dump is for.

**Comment by amazingfate** [comment] 2020-11-24 08:37
> ingredient

It could get found in the log:
```
[16:02:59:078] [16054:16055] [DEBUG][com.freerdp.core.rdp] - recv Fast-Path Surface Commands Update (0x04), length:131068
[16:02:59:078] [16054:16055] [INFO][com.freerdp.core.fastpath] - fastpath_recv_update stream length is 131068
```
These two lines are printed in the same function.

**Comment by akallabeth** [comment] 2020-11-24 08:48
sorry, realized just after I wrote that that is in the log :)
checked the spec and rereading the code I can not find any problem except the data received is invalid (aka short)

**Comment by akallabeth** [comment] 2020-11-24 08:51
Only thing I can think of is `bulk_decompress` reporting 2 bytes short, but that would lead to more than this issue.

**Comment by akallabeth** [comment] 2020-11-24 08:55
just a silly question, can you reproduce this issue without your program installed?

**Comment by amazingfate** [comment] 2020-11-24 09:06
> just a silly question, can you reproduce this issue without your program installed?

RemoteFX is not enabled by default in a clean installed windows10, so I install this program to enabled RemoteFX and other features. Maybe I can modify the group policy by myself in a clean installed machine and see if this issue can be reproduced.

**Comment by amazingfate** [comment] 2020-11-24 14:27
@akallabeth Since the surface command 4 (Frame Marker Command) length is 2 instead of 6, missing the frameId(length 4), I made a dirty hack:
```
diff --git a/libfreerdp/core/surface.c b/libfreerdp/core/surface.c
index c406b954a..fb9e1caca 100644
--- a/libfreerdp/core/surface.c
+++ b/libfreerdp/core/surface.c
@@ -107,11 +107,19 @@ static BOOL update_recv_surfcmd_frame_marker(rdpUpdate* update, wStream* s)
 {
        SURFACE_FRAME_MARKER marker = { 0 };

-       if (Stream_GetRemainingLength(s) < 6)
+       if (Stream_GetRemainingLength(s) < 2)
                return FALSE;

        Stream_Read_UINT16(s, marker.frameAction);
-       Stream_Read_UINT32(s, marker.frameId);
+       if (Stream_GetRemainingLength(s) < 4)
+       {
+               marker.frameId = 0;
+               WLog_INFO(TAG, "Frame Marker Command lost frameId, use 0 instead");
+       }
+       else
+       {
+               Stream_Read_UINT32(s, marker.frameId);
+       }
        WLog_Print(update->log, WLOG_DEBUG,
                   "SurfaceFrameMarker: action: %s (%" PRIu32 ") id: %" PRIu32 "",
                   (!marker.frameAction) ? "Begin" : "End", marker.frameAction, marker.frameId);
```
In my test the diconnecction doesn't happen, but I don't know if frameId is always 0.
Reference: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/7a4d7c0c-06e3-4802-aaa8-92c8f1d86f6e

**Comment by akallabeth** [comment] 2020-11-25 06:47
@amazingfate I believe you that it helps for your case. I´d still want to know if this is a real bug with windows RDP server or the program you use.
The former would make an argument to upstream the hack, the latter not so much.

**Comment by amazingfate** [comment] 2020-11-25 07:39
@akallabeth What the program did is installing some windows update patch and configuring some RDP related group policies after  decompiling it. It seems that the root cause is hard to find out :( .
The windows 10 server is a KVM machine, I gonna see if this issue can be reproduced in a physical machine.

**Comment by akallabeth** [comment] 2020-11-25 08:14
@amazingfate ok. can you give me some insight in what this `program` is and if there are public sources?

**Comment by amazingfate** [comment] 2020-11-25 08:29
@akallabeth This program should be provided by a arm thinclient vendor. I can unarchive this program and see a file named readme.txt:
```
This package is used to optimize the performance of microsoft RDP connection. When you use the thin client, please enable the RemoteFX option for RDP connection to get a better experience. 

Notices: 

1, This package is released for windows 7 and windows 2008 R2 system.

2, Please make sure the host CPU supports SLAT feature.

3, Please make sure the RemoteFX option is enbaled in the thin client.
```

**Comment by amazingfate** [comment] 2020-11-25 08:38
@akallabeth The program should be downloaded from here: http://www.jieyung.com/download/showdownload.php?id=61&lang=en

**Comment by amazingfate** [comment] 2020-11-25 08:45
These are the group policies configured by this program on Windows 10:
```
public static void Windows10()
{
	LocalPolicyEdit("ColorDepth", 999, RegistryValueKind.DWord);
	LocalPolicyEdit("fEnableVirtualizedGraphics", 1, RegistryValueKind.DWord);
	LocalPolicyEdit("GraphicsProfile", 1, RegistryValueKind.DWord);
	LocalPolicyEdit("ImageQuality", 3, RegistryValueKind.DWord);
	LocalPolicyEdit("VGOptimization_CaptureFrameRate", 1, RegistryValueKind.DWord);
	LocalPolicyEdit("VGOptimization_CompressionRatio", 3, RegistryValueKind.DWord);
	LocalPolicyEdit("fDenyTSConnections", 0, RegistryValueKind.DWord);
	LocalPolicyEdit("UserAuthentication", 0, RegistryValueKind.DWord);
	LocalPolicyEdit("SelectNetworkDetect", 3, RegistryValueKind.DWord);
	LocalPolicyEdit("fEncryptRPCTraffic", 1, RegistryValueKind.DWord);
	LocalPolicyEdit("AllowedAudioQualityMode", 7, RegistryValueKind.DWord);
	LocalPolicyEdit("fDisableAudioCapture", 0, RegistryValueKind.DWord);
	LocalPolicyEdit("SecurityLayer", 0, RegistryValueKind.DWord);
	LocalPolicyEdit("fDisableTerminalServerTooltip", 1, RegistryValueKind.DWord);
	LocalPolicyEdit("LicensingMode", 4, RegistryValueKind.DWord);
	LocalPolicyEdit("bEnumerateHWBeforeSW", 1, RegistryValueKind.DWord);
	LocalPolicyEdit("fEnableRemoteFXAdvancedRemoteApp", 1, RegistryValueKind.DWord);
	LocalPolicyEdit("AVC444ModePreferred", 1, RegistryValueKind.DWord);
	LocalPolicyEdit("AVCHardwareEncodePreferred", 1, RegistryValueKind.DWord);
	LocalPolicyEdit("MaxCompressionLevel", 1, RegistryValueKind.DWord);
	LocalPolicyEdit("VisualExperiencePolicy", 1, RegistryValueKind.DWord);
	LocalPolicyEdit("LicenseServers", "127.0.0.1", RegistryValueKind.String);
}
```
Rename the program to a .rar file, then unarchive it, and decompile RDPAccelerator.exe, we can see the code above.

**Comment by akallabeth** [comment] 2021-02-10 09:45
#6626 fixed glyph cache issues, closing.
create a new issue if not resolved.

**Closed by akallabeth** 2021-02-10 09:45 UTC
Labels: waiting-feedback
