### ISSUE TITLE
Strange font rendering for disabled widgets

### ISSUE THREAD

**Issue by frispete** [FreeRDP/FreeRDP#4331] opened 2017-12-22 18:31 UTC
Since current git (as of yesterday) allows me to work on a Windows 2008 R2 Terminal Server, that requires proper smartcard support (horray!), I noticed a strange font rendering behavior:

![grafik](https://user-images.githubusercontent.com/1009685/34308048-84f2950e-e74b-11e7-808a-a8e7a2d1de83.png)

I played with +font and +aero settings, but the issue persists. It used to look like this with the patched 1.0.x version:

![grafik](https://user-images.githubusercontent.com/1009685/34308079-c494bf48-e74b-11e7-9cb6-18cfe3bd65e8.png)

It seems not to depend on the cleartype enabled setting in the terminal server session, but related to the the switch to 2.0. It doesn't happen everywhere with disabled text, but even on buttons in windows control center.

Any idea, what's going wrong?

**Comment by akallabeth** [comment] 2017-12-26 08:31
Duplicate of #3907. See details for the issue there, use ```/gdi:sw``` to avoid until xfreerdp is fixed.

**Closed by akallabeth** 2017-12-26 08:31 UTC

**Comment by frispete** [comment] 2017-12-26 08:55
Thanks for pointing me to the origin issue and sorry for the noise.

Of course, I've tried to locate the issue here, but failed...
