### ISSUE TITLE
Point leaks when drawing in AutoCAD

### ISSUE THREAD

**Issue by shweng** [FreeRDP/FreeRDP#2590] opened 2015-05-04 03:09 UTC
Hi all,
I use xfreerdp to connect win7 guest using AutoCAD software,when drawing a line or circle arc,
the drawing track will remains some points on drawing canvas.
please refer to http://imagebin.ca/v/20WLuqLCCG9T
testing environment:
Host:Fedora 20 x64
Guest:Win7 64bit with AutoCAD 2012
FreeRDP command: xfreerdp /u:administrator /p:passwd /cert-ignore /gdi:hw /sound /bpp:32 /f /v 192.168.10.198

I have tried FreeRDP version including master-git(1.2.1-dev),1.2.0-beta1+android9,1.20-beta1+android7,stable-1.1 and stable-1.0,the same bugs exist.
I also tried another open source remote desktop client rdesktop which has the same issue.but Microsoft's MSTSC.EXE is OK.

When replace parameter from /gdi:hw to /gdi:sw,the phenomenon seems to disappear, but sw rending performance is poor.
could anybody help to investiage this issue, it's appreciate to give me some idea to resolve this issue.

**Comment by hardening** [comment] 2015-05-07 09:09
@shweng can you confirm with the last master (which is 1.2.3-dev) that the bug is still there. Thank you.

**Comment by shweng** [comment] 2015-05-07 09:59
confirmed this bug still exist in latest master(1.2.3-dev)

**Comment by bmiklautz** [comment] 2015-05-07 23:21
@shweng do you have also other ways to reproduce this issue otherwise it will be hard for us do track it down since I think nobody of us has AutoCAD 2012 available for testing.

**Comment by shweng** [comment] 2015-05-12 02:44
@bmiklautz  I cannot reproduce this issue on other rich graphics software such as Photoshop CS,CAXA(a CAD/CAM design software similar to AutoCAD), but exist on variety version of AutoCAD.
ps: AutoCAD can download at
 http://188.138.9.146/Getintopc.com/Autodesk_AutoCAD_2013_x64.zip
http://85.25.103.117/Getintopc.com/Autodesk_AutoCAD_2013_x86.zip
and we can free trial in 30 days.

**Comment by nfedera** [comment] 2015-05-20 21:19
@shweng please test again with current master. Some gdi bugs got fixed.

**Comment by akallabeth** [comment] 2017-02-17 12:10
Fixed on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef

**Closed by akallabeth** 2017-02-17 12:10 UTC
Labels: x11-client
