### ISSUE TITLE
Received invalid TPKT header length error since update to build 780 thru 784

### ISSUE THREAD

**Issue by garphi** [FreeRDP/FreeRDP#5952] opened 2020-03-07 21:32 UTC
Hi there,
I've just updated on my debian buster system by using your nightly builds on https://ci.freerdp.com/job/freerdp-nightly-binaries

Since this and the previous versions down to https://ci.freerdp.com/job/freerdp-nightly-binaries/780/architecture=amd64,distribution=buster,label=pkg-deb/

I get the following error message, when I'm connecting via this commandline:
`garphi@work-nb:/opt/freerdp-nightly/bin$ ./xfreerdp /f /multimon /cert-ignore /d:WORKGROUP /v:127.0.0.9:33389 +auto-reconnect /network:lan /gfx:AVC444 /gfx-progressive /video /gdi:hw +fonts +aero -bitmap-cache -offscreen-cache /audio-mode:0 /sound:sys:pulse /u:user /p:passwd`

Destination is a Win 2016 server. 

`[22:14:59:845] [4291:4292] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[22:14:59:845] [4291:4292] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[22:14:59:845] [4291:4292] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[22:14:59:845] [4291:4292] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[22:14:59:845] [4291:4292] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[22:14:59:185] [4291:4292] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized
[22:14:59:191] [4291:4292] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[22:14:59:191] [4291:4292] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[22:15:01:784] [4291:4292] [ERROR][com.freerdp.core.tpkt] - Received invalid TPKT header length 5257, 16 bytes too long!
[22:15:01:785] [4291:4292] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[22:15:01:785] [4291:4292] [ERROR][com.freerdp.core] - rdp_client_connect:freerdp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[22:15:01:800] [4291:4292] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[22:15:01:800] [4291:4292] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[22:15:02:390] [4291:4292] [ERROR][com.freerdp.core.tpkt] - Received invalid TPKT header length 5257, 16 bytes too long!
[22:15:02:390] [4291:4292] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[22:15:02:390] [4291:4292] [ERROR][com.freerdp.core] - rdp_client_connect:freerdp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[22:15:02:390] [4291:4292] [ERROR][com.freerdp.core] - freerdp_post_connect failed
`
Thanks in advance.

**Comment by akallabeth** [comment] 2020-03-07 21:44
Well, these are nightlies.
Please update, duplicate of #5954

**Closed** 2020-03-07 21:45 UTC
