### ISSUE TITLE
Not releasing modifiers keys on focus gain?

### ISSUE THREAD

**Issue by Arokha** [FreeRDP/FreeRDP#5092] opened 2018-12-03 18:44 UTC
To continue the long trend of these issues (#2104, #4662, #1335, #1010, #540), here this is again. Appears to be a regression fairly recently.

**To Reproduce**
1. Give freerdp window focus
2. ~~Use any keyboard combinations with ALT that cause the window to lose focus (alt-tab, workspace switching combos, etc)~~ See first comment.
3. Return to freerdp window, find that ALT is continually held until both (always both) alt keys on keyboard are tapped (remote OS does not see this, only local)

**Expected behavior**
I have -grab-keyboard, and freerdp should drop keys when losing focus. There were various patches to fix this over the years in the above-mentioned issues, but it seems to have been lost.

* Ver: 2.0.0-rc4
* Distro: Manjaro (so, Arch)
* Windows 10 remote host (not sure that's relevant in this case though)

**Additional context**
This did not always happen, something recent changed this, though I don't know what. I looked through recent PRs and don't see anything that might.

**Comment by Arokha** [comment] 2018-12-03 19:22
Actually, after a little experimentation, this appears to be the opposite of the above issues?

Losing focus seems fine. It's GAINING focus with a modifier key pressed that pins it.

So for e.g.:
xfreerdp open on workspace 1
Switch to workspace 2 with Ctrl-Alt-2
Return to workspace 1 with something other than kb shortcuts = works fine

xfreerdp open on workspace 1, currently viewing workspace 2
Switch to workspace 1 with Ctrl-Alt-2
Alt pinned in xfreerdp until both alt keys pressed

**Comment by akallabeth** [comment] 2018-12-03 21:19
Duplicate of #4966 
Looks like this might be something of a window manager / X11 event combination but so far I could never reproduce. (all keys are released on focus out and the current state is read on focus in)
If you have additional information please attach that to the issue referenced.

**Closed by akallabeth** 2018-12-03 21:19 UTC

**Comment by yeroc** [comment] 2023-10-31 17:01
This ticket and the subsequent analysis by @Arokha perfectly describe the symptoms I'm experiencing on AlmaLinux 8 with Gnome.  I understand this may well be a duplicate of #4966 but quite frankly this ticket describes the issue much more succinctly.  If I can provide more info to be of help let me know.
