### ISSUE TITLE
xfreerdp disconnects after receiving "Network disconnect!" when idle on VPN

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#1972] opened 2014-07-18 15:30 UTC
Need help to debug this problem; any help appreciated.

Running FreeRDP (Ubuntu 14.04) over a VPN to a variety of Windows 2K3-2K12-2K12R2 RDS servers. Using both the stable 1.1 and the most recent master builds. The stable 1.1 version runs perfectly over the VPN and on the LAN to all servers. Using the most recent master (and those from a coupls months back as I remember), a strange thing started to happen. The master versions are now disconnecting from the servers when idle. The idle times can very between 18 seconds and a couple minutes, but it always happens now. Internally, on the LAN, the master never disconnects like this. Now the debug help I need is because I have set all the debug flags, been in gdb, etc and nothing strange happens. The only message from FreeRDP is "Network disconnect!" coming from line 1218 of xf_client.c in xf_auto_reconnect(). There is no thread information or any other debug info that would give me any indication of what is going wrong.

Obviously something changed between stable and master but I cannot find out what it is. I believe the network code changed that now for some reason is sensitive to the VPN. Nothing has changed on the VPN side and as previously mentioned, it just started a few months back in master. Could a FreeRDP expert share some help on how I could pinpoint this problem?

**Comment by lschoepps** [comment] 2015-04-09 14:05
Hi,
I have the same issue, I'm running FreeRDP over a VPN and with the last master build I keep receiving `Network disconnect!` error but there is no problem with the stable 1.1 build.
I tried to comment the keep_alive ifdefs (by removing only some of them or all of them) but to no avail.
What should I do to fix this issue in the master build ?

**Comment by bmiklautz** [comment] 2015-04-10 10:14
@lschoepps just to make sure your VPN is still running and functional when you get the "Network disconnect"?

**Comment by lschoepps** [comment] 2015-04-10 11:14
Yes, it's still functional since I can stay connected with the stable 1.1 build while I receive "Network disconnect" by running the master build.

**Comment by cgholam** [comment] 2015-04-10 12:53
Le 10 avr. 2015 10:15, "Bernhard Miklautz" <notifications@github.com> a
écrit :

**Comment by bmiklautz** [comment] 2015-04-10 16:54
@cgholam pleas stop adding empty comments in our issues!

**Comment by cgholam** [comment] 2015-04-10 18:37
بتاريخ Apr 10, 2015 4:54 PM، كتبها "Bernhard Miklautz" <
notifications@github.com>:

**Comment by freerdp-github** [comment] 2016-05-26 03:01
@bmiklautz, we kind of got side tracked during this discussion. If I may refresh your memory about this problem. I ended up changing the TCP_KEEPINTVL to 0 which I believe disables it. This or changing it to 75 also works.  I believe we got side tracked just as you were asking @vworkspace if he would change this to use the system values (which are correct in my case) instead of overriding them in the freerdp_tcp_set_keep_alive_mode() function. I never saw any reply or acknowledgement and the problem at least for me has never gone away. However, since I must change this option after every new git update it is getting tiresome. Just wondering if there is a permanent fix available from vworkspace.

Thanks

**Comment by bmiklautz** [comment] 2016-05-27 22:00
@freerdp-github just to make sure you are the initial author of this issue (as it seems your account was deleted)?

**Comment by freerdp-github** [comment] 2016-05-28 17:02
Yes I am. Long story why the account was deleted.

**Comment by tomarch** [comment] 2016-06-10 10:09
Is this issue has been fixed in lastest master ?
Or is here anything that can resolv it (without recompil) ?

**Comment by akallabeth** [comment] 2018-12-05 14:44
Have not seen such disconnects in ages for the `2.0.0-rc4` and later series.
Closing. Create a new issue if still reproducible.

**Closed by akallabeth** 2018-12-05 14:44 UTC
