### ISSUE TITLE
rdpgfx or tsmf | freerdp session crashing with all local video formats

### ISSUE THREAD

**Issue by T3N4K4** [FreeRDP/FreeRDP#3422] opened 2016-06-23 11:57 UTC
FreeRDP Master - Git Revision 0d7a6b5
Applied patches http://nopaste.narf.at/show/330331/

All cmake Options:
http://pastebin.com/fwQbSPZx

Connection server -> Windows Server 2012 R2 Standard 64-Bit
Client system -> Linux vagrant-ubuntu-trusty-32 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:41 UTC 2016 i686 GNU/Linux

Local video formats tried: mp4, AVCHD-Video, divx (videoclip), wmv
(played via network drive)

**Command Line:**
/opt/freerdp/bin/xfreerdp /u:$USER /p:$PASS /d:WINDOWS.LOCAL +sec-tls -sec-nla /rfx /gfx /multimedia:decoder:gstreamer /sound:sys:pulse /audio-mode:0 /cert-ignore /v:$SERVER

Errors with **/multimedia:decoder:gstreamer** ->
[11:20:32:675] [1674:1675] [ERROR][com.winpr.timezone] - Unable to find a match for unix timezone: Etc/UTC
[11:20:40:568] [1674:1678] [ERROR][com.freerdp.channels.tsmf.client] - Failed to create new pipe
[11:20:40:569] [1674:1678] [WARN][com.freerdp.channels.tsmf.client] - Format not supported by decoder gstreamer
[11:20:40:596] [1674:1678] [ERROR][com.freerdp.channels.tsmf.client] - Failed to create new pipe
[11:20:40:597] [1674:1678] [WARN][com.freerdp.channels.tsmf.client] - Format not supported by decoder gstreamer
[11:20:40:934] [1674:1678] [ERROR][com.freerdp.channels.drdynvc.client] - ChannelId 10 not found!
[11:20:40:934] [1674:1678] [ERROR][com.freerdp.channels.drdynvc.client] - drdynvc_order_recv failed with error 1359!
[11:20:40:941] [1674:1675] [ERROR][com.freerdp.core] - drdynvc_virtual_channel_client_thread reported an error. Error was 1359
[11:20:40:941] [1674:1675] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
[11:20:32:581] [1674:1675] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[11:20:32:582] [1674:1675] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[11:20:32:582] [1674:1675] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
[11:20:32:813] [1674:1675] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel tsmf
[11:20:32:813] [1674:1675] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
[11:20:32:826] [1674:1677] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded pulse backend for rdpsnd
[11:20:40:941] [1674:1675] [INFO][com.freerdp.client.x11] - Network disconnect!

**Valgrind gstreamer:** http://pastebin.com/ZyA1VEGx

Errors with **/multimedia:decoder:ffmpeg** ->
[11:24:49:008] [1730:1731] [ERROR][com.winpr.timezone] - Unable to find a match for unix timezone: Etc/UTC
[11:24:55:854] [1730:1734] [WARN][com.freerdp.channels.tsmf.client] - presentation id EB10E43FC7D88948978A770EC41CBE34 not found
[11:24:55:154] [1730:1747] [ERROR][com.freerdp.channels.tsmf.client] - data_size 1046, no frame is decoded.
[11:24:55:154] [1730:1747] [ERROR][com.freerdp.channels.tsmf.client] - decode error, queue ack anyways
[11:24:55:159] [1730:1734] [ERROR][com.freerdp.channels.drdynvc.client] - ChannelId 10 not found!
[11:24:55:159] [1730:1734] [ERROR][com.freerdp.channels.drdynvc.client] - drdynvc_order_recv failed with error 1359!
[11:24:55:159] [1730:1731] [ERROR][com.freerdp.core] - drdynvc_virtual_channel_client_thread reported an error. Error was 1359
[11:24:55:159] [1730:1731] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
[11:24:49:902] [1730:1731] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[11:24:49:902] [1730:1731] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[11:24:49:902] [1730:1731] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
[11:24:49:115] [1730:1731] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel tsmf
[11:24:49:115] [1730:1731] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
[11:24:49:124] [1730:1733] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded pulse backend for rdpsnd
[11:24:55:159] [1730:1731] [INFO][com.freerdp.client.x11] - Network disconnect!

**Valgrind ffmpeg:** http://pastebin.com/ZgqgieuG

Errors with **-DBUILTIN_CHANNELS=OFF**

**Gstreamer:**
[11:52:05:934] [9545:9546] [ERROR][com.winpr.timezone] - Unable to find a match for unix timezone: Etc/UTC
[11:52:12:375] [9545:9549] [ERROR][com.winpr.library] - GetProcAddress: could not find procedure freerdp_tsmf_client_subsystem_entry: /opt/freerdp/lib/i386-linux-gnu/freerdp2/libtsmf-client-gstreamer-decoder.so: undefined symbol: freerdp_tsmf_client_subsystem_entry
[11:52:12:376] [9545:9549] [ERROR][com.winpr.library] - GetProcAddress: could not find procedure freerdp_tsmf_client_subsystem_entry: /opt/freerdp/lib/i386-linux-gnu/freerdp2/libtsmf-client-gstreamer-decoder.so: undefined symbol: freerdp_tsmf_client_subsystem_entry
[11:52:12:384] [9545:9549] [ERROR][com.winpr.library] - GetProcAddress: could not find procedure freerdp_tsmf_client_subsystem_entry: /opt/freerdp/lib/i386-linux-gnu/freerdp2/libtsmf-client-ffmpeg-decoder.so: undefined symbol: freerdp_tsmf_client_subsystem_entry
[11:52:15:532] [9545:9549] [ERROR][com.freerdp.channels.drdynvc.client] - ChannelId 10 not found!
[11:52:15:532] [9545:9549] [ERROR][com.freerdp.channels.drdynvc.client] - drdynvc_order_recv failed with error 1359!
[11:52:15:533] [9545:9546] [ERROR][com.freerdp.core] - drdynvc_virtual_channel_client_thread reported an error. Error was 1359
[11:52:15:533] [9545:9546] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
[11:52:05:840] [9545:9546] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[11:52:05:840] [9545:9546] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[11:52:05:840] [9545:9546] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
[11:52:06:272] [9545:9546] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel tsmf
[11:52:06:273] [9545:9546] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
[11:52:06:287] [9545:9548] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded pulse backend for rdpsnd
[11:52:15:533] [9545:9546] [INFO][com.freerdp.client.x11] - Network disconnect!

**FFMPEG:**
[11:53:08:571] [9563:9564] [ERROR][com.winpr.timezone] - Unable to find a match for unix timezone: Etc/UTC
[11:53:13:545] [9563:9567] [ERROR][com.winpr.library] - GetProcAddress: could not find procedure freerdp_tsmf_client_subsystem_entry: /opt/freerdp/lib/i386-linux-gnu/freerdp2/libtsmf-client-ffmpeg-decoder.so: undefined symbol: freerdp_tsmf_client_subsystem_entry
[11:53:13:548] [9563:9567] [ERROR][com.winpr.library] - GetProcAddress: could not find procedure freerdp_tsmf_client_subsystem_entry: /opt/freerdp/lib/i386-linux-gnu/freerdp2/libtsmf-client-gstreamer-decoder.so: undefined symbol: freerdp_tsmf_client_subsystem_entry
[11:53:13:560] [9563:9567] [ERROR][com.winpr.library] - GetProcAddress: could not find procedure freerdp_tsmf_client_subsystem_entry: /opt/freerdp/lib/i386-linux-gnu/freerdp2/libtsmf-client-ffmpeg-decoder.so: undefined symbol: freerdp_tsmf_client_subsystem_entry
[11:53:13:826] [9563:9567] [ERROR][com.freerdp.channels.drdynvc.client] - ChannelId 10 not found!
[11:53:13:826] [9563:9567] [ERROR][com.freerdp.channels.drdynvc.client] - drdynvc_order_recv failed with error 1359!
[11:53:13:826] [9563:9564] [ERROR][com.freerdp.core] - drdynvc_virtual_channel_client_thread reported an error. Error was 1359
[11:53:13:826] [9563:9564] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
[11:53:08:480] [9563:9564] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[11:53:08:481] [9563:9564] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[11:53:08:481] [9563:9564] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
[11:53:08:677] [9563:9564] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel tsmf
[11:53:08:678] [9563:9564] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
[11:53:08:684] [9563:9566] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded pulse backend for rdpsnd
[11:53:13:826] [9563:9564] [INFO][com.freerdp.client.x11] - Network disconnect!

If you have any more questions, feel free to ask.

**Comment by T3N4K4** [comment] 2016-06-27 11:02
I guess the crashing is because of gfx.
If I remove the parameter /gfx I get the error messages from above but my session stays alive.

**Comment by T3N4K4** [comment] 2016-07-04 10:52
It even crashes with the last nightly binary -> Build i386,trusty,pkg-deb (Jul 1, 2016 3:48:55 AM)

**Comment by bmiklautz** [comment] 2016-07-04 11:22
@T3N4K4 how do you play the content on the server side?

**Comment by T3N4K4** [comment] 2016-07-04 11:44
With the windows media player -> 12.0.9600.17031
I just tested without gfx, but with /rfx /multimedia:decoder:gstreamer and this works like a charm.
(Note: On the windows server 2012 r2 one has to enable the 32bit limitation with gpedit.msc in the remote desktop services host session)
This could be a workaround..

**Comment by T3N4K4** [comment] 2016-07-14 06:43
Update: With /gfx:rfx it does not crash, but shows the message:

[08:41:10:572] [9655:9692] [ERROR][com.freerdp.channels.drdynvc.client] - Protocol error: Duplicated ChannelId 6 (Microsoft::Windows::RDS::Graphics)!
[08:41:10:572] [9655:9692] [ERROR][com.freerdp.channels.drdynvc.client] - dvcman_channel_new failed!

Any ideas what is going wrong here ?

**Comment by T3N4K4** [comment] 2016-07-22 11:48
@bmiklautz is there any reference where I can lookup (specific)/ the errors ? I could try to fix them for myself.. but there seems to be almost nothing when I search for MS-RDPEGFX (except for the protocol specification) or for things like "drdynvc_order_recv failed with error 1359!" or "ChannelId 10 not found!".
I can only guess that ChannelId 10 is the GFX-Channel..

**Comment by bjcollins** [comment] 2016-09-27 21:08
I was playing around with this lately, ran into the same thing and bumped up the logging to see that ChannelID 10 is for the Channel defined in MS-RDPEGT which has the name "Microsoft::Windows::RDS::Geometry::v08.01". There are other related channels requested as well that we are not handling on the client side that I think are related: Microsoft::Windows::RDS::Video::Control::v08.01"" and "Microsoft::Windows::RDS::Video::Data::v08.01". That is all I know at this point, but it does not seem like freerdp is trying to support these channels based on my initial search through the code.

**Comment by bjcollins** [comment] 2016-09-28 14:05
As far as I can tell xfreerdp is doing the appropriate thing, MS-RDPEGT says a client should just not open the channel when requested from the server if it is not supported and that appears to be what is being done for the channel causing a problem: "Microsoft::Windows::RDS::Geometry::v08.01". However, the server still tries to use this channel when I open a video in Windows Media Player on Windows 10 and this causes the client to exit out since the channel is not open on the client side. This channel spec seems pretty simple, I wonder if it could be stubbed out to make things happy.

**Comment by T3N4K4** [comment] 2016-09-29 07:04
The problem is, that it worked fine for some months. And suddenly even with the before perfectly working versions freerdp crashes (local video formats played up to 1080p almost smoothly, 720p was perfect in image and sound).

I've done some tests with /gfx-h264. Youtube works, but local videos do not. And I've tried /gfx:rfx which does not work. I've even tried diifferent hardware since I thought this could be a problem too.

What I've seen lately on the windows side in the event viewer is that even without /multimedia or /gfx just with /rfx the gfx-channel is still loaded or somewhat tries to load the channel and fails therefore closing the connection.

With just /rfx the video channel is loaded correctly (event viewer) but the performance is not nearly good enough for 480p it seems.

When I have some more time I am going for a big debug session.

**Comment by bjcollins** [comment] 2016-09-29 17:59
I think you should check out this article: https://blogs.technet.microsoft.com/enterprisemobility/2012/08/16/enabling-a-seamless-multimedia-experience-with-remotefx-media-streaming-in-windows-server-2012-and-windows-8/

I am using Windows 10 which no longer supports MMR(/multimedia option in xfreerdp) and only supports the newer Media Streaming(which is not implemented in freerdp). Your backend supports both and it looks like the server side automatically determines which it thinks is better based on network conditions, etc. Maybe you can try using "/network:lan" in your command-line to see if that helps. Unfortunately, I am not sure how we can force the server side to never try media streaming at all since that is what is breaking the freerdp client software. When it worked before, I believe your windows media player was deciding to use MMR and is now deciding to use Media Streaming instead automatically. The problem is that media streaming consists of the channels I mentioned above which are only loaded if the gfx channel is loaded. FreeRDP is not opening these other channels and appears to be telling the server it did not open the channels, but when you go to play local video it decides to use the unopened channel "Microsoft::Windows::RDS::Geometry::v08.01" anyways. From what I can see in the spec, the only way the client says it does not support this channeling is by telling the server the channel open failed once the server requests it to be opened. So, I think FreeRDP is doing the correct thing(considering it does not support those three other channels).

I would suspect that without this bug with the media streaming channels and without /multimedia supplied that then the standard gfx channel handling of the desktop would then be used. Like this is when /gfx-h264 might be used for local video playback.

**Comment by T3N4K4** [comment] 2016-09-30 06:36
Thank you for your extensive answer.
Does that mean that from now on one should not use either -DWITH_X264 or -DWITH_OPENH264 since both are for decoding on the client side ?

I thought about it before that it is based on network or the server having the last decision whether to use MMR or the normal RFX Media Streaming.. Yesterday I tried with UDP since I read that 

> “This feature offers advanced techniques such as intelligent and adaptive UDP transports, network loss tolerance, and recovery to provide a fast and fluid experience to users on a WAN.”

Without MMR and without /gfx in any variety it works just with /rfx. Not perfectly, but it works (720p are a bit laggy but good enough I guess).
I guess I have to ditch /multimedia and focus on /rfx. 
What exactly does /gfx:rfx do ?

**Comment by bjcollins** [comment] 2016-09-30 19:28
@T3N4K4 I do not have all the answers because I am just digging through the spec myself, so you will most likely have to experiment for yourself.

If you are heavy on playing back local videos and running on Windows 2012R2, then you might want to use /multimedia without any /gfx options(this seems to work for me as it avoids the case that is breaking freerdp). /multimedia will give you the best video playback(should be built against gstreamer) if you are on a fast connection.I think /gfx:rfx just enables the rdpgfx channel without any H264 support. Based on my testing, the server seems to incorrectly try to send data on the channel from MS-RDPEGT we never agreed to open as soon as you start windows media player if we advertise to the server that we support the gfx channel. OPENH264 and X264 are only used for /gfx AVC420 and AVC444 it seems.

BTW: if you are getting those GetProcAddress errors still for tsmf then your /multimedia will do nothing. I think there is a bug in the current master with tsmf, it might work as is with BUILTIN_CHANNELS set but it is broke if you disable BUILTIN_CHANNELS.

**Comment by awakecoding** [comment] 2016-11-03 13:53
Even without multimedia redirection enabled, I can observe the same problem with Windows Server 2012 R2. To reproduce the issue, use /gfx when connecting, and play this [big buck bunny video](https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_h264.mov) in Windows Media Player.

**Comment by awakecoding** [comment] 2016-11-03 14:15
I've got a pull request here: https://github.com/FreeRDP/FreeRDP/pull/3584

**Comment by bmiklautz** [comment] 2016-11-03 14:58
@T3N4K4 could you verify that this fixes your problem? - It's merged to master now and should be in the nightly by tomorrow.

**Closed** 2016-11-03 14:57 UTC

**Comment by uplusplus** [comment] 2016-11-04 02:25
How to enable the 32bit limitation with gpedit.msc?

2016-07-04 19:44 GMT+08:00 Kai <notifications@github.com>:

**Comment by T3N4K4** [comment] 2016-11-04 07:43
@uplusplus 
Start: gpedit.msc
Go to: Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Remote Session Environment -> Limit maximum color depth.
There you go.

@bmiklautz It is working, but the input is hanging again when a video is playing. +async-input +async-update do not work here. What /max-loop-time do I have to configure to make it less laggy?
