### ISSUE TITLE
Middle mouse click autoscroll problem - Server 2008 R2

### ISSUE THREAD

**Issue by shivamsinghgit** [FreeRDP/FreeRDP#5374] opened 2019-05-04 12:10 UTC
I am facing the auto-scroll problem during taking RDP session in window Server 2008 R2 .
When clicking on the mouse wheel in a 2008 R2 RDP sessoin, autoscroll is activated in Excel 2007 as expected but it's not possible to release the scroll, or control the speed. plz provide the solution .
thanks in advance.

**Comment by akallabeth** [comment] 2019-05-04 18:54
Seriously?
Could you please at least read the issue template? 
I am no fortune teller and from the few things mentioned can not even guess what your problem is...

**Comment by shivamsinghgit** [comment] 2019-05-04 19:33
If you are not understanding the problem then u can ask for clarification ,
don't behave like u are boss here and I don't take tension this problem is
not at your level .

**Comment by akallabeth** [comment] 2019-05-04 21:12
hmm, looks like you're correct, sorry.
when first reading this your second sentence with the excel description was not there. (sorry, maybe missed it, but was really annoyed by not having that info ;))

anyway, the rest of the information in https://github.com/FreeRDP/FreeRDP/wiki/BugReporting is not meant as punishment for bug reporters but necessary information to reproduce and find a solution,
specifically the `/buildconfig` of your version (what are you actually using?)
and your command line (leave out passwords and such sensitive stuff)

**Comment by hardening** [comment] 2019-05-04 21:29
@akallabeth you're really nice, and BTW you're a kinda boss here ;)

**Comment by shivamsinghgit** [comment] 2019-05-05 05:34
Actually I am new on git so really sorry.

**Comment by akallabeth** [comment] 2019-05-05 09:06
@shivamsinghgit looks like we started on the wrong track.
so, `git`? no need for using that, just add the missing details about what you're using (aka which freerdp version/build) and how you connect (command line).

**Comment by shivamsinghgit** [comment] 2019-05-05 12:42
Actually I am taking the RDP session of  window server 2008 R2 and I open Excel 2007 and start auto-scroll using the mouse wheel and in a second try to stop at certain point of my Excel but it's not possible to release the scroll and my machine get stuck even I can't perform any other task on that RDP session.

**Comment by akallabeth** [comment] 2019-05-07 07:07
any update?
still waiting for the missing information...

**Comment by shivamsinghgit** [comment] 2019-05-07 09:30
Actually configure window server 2008 R2 and then take the RDP of that
machine .
After open Excel 2007 on that RDP session then press mouse wheel for
auto-scroll .
And after few second try to stop that scroll.
In my case I am not able to stop , for that I have to close the RDP session
.

**Comment by akallabeth** [comment] 2019-05-07 11:20
@shivamsinghgit ok, please read the whole thread and the link I sent you again. This is not the information requested.
* freerdp version you are using (`xfreerdp /buildconfig`)
* your command line you use for connecting

**Comment by shivamsinghgit** [comment] 2019-05-07 11:28
Microsoft Remote desktop connection.
I am taking the RDP session from other machine which supported Remote desktop
protocol 10.2.

**Comment by akallabeth** [comment] 2019-05-07 11:29
ok, not reponding to questions, closing.

**Closed by akallabeth** 2019-05-07 11:29 UTC
Labels: waiting-feedback

**Comment by shivamsinghgit** [comment] 2019-05-07 11:39
Okay
