### ISSUE TITLE
Parser error with "update_read_cache_bitmap_v2_order() failed" with /bpp:32 under unknown conditions

### ISSUE THREAD

**Issue by sergey-cheperis** [FreeRDP/FreeRDP#4166] opened 2017-10-05 22:00 UTC
While managing a set of customers' computers I've found that one of them causes xfreerdp to crash in a second after login if /bpp:32 is used. With /bpp:16 and /bpp:24 this does not happen. I have no idea in which way the computer is different from others. Might be some differences in Terminal Services settings forced by  group policies.  The target OS is Windows 7 Ultimate. XFreeRDP is compiled from current GIT master, and my OS is Ubuntu 16.04 LTS.

Command which works:

/usr/local/bin/xfreerdp /cert-ignore /bpp:24 /v:NNN /u:XXX /p:XXX /size:1920x1080

Command causing the crash:

/usr/local/bin/xfreerdp /cert-ignore /bpp:32 /v:NNN /u:XXX /p:XXX /size:1920x1080

Crash output:

[17:49:21:452] [19849:19850] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[17:49:23:006] [19849:19850] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[17:49:23:006] [19849:19850] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
[17:49:23:050] [19849:19850] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[17:49:25:086] [19849:19850] [ERROR][com.freerdp.core.orders] - ORDER_TYPE_BITMAP_COMPRESSED_V2 - update_read_cache_bitmap_v2_order() failed
[17:49:25:086] [19849:19850] [ERROR][com.freerdp.core.fastpath] - FASTPATH_UPDATETYPE_ORDERS - fastpath_recv_orders()
[17:49:25:086] [19849:19850] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data: fastpath_recv_update() - -1
[17:49:25:086] [19849:19850] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[17:49:25:086] [19849:19850] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[17:49:25:086] [19849:19850] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[17:49:25:086] [19849:19850] [INFO][com.freerdp.client.x11] - Network disconnect!
[17:49:25:086] [19849:19850] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor

**Comment by bmiklautz** [comment] 2017-10-06 08:23
@sergey-cheperis thanks for the report. Could you try if you can reproduce the problem when you add the parameter /gdi:sw?

**Comment by sergey-cheperis** [comment] 2017-10-06 15:24
@bmiklautz With /gdi:sw it acts the same.

**Comment by akallabeth** [comment] 2017-10-09 07:13
@sergey-cheperis Could you print out the order parameters (cacheId, flags, bpp, stream length, ...)? Would be nice to know, if the issue is due to a faulty packet in stream (sadly happens:/) or our decoder doing something it should not.
The second thing you can try is add ```-bitmap-cache -offscreen-cache``` and check if the connection is stable then.

**Comment by sergey-cheperis** [comment] 2017-10-11 15:03
@akallabeth 
update_read_cache_bitmap_v2_order() returns FALSE on the following condition:

`if (Stream_GetRemainingLength(s) < cache_bitmap_v2->bitmapLength)
			return FALSE;`

At this point, cache_bitmap_v2 contains the following: 

`{cacheId = 2, flags = 25, key1 = 0, key2 = 0, bitmapBpp = 32, bitmapWidth = 64, bitmapHeight = 64, bitmapLength = 2855, cacheIndex = 32767, 
  compressed = 1, cbCompFirstRowSize = 0, cbCompMainBodySize = 0, cbScanWidth = 0, cbUncompressedSize = 0, 
  bitmapDataStream = 0x7fffe40ca63d "0_\377\377\377\376\377\302\003/\001"}`

and compressed=1, and flags=3250, and Stream_GetRemainingLength(s)=451

**Comment by akallabeth** [comment] 2017-10-12 09:38
@sergey-cheperis Interesting, the header seems valid but the stream is short. Possibly a bug in the TCP/TLS code or with compression. Could you run with ```-compression``` to eliminate one of the two?

**Comment by sergey-cheperis** [comment] 2017-10-12 10:16
@akallabeth  Strange but when run with "-compression" it still receives ORDER_TYPE_BITMAP_COMPRESSED_V2 and crashes in exactly the same way.

**Comment by akallabeth** [comment] 2017-10-12 11:28
@sergey-cheperis good, so it is not that. Does the client keep running if you just return true?

**Comment by hardening** [comment] 2017-10-12 12:47
@sergey-cheperis can you try that => https://github.com/hardening/FreeRDP/tree/bitmapv2_fix ?

**Comment by sergey-cheperis** [comment] 2017-10-14 14:43
@hardening bitmapv2_fix does not fix the issue, it still acts exactly the same way.
When I replaced `return FALSE` with `return TRUE`, instead of crashing, it freezes screen update and starts flooding with messages:
`[10:39:25:713] [52662:52663] [ERROR][com.freerdp.cache.offscreen] - invalid offscreen bitmap at index: 0x00000000
[10:39:25:713] [52662:52663] [ERROR][com.freerdp.cache.offscreen] - invalid offscreen bitmap at index: 0x00000000
[10:39:25:713] [52662:52663] [ERROR][com.freerdp.cache.offscreen] - invalid offscreen bitmap at index: 0x00000000
[10:39:25:713] [52662:52663] [ERROR][com.freerdp.cache.offscreen] - invalid offscreen bitmap at index: 0x00000000
...........`

**Comment by akallabeth** [comment] 2017-11-08 14:10
@sergey-cheperis Any news on this one? Still crashing with current nightlies?

**Comment by sergey-cheperis** [comment] 2017-11-19 19:05
@akallabeth Unfortunately I do not have remote access to this PC anymore, and with none of other > 50 PC's could I reproduce the issue. I'll let you know if I encounter it again.

**Comment by sherwinkh** [comment] 2018-03-05 03:24
@akallabeth I have the same issue when the bbp set to 32.
update_read_cache_bitmap_v2_order() returns FALSE on the following condition:

if (Stream_GetRemainingLength(s) < cache_bitmap_v2->bitmapLength) return FALSE;
at this point ,my debug info:
Stream_GetRemainingLength(s)=1621,cache_bitmap_v2->bitmapLength=6065
any suggestion？

**Comment by akallabeth** [comment] 2018-03-05 08:43
@sherwinkh could you give some more details on your setup?

**Comment by akallabeth** [comment] 2018-03-05 08:46
@sherwinkh And are you getting this error with compressed or uncompressed bitmaps?

**Comment by sherwinkh** [comment] 2018-03-05 09:08
@akallabeth 
I use below script to start rdp in my device （arm platform）：
#!/bin/sh
USERIP=192.168.1.60
USERNAME=dbg
PASSWORD=1
BPP=32
CONST_CMD="+fonts /f -sec-tls -sec-nla"
/usr/bin/Xorg  -pixmap32 vt13  &
export DISPLAY=:0.0
/usr/bin/xfreerdp /v:$USERIP /u:$USERNAME /p:$PASSWORD /bpp:$BPP $CONST_CMD &

**Comment by akallabeth** [comment] 2018-03-05 09:12
@sherwinkh And the remote end? This seems to be some issue with the received orders.

**Comment by sherwinkh** [comment] 2018-03-05 09:12
@akallabeth ，more detail log：
	Stream_GetRemainingLength(s)=1698
	cache_bitmap_v2 Info
		cacheId           =2
		flags             =25
		key1              =0
		key2              =0
		bitmapBpp         =32
		bitmapWidth       =64
		bitmapHeight      =64
		bitmapLength      =6065
		cacheIndex        =32767
		compressed        =1
		cbCompFirstRowSize=0
		cbCompMainBodySize=0
		cbUncompressedSize=0
	update_read_cache_bitmap_v2_order,@line1871
[00:52:28:727] [1300:1304] [ERROR][com.freerdp.core.orders] - ORDER_TYPE_BITMAP_COMPRESSED_V2 - update_read_cache_bitmap_v2_order() failed
[00:52:28:727] [1300:1304] [ERROR][com.freerdp.core.fastpath] - FASTPATH_UPDATETYPE_ORDERS - fastpath_recv_orders()
[00:52:28:727] [1300:1304] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data: fastpath_recv_update() - -1
[00:52:28:728] [1300:1304] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[00:52:28:728] [1300:1304] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[00:52:28:728] [1300:1304] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[00:52:28:728] [1300:1304] [INFO][com.freerdp.client.x11] - Network disconnect!
[00:52:28:728] [1300:1304] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor

**Comment by akallabeth** [comment] 2018-03-05 09:15
And a last question, you're using which version of FreeRDP?

**Comment by sherwinkh** [comment] 2018-03-05 09:18
@akallabeth ,I download the latest  FreeRDP from github on last Friday ，at version 4d401b4 Merge pull request #4459 from akallabeth/surface_cmd_fix

**Comment by akallabeth** [comment] 2018-03-05 09:25
@sherwinkh Ok, that is something to work with. Still need information about your remote end though. Which RDP server / version are you using?

**Comment by sherwinkh** [comment] 2018-03-05 09:28
RDP server： Windows 7 Ultimate SP1

**Comment by akallabeth** [comment] 2018-03-05 10:14
@sherwinkh Created a branch with some additional checks here https://github.com/akallabeth/FreeRDP/tree/order_fixes
Could you test if this is working better / or at least giving some hint on what is wrong?

**Comment by sherwinkh** [comment] 2018-03-05 10:30
@akallabeth I'll test this branch，and give you feedback as soon.

**Comment by akallabeth** [comment] 2018-03-05 10:33
@sherwinkh Ok, managed to reproduce with a win7 VM here too.
Strangely enough this seems to be a bug in win 7 (the whole order is correct, except the length of the bitmap does not correspond to the data received?!?)
Changing to `/bpp:24` resolves the issue and the whole bitmap cache is working correctly here.

**Comment by akallabeth** [comment] 2018-03-05 10:35
@sherwinkh Even more odd, the issue only occurs after receiving ~20 correct bitmap orders :/

**Comment by akallabeth** [comment] 2018-03-05 10:53
And another data point is `/codec-cache:rfx` is working perfectly fine, whereas `/codec-cache:nsc` exposes the same issue.
Both of these options just enable bitmap cache v3 with the same header parsing.
Looks like some servers send invalid header data with certain bitmap encodings.

**Comment by sherwinkh** [comment] 2018-03-05 11:03
@akallabeth ,I have test your branch，seems not work.
I just replace my order.c with the order.c copied from your branch.
On  my device， /bpp:24 also work well

**Comment by sherwinkh** [comment] 2018-03-05 11:07
with /codec-cache:nsc  ，encounter this issue：
ORDER_TYPE_BITMAP_COMPRESSED_V3 - update_read_cache_bitmap_v3_order() failed

**Comment by akallabeth** [comment] 2018-05-11 09:57
Closing this as it is a server side bug (invalid data in headers)

**Closed by akallabeth** 2018-05-11 09:57 UTC
Labels: waiting-feedback

**Comment by janecer** [comment] 2020-03-16 04:32
> with /codec-cache:nsc ，encounter this issue：
> ORDER_TYPE_BITMAP_COMPRESSED_V3 - update_read_cache_bitmap_v3_order() failed

did you salve it ?i have the same problem
