### ISSUE TITLE
Smartcard sharing to Windows 2012

### ISSUE THREAD

**Issue by LordPicard** [FreeRDP/FreeRDP#2891] opened 2015-09-16 16:15 UTC
Hello there,

I'm using the Remmina to connect from a Ubuntu 15.04 to a Windows 2012 Server (and a 2016 Technical Preview 3, just for testing of thie issue, but none work).

Steeps to reproduce:

1 - device is correctly attach and configured, and I can use it localy; check with dmesg also
2 - try to connect to a RDP using Windows 2012 or 2016 TP 3 (I don't have any licencing for 2008, so I can't tell if it does work)
3 - use the card with Windows software and you see that you can't

I've the most updated version of FreeRDP and Remmina 
Please node my card have two certificates (PKCS#11).

I've inicialy post this on Remmia issues, here https://github.com/FreeRDP/Remmina/issues/643, but was redirected to this track.

antenore suggest me to use the command line to debug the issue - however, as I'm switching from Windows to Linux I'm not yet familiar with the tiny things I've to learn and using --help I found many (too many) commands to try.

Can someone point me to the right direction debugging this issue?

Thank you,

LP

**Comment by bmiklautz** [comment] 2015-09-17 10:17
@LordPicard you could reproduce this problem also if you used xfreerdp directly?

**Comment by LordPicard** [comment] 2015-09-17 11:22
Hello, 

I'm not sure how can I do it, because I don't quite know how to launch xfreerdp from the console with what I need.

Could you give me an example? Reading --help didn't get me anywhere, as I don't know if I must enter the address to connect in the command line or not.

Thanks.

LP.

**Comment by HenryJacques** [comment] 2015-09-18 08:36
@LordPicard : how do you know that you can indeed use the smartcard on Linux? What do you mean by "I can use it locally"? Using dmesg only shows that the smartcard has been in some way "seen" by the kernel, that's all.

Do you have the following packages installed: pcscd, libpcsclite1, libccid?
(in console, just type 
$ dpkg -l | grep -E "ccid|pcsc"
and past here the output)

Regards

**Comment by LordPicard** [comment] 2015-09-18 10:04
Hello,

Here is the result:
$ dpkg -l | grep -E "ccid|pcsc"
ii  libccid                                             1.4.18-1                                       i386         PC/SC driver for USB CCID smart card readers
ii  libpcsclite1:i386                                   1.8.11-3ubuntu1                                i386         Middleware to access a smart card using PC/SC (library)
ii  pcscd                                               1.8.11-3ubuntu1                                i386         Middleware to access a smart card using PC/SC (daemon side)


I know  I can use it locally because I can sign e-mails on Thunderbird. However when I connect to a Windows 2012 Server and try to use the same card, using Thunderbird to sigh documents, it fails.

I have the software needed in both Linux and Windows to read the card and the certs in the card.

Hope this can help you diagnose the problem.


Thanks for your help.

LP

**Comment by HenryJacques** [comment] 2015-09-18 11:32
All right, I see.
Maybe another silly question but I have to ask it: directly on your Windows Server 2012 (without FreeRDP) can you sign documents using the smartcard?

Another thing: does it work from a Windows workstation using the mstsc client? (if it works with mstsc, it should work with FreeRDP. It also allows to check that smartcard redirection is allowed on your 2012 server).

Using FreeRDP, on your 2012 server, what is the output of the software who read the certs in the card? Does it at least show the reader?

Bye

**Comment by LordPicard** [comment] 2015-09-18 12:47
Hey @HenryJacques thanks for the quick reply.

Regarding your questions:
I can't say if it works using a Windows 2012 Server directly as this is a virtual machine (both KVM and VMware have the same problem with the card on Linux)
However I can guarantee you that I can use it using a Windows 7 and 8 with the defaut MS client.

Prior to the update I did following the information on https://github.com/FreeRDP/Remmina/issues/643 the card where not detected at all.
Now I get a message saying this:
![card](https://cloud.githubusercontent.com/assets/14263158/9959344/1d251ecc-5e0b-11e5-84f5-1614cb260a08.png)

One other thing worth mention is that the card is a MiniLector EVO - check http://www.bit4id.com/pt/index.php?option=com_content&view=article&id=157&Itemid=179 for product information - but when I connect using Ubuntu it is show as "ACS ACR 38U-CCID 0" witch probably means this product: http://www.bit4id.com/pt/index.php?option=com_content&view=article&id=157&Itemid=179

The products are visualy allmost identical and maybe - this is just a wild guess - Ubuntu is getting the hardware-related drivers (is there such thing as "drivers" in Linux?) wrong.

I just notice this a few minutes ago, so I'm not sure if this is a xfreerdp issue or not. 
But if it's not, if you can point me to the right direction I'd appreciate. 

Thanks,
LP

**Comment by HenryJacques** [comment] 2015-09-18 13:12
If you can use your smartcard on Linux (with Thunderbird as you did for example), then it is ok to say that it is a FreeRDP-related problem.
Yes, Linux (the daemon which allow to communicate with the card - pcscd) use a driver which is shipped with libccid. 

DId you install freerdp from https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next (1.2.0~git20150207)?

You should definitely use freerdp from the command line:

Try this:

$ xfreerdp /v:YOUR_SERVER_IP /sec:rdp /smartcard:xxxx:xxxx

**Comment by LordPicard** [comment] 2015-09-18 14:22
Hello agains.

What should be the value on xxxx:xxxx for /smartcard?
It's the ID I get from dmsg when I connect the smartcard?

I will try it as soon as I got that tiny thing figure out.


About the version I have, its version 1.2.1-dev (git n/a). I use what I got frtom standart Ubuntu 15 and then update with the instructions here for end users: https://github.com/FreeRDP/Remmina/wiki

Should I try to update xfreerdp before trying that command? If yes, do you have a similar guide like that one?


Thanks,

LP

**Comment by HenryJacques** [comment] 2015-09-18 14:56
You can use literally the string "xxxx:xxxx". It is not really taken into account by freerdp because it counts on libpcsc to enumerate the readers and in the end it will redirect all the readers you have connected (even if you only specify one - which isn't your problem anyway)
In theory xxxx:xxxx should be the USB vendorID and productID as shown by the command "lsusb"

No don't try to update xfreerdp yet, try as it is and past the output of the command.
But I fear that you'll have to use a debug version of freerdp with more verbose messages.

Bye

**Comment by LordPicard** [comment] 2015-09-19 07:10
Hello,

I got this error, but

[08:08:03:434] [2791:-1236235456] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[08:08:03:435] [2791:-1236235456] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[08:08:03:436] [2791:-1236235456] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: lordpicard
[08:08:03:654] [2791:-1236235456] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[08:08:03:654] [2791:-1236235456] [ERROR][com.freerdp.core] - freerdp_set_last_error 0x2000C
[08:08:03:655] [2791:-1236235456] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure

I solve the username thing, however viewing --help and trying some security options for RDP seems harder than I can take.

This is not related to smartcard I think.
Can you help me with the /command to get around the negotiation of the SSL connection?

Thanks,
LP

**Comment by HenryJacques** [comment] 2015-09-23 13:50
Yes this is not related the the smartcard. You're not even connected yet.

Try with 
$ xfreerdp /v:YOUR_SERVER_IP /u:WINDOWS_LOGIN /sec:nla /smartcard:xxxx:xxxx
(and add a "/d:YOURDOMAIN" if the server is in a domain)

Bye

**Comment by sconstantine** [comment] 2015-10-19 16:08
Any progress or updates to smart card redirection?  (different from authentication which works fine for me, talking about the actual redirection of the card services into the RD session)

**Comment by mindisfree** [comment] 2016-04-30 00:30
Hello any updates on this. New to smart cards and running MAC OS X 10.11.4 trying to run freeRDP. Here is the command i am running xfreerdp +sec-nla /f /d:us /smartcard: /v:IPhere 
Get this error: (it takes the password)
loading channel rdpdr
loading channel rdpsnd
Warning xf_GetWindowProperty (177): Property 302 does not exist
connected to 10.217.72.248:3389
Password: 
SSL_read: Failure in SSL library (protocol error?)
SSL_read: error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied
credssp_recv() error: -1
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
Error: protocol security negotiation or connection failure

any help would be great

**Comment by mindisfree** [comment] 2016-05-02 23:47
Hello any updates on this. New to smart cards and running MAC OS X 10.11.4 trying to run freeRDP. Here is the command i am running xfreerdp +sec-nla /f /d:us /smartcard: /v:IPhere 
Get this error: (it takes the password)
loading channel rdpdr
loading channel rdpsnd
Warning xf_GetWindowProperty (177): Property 302 does not exist
connected to IPHERE .248:3389
Password: 
SSL_read: Failure in SSL library (protocol error?)
SSL_read: error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied
credssp_recv() error: -1
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
Error: protocol security negotiation or connection failure

any help would be great

**Comment by HenryJacques** [comment] 2016-05-03 05:24
@mindisfree I suggest you open another issue instead of using an already opened post.
That said, your issue has nothing to do with smartcard redirection. First you have an authentication problem. You didn't put the user parameter (/u:user), why is that? By default it will take your session username and that's generally not what you want to do.

**Comment by sconstantine** [comment] 2016-05-03 07:31
@HenryJacques, there are a number of open issues for smart card redirection however I'm not seeing much activity in them.  Would it be rude to open yet another issue or better to bump the existing ones?  I believe Felix & @lemonmojo team are aware of it with details, unsure what the hurdles or any plans are though...?

**Comment by mindisfree** [comment] 2016-05-03 12:39
@HenryJacques  I will open a new issues. The reason why I don't username is I am using a smart card and I will never need to enter a username. It will take that from the smart card it self.

**Comment by bmiklautz** [comment] 2017-12-14 16:05
There have be a log of fixes and improvements on master. Please try. I'll close the issue if the problem still exists please re-open or open a new one.

**Closed by bmiklautz** 2017-12-14 16:05 UTC
