### ISSUE TITLE
Multiple remote apps not sharing session

### ISSUE THREAD

**Issue by jcrespo-asg** [FreeRDP/FreeRDP#3651] opened 2016-12-11 17:39 UTC
Hello,

When using the below rdp files on windows the sessions created on the server (windows server 2012 r2 native remote apps) are the same, so both applications run under the same session. But when using freerdp every connection creates a new session on the server. I am not sure if it is a bug or if I am doing something wrong, as per my understanding it should behave the same as native remoteApp.  Have tried on master and s1.1

rdp 1- Calculator
`disableconnectionsharing:i:0
redirectclipboard:i:0
redirectprinters:i:0
redirectcomports:i:0
redirectsmartcards:i:0
session bpp:i:32
span monitors:i:1
use multimon:i:1
remoteapplicationmode:i:1
server port:i:3389
allow font smoothing:i:1
videoplaybackmode:i:1
audiocapturemode:i:1
full address:s:10.50.2.180
alternate shell:s:||calc
remoteapplicationprogram:s:||calc
remoteapplicationname:s:Calculator
remoteapplicationcmdline:s:
workspace id:s:10.50.2.180
username:s:FBar
domain:s:FOREST
`

rd2 - chrome
`disableconnectionsharing:i:0
redirectclipboard:i:0
redirectprinters:i:0
redirectcomports:i:0
redirectsmartcards:i:0
session bpp:i:32
span monitors:i:1
use multimon:i:1
remoteapplicationmode:i:1
server port:i:3389
allow font smoothing:i:1
videoplaybackmode:i:1
audiocapturemode:i:1
full address:s:10.50.2.180
alternate shell:s:||chome
remoteapplicationprogram:s:||chrome
remoteapplicationname:s:Google Chrome
remoteapplicationcmdline:s:
workspace id:s:10.50.2.180
username:s:FBar
domain:s:FOREST
`

**Comment by akallabeth** [comment] 2016-12-11 18:26
Duplicate of #3032

**Closed by akallabeth** 2016-12-11 18:26 UTC
