### ISSUE TITLE
Bad RDP performance when using notepad++ - glyph-cache performance

### ISSUE THREAD

**Issue by Arakis** [FreeRDP/FreeRDP#1612] opened 2013-11-22 14:53 UTC
Hello,
I'm working very intensive with freerdp on different servers. All is fine (on every server), but when using Notepad++ (on windows), and editing a large file, its very, very slow. Freerdp seems to be frozen, but some seconds later, there is a delayed reaction.

This problem occurs only in Notepad++.
The problem occurs in freerdp 1.0.2 as also in the latest git (self) compilation. On microsoft rdp (mstsc) all is fine.

Because i need a good texteditor in the remote session, i'm using now Geany (windows binary compilation).

Greetings,
Sebastian

**Comment by roms2000** [comment] 2017-02-16 09:04
In FreeRDP version 2.0.0-dev (git 5707319) and with Notepad++, the bad scrolling performance is always present.

Command line with "-offscreen-cache -glyph-cache" make it response fast but without or only with "-offscreen-cache" or "-glyph-cache" does not.

**Comment by akallabeth** [comment] 2017-02-16 12:37
@roms2000 Can not reproduce your issues with ```xfreerdp /v:<server> /u:<user> /p:<pwd> /f /bpp:32``` where the remote end is a windows 10 machine.
Could you elaborate what exactly you try?

**Comment by roms2000** [comment] 2017-02-16 14:24
Our remote server is a 2008r2.

Command line where (fast) scrolling is OK whit Notepad++ : 
- xfreerdp /f /d:domain.loc /rfx /sound /sec:rdp -glyph-cache -offscreen-cache /smartcard /v:192.168.0.212

With next commands lines, it is really bad :
- xfreerdp /f /d:domain.loc /rfx /sound /sec:rdp -glyph-cache /smartcard /v:192.168.0.212
- xfreerdp /f /d:domain.loc /rfx /sound /sec:rdp -offscreen-cache /smartcard /v:192.168.0.212

To view the bad scrolling performance, we have to scroll up / down (with mouse wheel) multiples times in Notepad++, go to Firefox (or other app), scroll up / down (with mouse wheel) multiples times, go back to Notepad++, then try to scroll up / down (with mouse wheel) : scrolling is jumping.

If I exit FreeRDP, then reconnect to server, use scrolling with Notepad++, it's OK. But if I change app and go back to Notepad++ it is not.

**Comment by akallabeth** [comment] 2017-02-16 14:54
@roms2000 Not reproducible here with a windows server 2008 R2 with any of your provided command lines. Some of them actually do not make any sense (```-glyph-cache```) as that is the default and /rfx overrides any of these options (they only apply to old style RDP connections, not RFX or GFX)
Are you using self compiled FreeRDP? Can you check if the issue also occurs with our nightly builds?

**Comment by roms2000** [comment] 2017-02-16 15:36
Strange, I have the same problem on a Debian Jessie with nightly build this time.
On a fullscreen at 1280x800, problem seems to be absent. But on the same machine with a fullscreen of 1600x1200, I have this behavior with the nightly.
Even with a 2016 server, the same apply.

In my first test, FreeRDP was compiled for Thinstation 5.5 with :
```
cmake . -DCMAKE_INSTALL_PREFIX=/usr \
                -DCMAKE_INSTALL_LIBDIR=lib \
                -DDOCBOOKXSL_DIR=/usr/share/sgml/docbook/xsl-ns-stylesheets \
                -DCMAKE_BUILD_TYPE=Release \
                -DWITH_PCSC=ON \
                -DBUILD_SHARED_LIBS=ON \
                -DWITH_CHANNELS=ON \
                -DWITH_CHANNELS_PRINT=ON \
                -DWITH_SERVER=OFF \
                -DWITH_CLIENT=ON \
                -DWITH_PULSE=OFF \
                -DWITH_ALSA=ON \
                -DWITH_CUPS=ON \
                -DWITH_FFMPEG=ON \
                -DWITH_OPENH264=OFF \
                -DCHANNEL_URBDRC_CLIENT=ON \
                -DWITH_GSTREAMER=ON \
                -DWITH_DIRECTFB=OFF \
                -DWITH_XINERAMA=ON \
                -DWITH_CUNIT=OFF \
                -DWITH_JPEG=ON \
                -DWITH_IPP=OFF \
                -DWITH_NPP=OFF \
                -DWITH_MANPAGES=OFF \
                -DWITH_SAMPLE=ON
```

**Comment by akallabeth** [comment] 2017-02-16 16:19
@roms2000 sounds like a performance issue (```RFX``` decoder) What kind of hardware are you running this on? Does the same issue occur if you try ```/gfx``` or ```/gfx:avc420``` or ```/gfx:avc444```? (for the latter it is desirable to compile with OpenH264 support or FFmpeg and very recent master)

**Comment by roms2000** [comment] 2017-02-17 15:30
Hardware on Debian Jessie is a Core 5i M560 and on Thinstation 5.5 a Celeron N3050
Defaults graphics cards.

With the 2016 srv adding /gfx is OK and really nice with Notepad++.

For one 2008r2 srv, the lag is here for notepad++ (nsc codec seems to be used), may be because it is in "remote administration" mode.
For other 2008r2 srv, the lag is not present with notepad++ (RDSH mode)

So the error is not on rfx codec but the fallback codec if rfx isn't available ?

**Comment by akallabeth** [comment] 2017-02-19 16:08
@roms2000 Ah, ok. We're closing in. Could you try a commandline completely without ```/rfx``` and ```/gfx``` only with ```/bpp:<32|24|16|15|8>```? That way we may get the culprit narrowed down a bit.

**Comment by roms2000** [comment] 2017-02-20 10:37
Ok, I have tried all `/bpp:<32|24|16|15|8>` against 2008R2 and 2016, command line used :

`xfreerdp /f /d:mydomain.loc /u:myuser /p:mypassword /v:myserver /log-level:DEBUG /bpp:X`

My results :
```
          |   2008R2   |   2016   |
/bpp:32   |   bad      |   OK     |
/bpp:24   |   bad      |   OK     |
/bpp:16   |   bad      |   OK     |
/bpp:15   |   bad      |   OK     |
/bpp:8    |   OK       |   OK     |
```

**Comment by roms2000** [comment] 2017-02-22 10:00
Another test againts 2008R2 with differents commands lines : 
Test -> ```xfreerdp /f /d:mydomain.loc /u:myuser /p:mypassword /v:myserver /log-level:DEBUG```
Result -> bad scrolling + No blinking cursor while typing text or scrolling in Word 2003 and maybe other apps.

Test -> ```xfreerdp /f /d:mydomain.loc /u:myuser /p:mypassword /v:myserver /log-level:DEBUG -offscreen-cache```
Result -> bad scrolling + No blinking cursor while typing text or scrolling in Word 2003 and maybe other apps.

Test -> ```xfreerdp /f /d:mydomain.loc /u:myuser /p:mypassword /v:myserver /log-level:DEBUG -bitmap-cache```
Result -> good scrolling + blinking cursor while typing text in Word 2003 : OK

Test -> ```xfreerdp /f /d:mydomain.loc /u:myuser /p:mypassword /v:myserver /log-level:DEBUG -bitmap-cache -offscreen-cache```
Result -> good scrolling + blinking cursor while typing text in Word 2003 : OK

**Comment by akallabeth** [comment] 2017-02-22 11:30
@roms2000 Ok, that looks like actually the bitmap cache is at fault and not the glyph cache (which is off by default)

**Comment by muwlgr** [comment] 2017-09-01 16:45
Having same scroll issues with mintty (Cygwin terminal app.). 
Server is 2008 R2 in default mode (remote admin, 2 active sessions only), i.e. without RD Session Host
I run xfreerdp /f /xm /clipboard on 1920x1200 monitor
Will test -bitmap-cache when I get to my Linux desktop and report my results (tomorrow)

**Comment by muwlgr** [comment] 2017-09-05 08:30
switched to FreeRDP nightly build from Ubuntu Xenial package and found that mintty scrolls perfectly without any -bitmap-cache

**Comment by argonym** [comment] 2017-12-08 14:45
Connecting to Server2008R2 (= Windows 7) with FreeRDP 2.0.0-rc1 (84f81618) _without_ `-bitmap-cache` still gives me the laggy graphics. Tried many other graphics- and transport-related commandline options and the bitmap cache seems to be the thing. (Server2012R2/Win8.1 is fine regardless of the option.)

Maybe it should be disabled by default, at least on servers with RDP protocol version < 8.

**Comment by hardening** [comment] 2017-12-28 10:27
@argonym I had some feedback from microsoft on a completely different issue and it seems like they have some other problems with bitmap cache disabled (disconnection in my case).

**Comment by argonym** [comment] 2017-12-28 13:31
Ok, then I'll simply use `-bitmap-cache` for now, as it works fine for me and my usage patterns do not seem to result in disconnects. (I experience some occasionally as my VPN+SSH tunnel combo is occasionally unstable or so I thought, but who knows, will let you know here if any DCs can be rather attributed to the disabled bitmap cache.)

**Comment by Onoro** [comment] 2018-02-02 13:44
There are is a problem with Freerdp, on some PC's it works slow. I don't know how to describe exactly, but I'll try with my own words and wideo. 
We have 100Mbit network, client - Debian 8 x64, server Windows 7 x64. Freerdp version - last from repository.
When I'm trying to move something on remote screen, image becomes indistinct. No matter it's Excell table scrolling or windows, there are is an video example:

http://www.filedropper.com/vokoscreen-2018-02-0214-50-46

My command line is 
/opt/freerdp-nightly/bin/xfreerdp /v:192.168.1.43 /f /bpp:32 /kbd:0x00000419 +menu-anims +window-drag -clipboard +auto-reconnect /gdi:sw +fonts /u:"buh3" /p:"23sdfq23eqweedas"
On old PC's it works fine, but there are is a problem with new Asus N3050I-C.

I tried with and without -offscreen-cache -glyph-cache, but with no luck. At the same time, there are no any problem with Remmina. 
The last attempt was 
/opt/freerdp-nightly/bin/xfreerdp /v:192.168.1.43 /f /u:"buh3" /p:"23sdfq23eqweedas"
but with no luck to.

**Comment by argonym** [comment] 2018-03-23 11:15
@Onoro Did you try with `-bitmap-cache`?

**Comment by akallabeth** [comment] 2018-11-22 14:07
We've disabled `glyph-cache` by default now and marked it experimental.
Since it is part of legacy GDI mode we'll probably will have to live with it not being available, but it is not required for operation anyway.

**Closed by akallabeth** 2018-11-22 14:07 UTC
Labels: waiting-feedback

**Comment by argonym** [comment] 2018-11-28 16:23
@akallabeth : What about the `bitmap-cache`? Is it also part of the legacy GDI mode? Would disabling it be a separate issue?

**Comment by akallabeth** [comment] 2018-11-29 09:01
@argonym `glyph-cache` is actually buggy (client wise), but if I read this thread correctly `bitmap-cache` is only slower in some implementations?
Should use `rfx` or `gfx` anyway if you're interested in performance ;)

**Comment by argonym** [comment] 2018-12-04 15:22
@akallabeth Sure, using `rfx` and `gfx`, just not supported by 2008R2/7 RDP servers.
Yes, `bitmap-cache` is so slow (X11 client) it shouldn't be on by default.
