### ISSUE TITLE
Slow windows drawing/update if i move with the mouse a powerpoint box - some seconds lag

### ISSUE THREAD

**Issue by ropetry** [FreeRDP/FreeRDP#3628] opened 2016-11-25 15:00 UTC
Hello, i think i have found an odd behavior in freerdp.  

Terminal Server 2008 R2
commandline:
xfreerdp -sec:rdp /f /multimon:force /v:servername

If i draw in Powerpoint an box with the mouse the box appears verry slowly on the screen. if i move the mouse ( still pressed ) and the box gets bigger and smaller i have a timelag of 2-5 seconds.

Same behavior in the freeplane mindmap manager.. moving a node item has also this lag..

I have tried to find an older working Version which hasn´t the problem.  This one is working for me.. 
GOOD: bfdab0ed4aff4ea09966e93aa73e31b186fe78ef.

First Version which doesn´t work is this one..
BAD: 06a04a0199b2c53bfdf121e94e885d7919ed3911

I checked also Master from today and still the problem is around.
i can upload a video if someone wants to see it 8-)..

Anyone around who can verify this ?

**Comment by akallabeth** [comment] 2016-11-27 13:34
@ropetry could you provide a command line to get an idea which operations may be at fault?

**Comment by akallabeth** [comment] 2016-11-27 13:37
sorry, wrong issue, question for you was could you find out which operations are involved in your example? bitblt may have a debug print, but not sure and nowhere near a proper computer.

**Comment by akallabeth** [comment] 2016-11-28 08:25
@ropetry Could you also check, if the issue persists when using ```/gdi:sw```?

**Comment by ropetry** [comment] 2016-11-28 11:51
@akallabeth I will try it as soon as possible.. today no access to the system. But perhaps you could help me in the meantime by explaing your debug wish..
i searched for bitblt in the code and some log lines near it, but didn´t find something i can use.

**Comment by akallabeth** [comment] 2016-11-28 14:02
@ropetry: You connect with 16bit color depth (default) and legacy GDI operations (no RFX/GFX/H264 modes active).
In this mode the drawing is done by ```gdi_BitBlt```, ```gdi_LineTo``` and a few others.
```gdi_BitBlt``` implements a whole lot of subfunctions, which are of different importance for different Windows Server versions.
The current implementation is falling back to a generic (slow) decoding to implement all possible subfunctions, but uses optimized versions for heavily used ones.
Since you encountered slow performance, it would be interesting to know, which one is responsible.

**Comment by akallabeth** [comment] 2016-11-28 14:04
@ropetry If you add a log line in ```BitBlt_process``` printing ```rop``` should be sufficient. Be aware that that will slow down the whole client and write a whole lot of logging.

**Comment by ropetry** [comment] 2016-11-30 13:19
@akallabeth : spent some time this morning to answer your question but i think i can´t answer your questions deeper 8-(..for the moment. perhaps you can take me a little bit further..

i started with a fresh checkout from master ( last commit e60d0d5) and added some wlog debug stuff in the bitmap.c and gdi.c
gdi_bitBlt gets a new line with
WLog_INFO(TAG,  "DEBUGDH initialize gdi_BitBlt function");
WLog_INFO(WLog_Get(TAG), WLOG_INFO, "DEBUG DH ROP=%s", rop);

but i don´t see them with my normal command line

xfreerdp -sec:rdp /v:servername

if i use the /gdi:sw switch i see those Loglines, but i get a segfault and freerdp crashes directly. So normally i don´t use gdi:sw.

i added also some lines to gdi.c like
WLog_INFO(TAG,  "DEBUG DH initialize gdi_bitmap_update");
in the gdi_bitmap_update function.. those lines appear verry often 8-).

If i don´t use the /gdi:sw switch i think it will use some hw gdi functions. Is there an other place to debug those lines ? as in the bitmap.c file

my configure script looks like this
-----
#!/bin/bash
cmake \
        -DCMAKE_BUILD_TYPE=Debug \
        -DCMAKE_C_FLAGS="$RPM_OPT_FLAGS" \
        -DCMAKE_INSTALL_PREFIX=/opt/freerdp \
        -DCMAKE_SKIP_INSTALL_RPATH=ON \
        -DSTATIC_CHANNELS=OFF \
        -DWITH_ALSA=OFF \
        -DWITH_FFMPEG=ON \
        -DWITH_GSTREAMER_0_10=ON \
        -DWITH_GSTREAMER_1_0=OFF \
        -DWITH_PULSE=ON \
        -DWITH_SSE2=ON \
        -DBUILD_SHARED_LIBS=OFF
------

Coudl you please give me some more assistance on this. Thanks for you time
bye
roman

**Comment by ropetry** [comment] 2016-11-30 14:03
@akallabeth : sorry i have to re-edit this 3 times. now the comments and logs are valid.

**Comment by akallabeth** [comment] 2016-11-30 14:40
@ropetry Please compile with some optimisations (just use Release build). This speeds things up a lot. As for your debug messages, better place is (as mentioned before)  ```BitBlt_process``` printing ```rop``` (which is already a string there) is sufficient.

As you mentioned that it is also quite slow when using default settings, you can try the following options:
* Different color depths ```/bpp:32``` or ```/bpp:24``` 
* ```/rfx```, ```/gfx```, ```/gfx-h264````(requires OpenH264) and a combination of these

**Comment by ropetry** [comment] 2016-11-30 15:38
@akallabeth : thanks again.. sorry i missed the old line with your hint to the right function to add the debug line. Did it now and i see this behavior: 
I have to use the gdi:sw switch again to see the debugs..
here are the outputs with gdi:sw enabled and doing powerpoint box drawing.

[16:13:01:910] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:02:572] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:02:572] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:02:723] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:02:724] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:02:843] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:02:844] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:02:987] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:02:988] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:02:060] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:02:060] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:03:236] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:03:236] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:03:343] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:03:344] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:03:580] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:03:580] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:03:852] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:03:852] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:05:262] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:05:263] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:05:263] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:05:263] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:07:372] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:07:372] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:07:372] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:07:372] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:18:812] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DSa
[16:13:18:813] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DSo
[16:13:18:814] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DSa
[16:13:18:815] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DSo
[16:13:18:862] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DSa
[16:13:18:863] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DSo
[16:13:45:234] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:45:560] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:45:560] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:45:655] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:45:656] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:46:520] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:46:521] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:46:521] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:46:521] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx
[16:13:46:521] [29890:29892] [INFO][com.freerdp.gdi.bitmap] - DEBUGDH initialize BitBlt_processROP= DPx

Test with /gfx fails with error loadling lib librdpgfx-client.so .not a real static build i think with my compile options. 
Test with /rfx works and looks good i think..
/bpp:32 or 24 doesn´t help

if i use /gdi:hw or /gdi:sw it is slow. with /rfx it is o.k
The old Version bfdab0e is at same speed for alloptions i think..
Anythink i can do further to help ? 
bye
roman

**Comment by akallabeth** [comment] 2016-12-01 10:01
@ropetry Ok, so it is not an issue with the ```BitBlt``` options. The one you posted in the logs is using X11 accelerated operation with ```/gdi:hw``` (default if ```/gdi:sw``` is not specified)
So to further debug this:
* Could you post the output of```xfreerdp /buildconfig```?
* Could you add debug options in ```gdi_opaque_rect```, ```gdi_multi_opaque_rect```, ```gdi_line_to```, ```gdi_polyline``` and ```gdi_surface_bits```

**Comment by ropetry** [comment] 2016-12-01 13:10
@akallabeth O.K. Thanks for those infos. If you want to see the problem have a look at //videobin.org/+ex4/iqu.html .
What do you want to add.. Just a info from the function ?like
WLog_INFO(TAG, "DEBUGDH initialize gdi_opaque_rect");
in the beginning of each function ?

The output of the /buildoptions and debug session is here: i hope pastebin is o.k..

http://pastebin.com/seRwN8nm

**Comment by akallabeth** [comment] 2016-12-01 14:59
@ropetry Ok, that's it. No I know which functions are invoked. ```gdi_opaque_rect``` definitely needs some speedup, but you have the laggy behavior with ```/gdi:hw``` too? That is indeed buzzling, because the X11 version uses ```XFillRectangle``` which should be really fast...

**Comment by ropetry** [comment] 2016-12-02 08:37
@akallabeth Glad to hear that you now know the place where the sloweness could appear in gdi:sw mode.. normally we don´t use this gdi:sw mode so you are right it should work via the faster XFillRectangle function.
Anything we can try to debug the gdi:hw mode ? if i use the old git version and gdi:hw it is fast. with the new git version it is slow.. same thinclient, same os.. just an other xfreerdp session.

Where there some changes in the logic for gdi:hw and gdi:sw in the commits between both versions. Perhaps i have to bisect again to find a closer commit..But there was a really huge 8-). pull request between those 2 git version i have mentioned in the first comment 8-)..
bye and thanks again for your help
roman

**Comment by akallabeth** [comment] 2016-12-02 09:27
@ropetry Yes, I know about the huge pull (that one is on me). With ```/gdi:hw``` nothing should have changed in regard to performance. ```/gdi:sw``` on the other hand has been (mostly) rewritten and therefore some issues were expected. So maybe we're missing something here.

**Comment by ropetry** [comment] 2016-12-02 13:42
@akallabeth 2 hours later i have some news 8-).. I checked again several commits and i think i have found the issue for the /sw:hw lag.
i compiled the following commits and did my test:
267dea9
071b79a
06a04a0
f5a6645
All o.k . The bad thing happened with commit
a6f4117
it lags.. xfreerdp /sec:rdp /f /multimon:force /gdi:hw /v:servername 
if i add this option -max-loop-time:1000 it´s better. 
perhaps it´s a to low default value for the max-loop-time ? If i use 100 instead of the 1000 i have the same lag.
See #3364 ... Sadly i´m also one of the people who sad this old pull request solved some other issue (excel endless scroll problem) 8-)..but introduced perhaps this new one ?
bye
roman

**Comment by akallabeth** [comment] 2016-12-02 14:22
@ropetry Ouch, that hurts. So we have contradicting requirements, great :/

**Comment by ropetry** [comment] 2016-12-02 14:26
@akallabeth yes.. perhaps someone will have a good idea over the wekend 8-).. at the moment my users use the /rfx and the max-loop-time:1000 options and i will see if i get complains next week.

**Comment by hardening** [comment] 2016-12-02 21:30
Well I really think there's no contradiction that https://github.com/FreeRDP/FreeRDP/pull/3364 gives that behaviour. If we treat inputs at a higher rate but the client side rendering is too slow, then we see the observed behaviour. When treating inputs generates a lot of rendering then we get stuck (like in the video when dragging makes the server re-render), I'm not sure how we can deal with this. Perhaps it's just a matter of setting the right value...

**Comment by hardening** [comment] 2016-12-06 10:19
Some thoughts about that bug: latency is the delay that is observed between an action and its feedback. 
In our case we would like to have a measurable feedback of the mouse move action, in the ideal case we would render what is the consequence of the mouse move, and while doing this we would stop treating inputs (so not flooding the server with mouse moves, that generates frames that we don't want to render client side). The problem is that we don't have such feedback.

So I guess that solving this problem will be only based on smart heuristics.

**Comment by ropetry** [comment] 2016-12-12 11:23
@hardening @akallabeth 
Just to give an update.. My users (30 thinclients at the moment) are working now for 1 week with the new delay option and 1000 as the max-loop time.. at the moment no complains about performance or hanging sessions.. 
so at the moment i will push this option to all other thinclients. 
Thanks for your help so far. 
bye
roman

**Comment by bmiklautz** [comment] 2016-12-13 14:18
@ropetry thanks for the update. I'll close the issue then for now. Just re-open it or create a new one in case. Thanks.

**Closed by bmiklautz** 2016-12-13 14:18 UTC
Labels: waiting-feedback
