### ISSUE TITLE
Constant "Receiving Out-of-Sequence RTS PDU" Errors during client->server connection

### ISSUE THREAD

**Issue by 13rac1** [FreeRDP/FreeRDP#2235] opened 2014-11-27 00:24 UTC
I am using a gateway to connect RDP to a Windows 2008 Server.

```
[16:19:38:654] [14421:-303823104] [INFO][com.freerdp.core.gateway.tsg] - TS Gateway Connection Success
[16:19:41:173] [14421:-320801024] [ERROR][com.freerdp.core.gateway] - Receiving Out-of-Sequence RTS PDU
[16:19:45:382] [14421:-320801024] [ERROR][com.freerdp.core.gateway] - Receiving Out-of-Sequence RTS PDU
[16:19:49:821] [14421:-320801024] [ERROR][com.freerdp.core.gateway] - Receiving Out-of-Sequence RTS PDU
[16:19:53:158] [14421:-320801024] [ERROR][com.freerdp.core.gateway] - Receiving Out-of-Sequence RTS PDU
[16:19:55:193] [14421:-303823104] [INFO][com.freerdp.client.x11] - Closed from X11
```

It only happens while I am actively using RDP. If minimize the window it doesn't seem to happen. _This is a minor issue because it doesn't seem to cause any problems (at least for me.)_

**Comment by awakecoding** [comment] 2015-01-13 18:59
@eosrei do you have an easy way to reproduce the issue? I'm trying to debug this but I have a hard time triggering it consistently.

**Comment by eosrei** [comment] 2015-01-13 20:47
I trigger by starting the connection and then switching to another program. I *think* it's important that it doesn't get any keyboard/mouse input.

**Comment by thenewnano** [comment] 2015-01-14 14:18
I moved to the latest master and that issue is not there, will try later
tonight again.


Shwan Ciyako

M.Sc Embbeded Electronics

Embedded Systems Design Engineer

**Comment by awakecoding** [comment] 2015-01-14 21:55
@thenewnano @eosrei you may want to try my branch, I've got a couple of improvements and some fixes. The latest master doesn't print out anything when an out-of-sequence RTS PDU is received (this is not an error). I also fixed an important problem with the ringbuffer usage that would affect gateway connections specifically. The other thing I fixed is detection of the transport layer being disconnected: when we we see the rpc_client_frag_read error, it's because the TCP connection was dropped by the gateway. After a bunch of testing and experimentation, it appears that we do not use the idle timeout value sent by the server. However, this value is meant to be used by the client so that it disconnects itself from the server after the given idle timer has expired, which we are not doing. There is another configurable timeout on the gateway side that controls a server-initiated disconnect: the session timeout. This one is what I think comes into play here. We are ignoring the status code of the final TsProxySendToServer call, and after parsing it I see that the server sends an E_PROXY_SESSIONTIMEOUT code before disconnecting the client after a certain idle time. I haven't done much testing with multiple configurations on the server, I just put the idle and session timeouts to 1 minute each (minimum). I haven't yet found anything in the spec that says we are supposed to send keep-alive packets initiated by the client to prevent this, but otherwise it looks like this is a voluntary thing and controlled by server-side configuration.

**Comment by eosrei** [comment] 2015-01-15 07:47
@awakecoding Nice! It doesn't lock up the terminal anymore when left idling. The connection is dropped, but it reconnects automatically. I just realized: The reconnect happens in a new window. It's spawning multiple windows.

It logs me in the Gateway, but I've got to re-login the Terminal Server; which is probably correct.

There's a lot of tsg_read errors, before it reconnects. They filled my terminal history. Seems to run for about 15 seconds?
```
[23:36:26:739] [10962:-483105024] [ERROR][com.freerdp.core.gateway.tsg] - tsg_read error: connection lost
[23:36:26:739] [10962:-483105024] [ERROR][com.freerdp.core.gateway.tsg] - tsg_read error: connection lost
[23:36:26:758] [10962:-483105024] [ERROR][com.freerdp.core.gateway.tsg] - error, connection lost
[23:36:26:758] [10962:-483105024] [ERROR][com.freerdp.core.gateway.tsg] - tsg_read error: connection lost
[23:36:26:758] [10962:-483105024] [INFO][com.freerdp.client.x11] - Network disconnect!
[23:36:26:758] [10962:-483105024] [INFO][com.freerdp.client.x11] - Attempting reconnect (1 of 20)
[23:36:28:789] [10962:-483105024] [INFO][com.freerdp.core.gateway.tsg] - TS Gateway Connection Success
```

**Comment by thenewnano** [comment] 2015-01-15 19:12
Okay, I am tryong your branch now

**Comment by thenewnano** [comment] 2015-01-15 21:47
[22:46:23:641] [9787:2130323200] [ERROR][com.freerdp.core.gateway.tsg] - tsg_read error: connection lost
[22:46:23:641] [9787:2130323200] [ERROR][com.freerdp.core.gateway.tsg] - tsg_read error: connection lost
[22:46:23:641] [9787:2130323200] [ERROR][com.freerdp.core.gateway.tsg] - tsg_read error: connection lost
[22:46:23:641] [9787:2130323200] [ERROR][com.freerdp.core.gateway.tsg] - tsg_read error: connection lost
[22:46:23:641] [9787:2130323200] [ERROR][com.freerdp.core.gateway.tsg] - tsg_read error: connection lost
[22:46:23:641] [9787:2130323200] [ERROR][com.freerdp.core.gateway.tsg] - tsg_read error: connection lost
[22:46:23:642] [9787:2130323200] [ERROR][com.freerdp.core.gateway.tsg] - tsg_read error: connection lost

I get a lot of these , no reconnect.

**Comment by thenewnano** [comment] 2015-01-15 21:50
It seems we need to do something about this, I'll ask our admin to see if there is anything he can do at serverside , for the gateway, as the computer I connect to is my own at the office, I can make changes if we know where to make them. 

"haven't done much testing with multiple configurations on the server, I just put the idle and session timeouts to 1 minute each (minimum). I haven't yet found anything in the spec that says we are supposed to send keep-alive packets initiated by the client to prevent this, but otherwise it looks like this is a voluntary thing and controlled by server-side configuration."

**Comment by akallabeth** [comment] 2018-11-23 10:39
Mostly rewritten gateway code, therefore closing.
Reopen / create a new issue if this is still occurring.

**Closed by akallabeth** 2018-11-23 10:39 UTC
