### ISSUE TITLE
remote app shows Very wide black border

### ISSUE THREAD

**Issue by Berry1994** [FreeRDP/FreeRDP#5949] opened 2020-03-06 03:38 UTC
![image](https://user-images.githubusercontent.com/17263848/76047773-cd2d7000-5f9e-11ea-914a-86c5c6cff640.png)

client/X11/xfreerdp  /v:192.168.1.174 /u:test /p:123123  /app:'||QQ'

Version
    master

system
    Ubuntu 16.04 Ubuntu 18.04

Remote:
    Win7 64 Sp1

**Comment by akallabeth** [comment] 2020-03-06 07:57
More or less a duplicate of #5945

**Closed by akallabeth** 2020-03-06 07:57 UTC

**Comment by weizhouw415** [comment] 2023-08-11 08:35
@akallabeth Hello, is this porblem sloved? I met with similar issue can't find a way to solve it

**Comment by breadyangg** [comment] 2024-11-28 05:37
i got a way to slov this problem（on kvm）——
1. First, right-click the "This Computer" icon on the desktop and choose "Properties".

2. In the window that is displayed, click Advanced System Settings on the left menu bar.

3. In the System Properties dialog box, click the Performance TAB.

4. Locate and click the "Settings" button below the Performance TAB.

5. In the Visual Effects TAB, you can see a list showing various adjustable visual effects. In this list, find and uncheck "Window shadow" at the bottom of the list to turn off the Windows 10 interface window shadow effect; If you want to enable this feature, you need to check it.

6. Click the "Apply" and "OK" buttons to save the changes and exit the dialog box.
