### ISSUE TITLE
Please explain sound and microphone options

### ISSUE THREAD

**Issue by stilyan** [FreeRDP/FreeRDP#4849] opened 2018-09-10 13:09 UTC
From manual

```
/microphone[:[sys:sys,][dev:dev,][format:format,][rate:rate,][channel:channel]]
/sound[:[sys:sys,][dev:dev,][format:format,][rate:rate,][channel:channel,][latency:latency,][quality:quality]]
```

Please explain those parameters
sys is clear - alsa or pulse
dev? what does it mean?
format? what are acceptable values?
rate? again - what are acceptable border values and what syntax
channel? what it means, please clarify

latency is clear - in milliseconds, lower = risky
what about quality? what are acceptable values?

Also - how are audio codecs working?
Do we specify prior run or freerdp chooses the most appropriate codec ?

Sorry for opening issue on this but I couldn't find those answers when researching, in man page or the wiki you got in git.

Thanks in advance for the answers.

**Comment by akallabeth** [comment] 2018-09-10 19:33
@stilyan best ignore the options if you don't know what they do.
Should probably remove most of them as they don't make that much sense and are mostly confusing.

**Comment by stilyan** [comment] 2018-09-11 05:58
@akallabeth thanks, but I'm still having little distortions and robotic voice after https://github.com/FreeRDP/FreeRDP/issues/4309 while using Slack.
Connecting with just /mic and /sound = quality of my voice as reported from the other side is very bad
Connecting with
`
/mic:sys:alsa,format:1,rate:44100
/sound:sys:alsa,format:1,quality:high,rate:44100,latency:50
`
Is great improvement but still some distortions and robotic voice.
So I'm trying to figure out how to squeeze the highest quality possible out of this.

**Comment by akallabeth** [comment] 2018-09-11 06:47
There are still some issues mostly with microphone (#4791, #4779) so I'd just skip all the options for `/sound`.

Knowing your buildoptions might give a hint. Also check with `/log-level:debug` which codec is used for `audin` (the microphone channel) so that we know where to look.

**Comment by stilyan** [comment] 2018-09-11 12:26
@akallabeth thanks. I'll open new issue if necessary as the purpose of this one was to request documentation.
Here's output from --buildconfig
`
This is FreeRDP version 2.0.0-dev4 (5bddbd1cf)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls
Compiler:            GNU, 7.3.0
Target architecture: x64
`
Following are several tries I did.
In those tests I used the Skype echo call to listen to my own voice and make a comparison.
In addition I did Slack calls with someone.
1) `/sound /mic`
Skype: Decent quality of recorded voice.
Slack: Very poor quality of my voice as reported from the other side. They say its crackling.
Log:
`[15:07:38:276] [11053:11054] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel audin
[15:07:38:281] [11053:11054] [INFO][com.freerdp.channels.audin.client] - Loaded pulse backend for audin
[15:07:57:509] [11053:11063] [DEBUG][com.freerdp.channels.audin.client] - microphone uses WAVE_FORMAT_AAC_MS codec
`
2) `/sound /mic:sys:alsa,format:1,rate:44100`
Skype: Decent quality of recorded voice. Just a little bit better than in previous try.
Slack: My voice is understandable but there are some side noises like static or something.
Log:
`
[15:18:44:711] [11099:11100] [INFO][com.freerdp.channels.audin.client] - Loaded alsa backend for audin
:18:49:956] [11099:11108] [DEBUG][com.freerdp.channels.audin.client] - microphone uses WAVE_FORMAT_PCM codec
`

So as far as I can see ffmpeg is not being used ?
As far as I understood from https://github.com/FreeRDP/FreeRDP/issues/4309 I just needed to compile with the FFMPEG=ON

How should I proceed ?

**Comment by akallabeth** [comment] 2018-09-11 12:44
@stilyan You have a weired build configuration (`WITH_GSM, WITH_FAAC, WITH_FAAD, WITH_LAME` are an alternative option to `WITH_DSP_FFMPEG`)

Anyway, you're using FFMPEG in your first example (`WAVE_FORMAT_AAC_MS` is used)
With the command line in 2. you're forcing the supported audio formats to `PCM/WAV` only, so no encoding necessary ;)

**Comment by stilyan** [comment] 2018-09-11 13:33
@akallabeth thanks, this is how I configured
`cmake -GNinja -DCMAKE_INSTALL_PREFIX=/home/stilyan/xfreerdp1 -DWITH_DSP_FFMPEG=ON -DWITH_FAAC=ON -DWITH_FAAD2=ON -DWITH_PULSE=ON`
So I manually forced faac and faad2 thinking they must to go with FFMPEG as per https://github.com/FreeRDP/FreeRDP/issues/4309#issuecomment-415445619 , now after looking closely it's clear they are completely independent. Surely I'm missing the deep understanding that's needed here.

So since "format" option **only restricts** the supported formats there's no point in using it.

Please forgive if question is too incompetent but can I force the codec being used? Does it make any sense to do it manually?

What I'm thinking of doing next to try reaching the best possible quality.
Test build with DWITH_FAAC=ON only
I will forcibly turn off GSM, LAME

Since FAAD2 is a decoder and I'm hearing the other side well - should I include in build?

**Comment by akallabeth** [comment] 2018-09-11 14:50
@stilyan You can only try to force a format by not announcing support for others.
If that format is also supported by the server it will be used, otherwise you'll have no working sound/mic.
Quality is mostly created by using a bandwidth estimation.
If you have sound issues there is not much use in playing around with other settings except trying to see if it works with the `PCM` codec.
 (That one is the most simple, bandwidth hungry but universally supported one)
That way you know if the issue is
1. a Bandwidth issue
1. A codec related issue
1. A remote application issue
1. A local capturing issue

**Comment by akallabeth** [comment] 2018-10-18 13:36
Closing this as it is mostly 'support'

**Closed by akallabeth** 2018-10-18 13:36 UTC
