### ISSUE TITLE
Missing Cursor in Outlook 2010 with +async-update and /gdi:hw

### ISSUE THREAD

**Issue by takenit2far** [FreeRDP/FreeRDP#2193] opened 2014-11-10 17:38 UTC
Hello

When connecting to a Server 2008 R2 Server with Office 2010,  when using the +async-update there is no cursor in Outlook.

A workaround is to additionally specify /gdi:sw , although there is a noticeable performance hit when scrolling in web browsers.

Hope this is of some use towards a possible bug,  I'm using the current master as of today. 

Regards

James

**Comment by scottsisco** [comment] 2016-04-19 16:36
My organization is having this exact same issue. If there still no resolution? We also use +async-update to stop the endless scrolling through cells in Microsoft Excel.

**Comment by ropetry** [comment] 2016-05-12 15:30
As my other issue is closed: #3338 . should we try to use this issue to try to solve. the issue is still around in freerdp 2.0 git as of last week. anything we an do to get this down? i will try to verify the +async.update option tomorrow, but today i tested it with the option and the behavior is the same.

**Comment by hardening** [comment] 2016-05-13 06:21
Hello all,
some time ago I did a test branch to see if limiting the packets treated per loop would improve the input latency, would you mind give a try ?

https://github.com/hardening/FreeRDP/tree/limit_frames

**Comment by ropetry** [comment] 2016-05-13 06:32
@hardening  i will try.. one question: on which version of freerdp is it based on ? so i can see what other issues are not fixed 8-).. 
thanks again for pointing me to this..

**Comment by hardening** [comment] 2016-05-13 06:41
2.0 of course, 1.1 is not developed or maintained actively :)

**Comment by ropetry** [comment] 2016-05-13 07:43
@hardening : just downloaded and compiled a static version with the following options:
#!/bin/bash
cmake \
        -DCMAKE_BUILD_TYPE=Debug \
        -DCMAKE_C_FLAGS="$RPM_OPT_FLAGS" \
        -DCMAKE_INSTALL_PREFIX=/opt/freerdp \
        -DCMAKE_SKIP_INSTALL_RPATH=ON \
        -DSTATIC_CHANNELS=OFF \
        -DWITH_ALSA=OFF \
        -DWITH_FFMPEG=ON \
        -DWITH_GSTREAMER_0_10=ON \
        -DWITH_GSTREAMER_1_0=OFF \
        -DWITH_PULSE=ON \
        -DWITH_SSE2=ON \
        -DBUILD_SHARED_LIBS=OFF

it looks better as the system comes back after a time.. so the loop isn´t infinite with the scrolling anymore.it takes 20-30 seconds till it ends the scrolling.  is there a way i can check that your patch is doing something... will check also youtube video if it has some bad behaviors on "normal" video refresh and also if remotefx is enabled..
for this test i have used just those command line:
/tmp/xfreerdppatched2 /f /v:desktopfarm08.dillinger.de
thx so far for help

**Comment by hardening** [comment] 2016-05-13 08:18
@ropetry you can try to lower the value here (let's say 5 instead of 10):
https://github.com/hardening/FreeRDP/commit/00fdc456df3303f592409577bc2c8fd0c117bed7#diff-a8013058ed4679c2ebad5273167deebaR235

I think the best approach would probably be to limit the time spend in that function instead of counting packets...

**Comment by akallabeth** [comment] 2016-05-23 09:48
@hardening What is the loop exactly for? This works quite fine without this blocking while in transport.c...

**Comment by ropetry** [comment] 2016-05-27 13:05
@hardening : did some more tests and still haven´t found an issue. did you try to get this included in master. perhaps with a "command line argument" option to enable it ?
+1 and thanks so far..

**Comment by ropetry** [comment] 2016-06-06 10:56
Cross Reference for pull request which fixes this for me. on my thinclients.
#3364

**Comment by akallabeth** [comment] 2018-04-16 10:29
Closing as fixed.

**Closed by akallabeth** 2018-04-16 10:29 UTC
Labels: waiting-feedback
