### ISSUE TITLE
[latest nightly] Drive (folder) redirection: Cannot open or copy files on camera

### ISSUE THREAD

**Issue by T3N4K4** [FreeRDP/FreeRDP#4025] opened 2017-06-29 10:42 UTC
With the latest nightly freerdp build I cannot open nor copy files from a camera which was redirected as a folder:

/shares/all is redirected.
The camera is mounted into /shares/devices/camera.
/shares/devices/camera is a symlink in /shares/all.

So when I open the Windows Server 2012R2 Session I find a drive "U" with the content camera (folder) in there storexxxx/DCIM/11__03/ and in here are the pictures.
I can normally access this folder within the explorer, but when I try to open or copy them windows says they're damaged or too big. The size of each of the pictures is around 2MB.

command line for drives:
/drive:"U","/shares/all"

Whole command line:

/usr/bin/xfreerdp /u: /p: /v: /d: /gdi:hw /f /kbd:0x407 +sec-nla -toggle-fullscreen -clipboard /drive:"U","/shares/all" /cert-ignore

Error message:

```
[12:33:48:492] [2783:2820] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
```

**Comment by bmiklautz** [comment] 2017-07-03 09:12
@T3N4K4 I have seen a similar issue when I redirect my /tmp directory. Looks like an regression introduced with the switch to winpr.

**Comment by T3N4K4** [comment] 2017-07-03 09:36
@bmiklautz if it helps: it works though with normal usb-drives.

**Comment by T3N4K4** [comment] 2017-07-12 13:53
@bmiklautz Forgot to mention that the camera is mounted with gphotofs. So .. if /tmp is buggy, too. Maybe gphotofs and tmpfs have something in common ? The missing x flag maybe?

**Comment by akallabeth** [comment] 2017-07-24 13:13
@T3N4K4 Added error code mappings in #4045, does this solve your issues?

**Comment by T3N4K4** [comment] 2017-07-24 14:23
@akallabeth does not work for me. I cannot access any picture on the camera nor copy the files to the windows desktop. :(

**Comment by akallabeth** [comment] 2017-07-25 06:38
@T3N4K4 Do you get any error messages from the drive channel? Or is it just impossible to access the files, but they are shown?

**Comment by T3N4K4** [comment] 2017-07-25 11:01
@akallabeth the whole log currently shows:
```
Di 25. Jul 12:59:05 CEST 2017
[12:59:07:639] [3122:3175] [WARN][com.freerdp.channels.smartcard.client] [smartcard_irp_device_control_call:2022] - IRP failure: SCardGetStatusChangeW (0x000900A4), status: SCARD_E_CANCELLED (0x80100002)
[12:59:18:523] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:18:527] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:19:457] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:19:459] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:22:371] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:22:374] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:22:376] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:22:379] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:23:369] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:23:372] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:23:409] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:23:412] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:23:429] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:23:431] [3122:3155] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:119] - Error code not found: -1073741823
[12:59:30:872] [3122:3252] [WARN][com.freerdp.channels.smartcard.client] [smartcard_irp_device_control_call:2022] - IRP failure: SCardGetStatusChangeW (0x000900A4), status: SCARD_E_CANCELLED (0x80100002)
[12:59:30:879] [3122:3254] [WARN][com.freerdp.channels.smartcard.client] [smartcard_irp_device_control_call:2022] - IRP failure: SCardGetStatusChangeW (0x000900A4), status: SCARD_E_CANCELLED (0x80100002)
[12:59:30:342] [3122:4433] [WARN][com.freerdp.channels.smartcard.client] [smartcard_irp_device_control_call:2022] - IRP failure: SCardGetStatusChangeW (0x000900A4), status: SCARD_E_CANCELLED (0x80100002)
[12:59:30:342] [3122:3154] [ERROR][com.freerdp.channels.rdpdr.client] [rdpdr_send:1501] - pVirtualChannelWriteEx failed with CHANNEL_RC_BAD_CHANNEL_HANDLE [00000007]
[12:59:30:342] [3122:3154] [ERROR][com.freerdp.channels.smartcard.client] [smartcard_thread_func:647] - smartcard_complete_irp failed with error 7!

```

**Comment by akallabeth** [comment] 2017-07-25 14:21
@T3N4K4 Better try the pull request with the fixes then ;)

**Comment by T3N4K4** [comment] 2017-07-25 14:40
@akallabeth my bad, did not see that the merging failed ... ^_^

**Comment by T3N4K4** [comment] 2017-07-26 06:56
@akallabeth this one works ;)

**Comment by T3N4K4** [comment] 2017-07-26 08:26
@akallabeth the only two errors I get (it is still working) are:
[08:56:08:860] [18307:18316] [ERROR][com.winpr.file] [map_posix_err:597] - Missing ERRNO mapping The filesystem is readonly [30]
We mount the camera read only since gphotofs sometimes bugs out.

[08:56:08:860] [18307:18316] [ERROR][com.freerdp.channels.drive.client] [drive_map_windows_err:129] - Error code not found: 3221225473

**Comment by akallabeth** [comment] 2017-08-16 13:34
@T3N4K4 The pull requests with drive fixes are merged. Reopen if still not working.

**Closed by akallabeth** 2017-08-16 13:34 UTC
Labels: blocker, regression, waiting-feedback
