### ISSUE TITLE
Long Path for /drive Causing Parameter Corruption

### ISSUE THREAD

**Issue by KenHolloway** [FreeRDP/FreeRDP#4249] opened 2017-11-19 18:51 UTC
If the path for /drive is too long, it seems to be corrupting the hostname for certificate matching. For example:

xfreerdp 5-B400DC003.rdp /drive:Remote,/home/KHolloway/xxxxxxx

works fine. However, adding one more character to the path:

xfreerdp 5-B400DC003.rdp /drive:Remote,/home/KHolloway/xxxxxxxx

causes a certificate name mismatch warning:

[10:49:34:726] [30755:30756] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[10:49:34:726] [30755:30756] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[10:49:34:726] [30755:30756] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - @           WARNING: CERTIFICATE NAME MISMATCH!           @
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - The hostname used for this connection (oway/xxxxxxxx:3389) 
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - does not match any of the names given in the certificate:
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - Common Name (CN):
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] -      host.domain.com
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - Alternative names:
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] -       host.domain.com
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] -       www.host.domain.com
[10:49:34:868] [30755:30756] [ERROR][com.freerdp.crypto] - A valid certificate for the wrong name should NOT be trusted!

**Comment by akallabeth** [comment] 2017-11-20 08:41
@KenHolloway Which version of FreeRDP did you test with? Does this also happen with our nightly builds?

**Comment by akallabeth** [comment] 2017-11-20 08:42
Oh, and the options used in the RDP file would also help ;)

**Comment by KenHolloway** [comment] 2017-11-20 15:11
I downloaded and compiled today:

This is FreeRDP version 2.0.0-dev (c3acaad46)

How do I get the nightly build? (I used "git clone git://github.com/FreeRDP/FreeRDP.git" to get this version.)

The (sanitized) RDP file is:

full address:s:111.222.333.444
/cert-name:host.domain.com
domain:s:domain.com
username:s:username
desktopwidth:i:1280
desktopheight:i:1024
#administrative session:i:1

**Comment by akallabeth** [comment] 2017-11-20 15:29
@KenHolloway Ok, tested with current master and (really long) filenames, can not reproduce. Could you compile with ```WITH_SANITIZE_ADDRESS=ON``` and post the result? (should print some memory corruption error in that case)

**Comment by akallabeth** [comment] 2017-11-20 15:34
@KenHolloway Btw, ```/cert-name:host.domain.com``` is not valid in an RDP file...

**Comment by KenHolloway** [comment] 2017-11-20 19:42
It is odd that /cert-name is not valid. It works for me (as long as I don't use a long path for /drive). The DNS name for this host does not match the certificate name. If I remove /cert-name from the .rdp file and connect, I get a certificate name mismatch error. If I put the /cert-name back in and connect, no error (unless I also use /drive with a long path).

**Comment by akallabeth** [comment] 2017-11-21 06:15
That may be a bug in the RDP file parser, need to check.
It is definitely not possible to be valid, all entries must conform to ```<key>:[si]:<value>``` format.
Did you try to build with address sanitizer? That should exit the application whenever a memory corruption occurs and print where that happened.

**Comment by akallabeth** [comment] 2017-11-21 12:53
Ok, looks like someone added FreeRDP argument support to .rdp files and called the command line parser recursively. Should be fixed in the aforementioned pull.

**Comment by KenHolloway** [comment] 2017-11-21 15:29
I would love to try this out. But, I haven't been able to figure out how to download this version. I normally just:

git clone git://github.com/FreeRDP/FreeRDP.git

I am sure there is a simple command line argument to add, but I can't find the right syntax....

**Comment by akallabeth** [comment] 2017-11-21 15:39
@KenHolloway on the bottom of the pull request there is the option ```command line options```

**Comment by KenHolloway** [comment] 2017-11-21 17:42
Sorry, I can't find it. I am looking at https://github.com/FreeRDP/FreeRDP/pull/4263. I don't see any options. Can you tell me what the command line is, or exactly where I can find it? I would love to test this change....

Thanks,
Ken

**Comment by akallabeth** [comment] 2017-11-21 18:03
```git remote add ak https://github.com/akallabeth/FreeRDP.git```
```git fetch ak```
```git checkout rdp_parser_mem_corruption_fix```

**Comment by KenHolloway** [comment] 2017-11-21 21:04
The first command gives me an error:

git remote add ak https://github.com/akallabeth/FreeRDP.git
fatal: Not a git repository (or any of the parent directories): .git

**Comment by hardening** [comment] 2017-11-21 22:13
@KenHolloway you're in the wrong dir, you should be in a directory with FreeRDP checked out

**Comment by KenHolloway** [comment] 2017-11-22 00:27
Excellent. That change seems to have resolved the problem for me.

Thanks!

**Closed** 2017-11-22 08:24 UTC
Labels: fixed-waiting-test
