### ISSUE TITLE
OS X El Capitan v10.11.4 I need to get smart card working with xfreerdp

### ISSUE THREAD

**Issue by mindisfree** [FreeRDP/FreeRDP#3315] opened 2016-05-03 12:52 UTC
Here is the commands I have tried and the errors after. Maybe my syntax is wrong.

**xfreerdp -sec-rdp /f /d:us /smartcard:scard /v:IPHERE**
loading channel rdpdr
loading channel rdpsnd
Warning xf_GetWindowProperty (177): Property 296 does not exist
connected to IPHERE:3389
Password: 
SSL_read: Failure in SSL library (protocol error?)
SSL_read: error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied
credssp_recv() error: -1
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
Error: protocol security negotiation or connection failure

**xfreerdp -sec-nla /f /d:us /smartcard:scard /v:IPHERE**
loading channel rdpdr
loading channel rdpsnd
Warning xf_GetWindowProperty (177): Property 302 does not exist
connected to IPHERE:3389
connected to IPHERE:3389
recv: Connection reset by peer
Error: protocol security negotiation or connection failure

**xfreerdp /f /d:us /smartcard: /cert-ignore /v:IPHERE**
loading channel rdpdr
loading channel rdpsnd
Warning xf_GetWindowProperty (177): Property 302 does not exist
connected to IPHERE:3389
Password: 
SSL_read: Failure in SSL library (protocol error?)
SSL_read: error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied
credssp_recv() error: -1
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
Error: protocol security negotiation or connection failure

**Comment by bmiklautz** [comment] 2016-05-03 12:57
@mindisfree please add the FreeRDP version/buildconfig you are testing with
```
xfreerdp --buildconfig
```

**Comment by HenryJacques** [comment] 2016-05-03 12:58
@mindisfree reading your last post in #2891 I see you want to do smartcart login directly from xfreerdp. That is not currently supported...

**Comment by bmiklautz** [comment] 2016-05-03 13:01
@HenryJacques do you know it this is generally supported. I vaguely remember that at least the username is always required.

**Comment by HenryJacques** [comment] 2016-05-03 13:54
@bmiklautz Well no, you can launch xfreerdo without the /u parameter, it will take your linux username by default. I've just tested it to connect to a Windows 7 with just the /p parameter. I had to create a Windows account with the same name as the linux account, though...

However what @mindisfree is trying to achieve is not supported at all!

**Comment by bmiklautz** [comment] 2016-05-03 14:03
@HenryJacques thank for the answer. I'm aware that the linux username is used by default (it was me that added it :). What I was actually wondering is if smart card authentication without supplying any credentials at all is generally supported with RDP (I don't use smart card a lot).

**Comment by mindisfree** [comment] 2016-05-03 14:05
@bmiklautz 
xfreerdp /version
This is FreeRDP version 1.1.0-beta1 (git n/a)

**Comment by mindisfree** [comment] 2016-05-03 14:09
I guess I am confused, normal windows rdp will take  smart card login name you type password and it will carry that over to the rdp session. So with MAC and xfreerdp that is not possible? What are other people doing when required to use smart card to rdp into windows servers from a MAC.

**Comment by bmiklautz** [comment] 2016-05-03 14:12
@mindisfree just to re-check. You tried this with a windows client?

**Comment by mindisfree** [comment] 2016-05-03 14:16
@bmiklautz With the native RDP client from windows not using xfreerdp. I now have a MAC and have to use a smart card to connect to windows servers and trying to get that to work.

**Comment by bmiklautz** [comment] 2016-05-03 14:18
@mindisfree I think @HenryJacques is right and this is currently not supported with xfreerdp. However you could give the Microsoft Client (Microsoft Remote Desktop) on OS X a try (can be found in app store).

**Comment by HenryJacques** [comment] 2016-05-03 14:22
@bmiklautz ouch sorry ;) I was wondering why a FreeRDP dev would ask me this!
Concerning your question about smart card authentication without supplying any credentials, yes it is supported with RDP. Well at least mstsc!

What it does, it that mstsc takes the first X.509 cert with the "Microsoft Smartcardlogin" X509 Extended Key Usage; It then uses the X509 Subject Alternative Name which has to be the UPN (User Principal Name, something like username@DOMAIN)

**Comment by mindisfree** [comment] 2016-05-03 14:23
@bmiklautz I have tried most if not all other rdp clients for OS X. I was told by activeclient that the only supported RDP client would be xfreerdp.. That has lead me here. 
@HenryJacques is there a workaround like I have to use the username username@DOMAIN(this is what is does on windows.

**Comment by bmiklautz** [comment] 2016-05-03 14:30
@HenryJacques thanks for the info ;). I really need to get some proper smart card test environment here. Maybe at some time if time permits.

**Comment by HenryJacques** [comment] 2016-05-03 14:39
@mindisfree no there are no workaround.

**Comment by HenryJacques** [comment] 2016-05-03 14:44
@bmiklautz you have an example here: [http://docplayer.fr/docs-images/18/887966/images/8-0.png](url)

It's in French but the essential is here. You can see the UPN extracted from a certificate in the smartcard (ending with "@cart..."). And it only asks for the card PIN code.

**Comment by HenryJacques** [comment] 2016-05-03 14:48
@mindisfree I assume you also just want to enter the smartcard PIN code and not the Windows' password, right?

**Comment by mindisfree** [comment] 2016-05-03 14:50
@HenryJacques Correct the PIN and username from smart card with auth into windows

**Comment by sconstantine** [comment] 2016-05-03 15:44
Appears my issue is the same or at least related (however using OS X, not Linux).  The FreeRDP build I am using is a plugin for the Royal TSX app by @lemonmojo.  It seems to have 'partial' function, in that the Windows host recognizes a reader now, however unable to query card status.  For example, ActivClient and Remote Desktop clients sit at 'checking status'  indefinitely when trying to use for logon or state query.

Is there any debug output, or tools I could use to post data here that would help with troubleshooting & development?

Env: OS X v10.11.4 and FreeRDP plugin v3.0.0.8 (with Royal TSX v3.0.0.11 beta)

**Comment by bmiklautz** [comment] 2016-05-03 16:05
@sconstantine for  Royal TSX  related issue please use their issue tracker.

**Comment by sconstantine** [comment] 2016-05-03 16:38
I have; however, the issue is not with RoyalTSX but the FreeRDP plugin and it's capabilities so hoping to find traction here...  thanks~

**Comment by akallabeth** [comment] 2018-11-22 14:14
Smartcard support has been basically rewritten,
closing as no longer applicable.

**Closed by akallabeth** 2018-11-22 14:14 UTC
