### ISSUE TITLE
Poor audio performance on Mac

### ISSUE THREAD

**Issue by puneet101** [FreeRDP/FreeRDP#2950] opened 2015-10-26 22:47 UTC
Audio performance for simple youtube playback is poor. With local LAN, we see jerky audio playback; video works much better so something is off.

We used standard WITH_MACAUDIO #define enabled with no other tuning. Is this a known issue?

**Comment by puneet101** [comment] 2015-10-30 22:42
Any feedback on this? Thanks!

**Comment by puneet101** [comment] 2015-12-10 17:23
Who owns the Mac client?

**Comment by cloudecker** [comment] 2016-02-22 02:00
hi, Is your MAC client make freerdp get the source code? or get a MAC framework? Then use the iOS client Xcode source?

**Comment by bmiklautz** [comment] 2016-02-22 11:44
@cloudecker how's your question related to the issue?

**Comment by bmiklautz** [comment] 2016-02-22 11:46
@puneet101 "owns" is hard to define. I'd say the FreeRDP project. The license is Apache License v2.0 and different people do have the copyright on it (see the source headers).

Regarding your issue the Mac client is basically working but at the moment it isn't very well maintained and no further (as i new features) is done.

**Comment by cloudecker** [comment] 2016-02-23 01:04
@bmiklautz   I compiled freerdp MAC client, I got a framework, not a MAC client source code. My question, whether the MAC client also uses the iOS client source code?
![11](https://cloud.githubusercontent.com/assets/16411660/13238228/6c8403d4-da0c-11e5-9679-d9cd85cad83a.jpg)

**Comment by cloudecker** [comment] 2016-02-23 07:43
@akallabeth  thank you!!!

**Comment by bmiklautz** [comment] 2016-02-23 10:41
@cloudecker please stop adding your quiestions/issues into unrelated issues.

**Comment by lemonmojo** [comment] 2017-01-23 15:44
Fast forward one year and the question remains. Any news on the Mac audio redirection implementation?

**Comment by akallabeth** [comment] 2017-01-23 16:05
@lemonmojo The state @bmiklautz mentioned did not change, pull requests are welcome but nobody stepped up to fix that issue so far.

**Comment by cyp3d** [comment] 2017-04-05 18:03
I am hoping to get sound redirection from a windows 10 enterprise remote machine to my Mac running Royal TSX ( freeRDP ). It appears that sound will work for a brief moment every time I start a RDP connection, and then it will no longer play. - It seems that when the first audio source stops, then audio no longer works on the RDP session until restarting it.

I currently am using a workaround by keeping a silent audio stream going upon start, and that is the "fix"

Is there any troubleshooting or other solutions that I am overlooking?

**Comment by hardening** [comment] 2017-04-06 08:09
@cyp3d this is something you should address to Royal TSX

**Comment by cyp3d** [comment] 2017-04-06 13:25
@hardening I put in a ticket with Royal TSX and they stated 
"The best you can do at the moment is to push the following issue in the FreeRDP Github account: https://github.com/FreeRDP/FreeRDP/issues/2950  "

Just trying to get some visibility since they don't want to take ownership.

It does appear that the issue is the same regarding this github issue.

**Comment by rfoust** [comment] 2017-05-17 13:55
I'm also trying to get audio to work from windows to a mac, but having issues with it stopping after just a few seconds.  Would love to see future development on this feature to get the issues resolved.  Thanks!

**Comment by cyp3d** [comment] 2017-05-17 14:04
@rfoust Unfortunately, I've had to trade off. Depending on my audio playback device Microsoft's RDC for mac works sometimes.

Similarly, Jump Desktop actually has great remote audio, but is lacking other nice features of Royal TSX.

It seems that there is no perfect solution here- unless you can remote control audio to play at the parent machine from RoyalTSX which has the best functionality outside of audio.

**Comment by akallabeth** [comment] 2018-04-16 10:51
#4453 fixes a lot of sound related issues. Don't know if you can bundle that on mac like it is, but every pull fixing that is welcome.

**Comment by akallabeth** [comment] 2018-05-03 12:30
Sound redirection has been basically rewritten, closing this.
Reopen or create a new one if still not solved.

**Closed by akallabeth** 2018-05-03 12:30 UTC
Labels: client, mac
