### ISSUE TITLE
drdynvc_main.c mind bug

### ISSUE THREAD

**Issue by virtman** [FreeRDP/FreeRDP#3061] opened 2016-01-15 12:36 UTC
Hello,

just want to point you on small bug.
line 759
	else if (dataSize <= CHANNEL_CHUNK_LENGTH - pos)
	{
the pos variable is equal to 0 at this point even when already written data by
line 749
   cbChId = drdynvc_write_variable_uint(data_out, ChannelId);
this will cause issue, that when dataSize == CHANNEL_CHUNK_LENGTH
it will not fit into created buffer
line 739
   data_out = Stream_New(NULL, CHANNEL_CHUNK_LENGTH);
because  CHANNEL_CHUNK_LENGTH + cbChId will exhaust it.
Well, possibly I am wrong, do not know, but in my opinion that is just fortune, if this bug did not yet happen.

proposal is either change
else if (dataSize <= CHANNEL_CHUNK_LENGTH - pos)
to
else if (dataSize <= CHANNEL_CHUNK_LENGTH - Stream_GetPosition(data_out))
or add at
line 749
   cbChId = drdynvc_write_variable_uint(data_out, ChannelId);
   pos = Stream_GetPosition(data_out);
and remove some unnecessary calls to Stream_GetPosition(data_out); at line 752 and 761

**Comment by akallabeth** [comment] 2016-01-28 10:40
@virtman The ``` CHANNEL_CHUNK_LENGTH``` is defined as ```1600```, ```cbChld``` is at most ```2```
closing due to being not a bug.

**Comment by akallabeth** [comment] 2016-01-28 10:47
@virtman Ok, sorry for accidentally closing, fixed your complaint in #3090

**Comment by akallabeth** [comment] 2016-01-28 13:52
Ok, it is merged, thx again.

**Closed by akallabeth** 2016-01-28 13:52 UTC
