### ISSUE TITLE
Copying in freerdp gets stuck

### ISSUE THREAD

**Issue by milkpuff** [FreeRDP/FreeRDP#10294] opened 2024-06-20 10:39 UTC
**Describe the bug**
Copying in freerdp gets stuck.

Use xfreerdp3(3.5.1) connect win10, and copy strings or anything, then rdp stuck, with nothing error show; 
Use xfreerdp(2.11.5) connect win10, and copy strings or anything, then rdp terminate with error;

**Application details**
* FreeRDP version (`xfreerdp 3.5.1 or 2.11.5`)
* OS version Archlinux + hyprland / win10 
* with log.txt

 
**Environment (please complete the following information):**
 - OS: Archlinux + hyprland
 - Architecture: amd64

[log.txt](https://github.com/user-attachments/files/15912470/log.txt)
[log1.txt](https://github.com/user-attachments/files/15912475/log1.txt)

**Comment by akallabeth** [comment] 2024-06-20 11:10
@milkpuff
1. what exaclty do you mean with `stuck`? (sorry, too generic, do you mean copy, the screen updates, ...?
1. the log for 2.11.5 indicates that your `X11` does not like some stuff (how big is the data you try to copy? small string, big text file?), seen this randomly on some systems, can´t fix that (we provide a `RDP` client, not an `X11` server)
2. please define `strings or anything`. how big is the data to be transferred? (copying e.g. 1GB of text will take some time ;)

**Comment by milkpuff** [comment] 2024-06-20 14:34
Stuck means that the screen in the RDP client no longer moves, and you can only manually kill freerdp process and then reconnect.
I only copy very small text like "123" in this test. Actually no matter what things I copy, problem all shows when I click copy( mouse or keyboard ctrl + c). 
And, if I don't use `/clipboard` option, which means no "data to be transferred", it also shows the same problem.

**Comment by milkpuff** [comment] 2024-06-20 17:41
@akallabeth 
Yes, you right. I changed `-clipboard`, and copy goes right.

**Comment by akallabeth** [comment] 2024-06-21 03:05
ok, closing then.
as mentioned, this might be caused by a clipboard manager (we´ve seen such issues, although not recently)

**Closed by akallabeth** 2024-06-21 03:05 UTC
Labels: waiting-feedback

**Comment by milkpuff** [comment] 2024-07-06 15:50
I think it's wl-clipboard problem. 
I notice `wl-paste --watch cliphist store` running background. When I close it, problems gone.
