### ISSUE TITLE
Sometimes the desktop image freezes just after logon

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#3114] opened 2016-02-07 18:26 UTC
On both arch and ubuntu 15.04, sometimes, just after logon, the remote desktop freezes with this image:

![freerdp pcgiovanni lan ipablapieve it 22077_005](https://cloud.githubusercontent.com/assets/5477803/12874253/83f913a8-cdd0-11e5-8e8c-805c8ba9941a.png)

The circle at the left of "Windows" is not rotating. No animation at all. No way to see changing images here.
Standard input processing seems to be working, because I can press ALT-F4 (which opens a disconnection confirmation dialog, not visible) and then pressing enter. Then freerdp will disconnect regularly with ERRINFO_LOGOFF_BY_USER.

This started to happen some weeks ago. Not shure when. It also happens randomly, 1 time out of 4-8 connections.

freerdp launched with
`xfreerdp /v:remotecomputer.remotedom.com:21017 /u:myself /d:mydom`
and compiled under x64 with
`cmake -DWITH_SANITIZE_ADDRESS=on -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_CUPS=on -DWITH_WAYLAND=off -DWITH_PULSE=on -DCMAKE_INSTALL_PREFIX:PATH=/opt/remmina_devel/freerdp .`

**Comment by bmiklautz** [comment] 2016-02-07 20:09
@giox069 this applies only on windows 7 or have you seen this on other systems as well?

**Comment by giox069** [comment] 2016-02-07 20:56
I have been able to reproduce it only on Windows 7 PRO and Windows 2008R2 (located on two different subnets which I can access via an OpenVPN VPN and a Cisco IPSEC IKEv1 VPN).
Here is a small table of my tests

OS | Problem detected
---- | ----
Windows 2008 Server | No
Windows 7 Pro | Yes    (two tested, on the same domain/subnet)
Windows 2008 R2 Server | Yes   (one tested, on a different subnet/domain than win7)
Windows 2012 R2 Server | No
Windows 10 Pro | No

It seems to happens only when connecting to an already "open" desktop (when the user is logged on but no RDP connection is active).

Here is a trace with `/log-level:TRACE`
```
[...]
21:43:19:785] [15561:15562] [DEBUG][com.freerdp.core.update] - CacheBitmapCompressedV2
[21:43:19:785] [15561:15562] [DEBUG][com.freerdp.core.update] - MemBlt
[21:43:19:785] [15561:15562] [DEBUG][com.freerdp.core.update] - CacheBitmapCompressedV2
[21:43:19:785] [15561:15562] [DEBUG][com.freerdp.core.update] - MemBlt
[21:43:19:785] [15561:15562] [DEBUG][com.freerdp.core.update] - AltSecFrameMarker: action: End (1)
[21:43:19:786] [15561:15562] [DEBUG][com.freerdp.core.update] - SwitchSurface
[21:43:19:786] [15561:15562] [DEBUG][com.freerdp.core.update] - MemBlt
[21:43:19:828] [15561:15562] [DEBUG][com.freerdp.core.rdp] - recv Synchronize Data PDU (0x1F), length: 22
[21:43:19:828] [15561:15562] [DEBUG][com.freerdp.core.rdp] - recv Control Data PDU (0x14), length: 26
[21:43:19:877] [15561:15562] [DEBUG][com.freerdp.core.rdp] - recv Control Data PDU (0x14), length: 26
[21:43:19:886] [15561:15562] [DEBUG][com.freerdp.core.rdp] - recv Font Map Data PDU (0x28), length: 26
[21:43:19:011] [15561:15562] [DEBUG][com.freerdp.core.rdp] - recv Save Session Info Data PDU (0x26), length: 628
[21:43:19:011] [15561:15562] [DEBUG][com.freerdp.core.info] - LogonInfoV2: SessionId: 0x0002
```
this is the freeze point. Here I can press ALT-F4 and then enter, but nothing is logged while pressing these keys or clicking the mouse. Then...
```
[21:43:31:256] [15561:15562] [DEBUG][com.freerdp.core.rdp] - recv Set Error Info Data PDU (0x2F), length: 22
[21:43:31:257] [15561:15562] [INFO][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off his or her session on the server.
[21:43:31:257] [15561:15562] [DEBUG][com.freerdp.core.rdp] - DisconnectProviderUltimatum: reason: 3
```

**Comment by bmiklautz** [comment] 2016-02-08 08:11
@giox069 did some testing against my local windows 7 but couldn't reproduce the problem. - Any change you can test directly without the vpn to make sure that the VPN doesn't influence the behavior.

**Comment by giox069** [comment] 2016-02-08 09:06
This morning I had no freezes at all, both by VPN and NAT-ted port :( And I'm using the same laptop I used yesterday, but some system packages have been updated (gnutls and others). I will collect more data in the next days and report back here in the next days, when I will physically be at the customer site. In the meanwhile... thank you for answering :)

**Comment by giox069** [comment] 2016-03-31 11:08
After many testing, I'm able to reproduce more frequently the problem by increasing the network latency and connecting (to a windows 7, not yet extensively tested to windows 2008R2).
It happens in WAN, LAN or between two machines directly connected with an ethernet cable
```
sudo tc qdisc add dev eth0 root netem delay 350ms
xfreerdp /v:remotecomputer.remotedom.com /u:myself /d:mydom
```
The problem seems to be appeared between these two commits:
7af1ec85f0823cbe50f18b83c665dcef2647e017    (problem!)
974d2ef433cd867728ace80d6c5decf965f684f    (no problem here)

**Comment by awakecoding** [comment] 2016-04-07 17:52
settings->SupportMonitorLayoutPdu = FALSE; fixes the problem. It is currently set to TRUE by default, which advertises support for the monitor layout pdu to the server. I don't have confirmation, but by advertising support for the monitor layout pdu, the sequence of messages in the connection sequence is likely altered, and the current code is not robust enough (too strict on a specific message sequence).

**Comment by HenryJacques** [comment] 2016-04-28 10:14
@awakecoding what are the possible drawbacks of setting SupportMonitorLayoutPdu to FALSE?

**Comment by lemonmojo** [comment] 2016-04-29 18:19
I also have had several customers report this issue to me in the last few weeks. I can't reproduce it myself but they all mentioned it's happening with 2008 servers.
I don't want to disable SupportMonitorLayoutPdu as I (think I) need it to enable multi-monitor fullscreen connections but obviously if that's the only fix at the moment I will have to go that route. Any fix in sight?

**Comment by mydigia** [comment] 2016-04-29 19:43
+1 for this issue, I experienced on Win 2008 servers too.

**Comment by bmiklautz** [comment] 2016-05-02 18:29
@giox069 thanks I can reproduce it now nicely with your tc command.

**Comment by bmiklautz** [comment] 2016-05-04 08:44
I tried to pin point the real problem I didn't figure out why but it seems that windows 7 and Windows 2008 R2 Server don't send any updates if the early capability RNS_UD_CS_SUPPORT_MONITOR_LAYOUT_PDU is set and the "Font Map PDU" was received. I also did some testing with different versions of the Microsoft client also on Android against the sample server and none of them sent the support monitor layout early capability. Maybe there are some server side issues with that. I've created a PR #3318 to disable it. If it is required by someone we could make it configurable with the command line but I think the default should definitely be to have it disabled.

**Comment by mfleisz** [comment] 2016-05-04 09:34
Just verified the problem with latest mstsc on Windows 10 (version 10.0.10586) using NEWT (Network Emulator for Windows Toolkit) to simulate network delay. When enabling multi-monitor support the client hangs after the connection sequence and doesn't receive any data from the server anymore. So this must be a MS server-side bug with Windows7/2008R2.

**Comment by bmiklautz** [comment] 2016-05-04 09:36
@mfleisz thanks for testing. Really good to know. So we probably should really make this configurable.

**Comment by mfleisz** [comment] 2016-05-04 09:37
@bmiklautz Yes - for now I think we can def. merge #3318 and make it configurable with another PR.

**Comment by bmiklautz** [comment] 2016-05-04 09:59
It seems that disabling the bitmap cache resolves this issue (tested with mstsc and xfreerdp)
@giox069 could you verify if this solves the problem for you as well? 
* use a current build without PR #3318 
* run with -bitmap-cache

**Comment by hardening** [comment] 2016-05-04 10:24
just wondering if we could have tip that would allow us to not announce this flag is the remote server is potentially buggy...

**Comment by bmiklautz** [comment] 2016-05-04 10:28
@hardening good question. We probably could disable the bitmap cache capabilities but not sure if we can reliably detect only those two operating systems.

**Comment by giox069** [comment] 2016-05-04 11:54
@bmiklautz I tested the latest freerdp in the master branch with "-bitmap-cache", but the screen is still freezing.
With PR #3318 the prolem seems to be solved.

**Comment by bmiklautz** [comment] 2016-05-04 12:11
@giox069 interesting. I haven't managed to get the freeze without bitmap compression :). Thanks for your feedback.

**Comment by bmiklautz** [comment] 2017-09-23 13:44
The mentioned PR (#3318) was merged to master. If the problem still exist please update and re-open this issue or create a new one.

**Closed by bmiklautz** 2017-09-23 13:44 UTC
Labels: waiting-feedback
