### ISSUE TITLE
Continue #1795: freerdp_set_last_error 0x2000D

### ISSUE THREAD

**Issue by tgulacsi** [FreeRDP/FreeRDP#1890] opened 2014-06-06 08:30 UTC
Hmm, #1795  has returned:

```
709df9aecc01eee60a560362039362ec42fa82aa is the first bad commit
commit 709df9aecc01eee60a560362039362ec42fa82aa
Author: Marc-André Moreau <marcandre.moreau@gmail.com>
Date:   Fri May 30 14:03:20 2014 -0400

    libfreerdp-core: add connection timeout, fix gateway bypass local

:040000 040000 9d839ee6271782dc04a759adc5def59a8fd2c072 c85166e022d87ecf3876b26bbdf82b3118451847 M      include
:040000 040000 cc509131e9b62e76fa371797f104f7e3400443f4 b13a6b49fdb90c849cade47dd7949907bc69a1a0 M      libfreerdp
bisect run success
```

```
# bad: [3854bdff2975148954fd2ae13f3f5b89ed1d8cd7] Merge pull request #1885 from awakecoding/master
git bisect bad 3854bdff2975148954fd2ae13f3f5b89ed1d8cd7
# good: [603a6378fffd43a67e14ead860bcf9196be6979e] Fix null certificate that is not an error
git bisect good 603a6378fffd43a67e14ead860bcf9196be6979e
# good: [4bac8374de67cac47460c31525ade0b2bf889a83] Merge branch 'master' of github.com:FreeRDP/FreeRDP
git bisect good 4bac8374de67cac47460c31525ade0b2bf889a83
# good: [a3461cef0690dff3da3560b2d794b7dfd75babb3] transport: add a null pointer check.
git bisect good a3461cef0690dff3da3560b2d794b7dfd75babb3
# bad: [abd475060c6c3cecb52a42c827bb499666fdc6f7] libwinpr-winsock: fix build on Windows
git bisect bad abd475060c6c3cecb52a42c827bb499666fdc6f7
# good: [629858b67662add7f08737f601fc70e8bc352d5a] libfreerdp-core: add gateway-usage-method command line option, avoid resetting BIO flags we shouldn't reset
git bisect good 629858b67662add7f08737f601fc70e8bc352d5a
# bad: [c5e4c74bb6e7b928e2bcaf8e50c72d8c46b276c1] libfreerdp-core: fix build on Windows
git bisect bad c5e4c74bb6e7b928e2bcaf8e50c72d8c46b276c1
# bad: [d2ad5f698bdbee51c56374d6f6aa1c8cd86cb621] libfreerdp-core: fix VerifyX509Certificate to make distinction between gateway and direct connection
git bisect bad d2ad5f698bdbee51c56374d6f6aa1c8cd86cb621
# bad: [709df9aecc01eee60a560362039362ec42fa82aa] libfreerdp-core: add connection timeout, fix gateway bypass local
git bisect bad 709df9aecc01eee60a560362039362ec42fa82aa
# good: [e60a59134f1c8407fcfe1062d474a23e86220485] libfreerdp-common: add freerdp_update_gateway_usage_method helper
git bisect good e60a59134f1c8407fcfe1062d474a23e86220485
# first bad commit: [709df9aecc01eee60a560362039362ec42fa82aa] libfreerdp-core: add connection timeout, fix gateway bypass local
```

**Comment by akallabeth** [comment] 2017-11-23 12:59
still an issue?

**Comment by ccpp** [comment] 2017-11-27 08:43
Cannot reproduce anymore.

(The old commits now yield different error messages because of an NTLM update on my remote TSG)

**Comment by akallabeth** [comment] 2017-11-27 08:57
Ok, closing. Create a new one if the errors are not correct.

**Closed by akallabeth** 2017-11-27 08:57 UTC
Labels: waiting-feedback
