### ISSUE TITLE
Num Lock and Caps Lock issues while using gfx feature

### ISSUE THREAD

**Issue by RexFan** [FreeRDP/FreeRDP#2822] opened 2015-08-04 03:04 UTC
Hello, i face some problems about Num Lock and Caps Lock issues while enabled gfx features.
### Num Lock

If i enabled gfx features (i.e. /gfx, +gfx-thin-client or +gfx-h264), the Num Lock will always off by default in remote session whatever it is on or off before remote. So sometimes it may be opposite.

But if i don't use gfx features, there is no problem.
### Caps Lock

If i enabled gfx features, the Caps Lock will always lowercase by default in remote session whatever it is on or off before remote. But Caps Lock will auto fix this problem.

If i don't use gfx features, there is no problem.

```
Caps Lock off --> remote by freerdp --> lowercase in remote session --> everything all right
Caps Lock on --> remote by freerdp --> lowercase in remote session --> press Caps Lock (turn off) --> still lowercase in remote session --> press Caps Lock (turn on) --> uppercase in remote session --> auto fix problem.
```
### Test environment.

Device: Raspberry Pi 2

```
pi@raspberrypi ~ $ uname -a
Linux raspberrypi 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux
```

```
pi@raspberrypi ~ $ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

```
pi@raspberrypi ~ $ more /etc/debian_version
7.8
```

```
pi@raspberrypi ~ $ uname -a
Linux raspberrypi 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux
```

FreeRDP version: 1.2.4-dev (git dfa2980)

The dependencies i installed for FreeRDP

```
sudo apt-get install build-essential git-core cmake libssl-dev libx11-dev libxext-dev libxinerama-dev libxcursor-dev libxdamage-dev libxv-dev libxkbfile-dev libasound2-dev libcups2-dev libxml2 libxml2-dev libxrandr-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libxi-dev libavutil-dev libavcodec-dev libxtst-dev libgtk-3-dev libgcrypt11-dev libssh-dev libpulse-dev libvte-2.90-dev libxkbfile-dev libfreerdp-dev libtelepathy-glib-dev libjpeg-dev libgnutls-dev libgnome-keyring-dev libavahi-ui-gtk3-dev libvncserver-dev libappindicator3-dev intltool libgstreamer-plugins-base1.0-dev xsltproc docbook-xsl
```

Please advice.

Thank you.

Best regards,
Rex Fan

**Comment by bmiklautz** [comment] 2015-08-04 09:46
@RexFan what server are you connecting to and testing with? I just tried to reproduce your reported behavior with the latest nightly build against different windows version but couldn't observe any problems.

**Comment by RexFan** [comment] 2015-08-04 10:01
@bmiklautz I test this with windows server 2012 R2. And I compile freerdp with only -DTARGET_ARCH=ARM parameter. Maybe there are something confused you what i mentioned above. With gfx features, if my Num Lock LED is on before remote, the LED is still on after remote to server 2012 R2. But the function is same as Num Lock off even the LED is on in remote session. Any advice? Thanks.

**Comment by bmiklautz** [comment] 2015-08-04 10:09
@RexFan are you doing a cross compilation or native? - In the later case I think you don't need DTARGET_ARCH=ARM.

I don't think there is a confusion however here how I've tested (for example CAPS Lock):
* Turn CAPS Lock on 
* connect to a remote 
* check in notepad if caps lock is really on
* disconnect

* Turn CAPS Lock off
* connect to a remote 
* check in notepad if caps lock is off
* disconnect

I don't exactly know what you meant with "if my Num Lock LED is on before remote" - Where do you have a led when connecting remote?

**Comment by RexFan** [comment] 2015-08-04 10:18
@bmiklautz I am sorry my English is not good. The Num Lock button on my keyboard has a "light" on it. I think i use wrong word.
I use raspberry pi 2 which is ARM architecture. So i use cmake to compile freerdp. Below is my script.

cmake -DTARGET_ARCH=ARM -DCMAKE_INSTALL_PREFIX:PATH=/home/pi/freerdp

**Comment by RexFan** [comment] 2015-08-05 01:40
@bmiklautz I found there were some warnings occurred while compiling freerdp, which were related to gfx.
```
Scanning dependencies of target rdpgfx-client
[ 90%] Building C object channels/rdpgfx/client/CMakeFiles/rdpgfx-client.dir/rdpgfx_main.c.o
/home/pi/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c: In function ‘rdpgfx_recv_caps_confirm_pdu’:
/home/pi/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c:122:17: warning: unused variable ‘gfx’ [-Wunused-variable]
/home/pi/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c: In function ‘rdpgfx_send_frame_acknowledge_pdu’:
/home/pi/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c:146:17: warning: unused variable ‘gfx’ [-Wunused-variable]
/home/pi/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c: In function ‘rdpgfx_recv_pdu’:
/home/pi/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c:731:17: warning: unused variable ‘gfx’ [-Wunused-variable]
/home/pi/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c: In function ‘rdpgfx_on_open’:
/home/pi/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c:876:17: warning: unused variable ‘gfx’ [-Wunused-variable]
/home/pi/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c: In function ‘rdpgfx_on_close’:
/home/pi/FreeRDP/channels/rdpgfx/client/rdpgfx_main.c:888:17: warning: unused variable ‘gfx’ [-Wunused-variable]
[ 90%] Building C object channels/rdpgfx/client/CMakeFiles/rdpgfx-client.dir/rdpgfx_codec.c.o
[ 91%] Building C object channels/rdpgfx/client/CMakeFiles/rdpgfx-client.dir/rdpgfx_common.c.o
```
And some other warnings may cause issues. 
```
Scanning dependencies of target xfreerdp-client
[ 96%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_gdi.c.o
[ 97%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_gfx.c.o
[ 97%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_rail.c.o
[ 97%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_tsmf.c.o
[ 97%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_input.c.o
[ 98%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_event.c.o
[ 98%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_channels.c.o
[ 98%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_cliprdr.c.o
[ 98%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_monitor.c.o
[ 99%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_graphics.c.o
[ 99%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_keyboard.c.o
[ 99%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_window.c.o
/home/pi/FreeRDP/client/X11/xf_window.c: In function ‘get_shm_id’:
/home/pi/FreeRDP/client/X11/xf_window.c:339:2: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 4 has type ‘DWORD’ [-Wformat]
/home/pi/FreeRDP/client/X11/xf_window.c:339:2: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 4 has type ‘DWORD’ [-Wformat]
[100%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_client.c.o
```
Please advice. Many thanks.

**Comment by bmiklautz** [comment] 2015-08-05 09:30
@RexFan the warnings shouldn't be related to your problem. As said before I couldn't reproduce your problem. Maybe it's an arm specific issue but I can't test since I don't have any arm device around at the moment.

**Comment by dd-jacks** [comment] 2015-08-05 11:33
I don't know how about Caps but for Num I think I've got the same.
Nettop with Intel Atom D2700. Since the chip is provided with a GMA 3600 (дай бог им здоровья \*russian sarcasm\*), I have to use ubuntu 12.04 i386. I don't have any display managers, all I do is 
`exec startx`
~/.xinitrc:
`/usr/local/bin/xfreerdp /bla:bla +bla`

So if I add *numlockx on* at first line...
with gfx:
Num led is on, numbers are off

without gfx:
Num led is on, numbers are on

I thought that some problem in my X configuration until this issue

**Comment by dd-jacks** [comment] 2015-08-05 12:02
kernel version is 3.2

**Comment by bmiklautz** [comment] 2015-08-05 12:02
@dd-jacks thanks for the feedback. What FreeRDP version and server side do you use?
If this is in fact a problem it would be nice if I could properly reproduce it.

**Comment by dd-jacks** [comment] 2015-08-05 12:04
@bmiklautz 
git pull a few hour ago
server-side is Windows 2012 R2

**Comment by bmiklautz** [comment] 2015-08-05 12:09
@dd-jacks thanks. Also tested with the latest master and against Windows 2012 R2. No problem ;(.
Did you try if the problem also exists if you don't start a regular window manager and start xfreerdp manually?

**Comment by dd-jacks** [comment] 2015-08-05 12:44
@bmiklautz 
tty1:
```
X :0 vt7
```
push numlock button at vt7 (now led is on)
tty2:
```
export DISPLAY=:0 
xfreerdp /v:myserver /f /rfx /sec:rdp
```
everything works, closing xfreerdp
```
xfreerdp /v:myserver /f /rfx /sec:rdp +gfx-h264
```
num led is on, numbers are off

```
~$ uname -r
3.2.0-87-generic
```
I can't test another kernel now, but at my PC workstation with ubuntu 14.04 and kernel 3.13 it worked well (with/without GNOME)

**Comment by bmiklautz** [comment] 2015-08-05 12:56
@dd-jacks the kernel shouldn't (hopefully) influence this.
The test above is without any window manager right?
How do you "close" xfreerdp between the tests?

**Comment by dd-jacks** [comment] 2015-08-05 12:57
@bmiklautz 
Yes, without window manager, closing by "Esc"

**Comment by dd-jacks** [comment] 2015-08-05 13:00
Fedora 22
kernel 4.1.2-200.fc22.x86_64
Gnome
from gnome-terminal problem exist

**Comment by RexFan** [comment] 2015-08-12 10:03
@bmiklautz  i deployed a debian 7.7 x64 vm and do above testing. The problem is still there. So it may not caused by arm architecture. May i know your freerdp compile command and have a try?

**Comment by bmiklautz** [comment] 2015-08-13 19:34
@RexFan with libopenh264 installed I just the following in the cloned FreeRDP directory:
```
cmake -DWITH_OPENH264=ON -DCMAKE_BUILD_TYPE=Debug .
make -j8
```

**Comment by RexFan** [comment] 2015-08-14 03:08
@bmiklautz I try your command and try without installing openh264. But both have this issue. (Local host: Debian x64; Remote side: 2012R2)
```
With openh264
cmake -DWITH_OPENH264=ON -DCMAKE_BUILD_TYPE=Debug

Without openh264 (Not installed)
cmake -DCMAKE_BUILD_TYPE=Debug
```
The remote command i used is given below.
```
xfreerdp -sec-nla /cert-ignore /u: /f /gfx /v:x.x.x.x
```
Do you have any other suggestions?

**Comment by freerdp-github** [comment] 2016-01-06 21:44
I am getting this exact behaviour as well with the following command line:
$BIN/xfreerdp /rfx  /gfx +gfx-progressive -bitmap-cache -offscreen-cache -glyph-cache -themes -wallpaper /d:DOMAIN /sec:nla /cert-ignore /f /bpp:32 +auto-reconnect /u:$USER /p:$PASS /v:$IP

In fact, the NUMLOCK problem does not appear when I am not using /gfx command line options. This is a Ubuntu 14.04.3 LTS system connecting to a 2012 R2 RDS server.

**Comment by akallabeth** [comment] 2017-11-20 11:03
Is this still an issue? Can not reproduce.

**Comment by gh-user-7392** [comment] 2017-11-20 17:16
@akallabeth for me using any /gfx options no longer exhibits the strange NUMLOCK/CAPSLOCK behavior using the latest master git version.

**Comment by gh-user-7392** [comment] 2017-11-23 20:36
Spoke to soon on this I am afraid. Using the latest git master FreeRDP version 2.0.0-dev (d982cf0) connecting to a W2K12R264 RDS server with /gfx +gfx-progressive command line options using a Lubuntu 16.04.3 LTS client I still see the original issues the OP stated. Using @bmiklautz tests from above, this is what we are seeing here:

Test 1:
On the Linux thin client, turn CAPSLOCK on prior to connecting to server. Connect to server. Start notepad and test. Result is lowercase. Press CAPSLOCK once, still lowercase. Press once more, than uppercase. Disconnect back to the client, still in uppercase.

Test 2:
On the Linux thin client, do not turn on CAPSLOCK prior to connecting to server. Connect to server. Start notepad and test. Result is lowercase as expected. Press CAPSLOCK once, uppercase works. Press once more, lowercase as expected. Disconnect back to the client, still lowercase as expected.

Summary:
When CAPSLOCK is on at the client prior to connecting, the CAPSLOCK must be pressed twice in order to be recognized on the server. Wehn CAPSLOCK is off on the client prior to connecting, the sequencing works as expected.

Sorry for the late testing, I know another RC is forthcoming. Although I personally did not test NUMLOCK, my users complain that it also broken in the same way as CAPSLOCK.

**Comment by akallabeth** [comment] 2017-11-24 08:02
@gh-user-7392 Ok, so I just ran those test againsts windows 7,8,8.1,10, server 2012 essentials. Everything works as expected.
Just to check if something has changed in the meantime:
* Did you test with your own build or our nightlies?
* What kind of hardware are you using to run xfreerdp?

**Comment by akallabeth** [comment] 2017-11-24 10:07
@gh-user-7392 I've created a branch which synchronizes the modifier key state whenever a modifier key is pressed (to be exact when released)
https://github.com/akallabeth/FreeRDP/tree/key_sync
Would be interesting to know if that fixes the issue for you.

**Comment by gh-user-7392** [comment] 2017-11-24 20:07
@akallabeth to answer your first set of questions, I tested this with the latest master git that I compiled as a release. I also went back and installed the freerdp-nightly version 2.0.0-dev (2f281c06b). In both cases we saw the same problems. I am testing this remotely using a high-end Lenovo laptop running Lubuntu 16.04.3 LTS and onsite using custom thin clients that are basically AMD GX-415GA SOC with Radeon HD Graphics. They are using standard Logitech mice and keyboards. Since this is doing this for us using two different types of hardware it seems like it is not a coincidence. I am also surprised that the original author of this issue has not responded yet. The only common denominator I see is Lubuntu which is LXDE-based. I will spin up Debian 9 and CentOS VMs and see if it does this on them.
I tried your branch on both laptop and onsite and it exhibits the same problems as before, sorry.

**Comment by gh-user-7392** [comment] 2017-11-25 00:52
As a follow-up to my testing I found something interesting that may help you. Looking at an obscure Microsoft Support Document on CAPSLOCK sync with Windows 2012 Server I found a workaround that may shed some light on the problem. The document found here:  https://support.microsoft.com/en-us/help/3120433/caps-lock-key-unexpectedly-inverts-characters-in-a-remote-desktop-sess[](url) describes a workaround as:

_**To make the client and the remote desktop session Caps Lock key sync again, you need to minimize the remote desktop session window or click the mouse outside the remote desktop session window, and then click it again.**_ 

This made me think that if you are in a full screen session then you would not think to do this or have the ability unless you CTRL-ALT-ENTER to minimize the session. So, I tested this out by turning CAPSLOCK on and connecting to the server using a **/size:** option so it would not be in full-screen. I then opened notepad, clicked outside of the session and then back in and started typing in notepad. It turns out that the CAPSLOCK was working when you do this. So it appears there is some syncing going on with the windows server as a result of this clicking outside the session.

I also spun up a Debian 9 VM and this resulted in the same problem. So it is clearly distro agnostic at this point. I hope this helps you in your quest to reproduce this problem. Please let me know if I can help test anything else.

**Comment by akallabeth** [comment] 2017-11-25 06:58
Ok, so it looks like it is a win 2k12 bug. The workaround they mention is does something similar as I've done in my branch. Did you try that?

**Comment by gh-user-7392** [comment] 2017-11-25 07:23
Yes I tried your branch and it has the same problem as the original git master. I guess you were never able to reproduce the problem yourself though.

**Comment by gh-user-7392** [comment] 2017-11-25 22:35
Not to overly complicate the issue but I just compiled the latest git of Remmina and FreeRDP together and ran FreeRDP through Remmina at full screen and the problem goes away. I'm not sure if this is because Remmina is an external program or whether it is doing some syncing of it's own behind the scenes. Just thought I would throw that out there in case it helps....

**Comment by akallabeth** [comment] 2017-11-26 14:23
That is indeed interesting. Remmina does no extra sync at all, but they send  a TAB up like we do in FocusInEvent.
Did change my branch to send that too, could you confirm?
Btw, no I was never able to reproduce, so something is missing to get a reliable test case for this.

**Comment by gh-user-7392** [comment] 2017-11-27 23:28
I am sorry to report that the changes in your branch did not have any effect. I am still seeing the same behavior when connecting to W2K12R2 and WIN8 PRO. I see you deferred this problem to RC2. I think this is a reasonable thing to do for the time being. I will inform our user base about the workaround until a solution is found. Thanks again for all your great efforts on this software.

**Comment by bmiklautz** [comment] 2017-11-28 09:37
@gh-user-7392 when the problem occurs is it a re-connect to a running session or does this also happen if a new RDP session is started (so the user logs in)?

**Comment by gh-user-7392** [comment] 2017-11-28 18:06
Hi @bmiklautz, this occurs only when a new connection is made to the server. If a user reattaches to a disconnected session, then there is no problem. In this particular setup I have several RDS servers in a collection without load balancing. In other words, I have disabled the GPO "Use RD Connection Broker load balancing"; otherwise, it causes problems during direct connections.

**Comment by akallabeth** [comment] 2018-05-02 10:29
@gh-user-7392 Is this still an issue with current nightlies?
We fixed redirection issues which might be related.

**Comment by gh-user-7392** [comment] 2018-05-03 23:11
@akallabeth sorry, no go. Latest master using any /gfx related flags still exhibits the CAPS/NUM sync problems.

**Comment by akallabeth** [comment] 2018-12-11 14:37
No longer reproducible with `2.0.0-rc4`, closing.
Reopen / create a new issue if it can be reproduced with current versions.

**Closed by akallabeth** 2018-12-11 14:37 UTC
Labels: waiting-feedback
