### ISSUE TITLE
xfreerdp doesnt start, if folder (in key /drive) doesnt exist

### ISSUE THREAD

**Issue by ekorneechev** [FreeRDP/FreeRDP#4685] opened 2018-05-30 10:58 UTC
**To Reproduce**
```
$ ls /home/user/share
ls: cannot access /home/user/share: No such file or directory
$ xfreerdp /v:server /u:user@domain /p:passwd -sec-nla /drive:share,/home/user/share

FreeRDP - A Free Remote Desktop Protocol Implementation
See www.freerdp.com for more information

Usage: xfreerdp [file] [options] [/v:<server>[:port]]
....
$ mkdir /home/user/share
$ xfreerdp /v:server /u:user@domain /p:passwd -sec-nla /drive:share,/home/user/share
[13:32:57:521] [6135:6136] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[13:32:57:522] [6135:6136] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[13:32:57:522] [6135:6136] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[13:32:57:750] [6135:6136] [ERROR][com.winpr.timezone] - Unable to get current timezone rule
[13:32:57:890] [6135:6136] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[13:32:57:890] [6135:6136] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[13:32:57:952] [6135:6136] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[13:32:57:953] [6135:6141] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [Shared] (static)
[13:32:58:393] [6135:6141] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: share (type=8 id=1)
```
**Expected behavior**
Or as it was in 2.0.0-rc0: redirecting an empty folder and when copying files, creating it (if permissions are allowed). Or informing the user at startup xfreerdp that folder doesnt exist.

OS: Linux Mint 17.3
```
$ dpkg -s freerdp-x11 | grep Version
Version: 2.0.0~git201804050820-0+remmina201804082034.ra9ecd6a.d9be5820~ubuntu14.04.1
```
```
$ xfreerdp /buildconfig
This is FreeRDP version 2.0.0-dev2 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=off HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=on WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=on WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=on WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=OFF WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          None
CFLAGS:              -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wno-format-security -D_FORTIFY_SOURCE=2 -Wno-format-security  -march=i686 -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g
Compiler:            GNU, 4.8.4
Target architecture: x86
```

**Comment by hardening** [comment] 2018-05-30 14:14
IMHO, the best would be to print an explicit error message

**Comment by ekorneechev** [comment] 2018-05-30 15:43
And start without redirecting of this folder.

**Comment by akallabeth** [comment] 2018-06-01 07:09
@andycher11 what do you need that for? There is also hotplug support for external drives,

**Comment by andycher11** [comment] 2018-06-01 07:26
i use thinstation without GUI, and USB="/drive:'USB,/mnt/usbdevice/'" in freerdp.global for users who need usb drive redirection and CDROM="/drive:'CDROM,/mnt/cdrom0'"  who need cdrom. In rc2 this does not work, freerdp does not connect, if folder usbdevice does not exist. It appears if the user plug in the USB storage device. So user cannot connect to server without usb drive plugged

**Comment by ekorneechev** [comment] 2018-06-01 08:30
@akallabeth #4684 /drive and +drives dont work together...

**Comment by akallabeth** [comment] 2018-06-01 09:20
@andycher11 `/drive:auto,*` should do the trick to automatically redirect freshly mounted drives
@ekorneechev I don't understand what these two options have to do with this issue

**Comment by ekorneechev** [comment] 2018-06-01 09:47
@akallabeth "There is also hotplug support for external drives" -> i thought about '+drives'

**Comment by andycher11** [comment] 2018-06-04 10:08
with /drive:auto,* freerdp connects, but drive not redirects, +drives doesnt work too. I tried on ubunru 1804 and on thinstation. 
This is FreeRDP version 2.0.0-rc2 (2.0.0-rc2)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=on WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=ON WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=on WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=off WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Debug
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g
Compiler:            GNU, 7.3.0
Target architecture: x64

**Comment by ekorneechev** [comment] 2018-09-27 14:06
In 2.0.0-rc3 same behavior...

**Comment by chym95** [comment] 2020-06-08 10:05
I reproduce since this commit :
https://github.com/FreeRDP/FreeRDP/commit/27aac21c033f1c0e4b6dc1dbf1658c44d97b752f#diff-0e276575c13706073c07eccd0667705b

**Comment by akallabeth** [comment] 2020-06-08 11:01
Closing this as `not a bug`.
The arguments for drive redirection must be correct just as any other argument.

**Closed by akallabeth** 2020-06-08 11:01 UTC

**Comment by ekorneechev** [comment] 2020-06-26 11:41
> Closing this as `not a bug`.
> The arguments for drive redirection must be correct just as any other argument.
/media/$USER does not exists, if USB does not connected. And it is correct!

**Comment by akallabeth** [comment] 2020-06-29 06:58
@ekorneechev then use `/drive:hotplug,*` just as the documentation tells you to
