### ISSUE TITLE
Print problem through FreeRDP

### ISSUE THREAD

**Issue by Shuric1C** [FreeRDP/FreeRDP#3483] opened 2016-08-28 03:45 UTC
Hello.
There was one problem with the seal through Remmina.

remmina - version 1.2.0-rcgit-15
FreeRDP - version 2.0.0-dev

Client (Linux Mint 17.3 x32) connected via Remmina (tick cocked - make a local printer available to the public) to WinSrv2008R2 printer redirected = print one copy of all right, but if you set the number of copies 2 - go to print 4 sheets, if you set the number of copies 3 - published 6 sheets, etc.
Printers = Canon MF3010, Canon MF4330d - with www.canon.com driver.

Connect and so from a terminal:
xfreerdp /u:user /printer /v:10.10.10.1

terminal:
[INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
Password: XXXX
[INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer (static)
[INFO][com.freerdp.channels.rdpdr.client] - registered device #1: PRN1 (type=4 id=1)

... сonnected, started up 2 copies to print...
[ERROR][com.freerdp.channels.rdpdr.client] - Ignoring unhandled message PAKID_PRN_CACHE_DATA (EventID: 0x0002)

Result - 4 sheets

Please tell me where to find the problem and how to solve it?

**Comment by adamzolo** [comment] 2018-02-16 10:09
Hello.
Did you fix this issue?

**Comment by akallabeth** [comment] 2018-04-13 06:47
Tested with fc6780a86 and could not reproduce. Could you confirm?

**Comment by akallabeth** [comment] 2018-09-24 10:32
Not reproducible, no feedback.
Closing.

**Closed by akallabeth** 2018-09-24 10:32 UTC
Labels: fixed-waiting-test
