### ISSUE TITLE
Every colorful figures have shadows on the right side of themselves

### ISSUE THREAD

**Issue by linux40** [FreeRDP/FreeRDP#10376] opened 2024-07-13 14:54 UTC
**Describe the bug**
After login to Windows 11 desktop, every icons and characters have a shift of shadows on their right side if they have colors other than pure white and black, for example the icon of start menu below:
![2024_07_13_22_07_58_grim](https://github.com/user-attachments/assets/5a1c9be7-bc1f-45f7-ad8c-d1af1c8aee66)

**To Reproduce**
1. Run `sdl-freerdp3 /u:my@email /d: /p: /v:ip /w:foo /h:bar /bpp:16 /audio-mode:1 /sec:tls /gfx:avc444 /log-level:trace`
2. xfreerdp3 and wlfreerdp3 have the problem as well

**Expected behavior**
All figures should show properly

**Screenshots**
As above.

**Application details**
* This is FreeRDP version 3.6.3 (n/a)
* Command: As above
* Output of `xfreerdp /buildconfig`:
```
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ABSOLUTE_PLUGIN_LOAD_PATHS=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_BINARY_VERSIONING=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CJSON_REQUIRED=OFF WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL2=ON WITH_CLIENT_SDL3=OFF WITH_CLIENT_SDL_AVAILABLE=1 WITH_CLIENT_SDL_VERSIONED=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FULL_CONFIG_PATH=OFF WITH_FUSE=ON WITH_GFX_FRAME_DUMP=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_ICU=ON WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_JPEG=ON WITH_JSONC_REQUIRED=OFF WITH_JSON_DISABLED=OFF WITH_KRB5=ON WITH_KRB5_NO_NTLM_FALLBACK=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBRESSL=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_OPUS=OFF WITH_OSS=ON WITH_PCSC=ON WITH_PKCS11=ON WITH_PLATFORM_SERVER=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=ON WITH_RDTK=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SDL_IMAGE_DIALOGS=OFF WITH_SDL_LINK_SHARED=ON WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=OFF WITH_SWSCALE=ON WITH_SYSTEMD=OFF WITH_THIRD_PARTY=OFF WITH_TIMEZONE_ICU=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=ON WITH_WEBVIEW=ON WITH_WEBVIEW_QT=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_JSON=ON WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON
```
* OS version connecting to: 22631.3155
* If available the log output from a run with: https://pastebin.com/raw/skzEiqpX
* If you built it yourself: no.

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Artixlinux
 - Architecture: amd64

**Additional context**
Kernel: 5.15.160-1-lts515 from Artix
Graphic: Intel Corporation CometLake-S GT2 [UHD Graphics 630] (rev 03)
Mesa: 24.1.3

FreeRDP 2  does not have the issue but the performance becomes more and more trouble after updates.

**Comment by akallabeth** [comment] 2024-07-13 18:48
can you test with our flatpak as well?
this looks like a bug with your H264 decoder, so we need to be sure.

I´ve just ran a connection against a windows 11 with similar arguments and can not find any of these glitches.

**Comment by akallabeth** [comment] 2024-07-14 08:21
* could you tell us the resolution you use then?
* could you try a connection with `/rfx` and another one with `/gfx` instead of `/gfx:avc444` and tell how that behaves on your system?

**Comment by akallabeth** [comment] 2024-07-14 17:16
@linux40 ok, so we narrowed it down to the `h264` decoder or postprocessing. (`/gfx:avc420` is only supported by windows 8.1 and in all other cases uses the callisto/progressive codec)
since I can not reproduce this on any of my machines (debian 12, fedora 40, openh264 and ffmpeg/x264 as decoders) to windows 10 and 11 targets I assume it might be something with the H264 data.

do you have another target you can connect to? can you reproduce the issue there too?

**Comment by akallabeth** [comment] 2024-07-14 17:24
oh, and
> FreeRDP 2 does not have the issue but the performance becomes more and more trouble after updates.

what do you mean by that? we did not change performance related stuff in stable branch for years now.
but you might review your build options, there are some debug things activated that might slow down stuff ;)

**Comment by akallabeth** [comment] 2024-07-15 07:24
also,`/bpp:16 /gfx:avc444` is a bit contradictory, better leave these out and let the autodetection do it's magic.

**Comment by akallabeth** [comment] 2024-07-15 08:33
@linux40 could you also add which group policy settings you use to enforce `AVC444` mode?
maybe there is something hidden that requires these to be set for a reproduction test case

**Comment by akallabeth** [comment] 2024-07-22 03:18
@linux40 ok, that sounds more and more like a configuration issue on your server side.

1. the `/gfx:mask:0xFFF0` disables capabilities for `8`, `8.1`, `10` and `101` which should never be chosen by a well configured `RDP` server as newer capabilities are available. (you can check which ones are in use with a debugger/additional code for logging in `rdpgfx_send_caps_advertise_pdu`)
2. `result a remote desktop that does not react with my keyboard or mouse.` - that can only happen if your server is misbehaving
3. `not showing my wallpaper` that is a configuration option, not client side.  (there is a flag +/-wallpaper to announce a preference for on/off, but up to the server to enforce it)

so closing this as not a bug in `FreeRDP` until there is some conclusive evidence to the contrary.
(you might add how you configured your server so we can reproduce or answer some of the other questions I´ve posed)

**Closed by akallabeth** 2024-07-22 03:18 UTC
Labels: waiting-feedback

**Comment by akallabeth** [comment] 2024-07-24 14:48
@linux40 did you test with `mstsc`?
the whole thing smells for some buggy driver server side and you avoided answering these questions until now ;)

**Comment by akallabeth** [comment] 2024-07-25 07:38
@linux40 I´ve ran the test against one of our windows 11 VM and it works quite well. (connection uses AVC444 mode)

![image](https://github.com/user-attachments/assets/1a817f90-7657-476e-97b9-5886acbc966d)

**Comment by akallabeth** [comment] 2024-07-27 19:47
@linux40 
1. if server side software encoding and hardware encoding result in different behavior on the client the server is at fault.
2. that it is using `AVC444v2` was expected (the mask you gave did not make much sense as it only deactivates stuff that is never used anyway if you´re not connecting to windows 8.1 or older)
3. `mstsc` is a necessary comparison here, if you have the same artifact then point 1 is the way to debug, if not then I´ll start considering this a `FreeRDP` bug, but up till now nothing points to that direction.
