### ISSUE TITLE
Connecting to Windows 2012/2012R2/2016/10 with -fast-path and non-RGX/GFX color depth gives a black screen

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#4642] opened 2018-05-12 21:17 UTC
I'm not sure this is a bug.
As said in the title, if I connect to a windows server from version 2012 to 2016, with disabled fast-path (-fast-path) and a color depth which is not RFX or GFX, I can only get a black screen.

```
xfreerdp /v:_host_ /d:_domain_ /u:_user_ /bpp:32 -fast-path
```
Connecting to older OSes (i.e: 2008R2) works.

**Comment by akallabeth** [comment] 2018-05-14 07:36
Sounds like deprecation to me, need to check though.

**Comment by akallabeth** [comment] 2018-05-14 12:15
Ok, this is a deprecation issue.
closing.

**Closed by akallabeth** 2018-05-14 12:15 UTC

**Comment by chrislong** [comment] 2019-03-29 15:16
Can you explain what you mean by "this is a deprecation issue"? Does that mean disabling fast path is deprecated?

I'd really like to run a session without fast path to help debug #4934 .

**Comment by akallabeth** [comment] 2019-03-29 15:20
@chrislong then good luck with finding a (recent) server that still supports that.
Anyhow, what does debugging the referenced issue have to do with this?
That is independent of the transport but an application issue (local and remote sizes changes going into a loop)

**Comment by chrislong** [comment] 2019-03-29 15:42
Oh, I didn't know recent servers required fast path. Thanks.

The issue is that I'm looking at a packet capture to help understand (and explain to someone at Microsoft) the weird behavior from #4934. Wireshark understands some RDP, but it fails to parse a lot of the traffic and I also had problems figuring it out by hand, and I think it's because it doesn't understand fast path. I was hoping to disable fast path so it could parse the packets better.
