### ISSUE TITLE
RemoteApp is jittery, misaligned and glitchy on Ubuntu 21.10 and Windows 11, freerdp-nightly

### ISSUE THREAD

**Issue by jphein** [FreeRDP/FreeRDP#7784] opened 2022-04-06 16:56 UTC
Ubuntu 21.10
This is FreeRDP version 3.0.0-dev (1adb26381)
Windows 11 Enterprise multi-session 21H2

[09:39:14:465] [38852:38853] [WARN][com.freerdp.client.x11] - xf_Pointer: Invalid appWindow

RemoteApp does not align the viewport, and cursor. Apps are not usable because they jitter around, and the local view does not quite correspond with the remote app. Most of the top bar looks cut off. Regular remote desktop session works perfectly.

**To Reproduce**
/opt/freerdp-nightly/bin/xfreerdp /v: /app:||7b9d2845-d91d-4b17-e6ed-08da11342132 /sound /microphone /multitransport /network:auto /rfx /gfx:AVC444 /cert-ignore /drive:hotplug,* +fonts /u: /p: /d:

**Expected behavior**
Remote application behaving like a local app.

**Screenshots**
![Screenshot from 2022-04-06 09-39-42](https://user-images.githubusercontent.com/19301265/162025948-34bac54e-dbe3-4eac-9009-9b387daf4a28.png)

**Application details**
Ubuntu 21.10 AMD64
This is FreeRDP version 3.0.0-dev (1adb26381)
Windows 11 Enterprise multi-session 21H2 64-bit

* Output of `xfreerdp /buildconfig`
* /opt/freerdp-nightly/bin/xfreerdp --version
This is FreeRDP version 3.0.0-dev (1adb26381)
root@ultrabook2:~# /opt/freerdp-nightly/bin/xfreerdp /buildconfig
This is FreeRDP version 3.0.0-dev (1adb26381)
Build configuration: 
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -ffile-prefix-map=/build/freerdp-nightly-3.0.0+0~20220406014817.1107~1.gbp1adb26=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -fsanitize=address -fsanitize-address-use-after-scope
Compiler:            GNU, 11.2.0
Target architecture: x64

* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt`

**Comment by jphein** [comment] 2022-04-16 17:51
output of /log-level:trace 2>&1 | tee log.txt
[log.txt](https://github.com/FreeRDP/FreeRDP/files/8500409/log.txt)

**Comment by vesystem2022** [comment] 2022-07-20 05:41
https://github.com/FreeRDP/FreeRDP/pull/8082

I have submitted the repair of this problem, which has not been merged for the time being

**Comment by akallabeth** [comment] 2022-09-20 10:00
@vesystem2022 and I´ve stated the reasons why it was not merged ;)
Please address the issues for this to go forward or it will stall.

**Comment by gang929** [comment] 2022-10-11 14:08
Revert [8e87e9d](https://github.com/FreeRDP/FreeRDP/commit/8e87e9d6eb847a9af4e1b090112adc59d960fe66) maybe resolve this issue.
Although the window will be iconise when it is restored from the minimized state, it needs to be clicked again to restore, but it will not display misaligned.

By trace the log when window restore from minimize, the issue about iconise from minimize is is caused by the TS server sending update orders like the following
```
Window updae  ... show maximize...
Window update ... clientAreaWidth=0 clientAreaHeight=0
Window update ... visibleWidth=160 visibleHeight=27
```
These order will maximize window, and then iconize window, so the remote app window will be show maximize and then iconise at last.

In the `xf_event_MapNotify`, regardless of sending SC_RESTORE or SC_MAXIMIZE, the remote app window will be show as iconise.
It maybe should be send a SC_MAXIMIZE after the window recv the last update order (eg. Window update ... visibleWidth=160 visibleHeight=27), But can not detect the "LAST" order or send time.

**Comment by gang929** [comment] 2022-10-13 01:29
Try this this patch,  it will solve the misaligned and restore window from minimized.
```
diff --git a/client/X11/xf_event.c b/client/X11/xf_event.c
index 747e818b6..62ef0964a 100644
--- a/client/X11/xf_event.c
+++ b/client/X11/xf_event.c
@@ -761,7 +761,7 @@ static BOOL xf_event_MapNotify(xfContext* xfc, const XMapEvent* event, BOOL app)
        {
                appWindow = xf_AppWindowFromX11Window(xfc, event->window);
 
-               if (appWindow && (appWindow->rail_state == WINDOW_SHOW))
+               if (appWindow)
                {
                        /* local restore event */
                        /* This is now handled as part of the PropertyNotify
diff --git a/client/X11/xf_rail.c b/client/X11/xf_rail.c
index 770234f7d..a04ea4566 100644
--- a/client/X11/xf_rail.c
+++ b/client/X11/xf_rail.c
@@ -506,6 +506,13 @@ static BOOL xf_rail_window_common(rdpContext* context, const WINDOW_ORDER_INFO*
                                                    visibilityRectsOffsetY, appWindow->visibilityRects,
                                                    appWindow->numVisibilityRects);
                }
+               if (appWindow->rail_state == WINDOW_SHOW_MAXIMIZED && appWindow->clientAreaHeight == 0 && fieldFlags & WINDOW_ORDER_FIELD_WND_OFFSET && !(fieldFlags & WINDOW_ORDER_FIELD_WND_SIZE))
+               {
+                       xf_rail_send_client_system_command(xfc, appWindow->windowId, SC_RESTORE);
+                       xf_rail_send_client_system_command(xfc, appWindow->windowId, SC_MAXIMIZE);
+               }
        }
 
        /* We should only be using the visibility rects for shaping the window */
```
Strangely, it must be sent SC_RESTORE and SC_MAXIMIZE, otherwise, the window may still be an iconize.

This method of detecting the "LAST window update order" is too "HARD CODE". It is write by the LOG as below, 
It seems that the window state is maximize and the width/height is smallest when restoring window from minimize state by clicking taskbar icon of app.
@akallabeth @jphein , Can you give some suggestions ?
```
[22:14:51:427] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:427] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 clientOffset=(0,19) visibleOffset=(0,0) visibilityRects=((0,0,1006,675))
[22:14:51:427] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:427] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 clientAreaWidth=1006 clientAreaHeight=656
[22:14:51:458] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:458] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 clientOffset=(4,23) visibilityRects=((0,0,1006,635))
[22:14:51:458] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:458] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 clientAreaWidth=998 clientAreaHeight=608
[22:14:51:489] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:489] [14735:14736] [DEBUG][com.freerdp.core.update] - ActivelyMonitoredDesktop activeWindowId=0x2b00d6
[22:14:51:490] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:490] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 show=maximized
[22:14:51:490] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:490] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 [ex]style=<0x15cfc000, 0x110 visible thickframe border caption> windowOffset=(0,0) windowClientDelta=(4,23) windowWidth=1006 windowHeight=635
[22:14:51:491] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:491] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 [ex]style=<0xb0000, 0x0>
[22:14:51:491] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:491] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 clientOffset=(4,632) visibleOffset=(0,609) visibilityRects=((0,0,160,27))
[22:14:51:492] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:492] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 clientAreaWidth=152 clientAreaHeight=0
[22:14:51:493] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:493] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 [ex]style=<0x15cfc000, 0x110 visible thickframe border caption> windowOffset=(0,609) windowWidth=160 windowHeight=27
[22:14:51:493] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:493] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 [ex]style=<0xb0000, 0x0>
[22:14:51:493] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:493] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 [ex]style=<0x15cfc000, 0x110 visible thickframe border caption>
[22:14:51:536] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:536] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 clientOffset=(4,23) visibleOffset=(0,0) visibilityRects=((0,0,1006,635))
[22:14:51:536] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:536] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 clientAreaWidth=998 clientAreaHeight=608
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 clientOffset=(4,631) visibleOffset=(0,608) visibilityRects=((0,0,1006,67))
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 visibilityRects=((0,0,160,27))
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 clientAreaWidth=152 clientAreaHeight=0
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 [ex]style=<0xb0000, 0x0>
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 [ex]style=<0x15cfc000, 0x110 visible thickframe border caption> windowOffset=(0,608)

**HERE, SENDING SC_RESTORE and SC_MAXIMIZE TO MAXIMIZE WINDOW.....**

[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 [ex]style=<0xb0000, 0x0>
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 [ex]style=<0x15cfc000, 0x110 visible thickframe border caption>
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[22:14:51:568] [14735:14736] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x2818262 [ex]style=<0xb0000, 0x0>
```

**Closed** 2023-07-26 19:41 UTC
Labels: client, channel:rail
