### ISSUE TITLE
Screen artefacts seen when resizing FreeRDP window

### ISSUE THREAD

**Issue by simonjhaggett** [FreeRDP/FreeRDP#6189] opened 2020-05-18 13:29 UTC
When resizing FreeRDP's window (e.g. by dragging from normal size to large), I observe artefacts appearing on the framebuffer. An occurrence of this is shown in the screenshot below. This is frequently reproducible. Dynamic resolution is switched on in my attempts.

![screenshot](https://user-images.githubusercontent.com/1611269/82217941-0f661c80-9913-11ea-84ad-2b3879c31a27.png)

I first noticed this issue in FreeRDP 2.0.0 (April 2020). This does not occur with FreeRDP 2.0.0-rc4. From a bisection, this appears to have been introduced by commit 1fa00c4.

**Host System:** Linux (CentOS 8 amd64)
**Remote System:** Windows 10 Enterprise 1909 amd64
**FreeRDP Version:** 3.0.0-dev (c11939e32)

**Build Steps**
Built from master branch pulled today, no local changes.
```
$ cmake ~/sources/freerdp/git/FreeRDP -DCMAKE_INSTALL_PREFIX=~/install_tmp -DWITH_ALSA=OFF -DWITH_CLIENT=ON -DWITH_FFMPEG=OFF -DWITH_MANPAGES=OFF -DWITH_OSS=OFF -DWITH_SERVER=OFF -DWITH_SERVER_INTERFACE=OFF -DWITH_XRANDR=OFF -DCHANNEL_URBDRC=OFF
$ make && make install
```
**Command Line**
```
$ ./xfreerdp ~/test.rdp /cert-ignore /dynamic-resolution /u:Bromine /log-level:TRACE
```
where `test.rdp` has the following content:
```
audiomode:i:2
authentication level:i:1
enablecredsspsupport:i:1
full address:s:192.168.0.183
negotiate security layer::i:1
redirectclipboard:i:1
redirectprinters:i:0
redirectsmartcards:i:0
```
The trace log (from the same run as the screenshot above) is here: [log.txt](https://github.com/FreeRDP/FreeRDP/files/4644320/log.txt)

**Comment by akallabeth** [comment] 2020-05-18 14:27
@simonjhaggett looks like a screen refresh is missing, needs to be investigated.
only thing for sure, the bisect seems to be off, the commit does not modify any code used by this configuration.
It might be caused by your odd configuration with certain `X11` features being turned off (why?)

**Comment by simonjhaggett** [comment] 2020-05-18 14:47
Thanks for the feedback.

> only thing for sure, the bisect seems to be off, the commit does not modify any code used by this configuration.

Commit 1fa00c4 refactors the progressive codec, and the trace log I attached suggests to me that this codec is being used in the connection:
```
[13:49:19:930] [33765:33776] [TRACE][com.freerdp.gdi] - surfaceId=0, codec=9, contextId=1, format=PIXEL_FORMAT_BGRX32, left=0, top=0, right=0, bottom=0, width=0, height=0 length=32350, data=0x00007f3b90d90739, extra=(nil)
[13:49:19:931] [33765:33776] [DEBUG][com.freerdp.codec.progressive] - ProgressiveSync
[13:49:19:931] [33765:33776] [DEBUG][com.freerdp.codec.progressive] - ProgressiveContext: flags: 0x01
[13:49:19:931] [33765:33776] [DEBUG][com.freerdp.codec.progressive] - ProgressiveFrameBegin: frameIndex: 0 regionCount: 1
[13:49:19:932] [33765:33766] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
[13:49:19:932] [33765:33776] [DEBUG][com.freerdp.codec.progressive] - Unused byes detected, 6 bytes not processed
[13:49:19:932] [33765:33776] [DEBUG][com.freerdp.codec.progressive] - ProgressiveRegion: numRects: 6 numTiles: 188 tileDataSize: 32223 flags: 0x01 numQuant: 1 numProgQuant: 1
...
```
I also can't reproduce the issue when I revert this commit.

>  It might be caused by your odd configuration with certain X11 features being turned off (why?)

Thanks, I'll check again with a default configuration.

**Comment by simonjhaggett** [comment] 2020-05-18 15:06
> Thanks, I'll check again with a default configuration.

I am able to reproduce this again when building as follows:
```
$ cmake ~/sources/freerdp/git/FreeRDP -DCMAKE_INSTALL_PREFIX=~/install_tmp
$ make && make install
```
The screenshot from this reproduction is below:
![screenshot](https://user-images.githubusercontent.com/1611269/82228618-43e0d500-9921-11ea-8548-04d8ac73f842.png)

And the corresponding trace log is here:  [log.txt](https://github.com/FreeRDP/FreeRDP/files/4644915/log.txt)

**Comment by akallabeth** [comment] 2020-05-18 15:19
@simonjhaggett ok, could you do a negative test, don´t use the RDP file but do a connection with only `/rfx`, one with `/gfx`, one with `/rfx /gfx` and one with `/gfx:avc444` and check if the issue can be reproduced with all of them?
(note, for `/gfx:avc444` please check the log which codec is actually used, as not every server supports that by default)

**Comment by simonjhaggett** [comment] 2020-05-18 16:10
@akallabeth sure, here's the results. For each run, my command line started with `./xfreerdp /v:192.168.0.183 /u:Bromine /cert-ignore /dynamic-resolution /log-level:TRACE`.

* `/rfx` only: cannot reproduce issue
* `/gfx` only: issue reproduced successfully
* `/rfx /gfx`: issue reproduced successfully
* `/gfx:avc444`: cannot reproduce issue (and log confirms  `codec=15` in use, which is `RDPGFX_CODECID_AVC444v2`).

Before I ran these, I rebuilt with `-DWITH_OPENH264=ON` (using OpenH264 v1.8.0). Let me know if you need any of the trace logs for these runs.

**Comment by mmorvai** [comment] 2020-09-08 07:57
This problem not only occurs when resizing FreeRDP. Desktop icons are displayed incorrectly, start menu fails to load sometimes and even moving a window causes this artifacts to appear. 

The artifacts are a bug in the progressive codec. After a git bisect, I can confirm that commit 1fa00c4 was the one to break it.

**Comment by akallabeth** [comment] 2020-09-08 09:12
@mmorvai could you give some more details on how to reproduce? (command line, freerdp versions, remote os and version)?

**Comment by mmorvai** [comment] 2020-09-08 09:53
Sure. Sorry. Could reproduce the problem with Windows 2016 (1607) and Windows 2012R2 (6.3 Build 9600) using FreeRDP 2.2.0 (and current master). The problem always occurs, when progressive codec is used (checked with /log-filters:com.freerdp.codec.progressive:DEBUG).

FreeRDP parameters: /gfx:RFX -gfx-thinclient-mode +window-drag

The parameter +window-drag is not necessary, but helps reproducing the problem.

Steps to reproduce:
1. Connect to server
2. Right click on Desktop -> Personalize -> Change background
3. Move Settings window around

**Comment by akallabeth** [comment] 2020-09-08 10:49
@mmorvai ok, got it. do you know which operation produces the artefact or you have the progressive log entries for a broken window segment by hand?

**Comment by mmorvai** [comment] 2020-09-08 15:08
Nope sorry. I gave it a try, but it's a bit too complicated for me. ;-) The only difference I saw in the logs is:
```
[16:55:20:229] [1971755:1971800] [DEBUG][com.freerdp.codec.progressive] - ProgressiveTileFirst: quantIdx Y: 0 Cb: 0 Cr: 0 xIdx: 10 yIdx: 6 flags: 0x2E quality: 255 yLen: 817 cbLen: 683 crLen: 713 tailLen: 0
[16:55:20:230] [1971755:1971800] [DEBUG][com.freerdp.codec.progressive] - ProgressiveTileFirst: quantIdx Y: 0 Cb: 0 Cr: 0 xIdx: 11 yIdx: 6 flags: 0x1C quality: 255 yLen: 1067 cbLen: 660 crLen: 787 tailLen: 0

```
The flags attribute for ProgressiveTileFirst is all over the place. But as long as only the first bit is used this shouldn't be a problem.

**Comment by marchaefner** [comment] 2021-03-01 10:44
This problem seems to be fixed in 2.3.0 (with the last batch of backports). I can no longer reproduce it.

@simonjhaggett: Can you confirm this?

**Comment by akallabeth** [comment] 2021-03-01 10:49
@marchaefner we´ve fixed a few progressive codec things, so closing this.
@simonjhaggett if you can reproduce, please reopen.

**Closed by akallabeth** 2021-03-01 10:49 UTC

**Comment by simonjhaggett** [comment] 2021-03-01 13:13
> @simonjhaggett: Can you confirm this?

Yep, I can no longer reproduce this issue either. Thanks!
