### ISSUE TITLE
Multimedia Redirection didn't work well.

### ISSUE THREAD

**Issue by daiqifan** [FreeRDP/FreeRDP#3336] opened 2016-05-12 10:11 UTC
Multimedia redirection has some problem:  it is just show a blank video and its error is:
[03:01:33:017] [5219:5220] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[03:01:33:017] [5219:5220] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[03:01:33:019] [5219:5220] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
[03:01:33:214] [5219:5220] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel tsmf
[03:02:04:209] [5219:5223] [WARN][com.freerdp.channels.tsmf.client] - presentation id 7AA5933095124B42A5B72BA50463F943 not found
[03:02:05:797] [5219:5751] [ERROR][com.freerdp.channels.tsmf.client] - data_size 4515, no frame is decoded.
[03:02:05:798] [5219:5751] [ERROR][com.freerdp.channels.tsmf.client] - decode error, queue ack anyways
[03:02:11:062] [5219:5223] [WARN][com.freerdp.channels.tsmf.client] - presentation id 7AA5933095124B42A5B72BA50463F943 not found
[03:02:11:062] [5219:5223] [ERROR][com.freerdp.channels.tsmf.client] - unknown presentation id
[03:02:11:062] [5219:5223] [ERROR][com.freerdp.channels.tsmf.client] - ifman data received processing error 1168
[03:02:11:062] [5219:5223] [WARN][com.freerdp.channels.tsmf.client] - presentation id 7AA5933095124B42A5B72BA50463F943 not found
[03:02:11:062] [5219:5223] [ERROR][com.freerdp.channels.tsmf.client] - unknown presentation id
[03:02:11:062] [5219:5223] [ERROR][com.freerdp.channels.tsmf.client] - ifman data received processing error 1168
[03:02:11:072] [5219:5223] [WARN][com.freerdp.channels.tsmf.client] - presentation id 7AA5933095124B42A5B72BA50463F943 not found

The Sound is noisy at the same time. But it is clearly when i  just use audio output redirection.
The host is CentOS 6.5, server is Win7_64, Freerdp version is 2.0.
if is needed addition info, please tell me.

**Comment by akallabeth** [comment] 2016-05-12 10:39
@daiqifan TSMF is buggy and needs some love. If you just need videos playing properly you can use ```/gfx``` or ```/gfx-h264``` (the latter requires a build against OpenH264)

**Comment by daiqifan** [comment] 2016-05-13 02:07
@akallabeth I need multimedia redirection properly.  I used the option  /multimedia:sys:alsa which called TSMF.  Is there any more proper option?  I am look forward to your reply.

**Comment by akallabeth** [comment] 2016-05-13 06:42
you need to compile with gstreamer support (ffmpeg success varies) and a debugger in case it does not work stable. last time I checked clang scanbuild gave some hints on errors.

**Comment by puneet101** [comment] 2016-09-07 01:00
Any update on this? What's the best video performance option right now?

**Comment by uplusplus** [comment] 2016-10-26 03:20
how to add multimedia redirection support for android?

**Comment by akallabeth** [comment] 2016-10-27 08:42
@uplusplus Well, you have to implement a backend to overlay the android view with the multimedia content. But multimedia redirection is deprecated anyway, why not just use GFX:rfx, GFX:avc420 or GFX:AVC422?

**Comment by uplusplus** [comment] 2016-10-27 10:03
@akallabeth The video playback speed is only 10 fps。

**Comment by akallabeth** [comment] 2016-10-27 15:10
@uplusplus That was the speed with the first or second command line?
AVC444 is maybe not the best mode for slow hardware, /gfx:AVC420 is much faster. If you don't care about bandwidth you can also just use /gfx:rfx
If that is still too slow you'll need hardware accelerated H264 for your device, which is currently not implemented for the GFX channel.

**Comment by uplusplus** [comment] 2016-10-28 01:24
@akallabeth 
That was the speed with the first command line.
The error was caused by "/multimedia:decoder:ffmpeg"
My device board is rk3188, support hardware h264 decode.

**Comment by akallabeth** [comment] 2016-10-28 06:17
@uplusplus Ok, I'll have a look at ClearCodec as soon as I have spare time (#3527 is the issue with ```/gfx:rfx```). So either you have success with ```/gfx:avc420``` or ```/rfx``` or you need to write some glue code to access the hardware h264 decoder of your device. (have a look at the functions in gfx.c)

**Comment by uplusplus** [comment] 2016-11-05 01:01
What do you mean about "multimedia redirection is deprecated", Freerdp will not support it anymore?

ref:
Does Windows Server 2012 still support Multimedia Redirection?

Windows Media Redirection still provides the best experience on LAN networks for supported video formats. Windows Server 2012 and Windows 8 automatically detect these conditions and turn on Multimedia Redirection. If these conditions are not met (for example, if the user is on a WAN network), the system automatically switches to use RemoteFX Media Streaming, even for WMP content. The determination of whether or not the user is on a WAN network is made by looking at the end-to-end latency—if the connection latency is above 30ms, Multimedia Redirection will not be used.

**Comment by akallabeth** [comment] 2016-11-05 09:55
@uplusplus Yes, that is the general direction. I'm aware that media redirection is still an option.
You pointed out the disadvantages of GFX (and H264) for that matter, still the problem is
* It is dependent on windows media player
* It requires the client to support multiple formats
* Bandwidth requirements are higher than with GFX options

Of course, if you have a very specific setup in mind it may still be the better option.

On a side note, the current aFreeRDP client has some bottlenecks you may encounter and would require some refactoring. (Use OpenGL and/or Vulcan to draw on screen)

**Comment by akallabeth** [comment] 2017-01-16 16:37
Closing as multimedia redirection is not planned for android.
Reopen if interest in providing a implementation exists.

**Closed by akallabeth** 2017-01-16 16:37 UTC

**Comment by sherwinkh** [comment] 2018-11-14 11:38
@akallabeth  Does Multimedia Redirection support in Windows server 2016？
