### ISSUE TITLE
Keyboard layout detection: doesn't works with gnome shell (or maybe it's wayland)

### ISSUE THREAD

**Issue by bbigras** [FreeRDP/FreeRDP#3553] opened 2016-10-13 20:49 UTC
It seems [freerdp_detect_keyboard_layout_from_xkb() uses xprop](https://github.com/FreeRDP/FreeRDP/blob/1855e36179fb197e713d41c4ef93e19cf1f0be2f/libfreerdp/locale/keyboard_x11.c#L51) and it doesn't seems to works on my computer. I'm using GNOME Shell 3.20.4 on Arch. I'm not sure if I'm using wayland or not (Xwayland and Xorg are running).

```
$ xprop -root _XKB_RULES_NAMES_BACKUP
_XKB_RULES_NAMES_BACKUP:  no such atom on any window.
```

**Comment by hendwolt** [comment] 2016-10-16 07:28
I tested this xprop command on Arch/openSUSE, KDE(Plasma5)/Gnome and X11/Wayland.

On all tested combinations the result is:

hendrik@linux-6380:~> xprop -root _XKB_RULES_NAMES_BACKUP
_XKB_RULES_NAMES_BACKUP:  no such atom on any window.
hendrik@linux-6380:~> xprop -root _XKB_RULES_NAMES
_XKB_RULES_NAMES(STRING) = "evdev", "microsoftpro", "de", "nodeadkeys", "terminate:ctrl_alt_bksp"
hendrik@linux-6380:~>

**Comment by zeppelinlg** [comment] 2017-06-22 15:29
I use xfreerdp with wayland (Gnome shell on arch) and my keymap (fr) is not detected. WIth Xorg it's working perfect.

**Comment by akallabeth** [comment] 2017-06-23 16:04
currently only X keyboard is supported, sadly no waland support yet. (scancode mapping that is)

**Comment by akallabeth** [comment] 2017-11-20 17:12
Basic xkbcommon keyboard handling for wayland has been merged.

**Closed by akallabeth** 2017-11-20 17:12 UTC

**Comment by bbigras** [comment] 2017-12-12 18:32
I just tested with 2.0.0-rc1 and it didn't detect the right layout. It detected "us" while it should be "cf" (french canadian).

```
[13:28:14:545] [4887:4888] [DEBUG][com.freerdp.locale] - display: 0x00007f0d640246b0
[13:28:14:545] [4887:4888] [DEBUG][com.freerdp.locale] - layouts: us
[13:28:14:545] [4887:4888] [DEBUG][com.freerdp.locale] - variants: 
[13:28:14:545] [4887:4888] [DEBUG][com.freerdp.locale] - group: 0
[13:28:14:545] [4887:4888] [DEBUG][com.freerdp.locale] - layout: us
[13:28:14:545] [4887:4888] [DEBUG][com.freerdp.locale] - variant: 
[13:28:14:545] [4887:4888] [DEBUG][com.freerdp.locale] - xkbLayout: us	xkbVariant: 
[13:28:14:545] [4887:4888] [DEBUG][com.freerdp.locale] - detect_keyboard_layout_from_xkb: 1033 (0x00000409X)
```

```
This is FreeRDP version 2.0.0-rc1 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EVENTFD_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=ON WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:              -march=native -O2 -pipe -fstack-protector-strong -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -msse2
Compiler:            GNU, 7.2.1
Target architecture: x64
```

**Comment by akallabeth** [comment] 2017-12-13 08:05
@bbigras Just had a look in ```xkbLayouts``` your specific layout is not supported (or wrongly mapped @awakecoding may shed some light on that). If you try one of the supported layouts it will work.

**Comment by maurerdietmar** [comment] 2026-04-15 10:22
I investigated this on a current system (GNOME 48 / Mutter 48.7, Xwayland 24.1.6, Debian Trixie) and the root cause
  is clear:                                                                                                            
                                                            
  Xwayland's actual XKB keymap is correct, but _XKB_RULES_NAMES on the root window is not.                             
                                                                                                                       
```
  $ xprop -root | grep XKB                                                                                             
  _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""         
```                                                   
 ```
                                                                                                                      
  $ xkbcomp :0 - 2>/dev/null | grep 'name\[group'                                                                      
      name[group1]="German";   
```                                                                                        
                                                                                                                       
  Mutter sends the correct compiled keymap to Xwayland via the XKB protocol, so xkbcomp reports German. But the        
  _XKB_RULES_NAMES property on the root window still says us.                                                          
                                                                                                                       
  FreeRDP's xf_detect_keyboard_layout_from_xkb() in client/X11/keyboard_x11.c reads _XKB_RULES_NAMES /                 
  _XKB_RULES_NAMES_BACKUP to determine the layout. It never looks at the actual compiled keymap, so it gets the wrong
  answer.                                                                                                              
                                                            
  The SDL3 client (client/SDL/SDL3/sdl_input.cpp:705-715) has the same gap -- it skips XKB entirely and only tries     
  freerdp_detect_keyboard_layout_from_system_locale(), which depends on LANG/LC_* rather than the keyboard layout.
                                                                                                                       
  Possible fix: Instead of (or in addition to) reading _XKB_RULES_NAMES, FreeRDP could query the active XKB keymap's   
  group name via XkbGetNames() with XkbGroupNamesMask and map the group name (e.g. "German") to an LCID. This would
  work correctly on both X11 and Xwayland.

**Comment by akallabeth** [comment] 2026-04-15 13:14
@maurerdietmar pull requests welcome. As for `sdl-freerdp`, would be great not to fall back to platform specific code.
