### ISSUE TITLE
v2.1.2: Can't connect to Windows7

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#6299] opened 2020-06-23 07:04 UTC
With xfreerdp2 in openSUSE (Leap15.1) I get the following:
[06:59:59:191] [4137:4138] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[06:59:59:192] [4137:4138] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[06:59:59:192] [4137:4138] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[06:59:59:192] [4137:4138] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[06:59:59:556] [4137:4138] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized
[06:59:59:599] [4137:4138] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[06:59:59:599] [4137:4138] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[07:00:00:959] [4137:4138] [WARN][com.freerdp.crypto] - Certificate verification failure 'unable to get local issuer certificate (20)' at stack position 0
[07:00:00:959] [4137:4138] [WARN][com.freerdp.crypto] - CN = my.windows.7.host
Password: 
[07:00:05:824] [4137:4138] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[07:00:05:824] [4137:4138] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
[07:00:05:848] [4137:4138] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[07:00:05:870] [4137:4138] [INFO][com.freerdp.channels.rdpsnd.client] - [static] Loaded fake backend for rdpsnd
[07:00:05:870] [4137:4138] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
[07:00:06:091] [4137:4138] [INFO][com.freerdp.client.x11] - Logon Error Info SESSION_ID [LOGON_MSG_SESSION_CONTINUE]
[07:00:09:055] [4137:4138] [WARN][com.freerdp.core.orders] - Invalid bmf 129
[07:00:09:055] [4137:4138] [ERROR][com.freerdp.core.update] - [0x01] PatBlt - update_read_dstblt_order() failed
[07:00:09:055] [4137:4138] [ERROR][com.freerdp.core.update] - order flags 0d failed
[07:00:09:055] [4137:4138] [ERROR][com.freerdp.core.fastpath] - Fastpath update Orders [0] failed, status 0
[07:00:09:055] [4137:4138] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update() - -1
[07:00:09:055] [4137:4138] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[07:00:09:055] [4137:4138] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -3
[07:00:09:055] [4137:4138] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[07:00:09:055] [4137:4138] [INFO][com.freerdp.client.common] - Network disconnect!
[07:00:09:055] [4137:4138] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor

when connecting this way:
xfreerdp /u:username /d:domain /f -clipboard -wallpaper /v:my.windows.7.host /rfx  /network:auto +fonts /gdi:hw

**Comment by akallabeth** [comment] 2020-06-23 07:35
@hendwolt thank you, already created #6300 that should address that.

**Comment by hendwolt** [comment] 2020-06-24 06:16
#6300 fixes this problem. Applied on top of 2.1.2.

**Comment by grosjo** [comment] 2020-06-24 20:00
Installed latest git. Same error

**Comment by akallabeth** [comment] 2020-06-25 07:17
@grosjo any specific version you have? `xfreerdp /version` or `xfreerdp /buildconfig` will tell you that.
This looks like you forgot to update.

**Comment by grosjo** [comment] 2020-06-25 08:06
# xfreerdp /buildconfig
This is FreeRDP version 3.0.0-dev (c205e75a2)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=ON WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=1 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=ON WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=ON WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=ON WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=ON WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=ON WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler:            GNU, 10.1.0
Target architecture: x64

**Comment by akallabeth** [comment] 2020-06-25 10:00
@grosjo is the output all you got? There is a warning missing that should be printed if this specific issue occurs.
Please retest and add the specific command line you have used.

**Comment by grosjo** [comment] 2020-06-26 07:07
@akallabeth using remmina

**Comment by akallabeth** [comment] 2020-06-26 07:32
@grosjo ok, and remmina is using the libraries you reference? Depending on installation method they ship their own copy of freerdp

**Comment by grosjo** [comment] 2020-06-26 07:33
it is all git based, recompiled by me

**Comment by akallabeth** [comment] 2020-06-26 07:40
@grosjo could you check where exactly the thing is failing in a debugger? I see no place (apart from broken input data) this could fail in the way your log suggests unless you use the wrong version)
Can´t reproduce locally with current master, only with the version before the commit.

**Comment by grosjo** [comment] 2020-06-29 13:16
I cleanup all freerdp libraries and all remmina code and re-compile and re-install
It is working again now, still disconnecting times to times (but was working like a charm before recent update)

**Comment by bmiklautz** [comment] 2020-07-20 11:30
Initial reported issue is fixed on master and is staged for 2.2.0. @grosjo if you still observe this problem please open a new issue for tracking. Thank you.

**Closed by bmiklautz** 2020-07-20 11:30 UTC
Labels: fixed-waiting-test
