### ISSUE TITLE
Orange RDP Session : Local framebuffer format  PIXEL_FORMAT_BGR16

### ISSUE THREAD

**Issue by meanbunny** [FreeRDP/FreeRDP#3709] opened 2017-01-18 21:09 UTC
Hey All,

I just installed a brand new Openbox (ArchLinux) desktop environment on a new machine. Cloned the latest source code in master. When I try to RDP into my machines everything is Orange. I noticed in the logging it says the following.

**My Command to connect** 
`xfreerdp /u:username /p:password /v:mmdesk3`

> [21917:21918] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGR16
>[16:03:13:589] [21917:21918] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16

I saw there was a /bpp: option and I tried setting it to 32 but everything looks super weird and still orange. The output when I do that is the following.
>[16:08:07:604] [22108:22109] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGR16
>[16:08:07:604] [22108:22109] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_ABGR32

I've also tried using the `/gdi:sw` and `/gdi:hw` switch and that still kept the screen orange. 

Any hints on what I might be missing here?

**Comment by akallabeth** [comment] 2017-01-19 07:41
you have a X server running with 16 bit color depth? that path is not widely tested, so it may be a simple change of color format to rgb16 for gdi init

**Comment by bmiklautz** [comment] 2017-01-19 12:58
@akallabeth, @meanbunny  I can easily reproduce this as well with Xephyr:
```bash
Xephyr :2 -ac -screen 800x600x16 
```
Seems that not only GDI but also rfx is affected (stride problem?)

**Comment by meanbunny** [comment] 2017-01-20 16:17
@akallabeth Awesome thank you!!! I went ahead and switched mine to 24 in my config and I can see clearly now

`Section "Monitor"
    Identifier             "Monitor0"
EndSection

Section "Device"
    Identifier             "Device0"
    Driver                 "nouveau" #Choose the driver used for this monitor
EndSection

Section "Screen"
    Identifier             "Screen0"  #Collapse Monitor and Device section to Screen section
    Device                 "Device0"
    Monitor                "Monitor0"
    DefaultDepth           24 #Choose the depth (16||24)
    SubSection             "Display"
        Depth              24
        Modes              "1024x768_75.00" #Choose the resolution
    EndSubSection
EndSection`

**Comment by bmiklautz** [comment] 2017-01-23 09:06
@meanbunny could you try pull request #3710 with 16 bit and verify that the behavior is there gone as well?

**Comment by bmiklautz** [comment] 2017-01-23 12:48
Should be fixed on current master. @meanbunny can you verify that this is also solved with 16 bit for you now?

**Comment by hendwolt** [comment] 2017-01-24 19:37
Since using the current master (as of yesterday evening) I see a lot of orange. Eventually the orange gets replaced widely with the real colors, but some elements like title bars or frames of dialog boxes are still orange. 
But setting the switch /gdi:sw solves this for me.

test systems:
- destination (server): Windows7 Professional
- clients running xfreerdp: openSUSE, 42.2/64bit + Tumbleweed/32bit

command with "orange" result:
xfreerdp /u:<username> /d:<domain> /f +clipboard -wallpaper /v:<ip>

output:
[20:15:20:107] [14204:14206] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[20:15:20:107] [14204:14206] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16

**Comment by akallabeth** [comment] 2017-01-25 07:35
@hendwolt I've had a look at that, #3721 should fix that one.

**Comment by hendwolt** [comment] 2017-01-25 16:38
Confirmed, my issue is fixed.
Thanks!

**Comment by bmiklautz** [comment] 2017-01-26 08:32
@hendwolt thanks for the feedback

**Closed** 2017-01-26 08:32 UTC
Labels: regression, waiting-feedback
