### ISSUE TITLE
Second monitor not showing FreeRDP

### ISSUE THREAD

**Issue by TeruYuuji** [FreeRDP/FreeRDP#4081] opened 2017-08-09 12:25 UTC
Hi All,
I'm using **FreeRDP version 2.0.0-dev**, from the source code here.
On Lubuntu based on **Ubuntu 16.04.3 LTS**, **kernel 4.8.0-36-generic**.

On the (Windows 2008r2) server I can see it has detected the second monitor, the FreeRDP window does not appear on my second screen.
At the start, I see a flicker on the second screen but 1 second later just the normal (Lubuntu) desktop.

When I try multi monitor or span, with different sub commands like  /multimon:force or with /monitor:0,1 or /span I get the same results.

I have compiled the source code with this command:

> cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_ALSA=ON -DCHANNEL_URBDRC_CLIENT=ON  -DCHANNEL_URBDRC=ON .

I'm not sure if I have missed a command.

_Before this I had run the FreeRDP version 1.1.0-beta1, which worked with dual monitor.
Only there I don't have the ability to share audio and add a disk to the server from the client.
(And USB redirection was also a reason to go to use the source code. )_

**Comment by hardening** [comment] 2017-08-09 21:41
IIRC you need to go fullscreen (/f)

**Comment by TeruYuuji** [comment] 2017-08-10 08:18
Fullscreen with one screen works on both monitors. But when I try /mulitmon or /span it does not. When I had the /f I get same results.

It seems to be connected to Openbox I found another thread where they are discussion the same issue,  I think [#2707](https://github.com/FreeRDP/FreeRDP/issues/2707).

**Comment by T3N4K4** [comment] 2017-08-10 08:33
@TeruYuuji the source from our company is currently in the devel branch. The master branch is just a clone of FreeRDP-master if that helps.

**Comment by TeruYuuji** [comment] 2017-08-10 08:52
@T3N4K4 Ahh that helps! Thanks.
I now get a windowed screen, but it is visible on multiple monitors.
Can I set it to always be on top and undecorated it by the cli?

**Comment by hardening** [comment] 2017-08-10 08:56
@TeruYuuji reading #2707 you have the answer to your bug: TLDR; Openbox is broken regarding modern fullscreen support, anyway there's a way to workaround it but nobody took time to do it. So it's up to you to do a contribution ;)

**Comment by T3N4K4** [comment] 2017-08-10 09:04
@hardening maybe someone could cherry pick https://github.com/RangeeGmbH/FreeRDP/commit/580fff3796d4c744334d0e3fed8f8bdf362f581e for FreeRDP-master. Otherwise I can create a new branch on base of FreeRDP-master instead and create a PR with the commit.

@TeruYuuji without decoration is -decorations. Always on top may only work with tools like wmctrl.

**Comment by hardening** [comment] 2017-08-10 09:11
@T3N4K4 the patch looks nice except that from what @nfedera said, you can detect that NET_WM_FULLSCREEN_MONITORS support is available. So that would be the equivalent of the OpenBox switch but automatically detected.

**Comment by T3N4K4** [comment] 2017-08-10 11:06
@hardening I will look into it, maybe I can make it happen.

**Comment by TeruYuuji** [comment] 2017-08-10 11:57
@hardening I'm not sure if I'm able to do, my knowledge is a bit limited. But I can always try. Thanks for your help. And also thank you @T3N4K4. Now I'm trying to combine things so I have the +openbox function and be able the get sound.

**Comment by T3N4K4** [comment] 2017-08-10 14:08
@hardening Does this do the trick?
https://github.com/RangeeGmbH/FreeRDP/commit/dd1f33bbf4e24a78f19380a336b2cb531accf1d7

**Comment by bmiklautz** [comment] 2017-08-16 07:36
@TaGUNil would you re-test with the latest master an verify that this fixes your issue?

**Comment by ppokhriyal** [comment] 2017-08-31 13:26
Hello,
i am using xfreerdp 2.0.0 Dev version. This is how my multi monitor is working

a) Get the list of monitors

xfreerdp /monitor-list

b) xfreerdp /cert-ignore /monitors:0 or 1 /multimon /u:USERNAME /d:DOMAIN /p:PASSWORD /v:IP-ADDRESS

hope this will help...

**Comment by akallabeth** [comment] 2017-11-17 13:12
Closing as duplicate of #2707 
2.0.0 release candidates (and master) got a lot of fullscreen / multimon fixes, reopen only if still an issue.

**Closed by akallabeth** 2017-11-17 13:12 UTC
Labels: waiting-feedback

**Comment by qureshia21014** [comment] 2018-03-27 19:54
Newbie to github & xfreerdp.  Please bear with me, I'm also not good at programming.

I know this issue is closed, but I'm getting a similar issue on my PC.  I'm running openSuse Leap 42.3 with the latest nightly build from the openSuse repo: freerdp-nightly-2.0-0+0.20180327303817.452~1.gita42f6d6aa.  This my first time using freerdp, I'm used to using KRDC for RDP sessions, but I wanted to try to use my second monitor.

Does anyone know if the multimon flag is supported on opensuse or should I try another distro?  I'm trying the same combinations as above, but I get the same results: 1 screen, but windows detects both monitors.  I've tried it on Windows 10, Server 2016, Server 2012 & 2008 all with the same results.  What I did notice was when I identify the 2nd monitor in windows, it flashes 1 on the screen.  I hope someone can direct me to try and resolve this.

Thanks.
