### ISSUE TITLE
wfreerdp flagged as trojan

### ISSUE THREAD

**Issue by hank0137** [FreeRDP/FreeRDP#6856] opened 2021-03-03 15:01 UTC
Windows 2016 Server.  Multiple types of trojans including Wacatac

From Windows Defender:

Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
file:C:\Program Files (x86)\Myrtille\bin\wfreerdp.exe
process:pid:2244,ProcessStart:132592571524409468

Get more information about this item online.

Using Myrtille version 2.9.1.

**Comment by akallabeth** [comment] 2021-03-03 16:12
Please report this as false positive, duplicate of #6336

**Closed by akallabeth** 2021-03-03 16:12 UTC
