### ISSUE TITLE
endless selection by mouse

### ISSUE THREAD

**Issue by nixargh** [FreeRDP/FreeRDP#2238] opened 2014-11-30 16:51 UTC
**Client:** xfreerdp 1.2.0-dev (git c9bc88d)
It's builded from master branch (commit c9bc88d5f0fed0de03ee697dd382ba8f8a434a82) with following parameters:
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_CUPS=ON -DCHANNEL_PRINTER=ON -DWITH_PULSE=ON .

**Server:** MS Windows 2008 R2

**Steps to reproduce:**
1. Run web browser, Chrome or FF for example.
2. Open some site with "long" page that can be scrolled down. I used lenta.ru (news site) for tests.
3. Push left mouse button and start to select site content from top to bottom.
Then you can release mouse button but selection and scrolling will go until site botom will be reached.

When i found a bug i was using FreeRDP from master branch commit eda6671b0679d6be9c858e9d2246d78ab20b8865. It was worth than on current version because selection of cells in MS Excel leads to endless selection and stuck of rdp session.

I should mention that this bug is not reproducible on Windows 2012 as i can see. Also it is not reproducible with microsoft remote desktop client.

**Comment by abma** [comment] 2016-08-03 14:17
i'm having this issue, too. to reproduce:

open libreoffice calc, click and hold the scroll down button. release the scroll button after a few seconds:

it scrolls forever down.

this happens on a low end (linux based) thin-client: the xorg server is at ~60% cpu and only killing xfreerdp makes it responsive again.

**Comment by abma** [comment] 2016-08-03 15:41
i tested on the same machine with a different linux distribution which uses a newer version of the linux kernel / xorg server: it takes a bit to recover but i couldn't reproduce the endless scroll problem.


(better) working xorg 1.18.3 & linux 4.4 (ubuntu 16.04)
not working: xorg 1.10.1 & linux 3.14.25

**Comment by nixargh** [comment] 2016-08-03 16:02
You should try Yatc with 2xclient, it works better. I'm not sure it will
help, but there is a chance.

**Comment by nixargh** [comment] 2016-08-03 16:31
Oh, sorry, wrong repository...

**Comment by akallabeth** [comment] 2016-10-20 17:06
Fixed with #3364 on master.

**Closed by akallabeth** 2016-10-20 17:06 UTC
