### ISSUE TITLE
Freerdp-2.0.0-rc4 not connect Windows Server 2003 R2

### ISSUE THREAD

**Issue by AJNik77** [FreeRDP/FreeRDP#5127] opened 2018-12-10 14:33 UTC
Command line: `$ xfreerdp /sec:rdp /u:admin /v:192.168.59.101:3389`
Result:
```
[17:07:26:144] [19810:19811] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[17:07:26:260] [19810:19811] [ERROR][com.winpr.timezone] - Unable to get current timezone rule
[17:07:29:580] [19810:19811] [ERROR][com.freerdp.core.license] - expecting BB_ENCRYPTED_DATA_BLOB blob
[17:07:29:580] [19810:19811] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[17:07:29:580] [19810:19811] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[17:07:29:623] [19810:19811] [ERROR][com.winpr.timezone] - Unable to get current timezone rule
[17:07:29:643] [19810:19811] [ERROR][com.freerdp.core.license] - expecting BB_ENCRYPTED_DATA_BLOB blob
[17:07:29:644] [19810:19811] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[17:07:29:644] [19810:19811] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[17:07:29:644] [19810:19811] [ERROR][com.freerdp.core] - freerdp_post_connect failed
```
Freerdp-2.0.0-rc2 connects without problems.
Freerdp-2.0.0-rc4 connects to servers Windows Server 2008 with the option `sec:rdp` without problems.

**Comment by akallabeth** [comment] 2018-12-10 14:36
Duplicate of #5101

**Comment by akallabeth** [comment] 2018-12-10 14:37
Please search closed issues before creating a new one.

**Closed by akallabeth** 2018-12-10 14:36 UTC
