### ISSUE TITLE
Frequent RDP disconnects with latest version 2.3.2

### ISSUE THREAD

**Issue by kaijday** [FreeRDP/FreeRDP#6943] opened 2021-04-08 09:26 UTC
**Describe the bug**
In FlatPak Remmina 1.4.12 (FreeRDP version 2.3.1) for the first time, I stopped suffering frequent disconnects when either using a different application quickly (e.g sending an email in Geary) or walking away from PC to make a drink. (auto-connect attempt before disconnecting).
1.4.12 also stopped an issue whereby I had to clear the FreeRDP cache before I could connect again (otherwise I get a Can't connect error).
Since the update to 1.4.13 (FreeRDP version 2.3.2) both of these issues have come back again. I have downgraded back to 1.4.12 and can confirm the issues have gone away again so there is an issue with the latest version.

The FlatPak devs downgraded the FreeRDP version on 1.4.13 and all is good again, so issue appears to be a FreeRDP change in the latest 2.3.2 release.

**To Reproduce**
1. Go to 'Connect to RDP via Gateway connection'
2. Leave inactive for a minute - two minutes
3. Get the reconnecting issue and then can't reconnect if you don't wiggle mouse
4. Attempt to reconnect, can't.
5. Have to clear known_hosts2 and restart Remmina for it to connect again. Which is super annoying.

**Expected behavior**
Connection to stay open when left for a minute or two.

**Application details**
* FreeRDP version (`xfreerdp /version`) - 2.3.2
* Command line used - No, Flatpak so FreeRDP bundled within Remmina app.
* OS version connecting to (server side) - Windows 10 Enterprise.

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Windows/Android/..] - Linux
 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10] - Ubuntu 20.10
 - Architecture: [amd64, arm]: - amd64

Issue in GitLab I originally raised for Remmina - https://gitlab.com/Remmina/Remmina/-/issues/2462

**Comment by akallabeth** [comment] 2021-04-08 11:14
@kaijday ok, could you add some more information for this? 
1. Log files of your connections
2. Command line/remmina configuration for the connection
3. what are you connecting to? (server OS, gateway OS, ...)

**Comment by akallabeth** [comment] 2021-04-13 06:05
Ok, checked:
1. Direct connections (windows 10)
2. Gateway connections (rpc/http/websocket) (windows server 2016 setup)
3. Manual code comparison

long story short, there are no changes regarding autoreconnect, so if this really is a freerdp issue please provide some logs.
until more data is provided I´ll consider this resolved invalid.

btw, removing `known_hosts2` is a common superstition, I´d really love to know how that one came to be. The only reason why you might not be able to connect is because the server certificate changed, and that is exactly what this file is there for.

**Closed by akallabeth** 2021-04-13 06:05 UTC
Labels: waiting-feedback

**Comment by kaijday** [comment] 2021-04-13 07:34
@akallabeth How do I get to the logs for FreeRDP from Flatpak bundled Remmina app?

There's definitely an issue, and having been using broken Remmina for 6 months now removing known_hosts2 definitely works. Suddenly as of the last release all was good, I don't get disconnected all the time (I don't even get the "reconnecting" scren, the connection just stays open like it would if I was using RDP on Windows) and I don't have to clear known_hosts2 to reconnect.

**Comment by akallabeth** [comment] 2021-04-13 07:48
@kaijday ok, could you try to reproduce with `xfreerdp` or just add the remmina config to the issue? This sounds really weired as `known_hosts2` has not been modified for ~6years and it does exactly what it is supposed to do, so maybe there is something else going on?
Also, are you connecting directly or with a gateway/broker setup?

**Comment by akallabeth** [comment] 2021-04-13 07:57
as for logging:
1. set `FreeRDP log level` to `DEBUG` in remmina 
2. quit remmina (check the systray icon is no longer there)
3. run (from a terminal) `flatpak run org.remmina.Remmina 2>&1 |tee log.txt`
4. run your session
5. quit remmina

now you have a log file with all messages from the remmina session
