### ISSUE TITLE
winpr/event: Uses too many file descriptor

### ISSUE THREAD

**Issue by DavBfr** [FreeRDP/FreeRDP#3697] opened 2017-01-11 19:53 UTC
For thread synchronization between RDP channels, lot of events objects are created, that result in a lot of file descriptor opened.

Recent macOS starting from 10.11 allow only 256 open files per process. This limit can be reached with lot of channels like disk redirection, smart-cards, etc.

An other way to implement thread synchronization and intra process communication could help.

**Comment by bmiklautz** [comment] 2017-01-16 09:53
@DavBfr 256 is chosen pretty low imho. Under the hood using IPC isn't easily possible as it can't be (at least not with a lot of extra effort) integrated within the mechanism winpr uses. An example would be WaitForMultipleObjects with eventfd (or similar on mac) select or poll can be used to watch all events at once without having any busy waiting. But with IPC some extra mechanism would be required.

For now I suggest to increase the open file limit.

**Comment by hardening** [comment] 2023-06-15 21:40
Nothing we can do, using fd is by design. Closing.

**Closed by hardening** 2023-06-15 21:40 UTC
