### ISSUE TITLE
new warning -Wlto-type-mismatch with LTO enabled (gcc8)

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#5358] opened 2019-04-23 19:04 UTC
The openSUSE project is planning to use LTO (Link Time Optimization). So I tried to build version 2.0.0-dev5 (df280a7ff) for openSUSE Tumbleweed with LTO by adding "-flto=4" to the CFLAGS. Basically it worked, but I got a new warning:
...
[   76s] [ 93%] Linking C shared library libfreerdp-shadow2.so
[   77s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:37:13: warning: type of 'smartcard_DeviceServiceEntry' does not match original declaration [-Wlto-type-mismatch]
[   77s]  extern UINT smartcard_DeviceServiceEntry(void);
[   77s]              ^
[   77s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/smartcard/client/smartcard_main.c:724:6: note: type mismatch in parameter 1
[   77s]  UINT DeviceServiceEntry(PDEVICE_SERVICE_ENTRY_POINTS pEntryPoints)
[   77s]       ^
[   77s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/smartcard/client/smartcard_main.c:724:6: note: type 'struct DEVICE_SERVICE_ENTRY_POINTS *' should match type 'void'
[   77s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/smartcard/client/smartcard_main.c:724:6: note: 'smartcard_DeviceServiceEntry' was previously declared here
...

**Comment by hendwolt** [comment] 2019-04-23 19:05
The complete build log:
[osTWbuild_lto.zip](https://github.com/FreeRDP/FreeRDP/files/3109177/osTWbuild_lto.zip)

**Comment by jiridanek** [comment] 2022-04-29 09:17
Retrying with newer GCC might resolve the warning. I saw this warning in my project with GCC 8.5 and it went away when I use GCC 12. Looking at the OpenSUSE build at https://build.opensuse.org/package/view_file/X11:RemoteDesktop/freerdp/freerdp.spec?expand=1, looks like LTO is currently disabled there. If I try to enable it and rebuild, I don't see the warning any more

My build logfile from https://build.opensuse.org/build/home:jdanek:branches:X11:RemoteDesktop/openSUSE_Tumbleweed/x86_64/freerdp/_log can be viewed at 
[freerdp_os_tumbleweed_flto_auto.txt](https://github.com/FreeRDP/FreeRDP/files/8589714/freerdp_os_tumbleweed_flto_auto.txt)

**Comment by hendwolt** [comment] 2022-05-15 18:19
@jiridanek : openSUSE only ships freerdp 2.*. The type mismatch occurs in the master branch alias freerdp3. 
I checked the build log after openSUSE switched the default compiler for Tumbleweed to gcc12 and the type mismatch warning is still there; in freerdp3.

**Comment by akallabeth** [comment] 2023-07-31 08:44
@hendwolt I compiled here on fedora 38 with `clang-16` as well as `gcc 13.1.1` and did not get any `lto-type-mismatch` warnings.
closing, repoen if you can still reproduce.

**Closed by akallabeth** 2023-07-31 08:44 UTC
