### ISSUE TITLE
xfreerdp crashes the xorg session under xrdp running on RHEL/CentOS >7.5

### ISSUE THREAD

**Issue by Mikky83** [FreeRDP/FreeRDP#6290] opened 2020-06-17 15:57 UTC
Xorg under xrdp crashes every time when xfreerdp session to windows systems is closed/disconnected. On some specific windows systems crashes immediately after opening the RDP session.
Native remote desktop client "vinagre" doesn't have this problem and works fine with windows RDP sessions.
xorg crashes with "Segmentation fault at address 0x38"

Bug is still with status "open" in bugzilla
https://bugzilla.redhat.com/show_bug.cgi?id=1659113 

I'm using the following cobination:
CentOS/RHEL 7.8

freerdp-libs-2.0.0-4.rc4.el7_8.x86_64
freerdp-2.0.0-4.rc4.el7_8.x86_64
xorg-x11-server-Xorg-1.20.4-10.el7.x86_64
xrdp-0.9.13-2.el7.x86_64

RHEL/CentOS <= 7.5 works fine.

**Comment by akallabeth** [comment] 2020-06-18 05:29
@Mikky83 just as the referenced issue tells, this looks like a bug in the X server used with RHEL/CentOS.
You could, of course, try to compile current FreeRDP and check if that makes any difference (I doubt it, the X11 part has not been changed in ages)

**Comment by ondrejholy** [comment] 2020-06-18 06:37
I would like to mention that the reproducer doesn't work for me. Also I found similar crash reports caused by tigervnc and x2go, so I suppose that there is something wrong with xserver. So there is no point to report it here. We need some feedback from xserver maintainers...

**Comment by akallabeth** [comment] 2020-06-18 06:49
@ondrejholy thank you for the update. Closing this then as 'nothing we can do' :'(

**Closed by akallabeth** 2020-06-18 06:49 UTC
Labels: waiting-feedback

**Comment by Mikky83** [comment] 2020-06-18 09:24
@ondrejholy it's really easy to reproduce it. You need to install the mentioned packages and set xrdp to work with xorg. Then when you try to open windows RDP session with xfreerdp you will see the behaviour. On some windows distributions you can connect, but you will see the behaviour when you close the xfreerdp session.
btw, when you use xrdp with xvnc, everything works fine.

**Comment by ondrejholy** [comment] 2020-06-18 10:14
@Mikky83 that's exactly what I have tried before some time and everything worked fine. But anyway it is xserver what crashes, not freerdp, and I don't know how to debug xserver. Also it started happening in RHEL 7.6 as per the report, but there were no functional changes on freerdp side for RHEL 7.6. So we need feedback from xserver developers first...

**Comment by Mikky83** [comment] 2020-06-19 07:25
@ondrejholy Many thanks for your feedback. If you still keep the machine on which you tried to recreate the issue, I would like to ask you to share the output of all installed packages + xrdp configuration. If you didn't have the same issue with xfreerdp, it makes me think that it might be related with some other package.
Anyway if you say that xfreerdp doesn't need to be changed after changes with xorg-x11 package in redhat, then it's fine for me.
