### ISSUE TITLE
Support for IOCHARSET other than UTF-8 for filenames

### ISSUE THREAD

**Issue by sh-dvl** [FreeRDP/FreeRDP#4646] opened 2018-05-14 09:52 UTC
when a shared-folder (or one of its sub-folders) have a file with iso8859-encoding like "Vorfälle.txt" ('ä' == '\xe4') this and all following(!!!) files won't be shown in Windows (which sometimes leads to directories, which seems to be empty but aren't)

normally there shouldn't be any files with such an encoding, but sometimes they are and the standard-users are not always able to have a look at the directory directly on linux to identify and rename such files.

we're using remmina on linux as interface, so we can't switch any config-items for testing, but we believe that we've traced the problem down to libwinpr:

in file/generic.c in function FindNextFileW() the function ConvertToUnicode() is called for every filename and if this function returns a zero-lenght, the function returns false with OOM-error

unfortunately other errors might have occured: ConvertToUnicode() is a wrapper to MultiByteToWideChar(), which itself either calls u_strFromUTF8() (if WITH_ICU=on) or ConvertUTF8toUTF16() (if WITH_ICU=off) for conversion.

we've compiled freerdp with ICU=off, so let's look what happens there:
ConvertUTF8toUTF16()  is called with "strictConversion" from MultiByteToWideChar()
it looks at trailingBytesForUTF8 for the utf8-length and get 2 for '\xe4' and then checks the possible utf8-char via isLegalUTF8(length=2+1). Because '\xe4' is not between 0x80 and 0xbf, it returns false and so ConvertUTF8toUTF16() returns "sourceIllegal", which isn't checked at all.

but even if we've compiled it with ICU=on, nothing would change:
if u_strFromUTF8() see a unconvertible character it stops and returns U_INVALID_CHAR_FOUND via a pointer. Even here the error is completly ignored by MultiByteToWideChar().
either this should be checked, or u_strFromUTF8WithSub() should be called.

but also in ConvertUTF8toUTF16() there seems to be a solution coded, if strictConversion isn't set: in line 579 there'll be a UNI_REPLACEMENT_CHAR written to target.
unfortunately it wouldn't help to siimply deactivate strictConversion, because the call to isLegalUTF8 is done either and I'm not as familar with the code to see, if this change would break other things.

Nevertheless, the current behaviour is wrong (not showing files at all)
Right behaviour would be to either leave unrecognized chars as is, or replace them by the UNI_REPLACEMENT_CHAR
(I think it should depend on the reverse way, what happens, when the file with bad encoding is accessed - which we've not traced, yet: the file should not only be seen in filelist, but accessible, despite of its bad name)

**Comment by akallabeth** [comment] 2018-05-14 09:58
@sh-dvl The support for encodings other than UTF-8 is mostly non existent. Are you using a UTF-8 compatible locale?

**Comment by akallabeth** [comment] 2018-05-14 10:04
Also we're missing versions you worked with. Just tested with master and I have not seen any issues with non ASCII characters. locale is `en_US.UTF-8`

**Comment by sh-dvl** [comment] 2018-05-14 10:12
yes, we're using utf8 as standard-encoding, but there are many disks/filetrees in use, which are quite old or in private use, so we won't be able to prevent access to files with such old encodings.

new files on those disks/trees are written with right encodings, but maybe not accessible afterwards, due the break of the whole tree

freerdp/remmina are fresh compiled from github cloned at 20180509.
xfreerdp shows version 2.0.0-dev3 (7eb12bb)
(any possibility to look at that via remote-shell?)

**Comment by akallabeth** [comment] 2018-05-14 10:52
@sh-dvl Ok, looks like the filename reading in `readdir` is at fault here, we need to figure out the (correct) encoding before converting.

**Comment by akallabeth** [comment] 2018-05-14 11:45
@sh-dvl your answer regarding `utf-8` is somewhat ambigous, do you use it as `locale` or just for new entries in the filesystem? `readdir` should return strings in current locale if I did not misinterpret.

**Comment by akallabeth** [comment] 2018-05-14 11:59
@sh-dvl Ok, just verified. Creating a file `äᠦলⲈ` will have the following output with locales:
* `en_US.UTF-8` (and every other `*.UTF-8` locale): `äᠦলⲈ`
* `en_US`: `äᠦল��'$'\210`
* `C`: `'$'\303\244\341\240\246\340\246\262\342\262\210`

so, if you have the client system running a UTF-8 locale your issue should not occur.

**Comment by sh-dvl** [comment] 2018-05-15 21:11
thanks for your activity within short time.

unfortunately the issue occures with LANG=de_DE.UTF-8.

I'll put two pics from a test-folder, one on linux, where you can see all files and one from windows, where many files are missing, not only those, which have the wrong encoding.

another error occures in windows, if there's only a file with bad-encoding: the whole access to the folder is denied...

**Comment by sh-dvl** [comment] 2018-05-15 21:18
sorry, can't upload any files here.
(tried it as png, jpg and zip)

**Comment by akallabeth** [comment] 2018-05-16 12:16
@sh-dvl Ok, did manage to reproduce with old `fat` filesystem and manually mounting with a `iocharset`.
One way to solve could be some fallback to codepages to try to convert.

**Comment by CKD4XXH** [comment] 2018-11-13 21:44
So, does Remmina (and/or Rreerdp) support locales with encodings other than UTF-8?
(Or, is limited to UTF-8?)

It would be very welcome to support at least 8bit encodings (ISO-8859-*).

For example, via
G_FILENAME_ENCODING=UTF8,iso88592
environment variable.

The shared folder's file list, as seen through RDP, in the remote machine's file manager, is (silently, and even not necessarily apparently) truncated. (Local locale is non-UTF8 encoded.)

**Comment by akallabeth** [comment] 2018-11-13 22:37
No, we only test utf8, everything else is a case of good luck.

**Comment by mfu13** [comment] 2020-12-02 09:10
i m having same problem with special chars, is there any progress about the issue?

**Comment by akallabeth** [comment] 2020-12-02 09:28
@mfleisz no, this is simply put no use case we are testing or interested in.
Pull requests are very welcome, but we will invest no time in legacy encoding support.

**Comment by akallabeth** [comment] 2024-08-20 09:19
closing as this is a usage error.
mount your filesystems properly (aka without any ancient codepage settings), then this is a non issue.

**Closed by akallabeth** 2024-08-20 09:19 UTC
Labels: feature, help-wanted
