### ISSUE TITLE
Latetst aFreeRDP android client is having display issues when RDPing to 2008 machine with remoteFx enabled

### ISSUE THREAD

**Issue by chandramouligoru** [FreeRDP/FreeRDP#3527] opened 2016-10-07 09:49 UTC
Display is fragmented with white blocks when RDPing to 2008 machine with remoteFx enabled. Where as it is working fine with 2011 machines. Working well with 2008 machines as well If remoteFx is disabled though. Any idea on whats missing here.

**Comment by akallabeth** [comment] 2016-10-09 13:37
@chandramouligoru I've seen similar issues, looks like one decoding path for ClearCodec is the cause for that.

**Comment by chandramouligoru** [comment] 2016-10-12 11:13
@akallabeth When will the fix be available in master?

**Comment by akallabeth** [comment] 2016-10-12 11:17
@chandramouligoru When I've time and can pinpoint the exact issue. What I can say this far is that something in ```clear_decompress``` is not working as expected under certain conditions.

**Comment by akallabeth** [comment] 2016-10-28 06:40
@chandramouligoru Just created #3580 to trace the issue a bit further. Could you give it a try and have a look where the decoding aborts?

**Comment by akallabeth** [comment] 2016-10-28 10:09
Ok, managed to pinpoint the issue to a specific part of ClearCodec: ```clear_decompress_bands_data``` fails when connecting to windows 8 with ```/gfx:avc420```

**Comment by akallabeth** [comment] 2017-01-13 10:25
Client side fixed with #3702. Remainig issues seem to be server specific (black rectangles with windows 8 and 10)

**Comment by akallabeth** [comment] 2017-01-18 13:31
closing as pull is merged.
Reopen if still broken.

**Closed by akallabeth** 2017-01-18 13:31 UTC
Labels: android, fixed-waiting-test, ios, regression, x11-client
