### ISSUE TITLE
Slow video connection to Win2016

### ISSUE THREAD

**Issue by maddeer** [FreeRDP/FreeRDP#4072] opened 2017-08-04 11:22 UTC
I`ve tried to use last build of freerdp on linux. And I`ve got the problem. 
When I connect to Win2016 I can`t watch any action content. 
It looks like slide show with broken pixels. 
Connection to win2012 works good and I can watch even videos without problem. 

build from 48163a27dbbaa73c149c7df2c1a3e9afb3d3c34a works with win2016 good 
2.0.0-rc0 and last master have this problem 

my build options 
cmake -C /var/tmp/portage/kraftway/freerdp-2.0.0.1707250000/work/freerdp-2.0.0.1707250000_build/gentoo_common_config.cmake -G Unix Ma
kefiles -DCMAKE_INSTALL_PREFIX=/usr -DWITH_ALSA=yes -DWITH_CLIENT=yes -DWITH_CUPS=yes -DWITH_DEBUG_ALL=no -DWITH_MANPAGES=no -DWITH_F
FMPEG=yes -DWITH_LIBAVCODEC=yes -DWITH_GSTREAMER_1_0=no -DWITH_JPEG=yes -DWITH_NEON=no -DWITH_PULSE=yes -DWITH_SERVER=no -DWITH_PCSC=
yes -DWITH_LIBSYSTEMD=no -DWITH_SSE2=yes -DCHANNEL_URBDRC=yes -DWITH_X11=yes -DWITH_XINERAMA=yes -DWITH_XV=yes -DBUILD_TESTING=no -DW
ITH_WAYLAND=no -DWITH_OPENH264=no -DWITH_X264=no

my connect options 
xfreerdp /cert-ignore /f /bpp:16 -sec-nla /sound:sys:alsa /microphone:sys:alsa /rfx  /gfx /u:user /p:pass /v:IP

**Comment by realjiangms** [comment] 2017-08-06 11:11
This is issue in win2016 instead of FreeRDP. Win2016 seems no longer support avc420 for unknown reason, regardless how you configure the group policy.
So for this guy, use /gfx:AVC444 instead.

**Comment by maddeer** [comment] 2017-08-07 09:09
I don`t think so. 
The build of xfreerdp from the end of May still works good with /gfx:RDP and win2016 
New builds ALL have the same problem

**Comment by maddeer** [comment] 2017-08-07 09:12
and  /gfx:AVC444 or /gfx:AVC420 did not fix the problem

**Comment by maddeer** [comment] 2017-08-07 12:04
looks like the problem is in 88fa1312480cc1c6061d06bcb2a077af8cd90e4e commit 
git log says: 
```

commit 88fa1312480cc1c6061d06bcb2a077af8cd90e4e
Author: Armin Novak <armin.novak@thincast.com>
Date:   Wed Jul 19 11:36:28 2017 +0200

    Fixed variable assignment.

commit 4137282491562b5120c6591bded6f74ca125c1ca
Merge: f0fb219 3893058
Author: Bernhard Miklautz <bmiklautz@users.noreply.github.com>
Date:   Wed Jul 19 11:24:57 2017 +0200

    Merge pull request #4047 from akallabeth/win_gfx_fix
    
    Always use software GFX for windows client.

```
4137282491562b5120c6591bded6f74ca125c1ca works good
88fa1312480cc1c6061d06bcb2a077af8cd90e4e already broaken 

but reverting this patch in last builds brakes the h264 context 
```
[14:53:30:172] [20139:20140] [ERROR][com.freerdp.core.codecs] - Failed to create h264 codec context
[14:53:30:172] [20139:20140] [ERROR][com.freerdp.gdi] - failed to initialize gdi
[14:53:30:172] [20139:20140] [ERROR][com.freerdp.core] - freerdp_post_connect failed
[14:53:30:172] [20139:20140] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_POST_CONNECT_FAILED [0x00020003]
[14:53:30:172] [20139:20140] [ERROR][com.freerdp.client.x11] - Freerdp connect error exit status 1
```

**Comment by realjiangms** [comment] 2017-08-07 19:08
I will test latest master these days. I'm still using version of Jun 10

**Comment by akallabeth** [comment] 2017-08-08 13:10
@maddeer The referenced commit only affects connections with ```AVC420/AVC444```, the command line you provided uses ```RFX/GFX``` codec.
Could you post the output of ```xfreerdp /buildconfig``` your configuration options look weird (does CMake allow useing yes/no?)

**Comment by maddeer** [comment] 2017-08-08 13:15
This is FreeRDP version 2.0.0-dev (git n/a)
Build configuration: BUILD_TESTING=no BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EVENTFD_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=yes WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=yes WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=yes WITH_DEBUG_ALL=no WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=yes WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=no WITH_IPP=OFF WITH_JPEG=yes WITH_KRB5=OFF WITH_LIBAVCODEC=yes WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=no WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=no WITH_MBEDTLS=OFF WITH_NEON=no WITH_OPENH264=no WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=yes WITH_PROFILER=OFF WITH_PULSE=yes WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=no WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=yes WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=no WITH_X11=yes WITH_X264=no WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=yes WITH_XKBFILE=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=yes WITH_ZLIB=ON
Build type:          Gentoo
CFLAGS:              -Os -mtune=i686 -march=i686 -pipe  -march=i686 -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -msse2
Compiler:            GNU, 4.9.3
Target architecture: x86

**Comment by maddeer** [comment] 2017-08-08 13:20
the cmake options made by gentoo ebuild and cmake.eclass

**Comment by akallabeth** [comment] 2017-08-09 06:55
@maddeer Only difference in GFX channel I can spot is that with the newer version the more recent capability sets are announced. Could you try if the issue persists if you edit ```channels/rdpgfx/client/rdpgfx_main.c:127``` and add ```pdu.capsSetCount = 2;```?

**Comment by realjiangms** [comment] 2017-08-09 13:31
@akallabeth As my understanding, we have another difference:
Originally, if we don't have AVC444, the cap sets will not include version10 with AVC disabled flag.
Now, if we don't have AVC444 in the commandline argument, the capset will have version103 with AVC disabled flag.
Not sure whether it is expected, and whether it impacts the codec chosen by windows server.

@maddeer
I would recommend to have /log-level:DEBUG and grep RecvWireToSurface1Pdu to check what codec is used.

**Comment by maddeer** [comment] 2017-08-09 13:43
@realjiangms 

root@ktl-188[16:39]:~/KTL/scripts# grep RecvWireToSurface1Pdu ~/error2                                                               
[16:36:14:857] [28160:28175] [DEBUG][com.freerdp.channels.rdpgfx.client] - RecvWireToSurface1Pdu: surfaceId: 0 codecId: RDPGFX_CODECI
D_CLEARCODEC (0x0008) pixelFormat: 0x20 destRect: left: 0 top: 1024 right: 64 bottom: 1080 bitmapDataLength: 35
[16:36:14:993] [28160:28175] [DEBUG][com.freerdp.channels.rdpgfx.client] - RecvWireToSurface1Pdu: surfaceId: 0 codecId: RDPGFX_CODECI
D_CLEARCODEC (0x0008) pixelFormat: 0x20 destRect: left: 0 top: 1024 right: 64 bottom: 1080 bitmapDataLength: 35
[16:36:14:070] [28160:28175] [DEBUG][com.freerdp.channels.rdpgfx.client] - RecvWireToSurface1Pdu: surfaceId: 0 codecId: RDPGFX_CODECI
D_CLEARCODEC (0x0008) pixelFormat: 0x20 destRect: left: 0 top: 1024 right: 64 bottom: 1080 bitmapDataLength: 35
[16:36:14:141] [28160:28175] [DEBUG][com.freerdp.channels.rdpgfx.client] - RecvWireToSurface1Pdu: surfaceId: 0 codecId: RDPGFX_CODECI
D_CLEARCODEC (0x0008) pixelFormat: 0x20 destRect: left: 704 top: 512 right: 768 bottom: 576 bitmapDataLength: 134
[16:36:14:141] [28160:28175] [DEBUG][com.freerdp.channels.rdpgfx.client] - RecvWireToSurface1Pdu: surfaceId: 0 codecId: RDPGFX_CODECI
D_CLEARCODEC (0x0008) pixelFormat: 0x20 destRect: left: 832 top: 512 right: 1216 bottom: 640 bitmapDataLength: 6176
[16:36:14:145] [28160:28175] [DEBUG][com.freerdp.channels.rdpgfx.client] - RecvWireToSurface1Pdu: surfaceId: 0 codecId: RDPGFX_CODECI
D_CLEARCODEC (0x0008) pixelFormat: 0x20 destRect: left: 768 top: 576 right: 832 bottom: 640 bitmapDataLength: 1674
[16:36:14:145] [28160:28175] [DEBUG][com.freerdp.channels.rdpgfx.client] - RecvWireToSurface1Pdu: surfaceId: 0 codecId: RDPGFX_CODECI
D_CLEARCODEC (0x0008) pixelFormat: 0x20 destRect: left: 0 top: 1024 right: 64 bottom: 1080 bitmapDataLength: 35
[16:36:15:204] [28160:28175] [DEBUG][com.freerdp.channels.rdpgfx.client] - RecvWireToSurface1Pdu: surfaceId: 0 codecId: RDPGFX_CODECI
D_CLEARCODEC (0x0008) pixelFormat: 0x20 destRect: left: 968 top: 542 right: 969 bottom: 543 bitmapDataLength: 32
[16:36:15:204] [28160:28175] [DEBUG][com.freerdp.channels.rdpgfx.client] - RecvWireToSurface1Pdu: surfaceId: 0 codecId: RDPGFX_CODECI
D_CLEARCODEC (0x0008) pixelFormat: 0x20 destRect: left: 953 top: 543 right: 961 bottom: 551 bitmapDataLength: 235
[16:36:15:204] [28160:28175] [DEBUG][com.freerdp.channels.rdpgfx.client] - RecvWireToSurface1Pdu: surfaceId: 0 codecId: RDPGFX_CODECI
D_CLEARCODEC (0x0008) pixelFormat: 0x20 destRect: left: 963 top: 543 right: 972 bottom: 552 bitmapDataLength: 72
[16:36:15:206] [28160:28175] [DEBUG][com.freerdp.channels.rdpgfx.client] - RecvWireToSurface1Pdu: surfaceId: 0 codecId: RDPGFX_CODECI
D_CLEARCODEC (0x0008) pixelFormat: 0x20 destRect: left: 943 top: 539 right: 951 bottom: 549 bitmapDataLength: 283
[16:36:15:206] [28160:28175] [DEBUG][com.freerdp.channels.rdpgfx.client] - RecvWireToSurface1Pdu: surfaceId: 0 codecId: RDPGFX_CODECI
D_CLEARCODEC (0x0008) pixelFormat: 0x20 destRect: left: 942 top: 543 right: 943 bottom: 549 bitmapDataLength: 47
[16:36:15:206] [28160:28175] [DEBUG][com.freerdp.channels.rdpgfx.client] - RecvWireToSurface1Pdu: surfaceId: 0 codecId: RDPGFX_CODECI
D_CLEARCODEC (0x0008) pixelFormat: 0x20 destRect: left: 953 top: 543 right: 961 bottom: 551 bitmapDataLength: 67

@akallabeth I don't have time right now to build. I'll try it some time later.

**Comment by maddeer** [comment] 2017-08-09 16:49
@akallabeth 
maybe I did some thing wrong but for the commit 1648deb435ad52206f7aa2afe4b4dff71d9329bc 
your patch did not gave me to connect 
```
[19:46:01:398] [28720:28721] [INFO][com.freerdp.core] - ERRINFO_GRAPHICS_SUBSYSTEM_FAILED (0x0000112F):The server-side graphics subsystem is in an error state and unable to continue graphics encoding.
[19:46:01:398] [28720:28721] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
[19:46:01:398] [28720:28721] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[19:46:01:398] [28720:28721] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor

```

**Comment by akallabeth** [comment] 2017-08-09 17:36
now looks like a server configuration issue. does this setup work with gfx and another client?

**Comment by akallabeth** [comment] 2017-08-10 06:47
@realjiangms True, but since the only server os family supporting AVC420 is based on windows 8.1 (earlier and later do not support it) it won't make a real difference.
@maddeer So, you added the line in the current master and that is the error you get? Seems like something is not working correct on the server side as well. I assume your original command line is the one you tried?

**Comment by maddeer** [comment] 2017-08-10 09:09
@akallabeth 
xfreerdp /cert-ignore /f /bpp:16 -sec-nla /sound:sys:alsa /microphone:sys:alsa /rfx /gfx /u:user /p:pass /v:IP 

yes, just added your line 
```

--- channels/rdpgfx/client/rdpgfx_main.c.old    2017-08-10 12:05:48.746145880 +0300
+++ channels/rdpgfx/client/rdpgfx_main.c        2017-08-09 19:43:31.378935252 +0300
@@ -124,7 +124,7 @@
 
        if ((error = rdpgfx_write_header(s, &header)))
                goto fail;
-
+       pdu.capsSetCount = 2; 
        /* RDPGFX_CAPS_ADVERTISE_PDU */
        Stream_Write_UINT16(s, pdu.capsSetCount); /* capsSetCount (2 bytes) */
 
```
without this line everything connects 
with this line doesn't connect even to the win2012

**Comment by maddeer** [comment] 2017-08-10 09:11
but it connects to the win2008r2

**Comment by akallabeth** [comment] 2017-08-10 14:05
@maddeer The patch lets the client announce only GFX windows 8 and 8.1 capabilities. Looks like there is some server setup broken (RFX graphics adapter working correctly?)

**Comment by maddeer** [comment] 2017-08-10 14:40
This servers are vmware VPS with default settings.

**Comment by akallabeth** [comment] 2017-08-10 14:47
@maddeer Ok, got it, the patch must be before ```header.pduLength``` is set, that is line 114. damned typo :/

**Comment by maddeer** [comment] 2017-08-10 15:30
@akallabeth  now it works but nothing changes
Now I see this ERROR in log 
```
[18:27:28:452] [1602:1603] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[18:27:28:455] [1602:1603] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel audin
[18:27:28:455] [1602:1603] [INFO][com.freerdp.channels.audin.client] - Loaded alsa backend for audin
[18:27:28:455] [1602:1603] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel urbdrc
[18:27:28:455] [1602:1603] [ERROR][com.freerdp.channels.urbdrc.client] - error processing arguments
[18:27:28:455] [1602:1614] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded alsa backend for rdpsnd

```

**Comment by maddeer** [comment] 2017-08-10 15:31
maybe it nothing meters. 
But I don't see it in win2012

**Comment by akallabeth** [comment] 2017-08-11 07:38
@maddeer so you added ```/usb``` to the command line with an invalid syntax? Please try to focus on the RFX/GFX issue here, eliminate all unnecessary command line options for your tests.

**Comment by maddeer** [comment] 2017-08-11 08:59
Sorry, but with minimal options that I showed up here  nothing changed. Slide show and broken pixels.

**Comment by akallabeth** [comment] 2017-08-11 09:15
@maddeer Looks like we're missing some essentail detail. Just tried a connection to a Windows-Server-2016-Essentials with AVC444 and GFX (client is current master) and there have been no screen artifacts and the performance was quite good (video, etc).
The whole thing is on a virtualized environment (proxmox)
Same with every other machine I've tried (windows 10 enterprise, server 2012).
Maybe your setup is requiring bandwidth measurement enabled for graphics quality estimation or something similar?

**Comment by maddeer** [comment] 2017-08-11 09:49
Sorry I used 2.0-rc0 tag. 
Now I get master and your patch is fixes speed and quality

**Comment by akallabeth** [comment] 2017-08-11 10:32
@maddeer Ah :) Good to know, can this issue be seen as solved?

**Comment by maddeer** [comment] 2017-08-11 11:47
Will this patch get in master? or it's the hardcode
I can use it like patch but I don't think that it is wright

**Comment by akallabeth** [comment] 2017-08-11 12:59
@maddeer Well, not really. It was only meant to eliminate other sources of errors. 
This looks like a configuration issue (bandwidth measurement et al are necessary for newer windows versions). So you can try with ```/network:auto``` or similar.
Since this works with the old caps announced, the client decoder path can not be at fault as the same path is used, only a different protocol support level is announced to the server.

**Comment by akallabeth** [comment] 2017-08-17 09:27
Closing since the source of the problem is a configuration issue.

**Closed by akallabeth** 2017-08-17 09:27 UTC
