### ISSUE TITLE
tls-ciphers should be set appropriately to harden TLS usage by default

### ISSUE THREAD

**Issue by nicklowe** [FreeRDP/FreeRDP#2365] opened 2015-02-05 14:15 UTC
FreeRDP should comply with http://datatracker.ietf.org/doc/draft-ietf-tls-prohibiting-rc4/ and not offer RC4 or any other weak cipher suites over TLS.

tls-ciphers should therefore default to Mozilla's intermediate compatibility string unless specified otherwise.

https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29

This is:

ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA

Any that are not understood by an older version of OpenSSL will be ignored. Any cipher suites that are not applicable to a particular version of TLS (Microsoft only support TLS 1.0 for RDP at this time) will have no effect.

**Comment by hardening** [comment] 2015-02-05 15:24
Interesting.
Have you tried a xfreerdp modified client against some servers (and especially old ones) ? Microsoft used to love RC4 and put some everywhere, I suspect we could have troubles with old servers...

**Comment by nicklowe** [comment] 2015-02-05 15:38
You don't get any compat trouble as 3DES is available for use on old servers, with AES-based cipher suites available from Vista/Server 2008 onwards.

You can easily review and harden a Windows server for TLS-based RDP using the free https://www.nartac.com/Products/IISCrypto/

Clicking 'Best Prac' and rebooting does this.

**Comment by bmiklautz** [comment] 2015-02-05 16:04
@nicklowe I recently did some test with the suggested cipher strings from @bettercrypto (https://bettercrypto.org) with the result that it is not possible to connect to all RDP servers.
I'm fairly sure it will be the same result with the cipher string you suggested.

The problem is, that even if the cipher string provides more, and better, security it might have the result that some users can't connect to their servers anymore (not everyone hardens their server - unfortunately). Therefore we shouldn't use it as default value ;(.
However,  we could add an new option like "strong-cipher" (or so) that uses a good and sane (tm) cipher string.

What do you think?

**Comment by bmiklautz** [comment] 2015-02-05 16:05
Sidenote: at the moment you can set any cipher string you want with the command line option "tls-ciphers".

**Comment by nicklowe** [comment] 2015-02-05 16:13
Most users will use something like Remmina though rather than the command line and it is not practical or realistic to expect an additional parameter to be passed that way.

As all servers should at least implement TLS_RSA_WITH_3DES_EDE_CBC_SHA, I cannot see what compatibility issue you anticipate?

**Comment by bmiklautz** [comment] 2015-02-05 17:44
When thinking about GUI users:  If we add an "weaken" option it's most likely that the GUI doesn't expose it at first when it's added so if there was a problem with the cipher string and there is no option to use the old or weaker one in the GUI they are lost and can't connect anymore.
Nevertheless your argument about having a "weaken" option instead of a strengthen option is of course absolutely true - I personally would also prefer it.

So I'm generally absolutely with you on and like to see a good cipher string as default and even if I don't anticipate any compatibility issues we need to test the cipher string with all servers that we want or have to support before we can define and set it as default. But this is a time consuming process.

Thats why I suggested to have an option for  to enable "the good" cipher string first (as in now) and after some grace period we could make it the default if no problems show up.

To answer your question I have seen a server with RC4 only, might not be relevant for the common case but they are out there (scary face).

@awakecoding , @hardening what do you think?

**Comment by nicklowe** [comment] 2015-02-05 19:12
I would have thought that the best solution here would be to:

1) Change the default to Mozilla's intermediate compatibility set that will not have compatibility implications for servers that are running with Microsoft's default configuration for SCHANNEL.

2) Implement a configuration option to allow weak cipher suites to be used with TLS. Expose it in Remmina too.

3) Have a good error message that says where there is no cipher suite overlap, that the server should be corrected (with a link to documentation / the IIS crypto tool) and a pointer to the configuration option that allows weak cipher suites to be used.

**Comment by bmiklautz** [comment] 2015-02-05 20:03
@nicklowe I would be interested in the error message you mention maybe you can paste it somewhere?

**Comment by nicklowe** [comment] 2015-02-05 20:06
I would be happy to write one if that is what you mean?

I was suggesting displaying a good, informative error message in the case that there is no mutually acceptable cipher suite.

**Comment by azet** [comment] 2015-02-08 12:56
> As all servers should at least implement TLS_RSA_WITH_3DES_EDE_CBC_SHA

As a short comment: CBC-Mode is at least as broken as RC4 is. I would not recommend using it in TLS as is. TLS >= 1.2 offer AEAD ciphers (GCM, CCM mode for AES, CAMELLIA and ARIA and soon other ciphers/modes).

**Comment by bmiklautz** [comment] 2015-02-09 09:07
@azet thanks for the update.

**Comment by hardening** [comment] 2023-06-15 21:16
We can probably close this issue, as with new OpenSSL we go by default with up-to-date ciphers, and if you need to connect to an old server you must provide some command line args to weaken the ciphers.

**Comment by akallabeth** [comment] 2023-06-16 07:12
@hardening true.

**Closed by akallabeth** 2023-06-16 07:12 UTC
