### ISSUE TITLE
dynamic resolution with full screen toggle support

### ISSUE THREAD

**Issue by gnshkl1** [FreeRDP/FreeRDP#4757] opened 2018-07-19 05:48 UTC
for example:-
/dynamic-resolution +toggle-fullscreen  is used without /f in commandline
then freerdp should support restore,maximize with ALT+CTRL+ENTER for fullscreen

**Comment by akallabeth** [comment] 2018-07-19 07:34
And your issue is?

**Comment by gnshkl1** [comment] 2018-07-19 07:40
@akallabeth  feature request for display resolution update smoothness with above commandline

**Comment by akallabeth** [comment] 2018-07-19 07:54
@gnshkl1 Please be a bit more specific, what do you mean by `smoothness`?
I'd interpret it as a duplicate of your own #4753, but I don't think that is your intention?

**Comment by gnshkl1** [comment] 2018-07-19 10:46
@akallabeth just tested your FreeRDP-dyn_resize_fix branch on ubuntu 18.04_x64 with windows 10 as remote server as below,
1:-dynamic resolution is working fine with maximize and restore button of window border
2:-after maximize use ALT+CTRL+ENTER for fullscreen mode
3:-then again use  ALT+CTRL+ENTER to exit full screen
4:-now maximize button is hidden from window border and use cannot update resolution
Attached screenshot for same
![screenshot from 2018-07-19 16-13-07](https://user-images.githubusercontent.com/8046158/42938183-09ad2224-8b6f-11e8-8d25-b46b567e329e.png)
![screenshot from 2018-07-19 16-13-30](https://user-images.githubusercontent.com/8046158/42938184-09d834c8-8b6f-11e8-92ca-414692de40ec.png)

**Comment by gnshkl1** [comment] 2018-07-19 10:59
@akallabeth now tested on Xubuntu-16.04_x86 and got same result
![accops_os_0 8 4_vxl-2018-07-19-16-28-49](https://user-images.githubusercontent.com/8046158/42938710-da39150a-8b70-11e8-9bc1-84fd22247509.png)

**Comment by gnshkl1** [comment] 2018-07-19 11:05
@akallabeth second screnario on Xubuntu-16.04_x86 as below
1:-take session
2:-maximize 
![accops_os_0 8 4_vxl-2018-07-19-16-34-09](https://user-images.githubusercontent.com/8046158/42938943-b5c22ae4-8b71-11e8-9d94-a0e50138d150.png)

**Closed** 2018-07-30 11:31 UTC
Labels: client, fixed-waiting-test, x11
