### ISSUE TITLE
FreeRDP + Moonlight ?

### ISSUE THREAD

**Issue by philippemnoel** [FreeRDP/FreeRDP#5586] opened 2019-09-10 22:36 UTC
I tried using FreeRDP to stream an Azure Windows 10 VM and the latency when watching videos was incredibly high, making it barely usable. However, multiple streaming protocols for game (like Moonlight: https://github.com/moonlight-stream) can stream much more intensive tasks without problem. Are there any plans to interface them together to make smooth remote desktop with FreeRDP? 

I'd be happy to work on this project with a bit of guidance.

**Comment by akallabeth** [comment] 2019-09-11 06:11
Could you elaborate?
Are you talking about freerdp as client or as server here?

**Comment by akallabeth** [comment] 2019-09-11 12:33
In case you use it as client, could you add some information how you use it?
I´m using my multimonitor system via RDP on a regular basis and as long as you have proper connection settings the lag is minimal.

**Comment by philippemnoel** [comment] 2019-09-11 12:44
I have an Ubuntu 18.04 machine from which I use FreeRDP to connect to an Azure Windows 10 virtual machine. When I try to watch YouTube when connecting through FreeRDP, the latency is so much that you can see the frames get drawn from top to bottom. 

I then tried to connect to this VM using Microsoft RDP from a friend's laptop running Windows 10, and there was no problem at all watching YouTube - zero noticeable latency, so it seems like the connection is not the issue here.

Do you know why FreeRDP had that much more latency than actual RDP? My question is -- assuming this latency comes from non-optimal implementation of some FreeRDP protocol elements compared to Microsoft's RDP, couldn't the FreeRDP framework by augmented to make use of similar techniques as game streaming protocols do (like Moonlight) to fix this latency problem, since Microsoft's RDP is not available on Linux?

**Comment by philippemnoel** [comment] 2019-09-11 12:47
So to clarify -- I mean FreeRDP from the client (my laptop), not from the server (the Azure virtual machine), which has some RDP server pre-installed in Windows 10 that I can't do anything about.

**Comment by akallabeth** [comment] 2019-09-11 15:47
Try /rfx /gfx:avc444 /network:auto
Or set connectiontype 7/auto

**Comment by akallabeth** [comment] 2019-09-11 15:48
And you're on a release build, yes?

**Comment by akallabeth** [comment] 2019-09-11 19:30
Yes, the avc444 stuff and many others.
Not activated by default but the switches I mentioned do so.
Be sure you have installed freerdp2 or try our nightlies.

**Comment by akallabeth** [comment] 2019-09-13 07:16
answered on mailing list, closing this as it is not a bug but rather problems with compile and usage.
Note: performance improvements are always welcome, so if anyone does fire up a profiler and can find a way to optimize hotspots pull requests (or some hints what they discovered) are welcome ;)

**Closed by akallabeth** 2019-09-13 07:16 UTC
