### ISSUE TITLE
When vaapisink is used for TSMF (gstreamer), keyboard and mouse stops working on the video surface.

### ISSUE THREAD

**Issue by seamus-45** [FreeRDP/FreeRDP#5436] opened 2019-06-17 10:41 UTC
**Describe the bug**
With the recent versions of gstreamer-vaapi, the vaapisink will handle GstNavigation stuff, and this will break input event handling. If WMP in fullscreen mode, there is no way to control video, even close the window. [Similar issue](https://bugzilla.redhat.com/show_bug.cgi?id=1167029)

**To Reproduce**
1. Install latest gst-plugins-vaapi
2. Compile freerdp with gstreamer1.0 support
3. Connect to server with enabled MMR  (set gstreamer as multimedia decoder)
4. Play any H.264 video in fullscreen mode.
5. Keyboard and mouse stops working

**Expected behavior**
Keyboard and mouse should work

**Application details**
* Version of FreeRDP
` FreeRDP version 2.0.0-rc2 (2.0.0-rc2)`
* Command line used
`xfreerdp /f /bpp:16 /cert-ignore /kbd:0x409 /multimedia:sys:alsa /multimedia:decoder:gstreamer /v:ts2008`
* output of `/buildconfig`:
```
This is FreeRDP version 2.0.0-rc2 (2.0.0-rc2)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUNIT=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_NEON=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=OFF WITH_PAM=OFF WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_PULSEAUDIO=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON                         
Build type:          Release
CFLAGS:               -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=/home/yocto/poky/build/tmp/work/core2-64-tcx11-linux/freerdp/2.0.0+gitrAUTOINC+7a7b180277-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/yocto/poky/build/tmp/work/core2-64-tcx11-linux/freerdp/2.0.0+gitrAUTOINC+7a7b180277-r0=/usr/src/debug/freerdp/2.0.0+gitrAUTOINC+7a7b180277-r0 -fdebug-prefix-map=/home/yocto/poky/build/tmp/work/core2-64-tcx11-linux/freerdp/2.0.0+gitrAUTOINC+7a7b180277-r0/recipe-sysroot= -fdebug-prefix-map=/home/yocto/poky/build/tmp/work/core2-64-tcx11-linux/freerdp/2.0.0+gitrAUTOINC+7a7b180277-r0/recipe-sysroot-native=   -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse  --sysroot=/home/yocto/poky/build/tmp/work/core2-64-tcx11-linux/freerdp/2.0.0+gitrAUTOINC+7a7b180277-r0/recipe-sysroot -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls                                                    
Compiler:            GNU, 7.3.0
Target architecture: x64
```
* OS version connecting to
Windows Server 2008 R2

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
Issue can be resolved with below patch:
```
diff -Naur a/channels/tsmf/client/gstreamer/tsmf_X11.c b/channels/tsmf/client/gstreamer/tsmf_X11.c
--- a/channels/tsmf/client/gstreamer/tsmf_X11.c 2019-06-17 12:53:03.105884324 +0500
+++ b/channels/tsmf/client/gstreamer/tsmf_X11.c 2019-06-17 12:55:44.255619829 +0500
@@ -114,7 +114,7 @@
 #if GST_VERSION_MAJOR > 0
                hdl->overlay = GST_VIDEO_OVERLAY (GST_MESSAGE_SRC (message));
                gst_video_overlay_set_window_handle(hdl->overlay, hdl->subwin);
-               gst_video_overlay_handle_events(hdl->overlay, TRUE);
+               gst_video_overlay_handle_events(hdl->overlay, FALSE);
 #else
                hdl->overlay = GST_X_OVERLAY (GST_MESSAGE_SRC (message));
 #if GST_CHECK_VERSION(0,10,31) 
```

**Comment by akallabeth** [comment] 2019-06-25 08:20
I assume the issue is fixed with the patch being merged.
reopen / create a new issue if still not fixed.

**Closed by akallabeth** 2019-06-25 08:20 UTC
Labels: fixed-waiting-test
