### ISSUE TITLE
Black box around cursor and other problems when connecting to xrdp xubuntu 1704

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#3863] opened 2017-03-13 19:57 UTC
(from [remmina issue 1098](https://github.com/FreeRDP/Remmina/issues/1098))

I have configured xubuntu 1704 RDP server with xrdp, and I'm connecting to it.
I'm using the latest xfreerdp client on both an Ubuntu 16.04 desktop with nvidia module driver, and other users are using the intel i915 driver. I also tested with arch and nouveau driver.
`xfreerdp /v:192.168.56.80 /w:1024 /h:768`
1) There is a black box around the mouse cursor. I'm unable to take a screenshot, because the screenshot taken with `sleep 2 ; gnome-screenshot -p` or shutter shows the correct cursor without the black box. Here you can see an image from my smartphone camera :)
![img_20170313_204117](https://cloud.githubusercontent.com/assets/5477803/23872224/be932dee-082d-11e7-84cc-68854ff00267.jpg)
2) There are some font rendering problems on the logon screen:
`xfreerdp /v:192.168.56.80 /w:1024 /h:768`
![immagine](https://cloud.githubusercontent.com/assets/5477803/23872412/7632467e-082e-11e7-8d9f-202d595f71cf.png)
`xfreerdp /v:192.168.56.80 /w:1024 /h:768 /bpp:24`
![immagine](https://cloud.githubusercontent.com/assets/5477803/23872423/7fc0d9f8-082e-11e7-9d1b-a209b3b46630.png)
Using the software rendering `xfreerdp /v:192.168.56.80 /w:1024 /h:768 /gdi:sw` makes these artifacts on fonts disappear and text is displayed correctly.

The microsoft client, mstsc, seems to display both the cursor and the fonts correctly.

**Comment by freerdp-github** [comment] 2017-03-14 01:46
The problem you are seeing is caused by mouse pointers that have shadows enabled both in Linux and windows. To fix either disable shadows on mouse pointers. As a quick test/fix on the xrdp server side you can set .Xresources to disable this and then login to see if it goes away. Place the contesnts of .Xresources file in your home directory on server.
# cat .Xresources 
Xcursor.core: 1

**Comment by dankasak** [comment] 2017-03-14 22:45
I've just tested, and found something very strange. If I create that .Xresources file, as above, there is no change. But if I then run 'marco-compton' ( the Mate window-manager/compositor ), it kills and restarts marco, and _**then**_, the mouse pointer displays correctly. I then tried removing the .Xresources file and logging in again, and the problem returned and couldn't be fixed by restarting marco. In summary - I need *both* the .Xresources file, *and* to restart marco when starting each session.

Anyway, thanks for the pointer ( get it? ). This workaround is good enough for me :) I'm happy to help test / debug further if there is something I can do.

**Comment by giox069** [comment] 2017-03-17 21:44
@akallabeth: thank you for PR #3870: it seems to fix the cursor black box problem.
I have found another font rendering problem while connecting with xfreerdp to win2003 with /gdi:hw
![image](https://cloud.githubusercontent.com/assets/5477803/24063989/61f75ca8-0b62-11e7-80d9-73681ba087e1.png)
rendering is OK with /gdi:sw
![image](https://cloud.githubusercontent.com/assets/5477803/24063968/4399762e-0b62-11e7-8fc3-889783afb2c9.png)

**Comment by ben-cohen** [comment] 2017-12-03 16:14
As @giox069 says the text rendering bug goes away if you set "/gdi:sw" to use software rendering.  In update_process_glyph_fragments() the rdpGlyph member functions BeginDraw and Draw are called.  For software rendering these are set to gdi_Glyph_BeginDraw() and gdi_Glyph_Draw().  For hardware rendering they are set to xf_Glyph_BeginDraw() and xf_Glyph_Draw().

The implementations of these functions look different to me, for example the fOpRedundant is ignored for the gdi version and not for the xf version.

**Comment by akallabeth** [comment] 2018-01-08 09:20
Closing as the initial issue is resolved.
The drawing issue is tracked with #3907

**Closed by akallabeth** 2018-01-08 09:20 UTC
