### ISSUE TITLE
centos xfreerdp to win 7 fail: Failure in SSL library

### ISSUE THREAD

**Issue by lxia7212** [FreeRDP/FreeRDP#2128] opened 2014-09-29 14:41 UTC
This is FreeRDP version 1.0.2

Linux ????.com 2.6.32-279.el6.x86_64 #1 SMP Fri Jun 22 12:19:21 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
# xfreerdp 192.168.1.27 -u someone -f --sec nla

connected to 192.168.1.27:3389
Password: 
SSL_read: Failure in SSL library (protocol error?)
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.

Is there anyone can help me?

**Comment by relphj** [comment] 2015-02-24 14:14
I get the same failure:

$ xfreerdp --version
This is FreeRDP version 1.0.2

$ xfreerdp --sec nla win7host.nodc.noaa.gov
connected to win7host.nodc.noaa.gov:3389
Password:
SSL_read: Failure in SSL library (protocol error?)
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.

(By the way "--sec nla" is the correct form for xfreerdp 1.0.2.)

If I use the same command to a Windows Server 2003 system, it works fine.

**Comment by relphj** [comment] 2015-02-26 12:34
I am successfully able to connect to my Windows 7 host from another Windows 7 client using Remote Desktop Connection. The Windows 7 host has NLA enabled, no TLS or other authentication methods are enabled. This appears to be a reproducible problem in xfreerdp.

**Comment by aroundthfur** [comment] 2015-03-01 12:44
I have the same issue. 

$ xfreerdp /u:jovanam /p:Memory09 /v:hostname
connected to hostname:3389
SSL_read: Failure in SSL library (protocol error?)
SSL_read: error:14094419:SSL routines:SSL3_READ_BYTES:tlsv1 alert access denied
credssp_recv() error: -1
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
Error: protocol security negotiation or connection failure

Funny that some times it works and some times it does not. I can't seem to find any reason for the behaviour..

**Comment by relphj** [comment] 2015-03-21 00:31
I have tried using --no-tls, --ignore-certificate, and pretty much every other option I can think of. Still no connect to a Windows 7 system from centos using xfreerdp 1.0.2. (Does anybody read these reports?)

**Comment by trinacriax** [comment] 2015-04-24 09:04
I've experienced the same issue and the problem was that during cmake, it recognize the libssl 1.0.1 while during the build, the make linked the libssl 0.9.8, and when I run it, the libssl 1.0.1 was in the library path. Please check you libssl and libcrypto, as well.
This issue does not appear with Win2003 because no TLS is enabled, only Win2008+

**Comment by iy-propeller** [comment] 2015-07-23 15:32
ubuntu 15.04 x86_64:
Package libxfreerdp-client1.1:
i 1.1.0~git20140921.1.440916e+dfsg1-2ubuntu1 vivid 500 

Getting this error:"
SSL_read: Failure in SSL library (protocol error?)
SSL_read: error:14094419:SSL routines:SSL3_READ_BYTES:tlsv1 alert access denied
credssp_recv() error: -1
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
Error: protocol security negotiation or connection failure
" while connecting to win2012 and win10 tech. preview.

**Comment by bmiklautz** [comment] 2015-07-24 07:42
@iy-propeller I wonder what command line you've used?

**Comment by jpmorris** [comment] 2015-09-04 22:44
Also getting the same with windows 10.  A workaround is to disable Network Level Authentication on the windows side, but annoying nonetheless considering freerdp is one of the few clients that is supposed to support it.

**Comment by Fathardie** [comment] 2015-09-23 08:29
Getting the following error from Elementary OS (pantheon terminal) with freerdp version 1.0.2 to Windows Server 2012 R2 with NLA enabled. 

:~$ xfreerdp -u username 80.xxx.xxx.xxx
connected to 80.xxx.xxx.xxx:3389
Password: 
SSL_read: Failure in SSL library (protocol error?)

Turning off NLA on the server works. 100% sure the credentials match as I copy-pasted them.

Also tried with:
:~$ xfreerdp --sec nla --certificate-ignore -u username 80.xxx.xxx.xxx

This produces the same non-descriptive error.

**Comment by ubbe76** [comment] 2016-04-22 16:46
At last.
Successfully connected to Win 7 (connected to a domain) with:
xfreerdp --no-nla -u [username] [hostname]

**Comment by iammyownalterego** [comment] 2016-05-19 00:29
I uninstalled and reinstalled the "freerdp" package and all was well.
Unfortunately, the version was still "freerdp-1.0.2-5.el7_1.1.x86_64" (unchanged) when I reinstalled, so updated anything is out. My best guess is maybe weird linking as mentioned earlier in this thread???

**Comment by bmiklautz** [comment] 2016-05-31 10:10
@julianjm not quite sure what rdesktop has todo with this issue?

**Comment by dkwami** [comment] 2016-08-09 17:36
I thought the same thing, but changing the order of my arguments actually helped.  I've had the same problem going from ubuntu to windows server 2012 for a couple of weeks.  What finally worked for me was: xfreerdp --sec nla --ignore-certificate -u username -d domain serverName
Thanks @julianjm!

**Comment by paul-oprea** [comment] 2018-02-01 10:40
Thanks. for me it also worked without the --ignore-certificate, but the order of the arguments **does** seem to matter

**Comment by ondrejholy** [comment] 2018-02-01 13:44
@akallabeth do you want pull request for stable-1.0? I've already backported https://github.com/FreeRDP/FreeRDP/pull/3046 into RHEL 7.5:
https://bugzilla.redhat.com/show_bug.cgi?id=1312967

So, by the way, it should be part of CentOS 7.5 also.

**Comment by bmiklautz** [comment] 2018-02-13 15:07
Fixes merged to branch stable-1.0 and stable-1.1.

**Closed** 2018-02-13 15:31 UTC
Labels: stable-1.0

**Comment by xoloxuwo** [comment] 2018-09-27 11:08
Updated in Sept.2018:
freerdp version 1.1.0 betal(git n/a) ,remote access to window 7 sever from local computer with Linux OS ,use command line as follows 
it woks quite well:
commnad line1:
xfreerdp /sec:tls /v:192.168.1.1 /u:admin /p:123456789
commnad line2:
xfreerdp /sec:rdp /v:192.168.1.1/u:admin /p:123456789
both above are ok.
