### ISSUE TITLE
floatbar cannot be hidden/unpinned via pin/buttons

### ISSUE THREAD

**Issue by sblive** [FreeRDP/FreeRDP#4899] opened 2018-09-27 16:18 UTC
hi!
we are unable to disable the floatbar with "/floatbar:false" or "/floatbar:0" which I guessed should work looking at cmdline.h, but now I found "\"-floatbar\"" works.
no error is emitted as well, looking like it's getting parsed in all cases.
shouldn't the first two versions work as well or generate an error?

also users are very annoyed that the pin does not do anything.
in fact none of the buttons work (neither minimize/restore, nor close).
one user claimed the bar was not moveable, but on my test system it is.
weirdly resizing it works...

full cmdline below, connecting to win8, linux is fully up2date gentoo/xfce
xfreerdp is d0612151f

what's wrong? please help!

thanks,
regards,
k

/multimon /codec-cache:rfx /sound:sys:alsa /microphone:sys:alsa /aero /heartbeat /clipboard /wallpaper /decorations /window-drag /menu-anims /multitransport /floatbar:0 /fonts /f /rfx /bpp:32 /cert-ignore /auto-reconnect /async-input "/kbd:German (IBM)" /drive:USBStorage,/mnt/USBStorage /v:blah /u:blah /from-stdin

**Comment by akallabeth** [comment] 2018-09-28 06:29
@sblive No the first two examples are no valid command line syntax. The help output of `xfreerdp` also does not mention such a behaviour.
As for the buttons, do you use a custom build?
I can use it quite fine here with all buttons working just as expected (debian stretch and fedora 28, gnome3 mostly)

**Comment by sblive** [comment] 2018-09-28 14:37
Thanks, I see, I was just assuming that it would work like /bpp:32 etc. and there was no error. Don't remember even seeing it in help, but not sure right now.
We don't want/need that bar anyway, so now I found how to disable it, it's OK for us, however as it's default on, it would be nice if it works.
Define "custom build"? It's Gentoo with the included 9999 (=latest git) ebuild which is what we have used for years now.

**Comment by akallabeth** [comment] 2018-09-28 19:55
Ok, I'm asking because all my builds work as they should. Don't use gentoo though.
Could you add your /buildconfig, maybe some build dep is missing

**Comment by akallabeth** [comment] 2018-10-01 08:55
Closing this as the remaining claims can not be reproduced.
(Tested all buttons on fedora 28 and debian stretch for gnome, cinnamon, xfce and openbox)

**Comment by hendwolt** [comment] 2018-10-01 17:49
I experience the pin/button problem too. It happens when I start the client xfreerdp on KDE Plasma (openSUSE Leap15 and Tumbleweed). The buttons work, when I start it on IceWM.
target systems: Windows7 Prof., Windows 10 Insider Preview
build config:
This is FreeRDP version 2.0.0-dev4 (0b8a66188)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=OFF HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=OFF WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=ON WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls
Compiler:            GNU, 8.2.1
Target architecture: x64

**Comment by akallabeth** [comment] 2018-10-02 06:28
@hendwolt Ok, finally managed to reporduce on debian/kde plasma.
Looks like as if the focus setting of kde is stealing the mouse focus of the fullscreen bar in my case, so a second click is working.
Can you confirm this beahviour or is it something different you experience?

**Comment by akallabeth** [comment] 2018-10-02 18:45
Ok, then I'll close this then.
Tiling window managers are also affected, but then again it can be disabled in those cases

**Closed** 2018-10-02 18:45 UTC
Labels: client, waiting-feedback, x11

**Comment by sblive** [comment] 2018-12-12 08:36
This bug has reappeared for us within the last few days, current version "2.0.0-dev5 (4dac07667)" is broken again: floatbar is always shown in fullscreen, cannot hide, even with double click, "-floatbar" also does not do anything.

**Comment by sblive** [comment] 2018-12-12 08:40
using "/floatbar:sticky:off,default:hidden" makes it auto-hide, however we do not want it at all and buttons still do not work

**Comment by sblive** [comment] 2018-12-12 08:45
buildconfig:
This is FreeRDP version 2.0.0-dev5 (4dac07667)
Build configuration: BUILD_TESTING=no BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=yes WITH_CCACHE=OFF WITH_CHANNELS=ON WITH_CLIENT=yes WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=no WITH_DEBUG_ALL=no WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=yes WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=no WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=yes WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=yes WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=no WITH_MBEDTLS=OFF WITH_NEON=no WITH_OPENH264=no WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=no WITH_PROFILER=OFF WITH_PULSE=no WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=no WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=no WITH_X11=yes WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=yes WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=yes WITH_ZLIB=ON
Build type:          Gentoo
CFLAGS:              -march=znver1 -mtune=znver1 -fdiagnostics-color=always -O3 -pipe --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=256 -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mcx16 -msahf -mmovbe -maes -mpclmul -mpopcnt -mabm -mno-lwp -mno-fma4 -mno-xop -mno-sgx -mno-tbm -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mfsgsbase -mfxsr -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-avx5124fmaps -mno-avx5124vnniw -mno-clwb -mno-pku -mno-rdpid -mmwaitx -mclzero -msse4a -msha -mrdseed -mprfchw -mclflushopt -mfma -mbmi -mbmi2 -mavx -mavx2 -mf16c -mxsave -mxsaveopt -madx -mxsavec -mxsaves -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -DWINPR_DLL
Compiler:            GNU, 8.2.0
Target architecture: x64

**Comment by akallabeth** [comment] 2018-12-12 09:01
@sblive Have you tried just not to activate the floatbar if you don't want it? (`xfreerdp` without arguments should give you a full explanation of all available options)
As for the wiki, true, any volunteers?

**Comment by romwriter** [comment] 2019-04-30 20:35
I experienced inconsistent behaviour:
With freerdp2-x11 2.0.0-git201810050900, the default is enabled floatbar, switch "-floatbar" disables floatbar.
With freerdp2-x11 2.0.0-git201903080944, the default is disabled floatbar, switch "/floatbar" enables floatbar, and switch "-floatbar" does enable floatbar too.
Switch "-floatbar" should disable floatbar in any version.
