### ISSUE TITLE
"[winpr_Digest_Init_Internal]: Failed to initialize digest md4" Error caused

### ISSUE THREAD

**Issue by jaejung-lee** [FreeRDP/FreeRDP#11005] opened 2024-12-19 13:30 UTC
**Describe the bug**
1. Execute 'xfreerdp' command in terminal
2. Display Error message
`[22:24:09:664] [4913:ed3e7840] [ERROR][com.winpr.crypto.hash] - [winpr_Digest_Init_Internal]: Failed to initialize digest md4` 

**Expected behavior**
- Warning Message / Error Message not display

**Screenshots**
<img width="1584" alt="image" src="https://github.com/user-attachments/assets/e8a31f24-3f89-48db-920a-4507b8414e50" />

**Application details**
* FreeRDP version (`xfreerdp /version`) -> 3.10.2
* Command line used
* Output of `xfreerdp /buildconfig`
`xfreerdp /buildconfig
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x12a00a400]: *************************************************
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x12a00a400]: This build is using [runtime-check] build options:
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x12a00a400]: * 'WITH_VERBOSE_WINPR_ASSERT=ON'
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x12a00a400]: 
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x12a00a400]: [runtime-check] build options might slow down the application
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x12a00a400]: *************************************************
[22:28:39:465] [6829:ed3e7840] [ERROR][com.winpr.crypto.hash] - [winpr_Digest_Init_Internal]: Failed to initialize digest md4
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn_hash][0x12a00a400]: *************************************************
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn_hash][0x12a00a400]: [SSL] {Digest} build or configuration missing:
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn_hash][0x12a00a400]:  * md4: NTLM support not available
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn_hash][0x12a00a400]: *************************************************
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn_cipher][0x12a00a400]: *************************************************
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn_cipher][0x12a00a400]: [SSL] {Cipher} build or configuration missing:
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn_cipher][0x12a00a400]: * rc4: assistance files with encrypted passwords, NTLM, RDP licensing and RDP security will not work
[22:28:39:465] [6829:ed3e7840] [WARN][com.freerdp.core.rdp] - [log_build_warn_cipher][0x12a00a400]: *************************************************
This is FreeRDP version [xfreerdp] 3.10.2 (n/a)
[xfreerdp] Build configuration: BUILD_TESTING=OFF BUILD_TESTING_INTERNAL=OFF BUILD_TESTING_INTERNAL_AVAILABLE=1 WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRERROR_R=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H= WINPR_HAVE_SYS_FILIO_H=1 WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H=1 WINPR_HAVE_SYS_TIMERFD_H= WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ABSOLUTE_PLUGIN_LOAD_PATHS=ON WITH_AVX2=ON WITH_BINARY_VERSIONING=OFF WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CJSON_REQUIRED=OFF WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_MAC=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL2=ON WITH_CLIENT_SDL3=OFF WITH_CLIENT_SDL_AVAILABLE=1 WITH_CLIENT_SDL_VERSIONED=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DOCUMENTATION=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FDK_AAC=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FULL_CONFIG_PATH=OFF WITH_FUSE=OFF WITH_GFX_FRAME_DUMP=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_INSTALL_CLIENT_DESKTOP_FILES=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_JPEG=ON WITH_JSONC_REQUIRED=OFF WITH_JSON_DISABLED=OFF WITH_KEYBOARD_LAYOUT_FROM_FILE=OFF WITH_KRB5=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBRESSL=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=ON WITH_MACAUDIO_AVAILABLE=1 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_NO_UNDEFINED=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_OPUS=OFF WITH_PCSC=ON WITH_PKCS11=ON WITH_PLATFORM_SERVER=OFF WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_RDTK=ON WITH_RESOURCE_VERSIONING=OFF WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SDL_IMAGE_DIALOGS=OFF WITH_SDL_LINK_SHARED=ON WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SIMD=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_STREAMPOOL_DEBUG=OFF WITH_SWSCALE=ON WITH_SYSTEMD=OFF WITH_THIRD_PARTY=OFF WITH_TIMEZONE_COMPILED=ON WITH_TIMEZONE_FROM_FILE=OFF WITH_TIMEZONE_ICU=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WEBVIEW=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_JSON=ON WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON
Build type:          Release
CFLAGS:              -I/opt/homebrew/opt/sdl2_ttf/include/SDL2 -fno-omit-frame-pointer -O3 -DNDEBUG
Compiler:            AppleClang, 16.0.0.16000026
Target architecture: ARM`

**Environment (please complete the following information):**
 - OS: Apple M3 Pro

**Comment by hardening** [comment] 2024-12-19 13:35
Build with `WITH_INTERNAL_MD4=ON`.
BTW perhaps with recent openssl and removed old ciphers we could enable that by default (is there a way to test for the openssl version in cmake ?)

**Comment by jaejung-lee** [comment] 2024-12-19 13:56
@hardening 
Thank you for quick response!
Is this the build command you mentioned?
`brew install freerdp CMAKE_ARGS="-WITH_INTERNAL_MD4=ON"`

**Comment by akallabeth** [comment] 2024-12-19 14:09
@hardening no, because these are runtime settings (e.g. legacy cipher option enabled or not)
closing this as not a bug.

**Closed by akallabeth** 2024-12-19 14:09 UTC

**Comment by jaejung-lee** [comment] 2024-12-19 14:29
@akallabeth 
i can't understand your answer ..
I just installed freerdp with brew and ran the xfreerdp command.
Does the runtime setting means my Mac's own settings?

**Comment by akallabeth** [comment] 2024-12-19 14:35
@jaejung-lee exactly.
* openssl did deprecate and remove certain hashes and ciphers (they are insecure)
* RDP requires some of these outdated hashes/ciphers (not security relevant, but they need to be there)

so, you have 2 options:
1. use a build with the `WITH_INTERNAL_MD4` (MD5 and RC4) options
2. use a openssl with legacy ciphers enabled (configuration setting of your ssl library)

**Comment by akallabeth** [comment] 2024-12-19 14:38
@jaejung-lee this is also not an error bug a warning that certain features of the client will not work (connections to older systems, ...)
