### ISSUE TITLE
xfreerdp with /gdi:sw crashes in current master (4889652c1)

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#4336] opened 2017-12-31 06:46 UTC
On openSUSE Tumbleweed xfreerdp crashes with the current master version, when I use /gdi:sw.

Version info:
This is FreeRDP version 2.0.0-dev2 (4889652c1)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=OFF HAVE_AIO_H=1 HAVE_EVENTFD_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=OFF WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=ON WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -march=i686 -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -msse2
Compiler:            GNU, 7.2.1
Target architecture: x86

-------------------------------------------------------------
console output:

endrik@schlepptop:~> ./xfreerdp_buero.sh 
[07:32:01:834] [3165:3173] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
Password: 
[07:32:05:015] [3165:3173] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[07:32:05:015] [3165:3173] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[07:32:05:276] [3165:3173] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[07:32:05:331] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
[07:32:05:331] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
[07:32:06:400] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid width
[07:32:06:406] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
[07:32:06:423] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
[07:32:06:574] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid width
[07:32:06:574] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
[07:32:06:227] [3165:3173] [INFO][com.freerdp.client.x11] - Logon Error Info LOGON_WARNING [LOGON_MSG_SESSION_CONTINUE]
[07:32:07:776] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
[07:32:07:776] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
[07:32:07:777] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
[07:32:07:777] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
[07:32:07:799] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid width
[07:32:07:799] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
[07:32:07:815] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
[07:32:18:226] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid width
[07:32:18:226] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
[07:32:24:538] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
[07:32:24:538] [3165:3173] [ERROR][com.freerdp.gdi.region] - Invalid height
./xfreerdp.sh: Zeile 4:  3165 Speicherzugriffsfehler  (Speicherabzug geschrieben) xfreerdp /u:myuser /d:mydomain /f +clipboard -wallpaper /v:myhost /jpeg /gdi:sw

When I use /rfx instead of /gdi:sw, I see messages like "Invalid height" too, but (at least until now) without a crash.

The target system in this case is a Windows7 Prof. host.

**Comment by ggzengel** [comment] 2018-01-02 15:13
Same with https://github.com/FreeRDP/Remmina/issues/1425?

**Comment by hendwolt** [comment] 2018-01-02 18:41
IMHO the root cause is the new function gdi_CRgnToRect(...) in region.c, introduced by #4329.
If you see "Invalid width" or "Invalid height" it means that the member "bottom" or "right" of the Rect (= HGDI_RECT) don't get filled. In the functions using gdi_CRgnToRect(...) the structure Rect is not initialized and so the next function, trying to use the returned Rect, accesses a not initialized member variable.

**Comment by giox069** [comment] 2018-01-02 22:23
@hendwolt I agree. It was exactly commit cf899eb. My possible fix:
```
diff --git a/libfreerdp/gdi/region.c b/libfreerdp/gdi/region.c
index fabb8c2..9678f1a 100644
--- a/libfreerdp/gdi/region.c
+++ b/libfreerdp/gdi/region.c
@@ -192,12 +192,12 @@ INLINE void gdi_CRgnToRect(INT64 x, INT64 y, UINT32 w, UINT32 h,
        rect->left = (x > 0) ? x : 0;
        rect->top = (y > 0) ? y : 0;
 
-       if (r > 0)
+       if (r >= 0)
                rect->right = r;
        else
                WLog_ERR(TAG, "Invalid width");
 
-       if (b > 0)
+       if (b >= 0)
                rect->bottom = b;
        else
                WLog_ERR(TAG, "Invalid height");

```

**Comment by giox069** [comment] 2018-01-02 22:26
More paranoid/secure version:
```
diff --git a/libfreerdp/gdi/region.c b/libfreerdp/gdi/region.c
index fabb8c2..e5634ff 100644
--- a/libfreerdp/gdi/region.c
+++ b/libfreerdp/gdi/region.c
@@ -192,15 +192,19 @@ INLINE void gdi_CRgnToRect(INT64 x, INT64 y, UINT32 w, UINT32 h,
        rect->left = (x > 0) ? x : 0;
        rect->top = (y > 0) ? y : 0;
 
-       if (r > 0)
+       if (r >= 0)
                rect->right = r;
-       else
+       else {
+               rect->right = rect->left;
                WLog_ERR(TAG, "Invalid width");
+       }
 
-       if (b > 0)
+       if (b >= 0)
                rect->bottom = b;
-       else
+       else {
+               rect->bottom = rect->top;
                WLog_ERR(TAG, "Invalid height");
+       }
 }
 
 /**
```

**Comment by hendwolt** [comment] 2018-01-03 16:15
One more suggestion:
Instead of just logging "Invalid height", I'd like to see the values of all input parameters in the log.

**Comment by akallabeth** [comment] 2018-01-08 08:02
Looks like this one is on me, should be fixed with the referenced pull.

**Comment by giox069** [comment] 2018-01-08 09:36
@akallabeth your fix correctly stop crashing xfreerdp. But it still logs some "Invalid height" or "invalid width", because there are some rare rectangles in which b or r are zero. This is because i added "=" in my first patch proposal. To reproduce the "Invalid width" just connect to a win7 pro (use the VM I provided you if you like) and open the start menu. When you open the start menu an error is logged.
More "invalid width/height" error are logged when you use /gdi:sw.

**Comment by akallabeth** [comment] 2018-01-08 12:03
@giox069 The log message is correct in that case, but I've reduced severity (as it is only an annoyance and not a fatal error)

**Comment by hendwolt** [comment] 2018-01-08 18:49
I tested the fix and it works for me too.

**Closed** 2018-01-10 08:58 UTC
Labels: fixed-waiting-test
