### ISSUE TITLE
Black screen when connecting to Windows 7 using Vinagre since FreeRDP 2.0.0-rc3

### ISSUE THREAD

**Issue by kempniu** [FreeRDP/FreeRDP#4864] opened 2018-09-18 17:34 UTC
**Describe the bug**
Since updating FreeRDP to 2.0.0-rc3, Vinagre (a GNOME remote desktop viewer using FreeRDP for RDP support) only displays a black screen when connecting to a Windows 7 VM over RDP.  This was not happening with FreeRDP 2.0.0-rc2 and since no functional commits have been made to Vinagre's source repository in over a year, changes introduced in FreeRDP are my primary suspect for the time being.

**To Reproduce**
1. Build Vinagre from its *master* branch, linking with FreeRDP 2.0.0-rc3 or later.
2. Connect to a Windows 7 host using RDP.

**Expected behavior**
The host machine's desktop should be visible instead of a black screen.

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Additional context**
The following Vinagre log messages are generated while connecting when FreeRDP 2.0.0-rc3 is used:

```
[ERROR][com.freerdp.core.fastpath] - Fastpath update New Pointer [b] failed, status 0
[ERROR][com.freerdp.core.fastpath] - fastpath_recv_update() - -1
[ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -3
```

These messages are *not* generated when FreeRDP 2.0.0-rc2 is used.

The latest merge commit which seems to be working fine with Vinagre *master* is a1d9399ca00023163c652037e45f9dcdcd327b51.  The next merge commit, a0fddd174739fce10007f215d95a1be84653f7bc, causes Vinagre to crash. fc84e6dd2c249166e913b339d025c5f4416f746b and every commit after it causes a black screen to be displayed instead of the remote desktop.

I will be happy to provide any further diagnostic information, try out suggested fixes, etc., please just let me know if I can be of any further help.

**Comment by akallabeth** [comment] 2018-09-18 17:43
Seems like you don't register a pointer new function. That should be already fixed on master but fir the rc you need one.

**Comment by kempniu** [comment] 2018-09-18 18:34
Thanks for a lightning fast response.

I am still observing this behavior with FreeRDP's current *master*, i.e. 24936c185815e0013a2124a86a4583d9913bf51d.  Please also note that I am neither a Vinagre developer nor someone familiar with the internals of RDP and/or FreeRDP, so while I will be happy to pass on your recommendations to the Vinagre team, I do not understand what a "pointer new function" is or what can be done about it not being "registered", sorry :)

Since it still does not appear to be working for me as of FreeRDP's current *master*, do you need any further diagnostic information from me so that some follow-up fix can be committed to FreeRDP or will things stay as they currently are in FreeRDP and I need to inform Vinagre developers that their program will not work correctly with FreeRDP 2.0.0-rc3+?

Thanks,

**Comment by akallabeth** [comment] 2018-09-19 08:47
@kempniu Ok, then I mixed that up. `PointerNew` is a function that creates a new mouse pointer image that was sent from the server.
In the newer versions of freerdp we added a lot of return value checks and this seems to be a side effect of these.

As a reference, `xfreerdp` implements that in `xf_register_pointer`

**Comment by kempniu** [comment] 2018-10-09 07:42
I had a little time to look a bit deeper into what is happening here.  Apologies in advance if what I wrote below makes no sense - I am just trying to put the bits and pieces together without having a thorough understanding of either the RDP protocol, FreeRDP, *or* Vinagre :)

It seems to me that Vinagre does not support drawing any "custom" mouse pointer images sent by the server.  In fact, I think Vinagre only initializes just enough stuff to make RDP work (for some definition of "work") - specifically, its `PostConnect` callback barely [sets the `BeginPaint` and `EndPaint` callbacks][1], ignoring everything else.

I can confirm that applying the following hack (which, IIUC, effectively rips out mouse pointer image handling from update processing) makes Vinagre work with current FreeRDP *master* (again, for some definition of "work" - but no more black screen and things seem to be the way they were with FreeRDP 2.0.0-rc2):

```diff
diff --git a/libfreerdp/core/fastpath.c b/libfreerdp/core/fastpath.c
index c3506063c..00559a0aa 100644
--- a/libfreerdp/core/fastpath.c
+++ b/libfreerdp/core/fastpath.c
@@ -399,67 +399,12 @@ static int fastpath_recv_update(rdpFastPath* fastpath, BYTE updateCode, wStream*
 			break;
 
 		case FASTPATH_UPDATETYPE_PTR_NULL:
-			{
-				POINTER_SYSTEM_UPDATE pointer_system;
-				pointer_system.type = SYSPTR_NULL;
-				rc = IFCALLRESULT(FALSE, pointer->PointerSystem, context, &pointer_system);
-			}
-			break;
-
 		case FASTPATH_UPDATETYPE_PTR_DEFAULT:
-			{
-				POINTER_SYSTEM_UPDATE pointer_system;
-				pointer_system.type = SYSPTR_DEFAULT;
-				rc = IFCALLRESULT(FALSE, pointer->PointerSystem, context, &pointer_system);
-			}
-			break;
-
 		case FASTPATH_UPDATETYPE_PTR_POSITION:
-			{
-				POINTER_POSITION_UPDATE* pointer_position = update_read_pointer_position(update, s);
-
-				if (pointer_position)
-				{
-					rc = IFCALLRESULT(FALSE, pointer->PointerPosition, context, pointer_position);
-					free_pointer_position_update(context, pointer_position);
-				}
-			}
-			break;
-
 		case FASTPATH_UPDATETYPE_COLOR:
-			{
-				POINTER_COLOR_UPDATE* pointer_color = update_read_pointer_color(update, s, 24);
-
-				if (pointer_color)
-				{
-					rc = IFCALLRESULT(FALSE, pointer->PointerColor, context, pointer_color);
-					free_pointer_color_update(context, pointer_color);
-				}
-			}
-			break;
-
 		case FASTPATH_UPDATETYPE_CACHED:
-			{
-				POINTER_CACHED_UPDATE* pointer_cached = update_read_pointer_cached(update, s);
-
-				if (pointer_cached)
-				{
-					rc = IFCALLRESULT(FALSE, pointer->PointerCached, context, pointer_cached);
-					free_pointer_cached_update(context, pointer_cached);
-				}
-			}
-			break;
-
 		case FASTPATH_UPDATETYPE_POINTER:
-			{
-				POINTER_NEW_UPDATE* pointer_new = update_read_pointer_new(update, s);
-
-				if (pointer_new)
-				{
-					rc = IFCALLRESULT(FALSE, pointer->PointerNew, context, pointer_new);
-					free_pointer_new_update(context, pointer_new);
-				}
-			}
+			rc = TRUE;
 			break;
 
 		default:
```

The question is thus whether support for drawing custom mouse pointer images is **required** from applications using FreeRDP - I am having a hard time finding an authoritative source of information regarding that.  Is Vinagre required to handle custom mouse pointer images (as per FreeRDP 2.0.0-rc3) or are these optional (and thus FreeRDP 2.0.0 final will handle missing pointer callbacks gracefully)?

[1]: https://gitlab.gnome.org/GNOME/vinagre/blob/master/plugins/rdp/vinagre-rdp-tab.c#L601-602

**Comment by akallabeth** [comment] 2018-10-24 09:58
Does #4950 fix the issue for you?

**Comment by kempniu** [comment] 2018-10-25 04:36
Sadly, no.  I am still observing the same symptoms with a263da002d441e6c628ef24056547141cd101f7e (and, for the record, also with d3c1db1746b99c05d515de626d2c515e49debfdd, i.e. current *master*).

**Comment by akallabeth** [comment] 2018-11-07 15:53
@kempniu I've just tried to build vinagre (https://gitlab.gnome.org/GNOME/vinagre.git, master) against current freerdp.
There seem to be a few issues in vinagre (using old API stuff mostly).
Is there a `wip` branch somewhere? I can't get to the issues you have as it already aborts before.

**Comment by kempniu** [comment] 2018-11-07 18:13
> I've just tried to build vinagre (https://gitlab.gnome.org/GNOME/vinagre.git, master) against current freerdp.

Thank you, I appreciate the effort!

> There seem to be a few issues in vinagre (using old API stuff mostly).

This does not really surprise me.  As far as I can tell from commit history (I may be wrong, just sharing my impression), the project has basically been on life support for a few years now.

> Is there a `wip` branch somewhere?

Sorry, I do not know of any.

>  I can't get to the issues you have as it already aborts before.

So, I am aware this does not really help, but FWIW I am still observing the same symptoms with current *master* versions of both FreeRDP (cf43406dc30258bb0c3736bce07ce0ac4366ca26) and Vinagre (4c0ad5dfba024beff02f8e608e4892684a49a65c).

Just to make sure, are you trying to connect (with Vinagre) to a **FreeRDP** server or to a **Windows** server (as I specified in the subject of this issue)?  If the former, perhaps that is why you are observing different symptoms (Vinagre crashing instead of displaying a black screen and logging the errors I quoted)?

**Comment by akallabeth** [comment] 2018-11-08 09:43
@kempniu Are you sure you're properly linking and using the correct includes and not the ones of some system installation of freerdp?

**Comment by kempniu** [comment] 2018-11-08 14:06
Just to be sure, I removed the FreeRDP package from my system and retried building both FreeRDP and Vinagre - both of them still build and I am getting the same results.  But your question got me thinking and I recalled I am applying an [Arch Linux patch][1] on top of vanilla Vinagre sources and that patch is very likely what makes it possible to build Vinagre against recent FreeRDP versions.  Can you retry building after applying the patch?  If that still fails for you, I can capture full build logs from my machine and upload them somewhere for inspection.

Thanks!

[1]: https://git.archlinux.org/svntogit/packages.git/plain/trunk/freerdp2017.diff?h=packages/vinagre

**Comment by ondrejholy** [comment] 2018-11-19 14:40
Any updates here?

Just a note that I've filed the following issue for Vinagre:
https://gitlab.gnome.org/GNOME/vinagre/issues/3

I can assist with testing of a fix, or help to push some changes to Vinagre if needed.

**Comment by akallabeth** [comment] 2018-11-19 14:57
@ondrejholy I've managed to compile with the patch from arch @kempniu mentioned. Still can't reproduce with current master (the pointer callbacks should be optional again), so maybe I'm still missing something.

**Comment by ondrejholy** [comment] 2018-11-19 15:43
@akallabeth I've just tested with freerdp master on Fedora and still the black screen is shown.

**Comment by akallabeth** [comment] 2018-11-19 16:30
@ondrejholy Could you post a debug output with `WLOG_LEVEL=debug` somewhere? I'd be interested to know if that is still the same issue. (pointer messages)

**Comment by ondrejholy** [comment] 2018-11-19 16:42
Yes, it looks like as the same issue. Here is full output from `WLOG_LEVEL=debug vinagre`:
[vinagre.log](https://github.com/FreeRDP/FreeRDP/files/2596210/vinagre.log)

**Comment by akallabeth** [comment] 2018-11-19 16:55
@ondrejholy I think I got it. The default return path in update_pointer_color is false instead of true. Can't test as I'm afk

**Comment by akallabeth** [comment] 2018-11-20 08:07
@ondrejholy ok, got it now and can reproduce with `xfreerdp`. Commenting out `pointer_cache_register_callbacks` in `xf_post_connect` yields the same result.

**Comment by ondrejholy** [comment] 2018-11-20 09:01
Thanks, yes, https://github.com/FreeRDP/FreeRDP/pull/5030 fixes the pointer issue. To fix Vinagre in Fedora completely, the patch from Arch is also needed...

**Comment by akallabeth** [comment] 2018-11-20 09:15
@ondrejholy yes, that can not be avoided. Added https://gitlab.gnome.org/GNOME/vinagre/issues/5 for some changes that will be useful for future use. (newer servers start to get rid of the old GDI based protocol)

**Closed** 2018-11-20 09:53 UTC
Labels: fixed-waiting-test, regression
