### ISSUE TITLE
aFreeRDP can't auto-reconnect after network disconnect and reconnect later

### ISSUE THREAD

**Issue by ArvinBo** [FreeRDP/FreeRDP#4517] opened 2018-03-29 08:14 UTC
When I use the aFreeRDP , if network connection is interrupted and recovered later, RDP session cannot restore the previous connection state. And I know that there is not API can used to restore the connection.

**Comment by akallabeth** [comment] 2018-03-29 11:06
Duplicate of #4511

**Closed by akallabeth** 2018-03-29 11:06 UTC
